### PR TITLE
implement disallowed trait methods

### LINKED ISSUE #8581: `disallowed_methods` on trait impls
### Description

It should be possible to to specify a specific impl of a trait method (e.g. `<alloc::vec::Vec as core::iter::IntoIterator>::into_iter`) to be disallowed, rather than having to disallow the trait method for all impls. Two things will need to be done to fix this:

* `clippy.toml` syntax will need to be extended. See `clippy_utils::def_path_res`.
* The `DefId` for the trait method will need to be resolved to it's impl's `DefId`, if possible (generic code will need something more creative here as it could be calling `<T as IntoIterator>::into_iter`).

### Version

_No response_

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by Emilgardis**
resolves #8581

changelog: [`disallowed_methods`]: Allow specific trait impls via qualified call syntax to be linted.

### CODE REVIEW

**Comment by Emilgardis** [comment]
I want to support

`<T as std::convert::Into<U>>::into` also, but with the current parsing of the qualified path i'm not sure how to do that without just implementing `parse_qpath`

**Comment by flip1995** [comment]
I already dislike the parsing code like it is implemented in this PR. I.e. the split on `>::`. What if a user wants to put this inside the `<>`? `parse_qpath` has handling logic to find the correct `>`. Also what if someone were to write `> ::` for whatever reason? Parsing a string as a string instead of tokens just leads to problems.

IIUC the goal here is to specify that a certain trait method should not be allowed on a certain type? Why not invent our own config syntax for this. You could also configure this as

```
"std::string::String : std::default::Default::default"
```

meaning: On the type `String`, you can't call `Default::default`. Or disallowing `Default::default` on every type:

```
"std::default::Default::default"
```

Or go crazy with the `toml` parsing:

```toml
disallowed_methods = [{ type = "std::string::String", method = "std::default::Default::default" }, "my_crate::my_method" ]
```

But I wouldn't go crazy with the path parsing, as we can't cover everything without completely copying `parse_qpath`.

**Comment by xFrednet** [comment]
Hey @Emilgardis, this is a ping from triage, since there hasn't been any activity in some time. Are you still planning to continue this implementation?

If you have any questions, you're always welcome to ask them in this PR or on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy).

@rustbot author

**Comment by Emilgardis** [comment]
Yes, I'm going to continue this eventually!

**Comment by xFrednet** [comment]
Hey this is triage, I'm closing this due to inactivity. If you want to continue this implementation, you're welcome to create a new PR. Thank you for the time, you already put into this!

Interested parties are welcome to pick this implementation up as well :)

@rustbot label +S-inactive-closed -S-waiting-on-author -S-waiting-on-review

**Pull request closed without merging**
