### PR TITLE
Move `semicolon_if_nothing_returned` to `pedantic`

### PR DESCRIPTION
**Pull request by mbartlett21**
This moves the `semicolon_if_nothing_returned` lint to `pedantic` category.
I had done #7148, but on the master branch, and Github doesn't seem to let me change that, so here's another PR

changelog: Move [`semicolon_if_nothing_returned`] lint into `pedantic` category.

### CODE REVIEW

**Comment by Manishearth** [comment]
Ah, we need to fix this lint for most of clippy (which runs under pedantic).

I'm also okay `#[allow()]`ing it :)

**Comment by mbartlett21** [comment]
I think this should all be good now.

@rustbot label +S-waiting-on-review -S-waiting-on-author

**Comment by mbartlett21** [comment]
> I think this should all be good now.

... And I forgot to format.

@bors try

**Pull request merged**
