### PR TITLE
update most tests to 2021 edition

### LINKED ISSUE #7842: Upgrade UI tests to 2021
We should upgrade our UI tests to Rust 2021

This mostly involves adding a `// edition:2021` up top and ensuring the test still passes.

It's worth splitting this task up.

### PR DESCRIPTION
**Pull request by llogiq**
Some tests would no longer work at all, so I added `edition:2015` or `edition:2018` to them.

Notably 2021 panics are not yet detected correctly. Once ready, this closes #7842.

---

changelog: none

### CODE REVIEW

**Comment by Manishearth** [comment]
@llogiq can you make a PR bumping the revision?

**Comment by llogiq** [comment]
I haven't finished all of the tests. Will hopefully finish them shortly.

**Review by Manishearth — APPROVED** [review]

**Comment by llogiq** [comment]
@Manishearth r?

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
Please file issues for the fixmes

**Comment by llogiq** [comment]
I filed issues for the files still on the 2015 edition.

**Pull request merged**
