### PR TITLE
tests: disable incremental compilation in dogfood to reduce target dir size

### PR DESCRIPTION
**Pull request by matthiaskrgr**
tests: execute dogfood tests with incremental compilation disabled reduces target/ dir size of when "cargo test"ing by around 2 gigs.

changelog: none

### CODE REVIEW

**Comment by llogiq** [comment]
I tried this, and it appeared to slow down the inevitable "no space left on device", though not overcoming it. The `dogfood_tests` test seems to generate a lot of data on disk.

**Comment by llogiq** [comment]
Interestingly, if I run `cargo build && for d in clippy_workspace_tests clippy_workspace_tests/src clippy_workspace_tests/subcrate clippy_workspace_tests/subcrate/src clippy_dev rustc_tools_util; do CLIPPY_DOGFOOD=1 target/debug/cargo-clippy clippy --verbose -- -D clippy::all -D clippy::pedantic; done` from a clean repo, it "only" takes about 5G.

Perhaps a way to clear the incremental caches between dogfood and dogfood_tests would give us sufficient wins without losing all of the benefits of incremental compilation.

**Comment by matthiaskrgr** [comment]
>clear the incremental caches between dogfood and dogfood_tests
Hmm, I think the tests currently run in parallel, so we'd have to run them in linear order which will probably worsen execution time.

**Comment by matthiaskrgr** [comment]
Clippy seems to invoke rustc with `-C debuginfo=2` and I wonder how much that adds to the target dir size.
Is there a way to override it?
`RUSTFLAGS ="-Cdebuginfo=0"` or `cargo clippy -- -Cdebuginfo=0` does not seem to work.

**Comment by matthiaskrgr** [comment]
previous behaviour:

cargo build
time cargo test
time: 1147 seconds
size target dir: 6503 m
// change a string inside clippy to trigger incr comp
time cargo test
time: 155 seconds
size: 6837 m


with this branch:

cargo build
time cargo test
time: 993 s 
size target dir: 4146 m
// change string
time cargo test
time:  230 seconds
size target dir: 4479

**Comment by llogiq** [comment]
Thanks, @matthiaskrgr!

**Pull request merged**
