### PR TITLE
move `suspicious_doc_comments` to doc pass

### PR DESCRIPTION
**Pull request by y21**
This was my first lint. I've been meaning to move it over to `doc.rs` since that's a better place.
There weren't any changes made to the lint logic itself.

I guess this can be considered part of #11493

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
The `doc.rs` file is now almost 1kLoC. It might make sense to split it up into a `doc/` module. This doesn't really have anything to do with this PR. Just some food for thought.

**Comment by flip1995** [comment]
@bors r+

While I'm already here, I went ahead and reviewed the PR. Thanks for cleaning this up!

**Comment by y21** [comment]
@flip1995 That's a good idea. Same for `attr.rs` probably?

**Comment by flip1995** [comment]
`attrs.rs` also makes sense, looking at it. :+1:

**Pull request merged**
