### PR TITLE
Add Collapsible match lint

### LINKED ISSUE #1252: Merge nested `match`es
We should have a lint that suggest to change

``` rust
match foo {
    Ok(row) => match row {
        Some(pixels) => pixels,
        None => return Err(…),
    },
    Err(err) => return Err(…),
};
```

into

``` rust
match foo {
    Ok(Some(pixels)) => pixels,
    Ok(None) => return Err(…),
    Err(...) => return Err(…),
}
```

---

Copied from https://github.com/Manishearth/rust-clippy/issues/1245#issuecomment-250666810.

### LINKED ISSUE #2521: Suggestion: Single `if let` instead of nested `if let { if let`
Use a single `if let` instead of a nested one whenever possible:

```rust
let value = Some(Err("Some error"));
if let Some(Err(ref error)) = value { // TODO
    return Err(format!("Error parsing 'value': {}", error));
}
```

Instead of:

```rust
let value = Some(Err("Some error"));
if let Some(ref result) = value {
    if let Err(ref error) = *result {
        return Err(format!("Error parsing 'value': {}", error));
    }
}
```

### PR DESCRIPTION
**Pull request by camsteffen**
changelog: Add collapsible_match lint

Closes #1252
Closes #2521

This lint finds nested `match` or `if let` patterns that can be squashed together. It is designed to be very conservative to only find cases where merging the patterns would most likely reduce cognitive complexity.

Example: 

```rust
match result {
    Ok(opt) => match opt {
        Some(x) => x,
        _ => return,
    }
    _ => return,
}
```
to
```rust
match result {
    Ok(Some(x)) => x,
    _ => return,
}
```

These criteria must be met for the lint to fire:

* The inner match has exactly 2 branches. 
* Both the outer and inner match have a "wild" branch like `_ => ..`. There is a special case for `None => ..` to also be considered "wild-like".
* The contents of the wild branches are identical.
* The binding which "links" the matches is never used elsewhere.

Thanks to the hir, `if let`'s are easily included with this lint since they are desugared into equivalent `match`'es.

I think this would fit into the style category, but I would also understand changing it to pedantic.

### CODE REVIEW

**Comment by camsteffen** [comment]
Hmm my stderr is too long? I'm not sure what to do about that.

**Comment by giraffate** [comment]
How about splitting a test file into two?

**Comment by camsteffen** [comment]
Done.

**Comment by llogiq** [comment]
Good stuff! I especially like the `SpanlessEq` extension. I would start in the `style` category until we get reports about it swamping the output. @bors r+

**Pull request merged**
