### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by flip1995**
changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
Probably blocked on https://github.com/rust-lang/rust/pull/73257

**Comment by Manishearth** [comment]
r=me when ready!

**Comment by flip1995** [comment]
I'll continue working on fixing the fallout of https://github.com/rust-lang/rust/pull/72389 tomorrow. Now binary operators will be marked as expansions. This broke every lint, that tested for expansion with `span.from_expansion()`. This will require careful evaluation of every `span.from_expansion()` call in the Clippy code base.

**Comment by flip1995** [comment]
TODO:

- [ ] `UNIT_CMP`
- [ ] `BOOL_COMPARISON`
- [ ] `ITERATOR_STEP_BY_ZERO`
- [ ] `STRING_ADD`

In these cases neither `utils::in_macro`, nor `span.from_expansion()` works as expected. We should prepare ourselfs for multiple FN and FP issues because of macros in the near future.

**Comment by Manishearth** [comment]
@flip1995 I think we should be open to asking for that PR to be reverted while we fix this.

**Comment by Manishearth** [comment]
It's a diagnostics PR. If it is causing mass lint breakage, that's a problem, and perhaps its approach is not the best one.

**Comment by flip1995** [comment]
Yeah, I also thought about this.

There is currently the issue, that it seems that expn info is overridden. See the `string_add` example for this: https://github.com/rust-lang/rust-clippy/runs/780962847#step:10:1751

We're checking if the string addition comes from an external macro (what it does)
https://github.com/rust-lang/rust-clippy/blob/742706511c9f33c6a0d4380392e513e5249057e3/tests/ui/string_add.rs#L25

But since we're checking this on the `expr` with `expr.kind == ExprKind::BinaryOp`, it will get the expansion context of `ExpnKind::Desugaring(DesugaringKind::Operator)`, instead of `ExpnKind::Macro`. This means that everytime we find an `expr` with `expr.kind == BinaryOp`, we can't determine, if it is from a macro expansion, unless we check every parent expression (which would definitely be a very bad idea, since I can only imagine how many bugs this would introduce and how inefficient it would be).

**Comment by Aaron1011** [comment]
It sounds like the root issue is that `ExpnKind::Desugaring` and `ExpnKind::Macro` are mutually exclusive. What we really want is to be able to mark a `Span` with some desugaring information, and independently set whether or not it's coming from a macro.

I think the simplest way of achieving this would be to add an `Option<DesugaringKind>` to `ExpnData`, and delete the `Desugaring` variant from `ExpnKind`. I'll open a PR to rustc.

**Comment by Manishearth** [comment]
@flip1995 Oh, the loss of this functionality is _definitely_ a bug in https://github.com/rust-lang/rust/pull/72389 , since macros affect other diagnostics in rustc too.

**Comment by Aaron1011** [comment]
@flip1995: After thinking about this more, I think walking up the 'expansion stack' is actually the correct thing to do.

Consider the following code:

```rust
fn main() {
    if true || true {}
}
```

When we lower the `if` expression, we'll end up with both a `DesugaringKind::CondTemporary` and a `DesugaringKind::Operator` applied to the expression `true || true`. If we store the `DesugaringKind` alongside the existing `ExpnData`, we'll either need to overwrite one of the `DesugaringKind`s, or maintain a list of applied `DesugaringKind`s per `ExpnData`.

I think it would be simpler to have Clippy walk up the 'expansion stack' to check if an `ExpnKind::Macro` or `ExpnKind::AstPass` is present. We should be able to eliminate any performance impact by caching this in `ExpnData` on creation.

**Comment by matthiaskrgr** [comment]
The PR that fixed the ci-ice has been merged now :tada:

**Comment by phansch** [comment]
I believe this is currently waiting on https://github.com/rust-lang/rust/pull/73594, right?

**Comment by Manishearth** [comment]
Yes

**Comment by flip1995** [comment]
@bors r+

Next up: sync Clippy back in Rust repo

**Pull request merged**
