### PR TITLE
Remove `debug_assert` from `panic_in_result_fn`

### PR DESCRIPTION
**Pull request by daxpedda**
I couldn't find any documentation on `debug_assert` that should be remove.
In my humble opinion, I would also like to argue that `todo` and `unreachable` shouldn't trigger this lint?

Related: https://github.com/rust-lang/rust-clippy/issues/6082

r? @flip1995

changelog: Change `panic_in_result_fn` to ignore `debug_assert` and co macros

### CODE REVIEW

**Comment by flip1995** [comment]
`debug_assert` with a message still seems to get linted. I don't really know why off the top of my head.

**Comment by daxpedda** [comment]
That's fine, I just relalized I ran the wrong tests locally, I'm currently attending the rust gamedev meeting but will fix it when I'm done.

**Comment by daxpedda** [comment]
I don't know if this is an appropriate solution.
> In my humble opinion, I would also like to argue that `todo` and `unreachable` shouldn't trigger this lint?

@flip1995 what do you think about that? If this is alright I could just remove `find_macro_calls` and only check with `is_expn_of`.

**Comment by flip1995** [comment]
Since this is a restriction lint, I would leave `unreachable` and `todo` in it. For `unreachable` I'd argue, that you could also return `Err("unreachable code reached")` and `todo!` shouldn't be in the final code anyway. I see that this is opinionated, but `restriction` lints are really specific anyway, so I'm fine with leaving them in the lint and if people disagree they can allow this lint on functions that contains one of those macros. (`allow`ing restriction lints is even more encouraged than allowing normal Clippy lints, if you say that it is okay that a Clippy lint triggers in a specific case).

**Comment by flip1995** [comment]
@bors r+

Thanks!

**Comment by flip1995** [comment]
@bors r+

Thanks!

**Pull request merged**
