### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by camsteffen**

### CODE REVIEW

**Comment by Manishearth** [comment]
Was this done using `git subtree`?

**Comment by camsteffen** [comment]
No...I figured there must a process to this...

**Comment by ebroto** [comment]
@camsteffen take a look [here](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md#fixing-build-failures-caused-by-rust).

Since the first time it takes around 40 mins, I'm going to do it myself this time so we can merge some PRs, but don't hesitate to do it in the future, any help is appreciated :+1:

**Comment by camsteffen** [comment]
Okay, thanks!

**Pull request closed without merging**
