### PR TITLE
Deprecated `if_let_mutex` due to  stabilization in 2024 edition

### LINKED ISSUE #13679: Should disable `if_let_mutex` in 2024 edition
The [`if_let_mutex` rule](https://rust-lang.github.io/rust-clippy/master/index.html#if_let_mutex) should be disabled in the 2024 edition, because the `if…let` scoping issue that motivated it has been fixed in the 2024 edition:

- rust-lang/rust#131154

### PR DESCRIPTION
**Pull request by alex-semenyuk**
Close #13679

As mentioned at #131154 `if_let_rescope` is now stable for Edition 2024, so no need `if_let_mutex`

changelog: [`if_let_mutex`]: deprecation

### CODE REVIEW

**Comment by xFrednet** [comment]
Does the stabilization effect all editions or only Edition 2024 and onwards?

**Comment by alex-semenyuk** [comment]
> Does the stabilization effect all editions or only Edition 2024 and onwards?

Suppose only 2024

**Comment by xFrednet** [comment]
I haven't looked at the lint in detail, but would it make sense to make the linting dependent on the edition instead of deprecating it?

**Comment by alex-semenyuk** [comment]
Make sense, might you know examples such edition dependent issues

**Comment by y21** [comment]
> Make sense, might you know examples such edition dependent issues

`manual_c_str_literals` is one that only lints in Edition >= 2021 crates
https://github.com/rust-lang/rust-clippy/blob/786fbd6d683933cd0e567fdcd25d449a69b4320c/clippy_lints/src/methods/manual_c_str_literals.rs#L29

**Comment by alex-semenyuk** [comment]
When I try to use `//@edition:2024` something like [here](https://github.com/rust-lang/rust-clippy/blob/786fbd6d683933cd0e567fdcd25d449a69b4320c/tests/ui/manual_c_str_literals.rs#L4)
it gives
`error: edition 2024 is unstable and only available with -Z unstable-options`

**Comment by est31** [comment]
One can work around that issue by passing the option manually. I don't know how that test works.

```Rust
//@ compile-flags: -Zunstable-options
```

**Comment by Alexendoo** [comment]
The linked test is fine since it's only editions 2018 and 2021

**Pull request closed without merging**
