### PR TITLE
Rename `integer_arithmetic`

### PR DESCRIPTION
**Pull request by c410-f3r**
The lack of official feedback in #10200 made me give up on pursuing the matter but after yet another use-case that is not handled by `integer_arithmetic` (#10615), I think it is worth trying again.

---

changelog: Move/Deprecation: Rename `integer_arithmetic` to `arithmetic_side_effects`
[#10674](https://github.com/rust-lang/rust-clippy/pull/10674)

### CODE REVIEW

**Comment by Jarcho** [comment]
I'll look into this this week. Just as an initial comment it looks like this would be better as a rename rather than deprecation.

**Comment by Jarcho** [comment]
Sorry, this took longer to get to than expected.

I'm in favour of the change in general. The whole point of `integer_arithmetic` is to prevent silent edge case errors, and other types can definitely have the same problems as the builtin types. Given that this is a restriction lint, anybody using it should be willing to put up with the annoyance of having to configure it to allow operations which are safe to use.

It might be worth having an attribute which can be applied to the trait impls to opt-out of the lint. I don't feel like this needs to be a blocker, just a thing to consider.

An alternative to deprecating it is to just use the implementation of `arithmetic_side_effects`, but check the types of both operands before issuing the lint to determine whether `integer_arithmetic` or `arithmetic_side_effects` should be used. I'm not convinced the split is worth having though.

cc @rust-lang/clippy if anyone has something to add.

**Comment by xFrednet** [comment]
I agree that the merge makes sense, if `arithmetic_side_effects` covers all cases that `integer_arithmetic` has :)

**Comment by Manishearth** [comment]
I'm in favor

**Comment by c410-f3r** [comment]
Thank your very much @Jarcho and @rust-lang/clippy for accepting this proposal. A lot of effort was put into `arithmetic_side_effects` and more development will be applied in future iterations.

**Comment by Jarcho** [comment]
Thank you for pushing this through. @bors r+

**Comment by c410-f3r** [comment]
> Thank you for pushing this through. @bors r+

Thank you!

**Pull request merged**
