### PR TITLE
Return a value from find_format_args instead of using a callback

### PR DESCRIPTION
**Pull request by Alexendoo**
r? @flip1995

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
I haven't reviewed the PR yet. But I don't like the doc comment of `Symbol::as_str`

> in practice it works out ok.

I'll have to look more closely on this PR though, before making a decision.

**Comment by Alexendoo** [comment]
Assuming I've done it correctly it should be less of a crime than `Symbol::as_str`, since it's tied to a lifetime that's shorter than the thread local

**Comment by Jarcho** [comment]
There's nothing that actually stops a `&'static LateContext<'_>` value from existing. `Box::leak` is the easy way to do it, but there are others. `Symbol::as_ref` is unsafe for exactly the same reason as there's nothing stopping `&'static Symbol` from existing.

Neither of these are really a problem in practice, but there isn't a lifetime you can extend to that isn't technically unsafe.

**Comment by Alexendoo** [comment]
Yeah that's true, I've updated the comment a bit

**Comment by Alexendoo** [comment]
I thought about this again today and realised we could stick the `FormatArgs` in an `Rc`, which means it no longer needs any unsafe code since it's not borrowing from the thread local. Updated the PR to use that

**Review by flip1995 — APPROVED** [review]
Wow, turns out if you wait long enough, PR reviews resolve themselves. Sorry for taking so long.

Since this PR doesn't add unsafe code now, it was an easy review.

Thanks!

**Pull request merged**
