### PR TITLE
Rustup to rustc 1.40.0-nightly (29b6e0f0a 2019-10-13)

### PR DESCRIPTION
**Pull request by Manishearth**
changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
````
  Installed package `rustup-toolchain-install-master v1.7.0 (https://github.com/kennytm/rustup-toolchain-install-master#195899b8)` (executable `rustup-toolchain-install-master`)

fetching master commit hash... 

error: https://api.github.com/repos/rust-lang/rust/commits/master: Client Error: 403 Forbidden

error: toolchain 'master' is not installed

info: backtrace:

stack backtrace:

   0: backtrace::capture::Backtrace::new_unresolved::haff523f89eb04bca (0x10e95a46f)

   1: error_chain::backtrace::imp::InternalBacktrace::new::ha5b94c101126b153 (0x10e95739c)

   2: rustup_init::rustup_mode::main::h3b8924610bab40fa (0x10e6631ba)

   3: rustup_init::run_rustup_inner::hf1f793cde0dfdf85 (0x10e6a641f)

   4: rustup_init::main::he6c6720bae5c3813 (0x10e6a59f2)

   5: std::rt::lang_start::{{closure}}::ha3a23e391c100e83 (0x10e63d596)

   6: main (0x10e6aad0a)
````

@bors retry

**Comment by lzutao** [comment]
That's is known problem: https://github.com/kennytm/rustup-toolchain-install-master/issues/28

**Comment by phansch** [comment]
> That is known problem: [kennytm/rustup-toolchain-install-master#28](https://github.com/kennytm/rustup-toolchain-install-master/issues/28)

It's weird that it started happening today, though? It seems unrelated to the recently merged RTIM PRs

@bors retry (Going to give it another try)

**Comment by lzutao** [comment]
Mac builders failed again.

**Comment by flip1995** [comment]
Done in #4663

**Pull request closed without merging**
