### PR TITLE
add `option_as_ref_deref` lint

### LINKED ISSUE #4918: Lint for using Option::as_deref
With Rust 1.40.0, [`Option::as_deref`](https://doc.rust-lang.org/stable/std/option/enum.Option.html#method.as_deref) has landed. 

It would be great to have a clippy lint that detects `Option::as_ref` chained by `Option::map<F> where F: FnOnce(&T) -> &<T as Deref>::Target`. This would then automatically account for cases where `AsRef::as_ref` or a custom method like `String::as_str` are used.

By far the most compelling case is to apply it to `Option<String>` or `Option<PathBuf>`, with probably lots of code bases now containing `opt.as_ref().map(String::as_str)` or similar constructs.

**Example in:**

```rust
let opt = Some(" hello ".to_owned());
let trimmed = opt.as_ref().map(String::as_str).map(str::trim);
```

**Example out:**

```rust
let opt = Some(" hello ".to_owned());
let trimmed = opt.as_deref().map(str::trim);
```

There are probably more cases that could be detected, like `?` chaining or `match` statements, but I think those will get gradually less useful to be worth the effort.

Icing on the cake would be compatibility to rustfix :)

### PR DESCRIPTION
**Pull request by Areredify**
changelog: add a new lint that lints `option.as_ref().map(Deref::deref)` (and similar calls), which could be expressed more succinctly as `option.as_deref[_mut]()`. Closes #4918.

### CODE REVIEW

**Comment by mikerite** [comment]
I found a case where the lint gives a bad suggestion.

```
fn main() {
    let s: String = String::from("STRING");

    let _: Option<&str> = Some(&s).as_ref().map(|x| x.as_str());
    let _: Option<&String> = Some(&s).as_deref();
}
```
```
warning: called `.as_ref().map(Deref::deref)` (or with one of deref aliases) on an Option value. This can be done more directly by calling `Some(&s).as_deref()` instead
 --> src/main.rs:6:27
  |
6 |     let _: Option<&str> = Some(&s).as_ref().map(|x| x.as_str());
  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try using as_deref instead: `Some(&s).as_deref()`
```

This suggestion won't work because the type of `Some(&s).as_ref().map(|x| x.as_str())`  isn't the same type as `Some(&s).as_deref()`.

**Comment by Areredify** [comment]
I knew deref coercion would screw me over somewhere, should've created a test for that myself, thanks for noticing. I thought coercion is already explicit in hir but I guess it is not?

**Comment by flip1995** [comment]
Maybe we can check the type of `x.as_ref().map(..)` calls and check if `expr_ty(x)` has `Deref::Target` of the type of the `map(..)` call and only lint in this case.

**Comment by Areredify** [comment]
@flip1995 I am a little puzzled with getting `<T as Deref>::Target` type, maybe you can point me in the right direction?

**Comment by mikerite** [comment]
I think you can just check if `x` (i.e. the `as_str()` receiver) has any adjustments applied to it.

Here is my reasoning...

`o.as_def()` is ```o.as_ref().map(|x| x.deref())```.  So replacing ```o.as_ref().map(|x| x.as_str());``` with ```o.as_deref()``` boils downs to whether you can replace ```x.as_str()``` with ```x.deref()```. IMO, this should be the safe as long as there are no adjustments (autorefs, autoderefs) applied to `x` in ```x.as_str()```.

**Comment by Areredify** [comment]
@mikerite That was my reasoning as well when I was implementing it. Currently I am checking whether the first argument to `as_str` is a `QPath` that resolves to the input parameter of the closure. I thought that would be enough, bur apparently autoderef information is stored somewhere else (and not in the coercion table, because that one is empty) and is not explicitly converted to hir (`x.as_str()` is still `x.as_str()` in hir and not `(*x).as_str()`). I think I'll just check that `x`'s type is the same as `as_str`'s input parameter type (but I would welcome a more straightforward solution)

**Comment by mikerite** [comment]
Try the `is_adjusted` method in `utils`.

**Comment by flip1995** [comment]
> I am a little puzzled with getting `<T as Deref>::Target` type, maybe you can point me in the right direction?

I'm not sure myself. Somehow get the `Item` of the `Deref` impl of the type of `x` and the check the associated item `Target`. For types not implementing `Deref` explicitly is as easy as calling [`builtin_deref`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TyS.html#method.builtin_deref). But maybe this is too hard, idk.

**Comment by Areredify** [comment]
I presumably fixed it, can anybody think of any more tests to add?

**Comment by flip1995** [comment]
A macro test would be good

**Comment by pickfire** [comment]
Maybe `as_ref().map(|c| &**c)` to `as_deref()` too? Got it from @lzutao

**Comment by Areredify** [comment]
Lets merge this for now, I'll probably add `|x| &**x` later

**Comment by shepmaster** [comment]
> Lets merge this for now, I'll probably add `|x| &**x` later

Is this being tracked anywhere? That's how I tend to write this case.

**Comment by flip1995** [comment]
Good catch! It is now: #5367

**Pull request merged**
