### PR TITLE
Downgrade integer_division to restriction

### PR DESCRIPTION
**Pull request by dtolnay**
I believe that this lint falls outside of the scope of opinionated pedantism of the other pedantic lints. 

changelog: Downgrade integer_division lint from pedantic to restriction

### CODE REVIEW

**Comment by dtolnay** [comment]
The lint's justification is:

> **Why is this bad?** When outside of some very specific algorithms, integer division is very often a mistake because it discards the remainder.

I question whether there is evidence that this is "very often" the case. Out of the number of times that integer division has been used in Rust, what fraction of them were mistakes that should have used float division instead? Less than 1%?

I have no problem with it as a restriction for someone who consciously decides they want to avoid integer division in their code.

**Comment by dtolnay** [comment]
```console
error: integer division
 --> $DIR/integer_division.rs:7:13
  |
7 |     let p = a / b;
  |             ^^^^^
  |
  = help: division of integers may cause loss of precision. consider using floats.
```

Consider whether pushing people to use float division will fix more problems than it solves. In reality, using unnecessary float division instead of integer division is what often causes loss of precision.

```rust
fn main() {
    let numerator: u32 = 12_345_678 * 3;
    let denominator = 3;
    println!("integer quotient: {}", numerator / denominator);
    println!("float quotient:   {}", numerator as f32 / denominator as f32);
}
```

```console
integer quotient: 12345678
float quotient:   12345677
```

The integer quotient is exactly correct while the float quotient loses precision.

This lint seems intended to help people who don't yet have a firm grasp of the difference between integer and float, but I think it will do more harm than good for that group.

**Comment by mikerite** [comment]
This lint will have 99% false positive rate. (It triggers on _all_ integer division which means every instance of integer division is either a bug or a false positive.) In its current form, it's just going to annoy people. It be great if we could move this to restriction before 1.36 is released.

**Pull request merged**
