### PR TITLE
Changelog for Clippy 1.80 🌞 

### PR DESCRIPTION
**Pull request by xFrednet**
Roses are red,
Violets are blue,
Summer is fun,
So much sun

---

### The cat of this release is *Maunzer* submitted by @llogiq:

The cats of this Clippy release

Cats for the next release can be nominated in the comments :D

---

changelog: none

I wish everyone reading this a beautiful and happy day =^.^=

### CODE REVIEW

**Review by dswij — APPROVED** [review]
Thanks for writing up the changelog!

---

Please say hello to Maunzer for me

**Comment by llogiq** [comment]
Will do!

**Comment by llogiq** [comment]
Update: Maunzer got fresh chicken meat as a reward for his hard work that made him this release's cat.

His response was licking both his eyebrows.

**Comment by Alexendoo** [comment]
https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html

@bors r=dswij

**Pull request merged**
