### PR TITLE
[blocked] attempt to check rust-lang/rust with clippy in ci

### PR DESCRIPTION
**Pull request by matthiaskrgr**
r? @ghost

changelog: run clippy on rust-lang/rust as integration test 

This might be blocked on at least 
https://github.com/rust-lang/rust-clippy/issues/11230
https://github.com/rust-lang/rust-clippy/issues/11176
https://github.com/rust-lang/rust-clippy/issues/11256

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
wut that is outdated
@bors try

**Comment by matthiaskrgr** [comment]
/usr/bin/env: ‘python3’: No such file or directory
 lol
 @bors retry

**Comment by matthiaskrgr** [comment]
Hmm, so x.py does not find clippy.
https://github.com/rust-lang/rust-clippy/actions/runs/5685154608/job/15409484699#step:8:1426
we dont formally install the self-built clippy.
I tried to hack around via PATH but maybe even that does not help.

Maybe we can just copy the clippy bins from the target directory into ~/.rustup/... or  ~/.cargo/bin?
Although I would hate that when someone attempts to run these tests locally :sweat_smile:

**Comment by matthiaskrgr** [comment]
urgh I think we need to copy everything from the `target/$PROFILE` directory into ~/.rustup/<rustc-version>/bin/  :|

**Comment by matthiaskrgr** [comment]
not my proudest work :joy: 
@bors try

**Comment by matthiaskrgr** [comment]
still no change since  https://github.com/rust-lang/rust-clippy/pull/11235#issuecomment-1682755174 :/

**Comment by xFrednet** [comment]
Hey @matthiaskrgr, this is a ping from triage. Are you still working on this PR?

**Comment by matthiaskrgr** [comment]
I thiiink we can sunset it since there have been a lot of improvements in rustc including running clippy in ci there.

unless someone else feels strongly and definitely wants this here?

**Comment by xFrednet** [comment]
I'm fine with how it is, but this is something @flip1995 might have some thoughts on since he does the syncs.

Otherwise we can close this PR :)

**Comment by xFrednet** [comment]
Hey this is triage, I'm closing this due to inactivity. I think our current CI is sufficient and if not we can crate a new PR

**Pull request closed without merging**
