### PR TITLE
 more Use->DropTemps fixes 

### PR DESCRIPTION
**Pull request by matthiaskrgr**
changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
````
Running Install scripts
curl -sSf -o rustup-init.exe https://win.rustup.rs/
curl: (6) Could not resolve host: win.rustup.rs
Command exited with code 6
````
@bors retry

**Comment by Manishearth** [comment]
@bors retry

```
detecting the channel of the `9b67bd42b7cbf97f72d039afcba02f5177d0d68c` toolchain...
error: https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds/9b67bd42b7cbf97f72d039afcba02f5177d0d68c/rust-src-nightly.tar.xz: error trying to connect: No such host is known.
```

**Comment by Manishearth** [comment]
@bors r+

can't retry after a push

**Pull request merged**
