### PR TITLE
New lint: `empty_enum_variants_with_brackets`

### LINKED ISSUE #12007: Detect Enum Objects with empty attribute body using `{}`
### What it does

The proposed lint feature aims to improve code readability and consistency by discouraging the use of empty attribute objects `{}` succeeding structures without attributes. In Rust, empty attribute objects are often used to represent variants of an enum that carry no additional information. However, this usage can be misleading and may result in less expressive and clear code.

This lint feature shall check for the presence of empty attribute objects {} immediately following enum variants without associated data. If such a pattern is detected, the lint will emit a warning. This warning encourages developers to reconsider the necessity of the empty attribute object and suggests using the enum variant directly without the unnecessary attribute object.

### Advantage

- Prevent Code Blow, simplify code.

### Drawbacks

_No response_

### Example

```rust
pub enum Decoder {
    Absent {},
    Symbol(u8)
}


#[derive(Debug, thiserror::Error)]
pub enum CustomError {
    #[error("This is a custom error without attributes.")]
    CustomError { },
}

type Result<T, E = CustomError> = std::result::Result<T, E>;

impl Decoder {
    /// # Errors
    /// 
    /// May return an error..
    pub fn decode(&mut self, input: u64) -> Result<u8> {
            if input > 1 { return Err(CustomError::CustomError { })};

            match self {
                Decoder::Symbol(symbol) => {
                    Ok(*symbol)
                }
                Decoder::Absent{} => {
                    Ok(b'i')
                }
            }
    }
}

```
Could be written as:

```rust
pub enum Decoder {
    Absent,
    Symbol(u8)
}

#[derive(Debug, thiserror::Error)]
pub enum CustomError {
    #[error("This is a custom error without attributes.")]
    CustomError,
}

type Result<T, E = CustomError> = std::result::Result<T, E>;

impl Decoder {
    /// # Errors
    /// 
    /// May return an error..
    pub fn decode(&mut self, input: u64) -> Result<u8> {
            if input > 1 { return Err(CustomError::CustomError)};

            match self {
                Decoder::Symbol(symbol) => {
                    Ok(*symbol)
                }
                Decoder::Absent => {
                    Ok(b'i')
                }
            }
    }
}
```

In both cases, the nursery and the pedantic mode of `clippy` do not output any warnings nor errors. To prevent code blow, structures without attributes shall not be allowed to be succeeded by an empty attribute object, `{}`. The example shall result in a warning, while the second one should not.
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by ARandomDev99**
This lint checks for enum variants that don't have any fields but are declared using brackets.

Closes #12007 

changelog: new lint: [`empty_enum_variants_with_brackets`]

### CODE REVIEW

**Comment by J-ZhengLi** [comment]
Hi :smiley_cat: 

Since this code logic shares a lot common with [`empty_struct_with_brackets`], for example those functions are exactly the same, I think you can merge these two files together, **but keep them as separated lints**. 

That means have the `declare_lint_pass!` change to something like... : 

```rust
declare_lint_pass!(EmptyWithBrackets => [
    EMPTY_ENUM_VARIANTS_WITH_BRACKETS,
    EMPTY_STRUCTS_WITH_BRACKETS,
]);
```
and in that `EarlyLintPass` impl, move your lint logic there: 

```rust
impl EarlyLintPass for EmptyWithBrackes {
    /// code for empty_structs_with_brackets... bla bla
    fn check_item()

   /// your logic...
    fn check_variant()
}
```

reduces repeating code

**Comment by ARandomDev99** [comment]
That makes sense. I shall make these changes.

**Comment by ARandomDev99** [comment]
I'll be opening another PR after making the suggested changes.

**Comment by llogiq** [comment]
Feel free to add `r? @llogiq` to the description so I get to review it, as I already have the relevant context.

**Comment by ARandomDev99** [comment]
@llogiq another PR I've opened regarding this issue has already been merged. :)

**Pull request closed without merging**
