### PR TITLE
Enable test empty_loop_no_std on windows

### PR DESCRIPTION
**Pull request by alex-semenyuk**
Verified that it actully works on windows
changelog: none

### CODE REVIEW

**Review by dswij — APPROVED** [review]
Thanks!

I couldn't find the reason we're ignoring this though, curious about this.

**Comment by xFrednet** [comment]
I'm guessing it has something to do with the Compiler flag? 🤔

**Comment by alex-semenyuk** [comment]
Not sure why, but seems it was here https://github.com/rust-lang/rust-clippy/pull/5086 Probably, @Areredify remember why so?

**Comment by dswij** [comment]
Well if the test is passing, I guess it's fine then. Thanks again for this!

@bors r+

**Pull request merged**
