### PR TITLE
don't remove `dbg!` in arbitrary expressions

### LINKED ISSUE #9914: `dbg_macro` removes empty dbg! macro
### Summary

.

### Lint Name

dbg_macro

### Reproducer

I tried this code:

```rust
fn main() {
    let _: () = dbg!();
}
```

I saw this happen:
` cargo clippy --fix -- -Aclippy::all -Wclippy::dbg_macro`
```
    Checking clpy v0.1.0 (/tmp/clpy)
warning: failed to automatically apply fixes suggested by rustc to crate `clpy`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error: expected expression, found `;`
 --> src/main.rs:2:17
  |
2 |     let _: () = ;
  |                 ^ expected expression

error: aborting due to previous error

Original diagnostics will follow.

warning: `dbg!` macro is intended as a debugging tool
 --> src/main.rs:2:17
  |
2 |     let _: () = dbg!();
  |                 ^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#dbg_macro
  = note: requested on the command line with `-W clippy::dbg-macro`
help: ensure to avoid having uses of it in version control
  |
2 -     let _: () = dbg!();
2 +     let _: () = ;
  |

warning: `clpy` (bin "clpy") generated 1 warning (run `cargo fix --bin "clpy"` to apply 1 suggestion)
warning: failed to automatically apply fixes suggested by rustc to crate `clpy`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error: expected expression, found `;`
 --> src/main.rs:2:17
  |
2 |     let _: () = ;
  |                 ^ expected expression

error: aborting due to previous error

Original diagnostics will follow.

warning: `clpy` (bin "clpy" test) generated 1 warning (1 duplicate)
    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
```

I expected to see this happen:

### Version

```text
rustc 1.67.0-nightly (c5d82ed7a 2022-11-19)
binary: rustc
commit-hash: c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b
commit-date: 2022-11-19
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by y21**
Fixes #9914

The `dbg_macro` lint replaces empty `dbg!` invocations with the empty string in its suggestion, which is not always valid code in certain contexts (e.g. `let _ = dbg!();` becomes `let _ = ;`). This PR changes it to `()`, which should always be valid where `dbg!()` is valid (`dbg!()` with no arguments evaluates to `()`).

It also special-cases "standalone" `dbg!();` expression statements, where it will suggest removing the whole statement entirely like it did before.

changelog: [`dbg_macro`]: don't remove `dbg!()` in arbitrary expressions as it sometimes results in syntax errors

### CODE REVIEW

**Comment by Jarcho** [comment]
Does this work properly when `dbg!()` is expanded from another macro? e.g. `foo!();` where `foo!()` expands to `dbg!()`.

**Comment by y21** [comment]
> Does this work properly when `dbg!()` is expanded from another macro? e.g. `foo!();` where `foo!()` expands to `dbg!()`.

Hmm it seems like it breaks if the `dbg!()` is passed as an expr metavariable
```rs
macro_rules! foo {
    ($x:expr) => { $x; };
}

fn main() {
    foo!(dbg!());
}
```
```
warning: the `dbg!` macro is intended as a debugging tool
  --> test.rs:16:10
   |
16 |     foo!(dbg!());
   |          ^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#dbg_macro
note: the lint level is defined here
  --> test.rs:1:9
   |
1  | #![warn(clippy::dbg_macro)]
   |         ^^^^^^^^^^^^^^^^^
help: remove the invocation before committing it to a version control system
   |
16 -     foo!(dbg!());
16 +     foo!(
   |
```
so perhaps my way of checking if we're allowed to remove the `dbg!()` by checking if the parent node is a `StmtKind::Semi` is not that reliable.

**Comment by Jarcho** [comment]
I think the only thing you can do here is to start tokenizing from the end of the call site and see if the first non-whitespace token is a semicolon.

**Comment by y21** [comment]
Alright, it's not exactly pretty but it works.

**Comment by Jarcho** [comment]
It works, so...

Thank you. @bors r+

**Pull request merged**
