### PR TITLE
Add check if ty has_escaping_bound_vars in zero_sized_map_values lint

### PR DESCRIPTION
**Pull request by DevinR528**
Fixes: #7447

changelog: fix ICE in [`zero_sized_map_values`]

### CODE REVIEW

**Comment by DevinR528** [comment]
Not exactly sure if this is the best way, it seems that checking for `Cow` here would also work but the way it is now, seems more robust since that is the method call causing the ICE?

**Comment by flip1995** [comment]
I think this is a more general problem in Clippy. The same error with `layout_of` happened to me yesterday, when I did the rustup. The fix was the same. Clippy has about 20 calls to `layout_of`. So maybe we should implement a utils function for this, which calls `has_escaping_bound_vars` before calling `layout_of`?

**Comment by flip1995** [comment]
Let's ask about it: https://github.com/rust-lang/rust/pull/86867#issuecomment-881255693

**Comment by DevinR528** [comment]
Cool in a day or so I can just preemptively add this to all the `layout_of` calls, but I will follow the conversation in the rust repo.

**Comment by flip1995** [comment]
> can just preemptively add this to all the `layout_of` calls,

Yeah. Or better: implement a ``clippy_utils::layout_of``, that looks like this:

```rust
fn layout_of(cx: LateContext, ty: Ty) -> Option<_> {
    if ty.has_escaping_bound_vars() {
        return None;
    }
    cx.tcx.layout_of(ty)
}
```

If you don't have time for it, let me know and I'll do this tomorrow. We have to sync back those fixes before the release in 1 and a half weeks.

**Comment by flip1995** [comment]
Since we didn't get any more reports on this, I'm holding off from replacing all of the `layout_of` calls for now. I have a patch ready here: https://github.com/flip1995/rust-clippy/tree/layout_of-util

@bors r+

**Comment by DevinR528** [comment]
Cool thanks! Sorry I didn't get around to it I was doing a bit more traveling than I thought I'll keep an eye on any ICE that could be related.

**Pull request merged**
