### PR TITLE
test that we correctly detect panics in intergation tests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
should be merged after https://github.com/rust-lang/rust-clippy/pull/11225 

changelog: add test for integration tests

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Ah yes, forgot a `return` :rofl: 
@bors try

**Comment by matthiaskrgr** [comment]
Perfect: so on current master (broken integration tests) this now successfully detects the panic :tada: 
https://github.com/rust-lang/rust-clippy/actions/runs/5660689271/job/15337050597#step:7:21

once https://github.com/rust-lang/rust-clippy/pull/11225 is merged, this one should merge fine as well

**Review by flip1995 — APPROVED** [review]
r=me once the other PR is merged.

**Pull request merged**
