### PR TITLE
fix missing a semicolon

### PR DESCRIPTION
**Pull request by rchaser53**
related: https://github.com/rust-lang/rust-clippy/issues/3849

### CODE REVIEW

**Comment by flip1995** [comment]
That was fast. Thanks!

@bors r+

**Comment by mati865** [comment]
What is that `main` file?

**Comment by phansch** [comment]
> What is that `main` file?

huh, it even seems to have some history: https://github.com/rust-lang/rust-clippy/commits/master/main

We should remove it again and add it to the .gitignore?

**Comment by mati865** [comment]
The problem with binary files and git is you cannot totally remove all their remains and keep linear history. After removing it from the tree it will still remain inside `.git/` as a diff.
It's not big deal when single 1 MiB file slips through but if it was 100 MiB debug artifact the problem would be real and the only fix would be to rewrite history of commit that included it and force push.

Maybe `bors` should prevent committing binary files with simple `r+` and require instead `r+ binary` because it's usually not what you want to do?

**Pull request merged**
