### PR TITLE
style: sync GitHub Corner colors

### LINKED ISSUE #12349: GitHub Corner colors don't sync with the rest of the page
### Description

image

### Version

_No response_

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #12349.

*Please write a short comment explaining your change (or "none" for internal only changes)*

changelog: sync site GitHub Corner colors

### CODE REVIEW

**Comment by hamirmahal** [comment]
# Without this change

[Screencast from 02-25-2024 11:38:25 AM.webm](https://github.com/rust-lang/rust-clippy/assets/43425812/bb8d9c5b-8340-4833-94fb-6272996f33e0)

**Comment by hamirmahal** [comment]
# With this change

[Screencast from 02-25-2024 11:39:55 AM.webm](https://github.com/rust-lang/rust-clippy/assets/43425812/234e64cb-4b6d-4cf5-9eff-daac48951e19)

**Review by xFrednet — APPROVED** [review]
The changes to adapt the color to the theme look good to me. I liked the shadow cat beforehand as well, but this is nicer :D

The last time, you were able to undo the formatting, to keep the original one, can you do the same for this PR?

Some context for the formatting: I don't have anything against this formatting or another one. It's more the fact that everyone might have different settings, and the next PR might then reformat everything again.

For Rust we have rustfmt which enforces the same format everywhere, but we have nothing like that for HTML. We could potentially add one to the CI, but I don't really think it's worth it.

**Comment by hamirmahal** [comment]
Absolutely! That all makes sense. I just updated the commits.

**Comment by xFrednet** [comment]
Perfection, like last time. Thank you very much :D

@bors r+

**Comment by hamirmahal** [comment]
You're welcome! And thank you.

**Pull request merged**
