### PR TITLE
Move `needless_pass_by_ref_mut`: `suspicious` -> `nursery`

### PR DESCRIPTION
**Pull request by blyxyas**
[Related to [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/needless_pass_by_ref_mut.20isn't.20ready.20for.20stable)]

`needless_pass_by_ref_mut` has been released with some important bugs (notably having a lot of reported false positives and an ICE). So it may not be really ready for being in stable until these problems are solved. This PR changes the lint's category from `suspicious` to `nursery`, just that.
changelog: none

### CODE REVIEW

**Comment by Jarcho** [comment]
The changes to the other tests isn't needed, they should only need to be blessed. `needless_pass_by_ref_mut` should have been allowed on those tests in the first place.

**Comment by blyxyas** [comment]
Oh, you're right. I'll change those right now.

**Comment by Jarcho** [comment]
One more time. @bors r+

**Pull request merged**
