### PR TITLE
Rename run_lints -> lints_enabled

### PR DESCRIPTION
**Pull request by flip1995**
Just a quick rename of a utilities function. `run_lints` kinda suggested that the lints were run by this function. But the only thing this function does is to check if the lints are enabled in the context of the `hir_id`

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
rust-highfive bot was down because of a invalid json file https://github.com/rust-lang/highfive/pull/343

**Comment by camsteffen** [comment]
Can we just remove it and use `is_allowed` instead? We're always passing a single `LintId` anyways. Maybe rename to `is_lint_allowed`. I've always though `is_allowed` is too vague. But I think I'd prefer "allowed" to the opposite "enabled" because it refers to a specific `Level`. "enabled" doesn't really correspond to a rustc concept. Also `run_lints` is missing `Level::ForceWarn`.

**Comment by camsteffen** [comment]
One more thought. We could have a variant that uses `LateContext::last_node_with_lint_attrs`, similar to `span_lint`. So we could have `is_lint_allowed` and `is_lint_allowed_at`.

**Comment by flip1995** [comment]
> Can we just remove it and use `is_allowed` instead?

Oh I missed `is_allowed` when I added the `run_lints` function. I agree with your analysis and will rename `is_allowed` to `is_lint_allowed` and remove `lints_enabled`.

**Pull request merged**
