### PR TITLE
Demote float_cmp to pedantic

### PR DESCRIPTION
**Pull request by workingjubilee**
See this issue: https://github.com/rust-lang/rust-clippy/issues/7666

This is one of the most frequently suppressed lints. It is deny-by-default. It is not actually clearly wrong, as there are many instances where direct float comparison is actually desirable. It is only after operating on floats that they may lose precision, and that depends greatly on the operation. As most correctness lints have a much higher standard of error, being based on hard and fast binary logic, this should not be amongst them.

A linter is not a substitute for observing the math carefully and running tests, and doing the desirable thing is even more likely to lead one to want exact comparisons.

changelog: Demote [`float_cmp`] from correctness to pedantic lints

### CODE REVIEW

**Comment by giraffate** [comment]
IMO at least it should be `suspicious` (warn-by-default). `restriction` looks good too, but I want to hear other opinions.

@rust-lang/clippy do you have any opinions on this?

**Comment by camsteffen** [comment]
I think the FP rate is too high for warn-by-default.

**Comment by Manishearth** [comment]
I'm not sure if this should be _restriction_, but perhaps pedantic?

**Comment by workingjubilee** [comment]
That sounds fair. Pedantic **is** for "lints which are rather strict or might have false positives".

I did consider suspicious briefly, but I took a closer look at actual use and found that people are often using float equality for the right reasons and getting heat from clippy then. e.g. #2834. And the guidance from the lint is itself a touch questionable, as mentioned in #6816. If it was honed in so that it mostly didn't fire on the "right" uses, and the guidance was unambiguously Good, maybe suspicious would be best, because then silencing it would be a "yes, I know what I am doing" signal. As-is, it's a bit much and risks mis-teaching the subject.

I am happy with pedantic, so let's go with that?

**Comment by camsteffen** [comment]
I'm a little on the fence since I think this may have a high FP rate even for the pedantic category. But I'm okay with pedantic.

The lint docs probably should have a Known problems section.

**Comment by giraffate** [comment]
Thanks for comments!

I'm thinking of merging this as is, since it should at least be allow-by-default. And the categories can be discussed in another issue. If it looks good, I'll merge this later.

**Comment by dtolnay** [comment]
SGTM. I filed #7725 to follow up.

**Review by giraffate — APPROVED** [review]

**Comment by giraffate** [comment]
@bors r+

Thanks!

**Pull request merged**
