### PR TITLE
Fixed FP for `thread_local_initializer_can_be_made_const` for `os_local`

### PR DESCRIPTION
**Pull request by PartiallyTyped**
`os_local` impl of `thread_local` — regardless of whether it is const and unlike other implementations — includes an `fn __init() -> EXPR`.

Existing implementation of the lint checked for the presence of said function and whether the expr can be made const. Because for `os_local` we always have an `__init()`, it triggers for `const` qualified and `const`-qualifiable.

The solution is to check whether the `__init()` function is already const. If it is `const`, there is nothing to do. Otherwise, we can make it `const`.

changelog: [`THREAD_LOCAL_INITIALIZER_CAN_BE_MADE_CONST`]: fixed FP for `os_local` implementation of `thread_local_inner!`.

### CODE REVIEW

**Comment by PartiallyTyped** [comment]
I am not sure how to verify this. @petrochenkov If you don't mind, could you verify it?

**Comment by llogiq** [comment]
I'd agree that this should have some kind of test, or alternatively an explanation why it cannot be tested.

**Comment by PartiallyTyped** [comment]
@llogiq does the clippy test-suite include a cygwin backend?

**Comment by llogiq** [comment]
No, we currently don't have cygwin. I'd like to understand the difference that makes to the lint, though.

**Comment by PartiallyTyped** [comment]
The difference relates to which implementation is used. Threadlocal has 3 implementations whivh get conditionally compiled based on the platform.

For windows, threadlocal uses os native threads, for linux it uses llvm and `thread_local_fast`. Finally for wasm there is a "static" implementation.

For the former, we always have an init function regardless of whether the expression is const. If threadlocal is const, the function is a const fn.

For thread local fast, if const is used, the value is used directly by threadlocal, and we don't have the init fn. if there is no const, an init fn is used.

For static, there is no init fn either. 

So with the lint we check if we are in init fn. 
We then check if we can make the function const and with the changes if the function isn't already const. 


Does this make sense?

**Comment by mati865** [comment]
Wouldn't Cygwin (once and if it's added) use Windows implementation since it runs on Windows? Or does it provide some wrappers to emulate Unix thread-local?

**Comment by PartiallyTyped** [comment]
Cygwin will use the os native implementation once added, yes.

**Comment by llogiq** [comment]
We have a few windows-specific tests already (I believe we used to put them in a "ui.windows" test subfolder or some such. Could that work in this case?

**Comment by m-rph** [comment]
@llogiq I don't think the tests are actually running in the build scripts. `Clippy test` workflow only has ubuntu as a target.

**Comment by llogiq** [comment]
That's ok, I have a Windows partition I can run those tests on locally.

**Comment by m-rph** [comment]
Ok, so in theory if you run the code as-is, right now, it should fail because of differences between `.stderr` files.

**Pull request closed without merging**
