### PR TITLE
Add partialeq_to_none lint

### PR DESCRIPTION
**Pull request by lukaslueg**
Initial implementation of #9275, adding lint `partialeq_to_none`. This is my first time working on `clippy`, so please review carefully.

I'm unsure especially about the `Sugg`, as it covers the entire `BinOp`, instead of just covering one of the sides and the operator (see the multi-line example). I was unsure if pinpointing the suggestion wouldn't be brittle...

changelog: [`PARTIALEQ_TO_NONE`]: Initial commit

### CODE REVIEW

**Comment by Jarcho** [comment]
Implementation looks fine. Two things before merging:

* Should this be a `style` lint or a `pedantic` lint. I'm leaning towards `style`.
* I don't particularly like `PartialEq` in the lint name. There's nothing really wrong with it and it's not misleading, but it seems like unnecessary detail. `eq_none` might be better.

**Comment by lukaslueg** [comment]
```rust
          // We are only interested in comparisons between `Option` and a literal `Option::None`
          let scrutinee = match (
              is_none_ctor(left_side) && is_ty_option(right_side),
              is_none_ctor(right_side) && is_ty_option(right_side),
          ) {
              (true, false) => right_side,
              (false, true) => left_side,
              _ => return,
          };
```

Do we even need the `is_ty_option()` (don't mind the `right_side` bug 👀😅) to rule out comparisons like `1f32 == None`? AFAICS, as a `LateLintPass` comes after type-resolution, non-applicable comparisons are already ruled out?!

**Comment by lukaslueg** [comment]
Also: `x != &None` does not trigger because the `Expr` `&None` is not `is_lang_ctor(.., .., LangItem::OptionNone)`. How to peel off the references from a `QPath` akin to `Ty::peel_refs`?

**Comment by Jarcho** [comment]
You do need to check for an option type as `PartialEq` can be implemented across types.

You can use `clippy_utils::peel_hir_expr_refs`.

**Comment by lukaslueg** [comment]
Moving from `nursery` to `style` enables the lint by default, which causes it to get triggered in other ui-tests. For instance:

https://github.com/rust-lang/rust-clippy/blob/5721ca9a13562f5168c6ba9f43dc19bb76c6f7bb/tests/ui/manual_assert.rs#L19-L21

Should I update the triggering code in the ui-tests, bless the results, or `allow(clippy::partialeq_to_none)` in those ui-tests?

**Comment by Jarcho** [comment]
Normally adding `allow` in tests is the better approach. It's possible the change can cause the test to no longer function.

For the lint name, use whichever one you prefer.

**Comment by lukaslueg** [comment]
I've had to make some changes to get the suggestions right (see the `Box`-example). LGTM

**Comment by Jarcho** [comment]
Looks good. You can squash the changes.

**Review by Jarcho — APPROVED** [review]

**Comment by lukaslueg** [comment]
Squashed

**Comment by Jarcho** [comment]
Thank you. @bors r+

**Comment by trevyn** [comment]
I'm hitting this lint for code of the form `foo == option_env!("BAR")`, is that intended?

**Comment by llogiq** [comment]
Perhaps we should add a macro check for the `None` expr.

**Comment by lukaslueg** [comment]
@trevyn Thanks for the comment. The lint is certainly wrong as it would hardcode whatever `option_env` expanded to _at that time_.

**Pull request merged**
