### PR TITLE
Remove paths::STD_PTR_NULL

### PR DESCRIPTION
**Pull request by boxdot**
Related to #5393

changelog: none

### CODE REVIEW

**Comment by boxdot** [comment]
Looks like this is partially done in #7049. Feel free to close.

**Comment by camsteffen** [comment]
Thanks! I'll go ahead and merge this since it's ready and #7049 has some pending re-work.

@bors r+

**Comment by camsteffen** [comment]
Not sure what happened...

@bors retry

**Comment by camsteffen** [comment]
Oh the post was missing "changelog"

@bors retry

**Pull request merged**
