### PR TITLE
6399 Lint: is_ascii_digit instead of is_digit

### PR DESCRIPTION
**Pull request by rajcspsg**
`changelog: none`

### CODE REVIEW

**Review by ebroto — CHANGES_REQUESTED** [review]
Hi @rajcspsg and welcome to Clippy!

The objective of this issue is to create a lint that detects `c.is_digit(10)` and `c.is_digit(16)` and suggests changing that code to `c.is_ascii_digit()` and `c.is_ascii_hexdigit()` respectively. After implementing that lint, running clippy will suggest the changes you made to the code manually.

Take a look at the following docs:
* [Basics for hacking on Clippy](https://github.com/rust-lang/rust-clippy/blob/master/doc/basics.md)
* [Adding a new lint](https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md)
* [Common tools for writing lints](https://github.com/rust-lang/rust-clippy/blob/master/doc/common_tools_writing_lints.md)

These will help you to get started. In case you have any doubt, you can ask a question on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/clippy) or in this same PR.

**Comment by ebroto** [comment]
Also, you can take a look at other PRs that add lints, like #6394, to get an idea of what is needed.

Happy hacking!

**Comment by giraffate** [comment]
ping from triage @rajcspsg. Do you have any questions on how to proceed here?

**Comment by rajcspsg** [comment]
@giraffate - I'm facing below issue in my local 

```    
    $ cargo test
    error: failed to run `rustc` to learn about target-specific information

    Caused by:
    process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Zunstable-options --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
    --- stderr
    error: the option `Z` is only accepted on the nightly compiler
```
I tried these options -

1. `cargo +nightly rustc -- -Z external-macro-backtrace`
2. `rustup default nightly`

Even after I did `rustup default nightly` I'm seeing the rust version is `rustc 1.48.0 (7eac88abb 2020-11-16)`
I don't know how to fix this issue. Any idea on this

**Comment by giraffate** [comment]
@rajcspsg Can you do a rebase? `nightly-2020-12-14` is pinned by `rust-toolchain` file on master branch.
Also, you might look at  `${RUSTUP_HOME}/settings.toml` to check if you have a override on Clippy repo. `rustup override unset` might be useful if you had a override.

**Comment by ebroto** [comment]
According to the triage procedure, I should close this PR as there has been no activity and two weeks have passed since the last ping.

@rajcspsg did @giraffate suggestions help? Can we help you with another issue? Do not hesitate to reopen this in case you are working on it.

**Pull request closed without merging**
