### PR TITLE
Rustup to rustc 1.36.0-nightly (f843ad60e 2019-04-30)

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by Centril** [comment]
r=me with green travis... :)

**Comment by phansch** [comment]
Just fyi, I restarted the Travis MacOS job as it failed to download the master toolchain (https://travis-ci.com/rust-lang/rust-clippy/jobs/196530782) I hope that bors can still detect that as a passing build, even with a restarted job.

**Pull request merged**
