### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by Jarcho**
Hopefully this is done right.

changelog: None

### CODE REVIEW

**Comment by Jarcho** [comment]
Wonderful. Disk space issues again.

**Comment by Jarcho** [comment]
There doesn't seem to be much extra disk space used. Is there a reason `CARGO_INCREMENTAL=0` isn't being used? It cuts used disk space down to a quarterish.

**Comment by Jarcho** [comment]
The size of incremental builds looks to have gone up quite a bit recently. These are the sizes on windows after running `cargo test --features internal`:

| | master | merge | increase | 
| --- | ---: | ---: | ---: |
| incremental | 4.61 GB | 5.33 GB | 15% |
| non-incremental | 1.63 GB | 1.77GB | 8% |

The sizes get worse as tests are run for each crate. The clippy_lints rlib is over 1GB in size for incremental builds and running tests for each crate results in multiple copies. For reference it's a little over 200MB for non-incremental builds.

---
 
ping @flip1995 @Manishearth if we're ok with changing CI away from incremental builds. An alternative would be to somehow up the disk space given to the test runner.

**Comment by Manishearth** [comment]
That makes sense!

**Comment by Jarcho** [comment]
Then I'll go ahead with this. It can always be switched back later if need be. @bors r+

**Pull request merged**
