### PR TITLE
Autofocus search input

### PR DESCRIPTION
**Pull request by robjtede**
changelog: autofocus filter input on Clippy Lints page

### CODE REVIEW

**Review by giraffate — COMMENTED** [review]
For some reasons it seems not to work on chrome: `version: 97.0.4692.99（Official Build） （x86_64）`
Can you check it by `cargo dev serve`?

**Comment by robjtede** [comment]
True, dynamic loading means the simple approach will not work.

**Comment by giraffate** [comment]
@bors r+

Thanks!

**Comment by xFrednet** [comment]
It works, thank you, @robjtede, I wanted this for some time now! :upside_down_face:

**Pull request merged**
