### PR TITLE
Replace `Arg` with `Param`

### PR DESCRIPTION
**Pull request by JohnTitor**
Fix build issue.
Rustup to https://github.com/rust-lang/rust/pull/63127

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
Thanks! 

@bors r+ p=10

**Comment by JohnTitor** [comment]
@flip1995 Could I submit a PR to rust-lang/rust to fix toolstate?

**Comment by mati865** [comment]
There is https://github.com/rust-lang/rust/pull/63971 already

**Comment by JohnTitor** [comment]
@mati865 Oh, thanks!

**Comment by flip1995** [comment]
Oh, I just did that. But yeah in the future you just can open a PR in rust-lang/rust to update Clippy.

The TL;DR version on how to update a submodule in rustc:
```bash
# Assuming you already cloned the rust repo and you're in the correct dir
$ git submodule update --remote src/tools/clippy
$ cargo update -p clippy
$ git add -u
$ git commit -m "Update Clippy"
$ ./x.py test -i --stage 1 src/tools/clippy # This is optional and should succeed anyway
```
Open a PR in rust-lang/rust

**Comment by phansch** [comment]
Might be nice to add that script to our repo; I have my own version and I assume @matthiaskrgr also has some sort of script :sweat_smile:

**Pull request merged**
