### PR TITLE
Changelog for Clippy 1.77 :school: 

### PR DESCRIPTION
**Pull request by xFrednet**
Roses are violets,
Red is blue,
Let's create a world,
Perfect for me and you

---

### The cat of this release is: *Luigi*

The cats of this Clippy release

The cat for the next release can be voted on: [here](https://forms.gle/57gbrNvXtCUmrHYh6)

The cat for the next next release can be nominated in the comments and will be voted in the next changelog PR (Submission deadline is 2024-03-30 23:59CET)

---

changelog: none

### CODE REVIEW

**Comment by xFrednet** [comment]
Hey @rust-lang/clippy, if someone has the time, would you mind reviewing this changelog, so we can get it merged before the release tomorrow?

(Sorry, for creating it so last minute again, I should really learn :sweat_smile: )

**Review by dswij — APPROVED** [review]
Thank you for preparing the changelog!

**Comment by xFrednet** [comment]
I thought this flaky CI issue was resolved :sob

@bors retry

**Comment by blyxyas** [comment]
I'll nominate Keepy, a.k.a "El Keepy", "El señor" or "Don Keepy"

image

**Comment by xFrednet** [comment]
Why oh ci

@bors retry

**Pull request merged**
