### PR TITLE
Add y21 to the review rotation

### PR DESCRIPTION
**Pull request by Alexendoo**
https://github.com/rust-lang/team/pull/1342

r? @ghost, when you're ready to be added to the rotation `@bors r+` this @y21

changelog: none

### CODE REVIEW

**Review by flip1995 — APPROVED** [review]
Welcome to the team!

**Comment by y21** [comment]
Let's do it

@bors r+

**Comment by xFrednet** [comment]
image

BTW, now you're legally required to love cats and penguins =^.^= 

(JK, welcome to the team!)

**Pull request merged**
