### PR TITLE
Rustup to rustc 1.35.0-nightly (3eb4890df 2019-03-19)

### PR DESCRIPTION
**Pull request by Manishearth**
r? @oli-obk @phansch

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Looks liek appveyor is not happy.
````
cargo test --features debugging
 Downloading crates ...
  Downloaded libtest v0.0.1
  Downloaded walkdir v2.2.7
  Downloaded rustc-workspace-hack v1.0.0
  Downloaded derive-new v0.5.6
  Downloaded rustc_term v0.0.1
  Downloaded winapi-util v0.1.2
  Downloaded same-file v1.0.4
  Downloaded compiletest_rs v0.3.20
  Downloaded miow v0.3.3
  Downloaded diff v0.1.11
  Downloaded rustfix v0.4.4
  Downloaded socket2 v0.3.8
   Compiling failure_derive v0.1.5
   Compiling compiletest_rs v0.3.20
   Compiling rustc_term v0.0.1
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc_term-0.0.1\win.rs:5:1
  |
5 | extern crate libc;
  | ^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc_term-0.0.1\win.rs:31:14
   |
31 |     dwSize: [libc::c_short; 2],
   |              ^^^^^^^^^^^^^
   |
   = help: add #![feature(rustc_private)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc_term-0.0.1\win.rs:32:24
   |
32 |     dwCursorPosition: [libc::c_short; 2],
   |                        ^^^^^^^^^^^^^
   |
   = help: add #![feature(rustc_private)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc_term-0.0.1\win.rs:34:16
   |
34 |     srWindow: [libc::c_short; 4],
   |                ^^^^^^^^^^^^^
   |
   = help: add #![feature(rustc_private)] to the crate attributes to enable
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc_term-0.0.1\win.rs:35:27
   |
35 |     dwMaximumWindowSize: [libc::c_short; 2],
   |                           ^^^^^^^^^^^^^
   |
   = help: add #![feature(rustc_private)] to the crate attributes to enable
   Compiling vec_map v0.8.1
error: aborting due to 5 previous errors

````

**Comment by Manishearth** [comment]
hmm looks like this is a bug in libtest cc @gnzlbg

**Comment by mati865** [comment]
Probably fixed by https://github.com/rust-lang/libtest/pull/3/commits/fe77027fba0a10378c46fe78a2dc778a1225b98f but releasing new version depends on https://github.com/rust-lang/libtest/pull/11.

**Comment by gnzlbg** [comment]
So I'll hope that the libtest PR is reviewed today, so that i can merge and release libtest =0.0.2, there is a PR to compiletest-rs that upgrades to my branch: https://github.com/laumann/compiletest-rs/pull/165 and releases 0.4.0 - I will need to update this to use libtest=0.0.2 once that is released. 

Then clippy can be updated to use compiletest-rs 0.4.0, and will just need to enable the `unstable` feature of `compiletest-rs` to use unstable libtest features (if it needs them, which I don't know).

**Comment by Manishearth** [comment]
Yeah, holding off until the new compiletest stuff happens.

**Pull request closed without merging**
