### PR TITLE
Update version attribute for 1.72 lints

### PR DESCRIPTION
**Pull request by xFrednet**
Roses are red,
Violets are blue,
Marker is alive,
and so are you!

---

cat gif

cc: https://github.com/rust-lang/rust-clippy/issues/10847#issuecomment-1683927955

---

I've also checked the `beta-nominated` label, the changelog should include everything :)

changelog: none

### CODE REVIEW

**Comment by xFrednet** [comment]
Best r+ message I've ever gotten :heart: :joy:

**Comment by xFrednet** [comment]
I've just rebased:

@bors r=Centri3

**Comment by Centri3** [comment]
> Is this your cat?

<details>
<summary>No, but I nearly caught him in the act once:</summary>




</details>

**Comment by flip1995** [comment]
> I've also checked the `beta-nominated` label, the changelog should include everything :)

You mean `beta-accepted`? :thinking:

**Comment by xFrednet** [comment]
> > I've also checked the `beta-nominated` label, the changelog should include everything :)
> 
> You mean `beta-accepted`? 🤔

Yes, leave it to me, to have at least one typo in every PR ^^

> No, but I nearly caught him in the act once

He looks so fluffy!!! I want to have cats again :sob: We used to have two when I was in high school. Now I live in a student corridor, so it's not really an option. But one day! :cat:

**Pull request merged**
