### PR TITLE
Fix assertions on const lint

### PR DESCRIPTION
**Pull request by lzutao**
Replaces #4402
changelog: none

### CODE REVIEW

**Comment by lzutao** [comment]
Failed because of #61708

**Comment by phansch** [comment]
> Failed because of [rust-lang/rust#61708](https://github.com/rust-lang/rust/pull/61708)

Yes, looks like we have to add support for Or patterns now. It shouldn't be too difficult. Don't worry about fixing the author lint correctly, that can just print `unimplemented` for now.

**Comment by flip1995** [comment]
Thanks, closing in favor of #4407

**Pull request closed without merging**
