### PR TITLE
upper_case_acronyms: don't warn on public items

### LINKED ISSUE #6803: upper_case_acronyms warns on public items
I recently ran nightly clippy on a project and got the following warning:

```
error: name `YDBError` contains a capitalized acronym
  --> src/simple_api/mod.rs:95:12
   |
95 | pub struct YDBError {
   |            ^^^^^^^^ help: consider making the acronym lowercase, except the initial letter: `YdbError`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms
```
The lint is correct, it's not a false positive. However, fixing it would be a breaking change since `YDBError` is public. Maybe this lint should be off by default since it's only a style lint and it can be hard to fix?

I originally just added `#[allow(clippy::upper_case_literals)]`, but that gives more warnings on stable until this rides the release trains unless I add `allow(unknown_renamed_lints)`, which I'd rather not do.

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Fixes #6803

changelog: upper_case_acronyms: ignore public items

### CODE REVIEW

**Comment by mikerite** [comment]
Are these items still linted if you set the aggressive option on?

**Comment by matthiaskrgr** [comment]
According to the ui-toml-test no.

**Comment by mikerite** [comment]
Why remove them from the aggressive mode as well?

**Comment by matthiaskrgr** [comment]
Because it still breaks the api if public structs are renamed, regardless of the case.

**Comment by mikerite** [comment]
For this particular lint, I'm pretty sure that you want those warnings if you turn on aggressive mode.

**Comment by matthiaskrgr** [comment]
The aggressive mode was about warning about `ASTString` vs `ASTSTRING`, this is about false positives in public items and not related imo.

**Comment by flip1995** [comment]
I agree, that the aggressive mode of this lint shouldn't change this behavior. This should be addressed, once #6806 is implemented.

@bors r+

**Pull request merged**
