### PR TITLE
Readme improvements

### PR DESCRIPTION
**Pull request by camsteffen**
~Moved the table of contents up, added an Overview heading.~

~Made the "All the Clippy Lints" link clearer.~

Formatted the lint categories as a table with the default lint level (instead of saying on/off by default). Tweaked the descriptions.

changelog: Improve Readme

### CODE REVIEW

**Comment by flip1995** [comment]
I don't see how this makes the "All the Clippy lints" link clearer. Having the ToC where it currently is, is actually intended, since we want to have the most relevant information for the user at the top. If you want more information, you scroll past this either way. Having a ToC on top doesn't help find this information faster.

-1 for this change from me.

I like the reformat to a table though (but without the traffic lights). `clippy::all` is `warn/deny`

**Comment by llogiq** [comment]
As @flip1995 wrote, we would want some changes before merging this.

I will look into this later, just know that we'll need some discussion.

**Comment by camsteffen** [comment]
Here is take 2 with flip1995's input: https://github.com/camsteffen/rust-clippy/commit/54f6a3b423ccd89d36d4d32198fe7fd081a3764a

**Comment by flip1995** [comment]
The changes in https://github.com/camsteffen/rust-clippy/commit/25be6e7665d640553574b47679c36d970c3446a5 LGTM. @llogiq r=me if those changes are pushes and you're also good with them. :+1:

**Comment by llogiq** [comment]
The problem becomes that `cargo dev update_lints` expects a number of certain sequences of text in the README, which have now changed. Look at [clippy_dev/src/update_lints.rs](https://github.com/rust-lang/rust-clippy/blob/5b52474ae6a63a69e40f4f163ddfbd3548ddac7d/clippy_dev/src/update_lints.rs#L40-L56).

**Comment by camsteffen** [comment]
Pushed the revised version. I think that resolves the concern with `cargo dev update_lints`. The main thing is adding default lint levels so I don't mind tossing the other changes.

**Comment by llogiq** [comment]
Thank you! @bors r+

**Pull request merged**
