### PR TITLE
Use diagnostic item for `Vec`

### PR DESCRIPTION
**Pull request by llogiq**
This adds a new `is_type_diagnostic_item` to check items without lookup via `match_type`.

changelog: none

### CODE REVIEW

**Comment by llogiq** [comment]
cc @oli-obk

**Comment by llogiq** [comment]
This fails because the item doesn't match. I probably should use the `vec_type` item. How do I get that?

**Comment by oli-obk** [comment]
If there's no symbol in the sym list, you can call Symbol::intern("vec_type") 

At least I think there's a function called intern. As long as you don't use gensym, any way to create the symbol should be fine

**Comment by llogiq** [comment]
I left a few positions where either the paths were part of a slice of paths or the function would have needed a larger refactoring.

**Comment by llogiq** [comment]
Error seems unrelated. Do we need a rustup?

**Comment by mati865** [comment]
Yes, https://github.com/rust-lang/rust/pull/64220#issuecomment-529142212

**Comment by llogiq** [comment]
Rebased

**Comment by phansch** [comment]
Should we have a tracking issue of some sort for the different diagnostic items?

**Pull request merged**
