### PR TITLE
Ignore non-const ctor expressions in or_fn_call

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes https://github.com/rust-lang/rust-clippy/issues/1338

Should have been fixed by #919, however that focuses on const ctor expressions only, and `.or(Some(local))` isn't const.

This also automatically ignores things like `.or(Some(local.clone())` which we don't actually want to do; I need to figure out what to do here.

changelog: Fixed false positive in [`or_fn_call`] pertaining to enum variant constructors

r? @oli-obk @phansch

### CODE REVIEW

**Comment by Manishearth** [comment]
The fully general solution is to use a visitor and make sure that the `.or(foo(bar(baz)))` is composed purely of ctors and locals.

**Comment by oli-obk** [comment]
r=me with rustfmt applied

**Comment by Manishearth** [comment]
@bors r=oli-obk

ah, no wonder it wasn't getting formatted earlier, i'd forgotten `--all`

**Comment by Manishearth** [comment]
needs rustup

**Comment by Manishearth** [comment]
The rust queue has a rollup waiting so might as well squeeze this in before I land the submodule update

**Pull request merged**
