### PR TITLE
Add `std_instead_of_core`, `std_instead_of_alloc`, `alloc_instead_of_core`

### LINKED ISSUE #7724: Lint to identify core symbols consumed through std
### What it does

Personally, I think it would be helpful to have a lint that tells me that a symbol that I am using is available from the `core` crate, but I am importing it through `std`.

### Categories (optional)

- Kind: probably `clippy::pedantic`

*What is the advantage of the recommended code over the original code*

In embedded development or whenever there may be a reason to have `no_std` compatibility in one form or another at some point, it is helpful to get an understanding of what is consumed from `std`, but really coming from `core` and could be used directly from there (and would not need to be feature gated, replaced, or whatever). Hence, having a lint that could highlight the use of re-exported `core` symbols through `std` would be useful, e.g., when `no_std` support is desirable at some point in the future, but perhaps not implemented right now.

### Drawbacks

Not everyone may feel strongly about identifying `core` functionality as such and, in fact, in a good amount of cases there may not be any benefit to side-stepping `std` partly. But then it should be an optional feature, similar in nature to [`print_stdout`](https://rust-lang.github.io/rust-clippy/master/index.html#print_stdout), for example.

### Example

```rust
use std::hash::Hasher;
```

Could be written as:

```rust
use core::hash::Hasher;
```

### PR DESCRIPTION
**Pull request by i509VCB**
Closes #7724

Introduces 3 new lints:
- `std_instead_of_core` - lints items resolved through `std` which are available in `core`
- `std_instead_of_alloc` - lints items resolved through `std` which are available in `alloc`
- `alloc_instead_of_core` - lints items resolved through `alloc` which are available in `core`

Though the original issue only mentions `std_instead_of_alloc`, the other two lints could be useful as well.

questions:
- what do I call the file the lints live in? I was thinking `std_reexports`?

changelog: new lint's: [`std_instead_of_core`], [`std_instead_of_alloc`], [`alloc_instead_of_core`]

### CODE REVIEW

**Comment by i509VCB** [comment]
Fixed the merge conflicts

**Comment by Manishearth** [comment]
@bors r+

thanks!

**Comment by xFrednet** [comment]
Looks like bors was sleeping. I've added a changelog entry for the new lints

@bors r=Manishearth

**Pull request merged**
