### PR TITLE
Rustup for rustc-dev

### LINKED ISSUE #4651: can't build with default rustc master setup
We used to be able to
```
rustup-toolchain-install-master -n master  -f
cargo +master build
```
but this no longe works due to minimized std I think: https://github.com/rust-lang/rust/pull/64823

When I try the procedure that previously worked, I just get

```
   Compiling clippy_lints v0.0.212 (/home/matthias/vcs/github/rust-clippy/clippy_lints)
error[E0463]: can't find crate for `fmt_macros`
  --> clippy_lints/src/lib.rs:20:1
   |
20 | extern crate fmt_macros;
   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

We probably need to update at least the docs and CI...

### PR DESCRIPTION
**Pull request by lzutao**
cc https://github.com/rust-lang/rust/pull/64823
Closes #4651
changelog: none

### CODE REVIEW

**Comment by lzutao** [comment]
Closed and reopened to trigger CI rebuilt.

**Comment by mati865** [comment]
FYI this PR possibly will have to be reverted soon: https://github.com/rust-lang/rust/issues/65335#issuecomment-541328516
Once upstream issue is fixed, revert would be reverted.

**Comment by lzutao** [comment]
There is no need to revert. Just removing rustc-dev component is enough.

**Pull request merged**
