### PR TITLE
Add hint for collect type

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This should hopefully fix https://github.com/rust-lang/rust/pull/72054#issuecomment-626418591-- I have not yet had a chance to run tests locally though (I believe this should fix the remaining problem though).

I guess in the future we'll fix this upstream but this beta cycle we can't do that unfortunately :/

changelog: none

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I think CI failure is because it's testing against master rustc?

r? @flip1995

**Comment by flip1995** [comment]
Yes, we didn't set up our CI for the beta branch (yet). I'll take a look at it in about an hour and merge it by hand.

**Comment by flip1995** [comment]
I think the second error:
```
error[E0277]: `std::vec::Vec<rustc_middle::ty::Predicate<'_>>` is not an iterator
   --> src/tools/clippy/clippy_lints/src/needless_pass_by_value.rs:114:58
    |
114 |         let preds = traits::elaborate_predicates(cx.tcx, cx.param_env.caller_bounds.to_vec())
    |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `std::vec::Vec<rustc_middle::ty::Predicate<'_>>` is not an iterator
    |
    = help: the trait `std::iter::Iterator` is not implemented for `std::vec::Vec<rustc_middle::ty::Predicate<'_>>
```

should also be addressed here. I currently am compiling the rust PR to test this PR.

**Comment by Mark-Simulacrum** [comment]
I *think* I managed to address that upstream -- the PR on rust-lang/rust master changed that function to take `impl Iterator` but I changed it back to `impl IntoIterator`, there's not really a reason to force callers to `.into_iter()` on their side.

**Comment by flip1995** [comment]
Sorry for taking so long, had to compile LLVM... Local tests looked good.

I directly merged it in the beta branch, instead of branching it beforehand, since it will land in rustc beta branch anyway.

@Mark-Simulacrum please use commit d4092ace00d60634bcdc22135d82e05a53971263 for the submodule update.

**Pull request merged**
