### PR TITLE
Add `cargo dev dogfood`

### PR DESCRIPTION
**Pull request by Serial-ATA**
changelog: Add `cargo dev dogfood`

Part of #5394

### CODE REVIEW

**Comment by xFrednet** [comment]
Thanks for working on Clippy's internal tools! Wouldn't it be simpler to add new cargo aliases instead of extending `clippy_dev`?

**Comment by Serial-ATA** [comment]
I'm not sure how to best handle `--fix` in that case.

**Comment by xFrednet** [comment]
Good point, I just have never used `--fix` with dogfood, and in general tbh :sweat_smile:. We could have an environment value, like we have to uitest, but that feels hacky. Then I think this is a good solution! :upside_down_face:

**Review by giraffate — COMMENTED** [review]
Can the document about the dogfood tests be updated?
https://github.com/rust-lang/rust-clippy/blob/master/book/src/development/basics.md#building-and-testing

**Comment by giraffate** [comment]
@bors r+

Thanks!

**Pull request merged**
