### PR TITLE
Move two cast_lossless tests to their correct files

### PR DESCRIPTION
**Pull request by phansch**
First part of checking off the `tests/ui/cast.rs` checkbox in #3630.

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Just need `rustfmt`

````
+++set +ex
Diff in /Users/travis/build/rust-lang/rust-clippy/tests/ui/cast.rs at line 2:
     clippy::cast_precision_loss,
     clippy::cast_possible_truncation,
     clippy::cast_sign_loss,
-    clippy::cast_possible_wrap,
+    clippy::cast_possible_wrap
 )]
 #[allow(clippy::no_effect, clippy::unnecessary_operation)]
 fn main() {
tests/ui/cast.rs needs reformatting!
+++'[' true == true ']'
+++echo 'Tests need reformatting!'
Tests need reformatting!
````

**Comment by flip1995** [comment]
Is AppVeyor in shreds again?

@bors retry

**Comment by phansch** [comment]
Looks like some networking issues: 

```
error: failed to download from `https://crates.io/api/v1/crates/cargo_metadata/0.7.4/download`
Caused by:
  [6] Couldn't resolve host name (Could not resolve host: static.crates.io)
```

**Pull request merged**
