### PR TITLE
fix typo in Clippy Lints page

### PR DESCRIPTION
**Pull request by tamaroning**
https://rust-lang.github.io/rust-clippy/master/#significant_drop_in_scrutinee

changelog: none

### CODE REVIEW

**Review by giraffate — COMMENTED** [review]
Thanks!

Can this be corrected together?
https://github.com/rust-lang/rust-clippy/blob/70f1d0d8fd702d8d761ce5c15df5b238ab59c250/clippy_lints/src/large_const_arrays.rs#L27

**Comment by tamaroning** [comment]
Okey. Fixed it:)

**Comment by giraffate** [comment]
@bors r+

Thanks!

**Comment by xFrednet** [comment]
The changelog entry was missing

@bors r+

**Comment by matthiaskrgr** [comment]
if we only had some kind of linter that could catch these kind of typos automatically.. 😔

**Pull request merged**
