### PR TITLE
Add `cloned_instead_of_copied` lint

### LINKED ISSUE #3870: Prefer `iterator.copied()` over `iterator.cloned()` where possible
... and adjust our current `iterator.map(|x| *x)` lint to suggest `.copied()`

Requires https://github.com/rust-lang/rust/issues/57127 to get merged first though.

### PR DESCRIPTION
**Pull request by camsteffen**
Don't go cloning all willy-nilly.

Featuring a new `get_iterator_item_ty` util!

changelog: Add cloned_instead_of_copied lint

Closes #3870

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
@bors r+

thanks!

**Comment by camsteffen** [comment]
Added semicolon to doc examples 🤦

**Comment by Manishearth** [comment]
(feel free to `r=manishearth` for minor CI fixes)

**Pull request merged**
