### PR TITLE
`collection_is_never_read`: Handle unit type

### PR DESCRIPTION
**Pull request by schubart**
changelog: [`collection_is_never_read`]: Fix false negative
fixes: #10488

### CODE REVIEW

**Comment by llogiq** [comment]
What about methods that use `&mut`ably borrowed arguments to get the read values back to the caller?

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
r=me, though there are conflicts

(sorry about missing this PR)

**Comment by schubart** [comment]
Thanks, merge conflicts fixed.

**Pull request merged**
