### PR TITLE
I like to move it, move it

### PR DESCRIPTION
**Pull request by flip1995**
GHA now runs in the background for 6 days (#5088) 

Since then ~~15~~ 19 PRs were successfully merged and Travis+Appveyor agreed on the status in every case. ([GitHub PR search query](https://github.com/rust-lang/rust-clippy/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+merged%3A%3E%3D2020-02-12T15%3A42%3A00+sort%3Aupdated-desc+NOT+%5Bgh-pages%5D+in%3Atitle))

Some PRs were:
- #5163 
- #5170 
- #5168 
- #5173
- #5171  
- #5156 
- #4809
- #5177  
- #5182
- #5183  
- #5184
- #5185  
- #5186 
- #5181 
- #5189 

Bug with GHA:
- When a rustc PR gets merged between the `integration_build` and the `integration` job, the `integration` job will fail. This happened once in #5162, but not in the past 6 days. Even if it would happen every 4th PR we would save time, since splitting up the integration build and tests saves 5-7 minutes per run and a complete run takes 15-17 minutes
- Sometimes the MacOS build takes up to an hour to download the master toolchain. Until now, this happend 2 or 3 times and can be resolved by a `@bors r3try`+canceling the previous run (restarting single jobs is not supported yet)

## Before merging this, https://github.com/rust-lang/rust-central-station/pull/578 has to get merged

This PR is for starting the discussion and to get consensus (@rust-lang/clippy) on a final move to GHA. If we're ready, I'll contact Pietro, to finalize the move.

changelog: Clippy completely runs on GHA now :tada:

---

BTW: The deployment already runs on GHA, instead of Travis.

### CODE REVIEW

**Comment by phansch** [comment]
No objections from my side =)

**Comment by llogiq** [comment]
We like to **move it**!

**Comment by flip1995** [comment]
@Manishearth I think AppVeyor has to be disabled in the AppVeyor UI https://ci.appveyor.com/project/rust-lang-libs/rust-clippy/builds/30904772 (?)

**Pull request merged**
