### PR TITLE
Add new `unusable_matches_bindings` lint

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Re-opening of #11661 (original PR is still open but seem dead. Discussion [on zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy) agreed that I could cherry-pick the commits and make the last changes asked so here we go. :)

changelog: Add new `unusable_matches_bindings` lint

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Arf, you keep getting picked up. Setting someone else.

r? clippy

**Comment by Jarcho** [comment]
This would be better as a change to the `unused_variables` message rather than it's own lint with a second message about the same thing.

**Comment by GuillaumeGomez** [comment]
Good point.

**Comment by GuillaumeGomez** [comment]
This is actually already triggered by rustc's `unused_variable` so can be closed.

**Pull request closed without merging**
