### PR TITLE
rustup

### LINKED ISSUE #3708: Clippy nightly build broken
Due to https://github.com/rust-lang/rust/pull/57907 and https://github.com/rust-lang/rust/pull/57726 Clippy fails to build with the latest Rust nightly/master currently.

If you rely on using the nightly Clippy component, you can try using the last working nightly: `nightly-2019-01-26`. Please also be aware that Clippy has been available on `stable` Rust for a while now and is guaranteed to always work.

### PR DESCRIPTION
**Pull request by matthiaskrgr**
rustup https://github.com/rust-lang/rust/pull/57907/ and https://github.com/rust-lang/rust/pull/57726
Fixes #3708

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Current failures:
````
    [ui] ui/author/matches.rs
    [ui] ui/deprecated.rs
    [ui] ui/lint_without_lint_pass.rs
    [ui] ui/rename.rs
````

**Comment by matthiaskrgr** [comment]
It seems that there are additional messages about deprecated/renamed lints but I'm not sure what causes this.

**Comment by phansch** [comment]
Looks like the lints are emitted twice now?
I'd also be fine with updating the stderr, merging this and creating a separate issue for the duplicate emission.

**Comment by matthiaskrgr** [comment]
I tried updating test results but when doing so, there were a lot more changes than actually failing tests. Not sure what is happening :/

**Comment by phansch** [comment]
The new failures are probably due to https://github.com/rust-lang/rust/pull/57907, can you try going back to the rustc you were using yesterday to update the stderr files?

**Comment by matthiaskrgr** [comment]
Just fixed these :P

Anyway I was already getting this yesterday when the PR wasn't merged yet.

**Comment by phansch** [comment]
Awesome! :sparkles:

cc @euclio looks like you don't have to fix Clippy in this case =)

**Comment by matthiaskrgr** [comment]
````

failures:

---- [ui] ui/deprecated.rs stdout ----
normalized stderr:
error: lint `str_to_string` has been removed: `using `str::to_string` is common even today and specialization will likely happen soon`
  --> $DIR/deprecated.rs:1:8
   |
LL | #[warn(str_to_string)]
   |        ^^^^^^^^^^^^^
   |
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`

error: lint `string_to_string` has been removed: `using `string::to_string` is common even today and specialization will likely happen soon`
  --> $DIR/deprecated.rs:2:8
   |
LL | #[warn(string_to_string)]
   |        ^^^^^^^^^^^^^^^^

error: lint `unstable_as_slice` has been removed: ``Vec::as_slice` has been stabilized in 1.7`
  --> $DIR/deprecated.rs:3:8
   |
LL | #[warn(unstable_as_slice)]
   |        ^^^^^^^^^^^^^^^^^

error: lint `unstable_as_mut_slice` has been removed: ``Vec::as_mut_slice` has been stabilized in 1.7`
  --> $DIR/deprecated.rs:4:8
   |
LL | #[warn(unstable_as_mut_slice)]
   |        ^^^^^^^^^^^^^^^^^^^^^

error: lint `misaligned_transmute` has been removed: `this lint has been split into cast_ptr_alignment and transmute_ptr_to_ptr`
  --> $DIR/deprecated.rs:5:8
   |
LL | #[warn(misaligned_transmute)]
   |        ^^^^^^^^^^^^^^^^^^^^

error: lint `str_to_string` has been removed: `using `str::to_string` is common even today and specialization will likely happen soon`
  --> $DIR/deprecated.rs:1:8
   |
LL | #[warn(str_to_string)]
   |        ^^^^^^^^^^^^^

error: aborting due to 6 previous errors



expected stderr:
error: lint `str_to_string` has been removed: `using `str::to_string` is common even today and specialization will likely happen soon`
  --> $DIR/deprecated.rs:1:8
   |
LL | #[warn(str_to_string)]
   |        ^^^^^^^^^^^^^
   |
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`

error: lint `string_to_string` has been removed: `using `string::to_string` is common even today and specialization will likely happen soon`
  --> $DIR/deprecated.rs:2:8
   |
LL | #[warn(string_to_string)]
   |        ^^^^^^^^^^^^^^^^

error: lint `unstable_as_slice` has been removed: ``Vec::as_slice` has been stabilized in 1.7`
  --> $DIR/deprecated.rs:3:8
   |
LL | #[warn(unstable_as_slice)]
   |        ^^^^^^^^^^^^^^^^^

error: lint `unstable_as_mut_slice` has been removed: ``Vec::as_mut_slice` has been stabilized in 1.7`
  --> $DIR/deprecated.rs:4:8
   |
LL | #[warn(unstable_as_mut_slice)]
   |        ^^^^^^^^^^^^^^^^^^^^^

error: lint `misaligned_transmute` has been removed: `this lint has been split into cast_ptr_alignment and transmute_ptr_to_ptr`
  --> $DIR/deprecated.rs:5:8
   |
LL | #[warn(misaligned_transmute)]
   |        ^^^^^^^^^^^^^^^^^^^^

error: aborting due to 5 previous errors



diff of stderr:

 error: lint `str_to_string` has been removed: `using `str::to_string` is common even today and specialization will likely happen soon`
   --> $DIR/deprecated.rs:1:8
    |
 LL | #[warn(str_to_string)]
    |        ^^^^^^^^^^^^^
    |
    = note: `-D renamed-and-removed-lints` implied by `-D warnings`

 error: lint `string_to_string` has been removed: `using `string::to_string` is common even today and specialization will likely happen soon`
   --> $DIR/deprecated.rs:2:8
    |
 LL | #[warn(string_to_string)]
    |        ^^^^^^^^^^^^^^^^

 error: lint `unstable_as_slice` has been removed: ``Vec::as_slice` has been stabilized in 1.7`
   --> $DIR/deprecated.rs:3:8
    |
 LL | #[warn(unstable_as_slice)]
    |        ^^^^^^^^^^^^^^^^^

 error: lint `unstable_as_mut_slice` has been removed: ``Vec::as_mut_slice` has been stabilized in 1.7`
   --> $DIR/deprecated.rs:4:8
    |
 LL | #[warn(unstable_as_mut_slice)]
    |        ^^^^^^^^^^^^^^^^^^^^^

 error: lint `misaligned_transmute` has been removed: `this lint has been split into cast_ptr_alignment and transmute_ptr_to_ptr`
   --> $DIR/deprecated.rs:5:8
    |
 LL | #[warn(misaligned_transmute)]
    |        ^^^^^^^^^^^^^^^^^^^^

-error: aborting due to 5 previous errors
+error: lint `str_to_string` has been removed: `using `str::to_string` is common even today and specialization will likely happen soon`
+  --> $DIR/deprecated.rs:1:8
+   |
+LL | #[warn(str_to_string)]
+   |        ^^^^^^^^^^^^^
+
+error: aborting due to 6 previous errors



The actual stderr differed from the expected stderr.
Actual stderr saved to /home/matthias/vcs/github/rust-clippy/target/debug/test_build_base/deprecated.stderr
To update references, run this command from build directory:
tests/ui/update-references.sh '/home/matthias/vcs/github/rust-clippy/target/debug/test_build_base' 'deprecated.rs'

error: 1 errors occurred comparing output.
status: exit code: 1
command: "target/debug/clippy-driver" "tests/ui/deprecated.rs" "-L" "/home/matthias/vcs/github/rust-clippy/target/debug/test_build_base" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/home/matthias/vcs/github/rust-clippy/target/debug/test_build_base/deprecated.stage-id" "-L" "target/debug" "-L" "target/debug/deps" "-Dwarnings" "-Zui-testing" "-L" "/home/matthias/vcs/github/rust-clippy/target/debug/test_build_base/deprecated.stage-id.aux" "-A" "unused"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
{"message":"lint `str_to_string` has been removed: `using `str::to_string` is common even today and specialization will likely happen soon`","code":{"code":"renamed_and_removed_lints","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/deprecated.rs","byte_start":7,"byte_end":20,"line_start":1,"line_end":1,"column_start":8,"column_end":21,"is_primary":true,"text":[{"text":"#[warn(str_to_string)]","highlight_start":8,"highlight_end":21}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"`-D renamed-and-removed-lints` implied by `-D warnings`","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"error: lint `str_to_string` has been removed: `using `str::to_string` is common even today and specialization will likely happen soon`\n  --> tests/ui/deprecated.rs:1:8\n   |\nLL | #[warn(str_to_string)]\n   |        ^^^^^^^^^^^^^\n   |\n   = note: `-D renamed-and-removed-lints` implied by `-D warnings`\n\n"}
{"message":"lint `string_to_string` has been removed: `using `string::to_string` is common even today and specialization will likely happen soon`","code":{"code":"renamed_and_removed_lints","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/deprecated.rs","byte_start":30,"byte_end":46,"line_start":2,"line_end":2,"column_start":8,"column_end":24,"is_primary":true,"text":[{"text":"#[warn(string_to_string)]","highlight_start":8,"highlight_end":24}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: lint `string_to_string` has been removed: `using `string::to_string` is common even today and specialization will likely happen soon`\n  --> tests/ui/deprecated.rs:2:8\n   |\nLL | #[warn(string_to_string)]\n   |        ^^^^^^^^^^^^^^^^\n\n"}
{"message":"lint `unstable_as_slice` has been removed: ``Vec::as_slice` has been stabilized in 1.7`","code":{"code":"renamed_and_removed_lints","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/deprecated.rs","byte_start":56,"byte_end":73,"line_start":3,"line_end":3,"column_start":8,"column_end":25,"is_primary":true,"text":[{"text":"#[warn(unstable_as_slice)]","highlight_start":8,"highlight_end":25}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: lint `unstable_as_slice` has been removed: ``Vec::as_slice` has been stabilized in 1.7`\n  --> tests/ui/deprecated.rs:3:8\n   |\nLL | #[warn(unstable_as_slice)]\n   |        ^^^^^^^^^^^^^^^^^\n\n"}
{"message":"lint `unstable_as_mut_slice` has been removed: ``Vec::as_mut_slice` has been stabilized in 1.7`","code":{"code":"renamed_and_removed_lints","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/deprecated.rs","byte_start":83,"byte_end":104,"line_start":4,"line_end":4,"column_start":8,"column_end":29,"is_primary":true,"text":[{"text":"#[warn(unstable_as_mut_slice)]","highlight_start":8,"highlight_end":29}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: lint `unstable_as_mut_slice` has been removed: ``Vec::as_mut_slice` has been stabilized in 1.7`\n  --> tests/ui/deprecated.rs:4:8\n   |\nLL | #[warn(unstable_as_mut_slice)]\n   |        ^^^^^^^^^^^^^^^^^^^^^\n\n"}
{"message":"lint `misaligned_transmute` has been removed: `this lint has been split into cast_ptr_alignment and transmute_ptr_to_ptr`","code":{"code":"renamed_and_removed_lints","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/deprecated.rs","byte_start":114,"byte_end":134,"line_start":5,"line_end":5,"column_start":8,"column_end":28,"is_primary":true,"text":[{"text":"#[warn(misaligned_transmute)]","highlight_start":8,"highlight_end":28}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: lint `misaligned_transmute` has been removed: `this lint has been split into cast_ptr_alignment and transmute_ptr_to_ptr`\n  --> tests/ui/deprecated.rs:5:8\n   |\nLL | #[warn(misaligned_transmute)]\n   |        ^^^^^^^^^^^^^^^^^^^^\n\n"}
{"message":"lint `str_to_string` has been removed: `using `str::to_string` is common even today and specialization will likely happen soon`","code":{"code":"renamed_and_removed_lints","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/deprecated.rs","byte_start":7,"byte_end":20,"line_start":1,"line_end":1,"column_start":8,"column_end":21,"is_primary":true,"text":[{"text":"#[warn(str_to_string)]","highlight_start":8,"highlight_end":21}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: lint `str_to_string` has been removed: `using `str::to_string` is common even today and specialization will likely happen soon`\n  --> tests/ui/deprecated.rs:1:8\n   |\nLL | #[warn(str_to_string)]\n   |        ^^^^^^^^^^^^^\n\n"}
{"message":"aborting due to 6 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to 6 previous errors\n\n"}

------------------------------------------

thread '[ui] ui/deprecated.rs' panicked at 'explicit panic', /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.18/src/runtest.rs:2632:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- [ui] ui/rename.rs stdout ----
normalized stderr:
error: unknown lint: `stutter`
  --> $DIR/rename.rs:1:10
   |
LL | #![allow(stutter)]
   |          ^^^^^^^
   |
   = note: `-D unknown-lints` implied by `-D warnings`

error: lint `clippy::stutter` has been renamed to `clippy::module_name_repetitions`
  --> $DIR/rename.rs:3:8
   |
LL | #[warn(clippy::stutter)]
   |        ^^^^^^^^^^^^^^^ help: use the new name: `clippy::module_name_repetitions`
   |
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`

error: lint `clippy::new_without_default_derive` has been renamed to `clippy::new_without_default`
  --> $DIR/rename.rs:6:8
   |
LL | #[warn(clippy::new_without_default_derive)]
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use the new name: `clippy::new_without_default`

error: unknown lint: `stutter`
  --> $DIR/rename.rs:1:10
   |
LL | #![allow(stutter)]
   |          ^^^^^^^

error: lint `clippy::stutter` has been renamed to `clippy::module_name_repetitions`
  --> $DIR/rename.rs:3:8
   |
LL | #[warn(clippy::stutter)]
   |        ^^^^^^^^^^^^^^^ help: use the new name: `clippy::module_name_repetitions`

error: aborting due to 5 previous errors



expected stderr:
error: unknown lint: `stutter`
  --> $DIR/rename.rs:1:10
   |
LL | #![allow(stutter)]
   |          ^^^^^^^
   |
   = note: `-D unknown-lints` implied by `-D warnings`

error: lint `clippy::stutter` has been renamed to `clippy::module_name_repetitions`
  --> $DIR/rename.rs:3:8
   |
LL | #[warn(clippy::stutter)]
   |        ^^^^^^^^^^^^^^^ help: use the new name: `clippy::module_name_repetitions`
   |
   = note: `-D renamed-and-removed-lints` implied by `-D warnings`

error: lint `clippy::new_without_default_derive` has been renamed to `clippy::new_without_default`
  --> $DIR/rename.rs:6:8
   |
LL | #[warn(clippy::new_without_default_derive)]
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use the new name: `clippy::new_without_default`

error: aborting due to 3 previous errors



diff of stderr:

 error: unknown lint: `stutter`
   --> $DIR/rename.rs:1:10
    |
 LL | #![allow(stutter)]
    |          ^^^^^^^
    |
    = note: `-D unknown-lints` implied by `-D warnings`

 error: lint `clippy::stutter` has been renamed to `clippy::module_name_repetitions`
   --> $DIR/rename.rs:3:8
    |
 LL | #[warn(clippy::stutter)]
    |        ^^^^^^^^^^^^^^^ help: use the new name: `clippy::module_name_repetitions`
    |
    = note: `-D renamed-and-removed-lints` implied by `-D warnings`

 error: lint `clippy::new_without_default_derive` has been renamed to `clippy::new_without_default`
   --> $DIR/rename.rs:6:8
    |
 LL | #[warn(clippy::new_without_default_derive)]
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use the new name: `clippy::new_without_default`

-error: aborting due to 3 previous errors
+error: unknown lint: `stutter`
+  --> $DIR/rename.rs:1:10
+   |
+LL | #![allow(stutter)]
+   |          ^^^^^^^
+
+error: lint `clippy::stutter` has been renamed to `clippy::module_name_repetitions`
+  --> $DIR/rename.rs:3:8
+   |
+LL | #[warn(clippy::stutter)]
+   |        ^^^^^^^^^^^^^^^ help: use the new name: `clippy::module_name_repetitions`
+
+error: aborting due to 5 previous errors



The actual stderr differed from the expected stderr.
Actual stderr saved to /home/matthias/vcs/github/rust-clippy/target/debug/test_build_base/rename.stderr
To update references, run this command from build directory:
tests/ui/update-references.sh '/home/matthias/vcs/github/rust-clippy/target/debug/test_build_base' 'rename.rs'

error: 1 errors occurred comparing output.
status: exit code: 1
command: "target/debug/clippy-driver" "tests/ui/rename.rs" "-L" "/home/matthias/vcs/github/rust-clippy/target/debug/test_build_base" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/home/matthias/vcs/github/rust-clippy/target/debug/test_build_base/rename.stage-id" "-L" "target/debug" "-L" "target/debug/deps" "-Dwarnings" "-Zui-testing" "-L" "/home/matthias/vcs/github/rust-clippy/target/debug/test_build_base/rename.stage-id.aux" "-A" "unused"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
{"message":"unknown lint: `stutter`","code":{"code":"unknown_lints","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/rename.rs","byte_start":9,"byte_end":16,"line_start":1,"line_end":1,"column_start":10,"column_end":17,"is_primary":true,"text":[{"text":"#![allow(stutter)]","highlight_start":10,"highlight_end":17}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"`-D unknown-lints` implied by `-D warnings`","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"error: unknown lint: `stutter`\n  --> tests/ui/rename.rs:1:10\n   |\nLL | #![allow(stutter)]\n   |          ^^^^^^^\n   |\n   = note: `-D unknown-lints` implied by `-D warnings`\n\n"}
{"message":"lint `clippy::stutter` has been renamed to `clippy::module_name_repetitions`","code":{"code":"renamed_and_removed_lints","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/rename.rs","byte_start":27,"byte_end":42,"line_start":3,"line_end":3,"column_start":8,"column_end":23,"is_primary":true,"text":[{"text":"#[warn(clippy::stutter)]","highlight_start":8,"highlight_end":23}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"`-D renamed-and-removed-lints` implied by `-D warnings`","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"use the new name","code":null,"level":"help","spans":[{"file_name":"tests/ui/rename.rs","byte_start":27,"byte_end":42,"line_start":3,"line_end":3,"column_start":8,"column_end":23,"is_primary":true,"text":[{"text":"#[warn(clippy::stutter)]","highlight_start":8,"highlight_end":23}],"label":null,"suggested_replacement":"clippy::module_name_repetitions","suggestion_applicability":"MachineApplicable","expansion":null}],"children":[],"rendered":null}],"rendered":"error: lint `clippy::stutter` has been renamed to `clippy::module_name_repetitions`\n  --> tests/ui/rename.rs:3:8\n   |\nLL | #[warn(clippy::stutter)]\n   |        ^^^^^^^^^^^^^^^ help: use the new name: `clippy::module_name_repetitions`\n   |\n   = note: `-D renamed-and-removed-lints` implied by `-D warnings`\n\n"}
{"message":"lint `clippy::new_without_default_derive` has been renamed to `clippy::new_without_default`","code":{"code":"renamed_and_removed_lints","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/rename.rs","byte_start":66,"byte_end":100,"line_start":6,"line_end":6,"column_start":8,"column_end":42,"is_primary":true,"text":[{"text":"#[warn(clippy::new_without_default_derive)]","highlight_start":8,"highlight_end":42}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"use the new name","code":null,"level":"help","spans":[{"file_name":"tests/ui/rename.rs","byte_start":66,"byte_end":100,"line_start":6,"line_end":6,"column_start":8,"column_end":42,"is_primary":true,"text":[{"text":"#[warn(clippy::new_without_default_derive)]","highlight_start":8,"highlight_end":42}],"label":null,"suggested_replacement":"clippy::new_without_default","suggestion_applicability":"MachineApplicable","expansion":null}],"children":[],"rendered":null}],"rendered":"error: lint `clippy::new_without_default_derive` has been renamed to `clippy::new_without_default`\n  --> tests/ui/rename.rs:6:8\n   |\nLL | #[warn(clippy::new_without_default_derive)]\n   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use the new name: `clippy::new_without_default`\n\n"}
{"message":"unknown lint: `stutter`","code":{"code":"unknown_lints","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/rename.rs","byte_start":9,"byte_end":16,"line_start":1,"line_end":1,"column_start":10,"column_end":17,"is_primary":true,"text":[{"text":"#![allow(stutter)]","highlight_start":10,"highlight_end":17}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: unknown lint: `stutter`\n  --> tests/ui/rename.rs:1:10\n   |\nLL | #![allow(stutter)]\n   |          ^^^^^^^\n\n"}
{"message":"lint `clippy::stutter` has been renamed to `clippy::module_name_repetitions`","code":{"code":"renamed_and_removed_lints","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/rename.rs","byte_start":27,"byte_end":42,"line_start":3,"line_end":3,"column_start":8,"column_end":23,"is_primary":true,"text":[{"text":"#[warn(clippy::stutter)]","highlight_start":8,"highlight_end":23}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"use the new name","code":null,"level":"help","spans":[{"file_name":"tests/ui/rename.rs","byte_start":27,"byte_end":42,"line_start":3,"line_end":3,"column_start":8,"column_end":23,"is_primary":true,"text":[{"text":"#[warn(clippy::stutter)]","highlight_start":8,"highlight_end":23}],"label":null,"suggested_replacement":"clippy::module_name_repetitions","suggestion_applicability":"MachineApplicable","expansion":null}],"children":[],"rendered":null}],"rendered":"error: lint `clippy::stutter` has been renamed to `clippy::module_name_repetitions`\n  --> tests/ui/rename.rs:3:8\n   |\nLL | #[warn(clippy::stutter)]\n   |        ^^^^^^^^^^^^^^^ help: use the new name: `clippy::module_name_repetitions`\n\n"}
{"message":"aborting due to 5 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to 5 previous errors\n\n"}

------------------------------------------

thread '[ui] ui/rename.rs' panicked at 'explicit panic', /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.18/src/runtest.rs:2632:9


failures:
    [ui] ui/deprecated.rs
    [ui] ui/rename.rs

test result: FAILED. 235 passed; 2 failed; 1 ignored; 0 measured; 0 filtered out

test compile_test ... FAILED

failures:

---- compile_test stdout ----
thread 'compile_test' panicked at 'Some tests failed', /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.18/src/lib.rs:90:22


failures:
    compile_test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
````

This is the output.

When I run `./tests/ui/update-all-references.sh ` now, I suddenly get
````
 tests/ui/author/matches.stderr                 |  15 ++--
 tests/ui/builtin-type-shadow.stderr            |  10 +--
 tests/ui/cfg_attr_rustfmt.fixed                |   4 +-
 tests/ui/cfg_attr_rustfmt.stderr               |  16 ----
 tests/ui/collapsible_if.fixed                  | 142 ++++++++++++++++++------------
 tests/ui/collapsible_if.stderr                 | 260 -------------------------------------------------------
 tests/ui/const_static_lifetime.stderr          |  82 ------------------
 tests/ui/decimal_literal_representation.stderr |  34 ++------
 tests/ui/deprecated.stderr                     |   8 +-
 tests/ui/doc.stderr                            | 190 ----------------------------------------
 tests/ui/double_neg.stderr                     |  22 +++--
 tests/ui/double_parens.stderr                  |  40 ---------
 tests/ui/duplicate_underscore_argument.stderr  |  10 ---
 tests/ui/else_if_without_else.stderr           |  27 ------
 tests/ui/enum_variants.stderr                  | 101 ---------------------
 tests/ui/formatting.stderr                     | 139 +++++++----------------------
 tests/ui/fxhash.stderr                         |  40 ---------
 tests/ui/if_not_else.stderr                    |  27 ------
 tests/ui/inconsistent_digit_grouping.fixed     |   2 +-
 tests/ui/inconsistent_digit_grouping.stderr    |  34 --------
 tests/ui/int_plus_one.stderr                   |  44 ----------
 tests/ui/item_after_statement.stderr           |  20 -----
 tests/ui/rename.stderr                         |  14 ++-
 23 files changed, 167 insertions(+), 1114 deletions(-)
````

which looks very wrong (1k deletions..??!)

**Comment by matthiaskrgr** [comment]
NEVERMIND... ._.
I did a clean rebuild now which fixed the problem... looks like I still had some old files laying around, sorry.  :(

**Comment by mikerite** [comment]
I think the reason for the duplicates is this change here:
https://github.com/rust-lang/rust/blob/9b5535a6f38340d3be8fcae1822a04ba3febf82f/src/librustc/lint/context.rs#L1325

They now run `early_lint_crate` twice. Once with the builtin lints and once with the registered lint passes. Those warnings aren't generated by a normal lint but rather when the lints are looked up from attributes which happens twice now.

I'm not sure why only the first is duplicated though. Maybe because they filter duplicates but the first one has a note. :thinking:

**Pull request merged**
