### PR TITLE
Add `xor_swap` lint

### LINKED ISSUE #6598: Add XOR swap algorithm detection to (existing) clippy::manual_swap
### What it does

*This would warn the user that there is a better alternative to using a XOR swapping algorithm to swap the values of two variables*

### Categories (optional)

- Kind: *clippy::complexity*

*The std::mem::swap function exposes the intent better (this is somewhat the same reason for the warning for swapping using a temporary variable)*

For example:
- People reading the recommended code will see that it likely swaps two variables, as opposed to if they see a XOR swap algorithm and are unfamiliar with it.

### Drawbacks

None.

### Example

```rust
fn main() {
    let mut a = 5;
    let mut b = 10;
    
    // Swap them.
    a ^= b;
    b ^= a;
    a ^= b;
    
    println!("a: {}, b: {}", a, b);
}
```

Could be written as:

```rust
fn main() {
    let mut a = 5;
    let mut b = 10;
    
    // Swap them.
    std::mem::swap(&mut a, &mut b);
    
    println!("a: {}, b: {}", a, b);
}
```

### PR DESCRIPTION
**Pull request by hrishisd**
This adds the ``[`xor_swap`]`` lint to detect swaps via the xor trick. 

changelog: Add `xor_swap` lint
closes #6598

### CODE REVIEW

**Comment by hrishisd** [comment]
Closed this request because I think there are some mistakes in this change that I would like to fix

**Comment by hrishisd** [comment]
Sorry for the noise, reopening for feedback

**Comment by flip1995** [comment]
Haven't reviewed it. But I would make this an extension of the [`manual_swap`](https://rust-lang.github.io/rust-clippy/master/index.html#manual_swap) lint, rather than a new one.

**Comment by Manishearth** [comment]
Yeah, I agree.

**Comment by giraffate** [comment]
ping from triage @hrishisd. Can you have any updates? If you have any questions, feel free to ask us.

**Comment by giraffate** [comment]
ping from triage @hrishisd. I'm closing this because 2 weeks have passed with no activity. If you have more time to work on this, feel free to reopen this.

**Comment by HKalbasi** [comment]
finished in #7506 
@rustbot label -S-inactive-closed

**Pull request closed without merging**
