### PR TITLE
`Conf` macro improvements part 2

### PR DESCRIPTION
**Pull request by camsteffen**
changelog: none

Follow-up to #7150

I made the default value required again for `define_Conf!` so that it can be parsed by the magic Python. I guess it's just as well for readability.

r? @flip1995

### CODE REVIEW

**Comment by flip1995** [comment]
One documentation update missing: https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md#adding-configuration-to-a-lint

**Comment by flip1995** [comment]
@bors r+

Thanks!

**Comment by flip1995** [comment]
Lol, this backwards broke the beta deploy: 7c7683c 

Remind me in 6 weeks, that this will also break the stable 1.53 release deploy :smile: 

(Not your fault of course)

**Comment by camsteffen** [comment]
What happened?

**Comment by flip1995** [comment]
The deploy workflow checks out the scripts from the current master branch, so we don't deploy an old state of the website for beta and releases. Otherwise it would use the deploy and website generation scripts that were in the repo at the point of the release (6/12 weeks ago). Especially when I first implemented the deploy workflow this lead to many failures of beta/stable deployment. Maybe we could use the python scripts in `util` for releases and just checkout the `.github/deploy.sh` from master. But since the effects of this will only show in 6/12/42069 weeks, I'd rather not change this usually-working workflow. I will just hand update the gh-pages for the next 2 releases and we should be fine. Especially, because #7172 will take over the job of generating the deploy artifacts anyway in the future.

**Pull request merged**
