### PR TITLE
rustup

### PR DESCRIPTION
**Pull request by matthiaskrgr**
changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
uhm, what...?
````
   Compiling cargo_metadata v0.8.1
   Compiling clippy_lints v0.0.212 (C:\Users\travis\build\rust-lang\rust-clippy\clippy_lints)
    Finished dev [unoptimized + debuginfo] target(s) in 4m 02s
+++ cargo test --features 'debugging deny-warnings'
error: unable to unlink old fallback exe
info: caused by: Access is denied. (os error 5)
info: backtrace:
stack backtrace:
   0: <no info> (0x72aa68)
   1: <no info> (0x72aeca)
   2: <no info> (0x7275db)
   3: <no info> (0x5511eb)
   4: <no info> (0x5b9049)
   5: <no info> (0x470d5c)
   6: <no info> (0x46d302)
   7: <no info> (0x407bb6)
   8: <no info> (0x473032)
   9: <no info> (0x4013f8)
  10: <no info> (0x40151b)
  11: BaseThreadInitThunk (0x7fff15833034)
````

@bors retry

**Comment by phansch** [comment]
Hmm, that might be spurious? Let's see..

@bors retry

**Comment by leo60228** [comment]
I assume the goal of this pull request is to make clippy available on the nightly channel again?

**Comment by mati865** [comment]
@leo60228 yes but this has to also land in Rust repository.

**Pull request merged**
