### PR TITLE
Added a lint-fraction-readability flag to the configuration

### LINKED ISSUE #4176: unreadable_literal for floating-point numbers
unreadable_literal triggers for floating-point numbers such as

> ```
>   |
> 5 |     0.095332, 0.118095, 0.095332,
>   |                         ^^^^^^^^ help: consider: `0.095_332`
> ```

To me this is weird, because I consider `_` in numbers as an equivalent of a thousands separator, and I've never seen thousands separators used in the fractional part of a decimal fraction.

In integers, the thousands separators matter, because you can't see magnitude of the number without counting digits. But in the fractional part, the length doesn't matter: the most significant digits are always in the same place, easy to find.

I suggest not linting the fractional part, as it's weird and unnecessary.

----

clippy 0.0.212 (265318db 2019-05-17)

### PR DESCRIPTION
**Pull request by xFrednet**
This adds an option to disable the `unreadable_literal` lint for floats with a longer fraction. This allows users to write `0.100200300` without getting a warning. Fixes #4176 

I have some open questions about this PR:
1. I've named the option `lint-fraction-readability` is this a good name or should I rename it to something else?
2. What should the default configuration value be?
    * The current default value is `true` as this was also the previous default.
3. Do I have to document this new option somewhere else or will it be extracted from the code comment?
4. The current fix option will also rewrite the fraction if the integer part violates the `unreadable_literal` lint it would otherwise also trigger the `inconsistent_digit_grouping` lint. Is this also okay?
    * `1.100200300` will be unaffected by the fix function
    * `100200300.100200300` will be effected and fixed to `100_200_300.100_200_300`

---

The project needed some getting used to but I'm happy with the result. A big thank you to @flip1995 for giving me some pointers for this implementation and to everyone for the great introduction documentation!

---

changelog: Added the `unreadable-literal-lint-fractions` configuration to disable the `unreadable_literal` lint for fractions

### CODE REVIEW

**Comment by Manishearth** [comment]
> I've named the option `lint-fraction-readability` is this a good name or should I rename it to something else?

i would have `unreadable-literal` in the name, so `unreadable-literal-lint-fractions` or something

> * What should the default configuration value be?
>   
>   * The current default value is `true` as this was also the previous default.
> 
> * Do I have to document this new option somewhere else or will it be extracted from the code comment?

yes and yes

> The current fix option will also rewrite the fraction if the integer part violates the `unreadable_literal` lint it would otherwise also trigger the `inconsistent_digit_grouping` lint. Is this also okay?

not sure what you mean here

**Review by Manishearth — APPROVED** [review]
overall looks good

**Comment by xFrednet** [comment]
The configuration was renamed to `unreadable-literal-lint-fractions`. I agree that that is a better name.

The 4th question was about the automatic suggestion if the lint gets violated for the integer part. I haven't changed the suggestion generation. This means that a number that violated the integer readability like `100200300.100200300` would also have separation in the fraction part. The suggestion for that number would be: `100_200_300.100_200_300`. I believe that this is still a good thing to keep the number consistent.

**Comment by Manishearth** [comment]
> The 4th question was about the automatic suggestion if the lint gets violated for the integer part. I haven't changed the suggestion generation. This means that a number that violated the integer readability like `100200300.100200300` would also have separation in the fraction part. The suggestion for that number would be: `100_200_300.100_200_300`. I believe that this is still a good thing to keep the number consistent.

Oh. Yeah that seems fine, that's what I would expect.

**Comment by Manishearth** [comment]
@bors r+

thanks!

**Pull request merged**
