### PR TITLE
Don't try to determine sysroot. rustc_driver will use default value.

### LINKED ISSUE #2874: Clippy cannot find 'std' with non-standard libdir
When I try even hello world project I got error:

```
$ cargo clippy --verbose
    Checking tst001 v0.1.0 (file:///tmp/tst001)
     Running `/usr/bin/clippy-driver rustc --crate-name tst001 src/main.rs --crate-type bin --emit=dep-info,metadata -C debuginfo=2 -C metadata=9d53d8442a8c6217 -C extra-filename=-9d53d8442a8c6217 --out-dir /tmp/tst001/target/debug/deps -C incremental=/tmp/tst001/target/debug/incremental -L dependency=/tmp/tst001/target/debug/deps`
error[E0463]: can't find crate for `std`

error: Could not compile `tst001`.
```
Clippy version: 0.0.210
Rustc version:
```
rustc 1.28.0-dev (773ce53ce 2018-06-26)
binary: rustc
commit-hash: 773ce53ce7b3acb97cfbd3d189dc3fbf33ec05c6
commit-date: 2018-06-26
host: x86_64-unknown-linux-gnu
release: 1.28.0-dev
LLVM version: 6.0
```

Rustc built with non-standart libdir and libstd placed there:
```
/usr/lib64/rust-9999/libstd-c9650cebf997ec41.so
/usr/lib64/rust-9999/rustlib/x86_64-unknown-linux-gnu/lib/libstd-c9650cebf997ec41.rlib
/usr/lib64/rust-9999/rustlib/x86_64-unknown-linux-gnu/lib/libstd-c9650cebf997ec41.so
```

Rustc successfully builds programs but clippy fails to check it.

### PR DESCRIPTION
**Pull request by o01eg**
Fix #2874

### CODE REVIEW

**Comment by oli-obk** [comment]
It might not be necessary when installed via rustup. I'm not sure how to properly test that. Maybe we should copy the binary to `.rustup/toolchain/whatev/bin` instead of `.cargo/bin` and see how that goes

**Comment by djc** [comment]
So how do we make progress on this? It'd be nice to get this in.

**Comment by oli-obk** [comment]
> Maybe we should copy the binary to .rustup/toolchain/whatev/bin instead of .cargo/bin and see how that goes

@o01eg can you try this?

**Comment by o01eg** [comment]
@oli-obk Is it somewhere in the code?

**Comment by oli-obk** [comment]
Oh sorry. I completely misunderstood the issue. I assumed this was dogfood failing, but it's just our normal test suite.

You need to re-add the sysroot detection code that you removed, but only into our test suite, so it won't be in the final binary. I think it should suffice to have a check for windows and then run the sysroot detection right [here](https://github.com/rust-lang-nursery/rust-clippy/blob/master/tests/compile-test.rs#L59) and then append it to the `target_rustcflags`

**Comment by oli-obk** [comment]
You also don't need all the previous code, just the call to rustc: https://github.com/rust-lang-nursery/rust-clippy/pull/3257/files#diff-80f8b83dd8e9ced9366c4eabaf0bba64L42

**Comment by o01eg** [comment]
Something odd broke again.

**Comment by oli-obk** [comment]
we seem to have lost appveyor, too XD

**Comment by hcpl** [comment]
@o01eg likely related to https://github.com/rust-lang/rust-clippy/pull/3444 as both `BASE_TESTS` jobs failed due to dogfood tests.

**Comment by o01eg** [comment]
Rebased after #3444 merged

**Comment by o01eg** [comment]
Looks like it still failed. Should I add sysroot detection to dogfood tests as well?

**Comment by oli-obk** [comment]
Yea, that seems necessary sadly.

**Comment by o01eg** [comment]
I suppose it better to merge `rustc_sysroot_path`s but not sure where to place it.

**Comment by o01eg** [comment]
I've launched AppVeyor by hand, it works: https://ci.appveyor.com/project/o01eg/rust-clippy/builds/20814346

**Comment by djc** [comment]
@o01eg do you have a version of the patch that applies to 1.31.0?

**Comment by o01eg** [comment]
I have it only for `src/driver.rs` because it need to be built on the Gentoo: 
[1.31.0-clippy-sysroot.patch.gz](https://github.com/rust-lang/rust-clippy/files/2654678/1.31.0-clippy-sysroot.patch.gz)

**Pull request merged**
