### PR TITLE
Changelog for Clippy 1.76 🐈

### PR DESCRIPTION
**Pull request by xFrednet**
Roses are red,
Violets are blue,
So many cute cats,
How to choose?

---

### The cat of this release is: *Cabrel* submitted by @daniel-g-gagnon:

The cats of this Clippy release

The cat for the next release can be voted on: [here](https://docs.google.com/forms/d/e/1FAIpQLSfERam31AEi3_5uVsugi1-JHGF9Po1oC7OIiLs8jglprZNy_g/viewform)

The cat for the next next release can be nominated in the comments and will be voted in the next changelog PR (Submission deadline is 2024-02-06 23:59CET)

---

changelog: none

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors r+

nya~~

**Comment by xFrednet** [comment]
Looks like a fluke to me:

@bors retry :D

**Comment by Centri3** [comment]
Cat of the release is an actual thing now while I was away. I'm so proud of this community

Here's my nomination..s? :3 Marcus and Mango

**Comment by Temanor** [comment]
Adorable! Here's mine ready for attack 😼
[20240130_232108.jpg](https://github.com/rust-lang/rust-clippy/assets/91745601/174296a5-7399-4133-965e-f50579fd81c2)

**Comment by tristan-morris** [comment]
IMG_2426

Nala identifies as a catto. Holds concerns for build time due to fan noise, but clippy keeps her sane.

**Comment by EbbDrop** [comment]
Nominating Woodsy telling us to take a break ❤️

**Comment by nph278** [comment]
Koshka hiding under the piano
koshka_piano

**Comment by benwh1** [comment]
Nominating Shadow

shadow

**Comment by lensvol** [comment]
Nominating Zola, who is not amused.

BDF32C0C-6A9D-4940-819E-C66EAB67CE8D

**Comment by Temanor** [comment]
Nominating Luna, ready for attack

**Comment by Temanor** [comment]
Nominating Luna, ready for attack

**Comment by flip1995** [comment]
The mac runner is acting up again...

@bors retry

**Comment by flip1995** [comment]
I love how professional the cat selection has become :heart_eyes_cat:

**Comment by xFrednet** [comment]
I'll just leave this cat-penguin here as a nomination:

cat-penguin-pair

**Comment by nyurik** [comment]
Oops, the release year was cached, and stayed as 2023... fixed in #12235

**Comment by llogiq** [comment]
Another nomination for Tom a.k.a. Maunzer.

**Comment by SpriteOvO** [comment]
image

**Pull request merged**
