### PR TITLE
[`ptr_cast_constness`]: Only lint on casts which don't change type

### LINKED ISSUE #10874: FP ptr-cast-constness breaks code
### Summary

.

### Lint Name

ptr-cast-constness

### Reproducer

I tried this code:

````rust
unsafe fn _ptr_to_ref<T, U>(p: *const T, om: *mut U) {
    let _: &mut T = std::mem::transmute(p as *mut T);
    let _ = &mut *(p as *mut T);
    let _: &T = &*(om as *const T);
}

fn main() {}
````

I saw this happen:

```
warning: `as` casting between raw pointers while changing its constness
 --> ./src/tools/clippy/tests/ui/transmute_ptr_to_ref.rs:2:41
  |
2 |     let _: &mut T = std::mem::transmute(p as *mut T);
  |                                         ^^^^^^^^^^^ help: try `pointer::cast_mut`, a safer alternative: `p.cast_mut()`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_cast_constness
  = note: requested on the command line with `-W clippy::ptr-cast-constness`

warning: `as` casting between raw pointers while changing its constness
 --> ./src/tools/clippy/tests/ui/transmute_ptr_to_ref.rs:3:19
  |
3 |     let _ = &mut *(p as *mut T);
  |                   ^^^^^^^^^^^^^ help: try `pointer::cast_mut`, a safer alternative: `p.cast_mut()`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_cast_constness

warning: `as` casting between raw pointers while changing its constness
 --> ./src/tools/clippy/tests/ui/transmute_ptr_to_ref.rs:4:19
  |
4 |     let _: &T = &*(om as *const T);
  |                   ^^^^^^^^^^^^^^^^ help: try `pointer::cast_const`, a safer alternative: `om.cast_const()`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_cast_constness
```

I expected to see this happen:

The suggestion does not compile:

````rust
unsafe fn _ptr_to_ref<T, U>(p: *const T, om: *mut U) {
    let _: &mut T = std::mem::transmute(p.cast_mut());
    let _ = &mut *(p.cast_mut());
    let _: &T = &*(om.cast_const());
}
````

````
error[E0308]: mismatched types
 --> ./src/tools/clippy/tests/ui/transmute_ptr_to_ref.rs:4:17
  |
1 | unsafe fn _ptr_to_ref<T, U>(p: *const T, om: *mut U) {
  |                       -  - found type parameter
  |                       |
  |                       expected type parameter
...
4 |     let _: &T = &*(om.cast_const());
  |            --   ^^^^^^^^^^^^^^^^^^^ expected `&T`, found `&U`
  |            |
  |            expected due to this
  |
  = note: expected reference `&T`
             found reference `&U`
  = note: a type parameter was expected, but a different one was found; you might be missing a type parameter or trait bound
  = note: for more information, visit https://doc.rust-lang.org/book/ch10-02-traits.html#traits-as-parameters

````

### Version

```text
clippy 0.1.72 (0939ec1 2023-06-02)
rustc 1.72.0-nightly (0939ec13d 2023-06-02)
binary: rustc
commit-hash: 0939ec13d88dfafcbb7f25314bd0d2f1519bf0d5
commit-date: 2023-06-02
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.4
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by Centri3**
fixes #10874

changelog: [`ptr_cast_constness`]: Only lint on casts which don't change type

### CODE REVIEW

**Comment by Centri3** [comment]
PS, I think that if both `ptr_cast_constness` and `ptr_as_ptr` are enabled, they should lint even if the type changes; like `px.cast::<u32>().cast_mut()`

**Comment by xFrednet** [comment]
Hey @blyxyas, would you mind taking a look at this PR?

If you add a comment, I can assign you to the PR as well. That helps us both to keep track of it :D

r? @xFrednet

**Comment by blyxyas** [comment]
Yep, I'll take a look at it (and maybe even merge, omg! :heart: )

**Review by blyxyas — APPROVED** [review]
I don't see anything wrong with it, pretty good fix!

**Review by xFrednet — APPROVED** [review]

**Pull request merged**
