### PR TITLE
search_is_some: add checking for `is_none()`

### PR DESCRIPTION
**Pull request by mgacek8**
fixes: #6815 
changelog: search_is_some: add checking for `is_none()`.

To be honest I don't know what is the process of renaming the lints. Appreciate any feedback if that needs to be handled differently. Thanks!

### CODE REVIEW

**Comment by llogiq** [comment]
This looks mostly good. However I no longer see a `search_is_some` lint; we don't remove lints directly, but deprecate them instead.

**Comment by matthiaskrgr** [comment]
imo it would be fine to to keep the original lint name :thinking:

**Comment by flip1995** [comment]
We use `register_renamed` for renaming lints. I'm also ok with just keeping the old lint name.

**Comment by mgacek8** [comment]
Thanks for the info! I restored the original name then :)

**Comment by llogiq** [comment]
Thank you! @bors r+

**Pull request merged**
