### PR TITLE
Don't assume lang items will exist.

### PR DESCRIPTION
**Pull request by Jarcho**
~~Should fix lintcheck warnings caused by #6823~~
See below

changelog: None

### CODE REVIEW

**Comment by flip1995** [comment]
@matthiaskrgr can you test, if this fixes the issue, please?

**Comment by matthiaskrgr** [comment]
For the record; the command I use to test is `cargo dev-lintcheck` (it will build clippy, download and lint some test-sources and dump everything into a log file).  You can check the difference against the last update with `git diff` after running. 

It does not look like the patch made a different though, hm. :/

**Comment by Jarcho** [comment]
On closer investigation, those are all legitimate lints. Now to figure out why they didn't trigger before.

**Comment by Jarcho** [comment]
Turns out `match_path` isn't really suitable for most uses . `match_path` reverses both paths, then truncates the longer one before comparing. This works in the common case where only the trait name is used. In libc, the `Clone` trait is exported from the root module, and all uses of it are through `::Clone`, which will never match the path `core::clone::Clone`.

Should probably remove all uses of `match_path`, they probably have the same issue.

**Comment by Jarcho** [comment]
This still makes a technically correct change, even if it doesn't actually fix anything.

**Comment by flip1995** [comment]
I don't think this PR makes things better, since it only moves the `Option == Option` comparison into a `map_or` closure. This rather hurts the readability.

**Comment by Jarcho** [comment]
It does change the behaviour when the clone trait dosen't exist. I'm not sure if that will ever happen.

**Comment by flip1995** [comment]
Oh right. In that case, this makes sense.

**Comment by flip1995** [comment]
@bors r+

Thanks!

**Pull request merged**
