### PR TITLE
Fix some false negatives for [`single_char_pattern`]

### PR DESCRIPTION
**Pull request by nixxquality**
*Please write a short comment explaining your change (or "none" for internal only changes)*

changelog: Fix some false negatives for [`single_char_pattern`]

I noticed that clippy wasn't complaining about my usage of `split_once("x")` in a personal project so I updated the list of functions.

I had to update the test case for an unrelated issue because replace is now included in the list of functions to be linted.

### CODE REVIEW

**Comment by nixxquality** [comment]
What's up with these failing tests? I did test before I committed and I re-tested now as well and nothing fails locally.

**Comment by llogiq** [comment]
It seems like our code doesn't live up to your improved requirements. The dogfood tests shows where updates are needed.

**Comment by nixxquality** [comment]
How do I run those tests locally?
Following the instructions in basics.md to "only run dogfood tests" using `cargo test --test dogfood` doesn't produce any failing results.

**Comment by camsteffen** [comment]
Not sure why `cargo test` didn't work, but CI is passing now! Changes look good. Please squash commits (or change the commit message to something like "Fix dogfood").

**Comment by camsteffen** [comment]
Thanks! @bors r+

**Pull request merged**
