### PR TITLE
Rustup to rustc 1.36.0-nightly (1764b2972 2019-05-12)

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by oli-obk** [comment]
I have time right now, want me to take over?

**Comment by mati865** [comment]
Related PR https://github.com/rust-lang/rust/pull/60630

**Comment by oli-obk** [comment]
It should be mostly paint by numbers by now (if not or unclear otherwise, just leave it for me for tomorrow).

If any symbol is missing, just add it to the list in `utils::sym`. If any string literal has a type error, change it to `sym::string_content`. If that's not possible because it's not a valid identifier, find a new name for it and use `your_valid_identifier: "random string"` in `utils::sym`, if you get weird type errors when using a symbol, you are probably missing a `*` (due to lazy static), so use `*sym::foo` everywhere. There's still one weird thing with a method that I didn't look too closely at (one of the hack methods with loads of `collect` calls in it). Also gazillions of unused imports, just remove them with rustfix in the end.

**Comment by Manishearth** [comment]
We have a problem, cross referential statics doesn't really work, you get lots of temporary lifetime issues.

Perhaps we can just manually initialize these with unsafe?

Also we should move all our usage of match_def_path over to just having a `clippy::diagnostic::foobar` tag on items in the stdlib.

**Comment by Manishearth** [comment]
I think what we'll need to do is to reserve a nice block of a thousand symbol ids in rustc, and then have a proc macro generate them.

**Comment by Manishearth** [comment]
I ... I just had a super devious idea. DefIds don't change for a given compiler, right?

We could totally add an intrinsic `get_def_id::<T>()` that gives you a `DefId`, and use that in `match_def_path`. Then we can just `match_def_path::<Option>(def)`

kinda prefer just annotating things, though.

**Pull request merged**
