### PR TITLE
Spellcheck

### PR DESCRIPTION
**Pull request by cpw2n5**
I'm brand new to this so any feedback will be helpful. I set the project up locally and ran a spellcheck on it. The code changes should only be spelling corrections. I ran the build and tests and they came back successful locally.

changelog: Various spelling corrections in comments and code.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
thanks!

**Comment by Manishearth** [comment]
There's a merge conflict, but I can approve this once you've fixed it

**Comment by cpw2n5** [comment]
If you don't mind please rebase for me, I trust you more. Is there a way to avoid that in the future?

**Comment by Manishearth** [comment]
Done, in general you can avoid it by ensuring you're working off an up-to-date branch, but sometimes stuff just changes while you're working on stuff and it's inevitable

@bors r+

**Pull request merged**
