### PR TITLE
Add new `unconditional_recursion` lint

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Currently, rustc `unconditional_recursion` doesn't detect cases like:

```rust
enum Foo {
    A,
    B,
}

impl PartialEq for Foo {
    fn eq(&self, other: &Self) -> bool {
        self == other
    }
}
```

This is because the lint is currently implemented only for one level, and in the above code, `self == other` will then call `impl PartialEq for &T`, escaping from the detection. The fix for it seems to be a bit tricky (I started investigating potential solution to add one extra level of recursion [here](https://github.com/rust-lang/rust/compare/master...GuillaumeGomez:rust:trait-impl-recursion?expand=1) but completely broken at the moment).

I expect that this situation will remain for a while. In the meantime, I think it's acceptable to check it directly into clippy for the time being as a lot of easy cases like this one can be easily checked (next I plan to extend it to cover other traits like `ToString`).

changelog: Add new `unconditional_recursion` lint

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Finally fixed CI. ^^'

**Comment by llogiq** [comment]
I think more tests with e.g. `other == self` and/or various wrapper type combinations would be good to rule out any false positives.

**Comment by GuillaumeGomez** [comment]
I added a lot more tests. Please tell me if you have other ideas for tests to be added.

**Comment by GuillaumeGomez** [comment]
Fixed merge conflict.

**Comment by GuillaumeGomez** [comment]
Fixed merge conflict.

**Comment by llogiq** [comment]
How about the following test case:

```rust
Impl PartialEq for Foo {
    fn eq(&self, other: &Self) -> bool {
        Bar(self) == Bar(other)
    }
}
```

There might also be some macro test cases that prove hairy, e.g. when the impl is supplied by proc macro.

**Comment by GuillaumeGomez** [comment]
I disabled the lint if the code comes from macro expansion. Maybe I should just disable it from proc-macro expansion?

As for your code example: not detected. But in this case, I can put recursion. I'm just not sure how "deep" we want to make it. Let's start with 3 nested levels and we'll see.

**Comment by llogiq** [comment]
No, leaving the example undetected is fine, loop detection would be cool but slow.

And yes, detecting code inside macros would be great if we can pull off the reporting without showing weird macro-expanded code that will only confuse people.

**Comment by GuillaumeGomez** [comment]
I have put back the (proc) macros checks, only excluding the ones generated from rustc. I also disabled a lint in the test to have less noise and added some comments in the code to make it easier to understand what's going on.

**Comment by llogiq** [comment]
Thank you!

@bors r+

**Comment by llogiq** [comment]
Thanks, this looks good.

@bors r+

**Pull request merged**
