### PR TITLE
unnecessary_sort_by: avoid linting if key borrows

### LINKED ISSUE #2313: Redundant `x_by` and `x_by_key`
For example, these:

```
x.sort_by(|l, r| l.cmp(r))
y.sort_by(|l, r| l.0.cmp(r.0))
```

could become:

```
x.sort();
y.sort_by_key(|z| z.0);
```

This also applies to `binary_search_by` and similar methods.

Perhaps we could also add a lint for adding `_by` but not `_by_key` when implementing a type.

Demonstrated on bluss/ordermap#55.

### LINKED ISSUE #5754: False positive for unnecessary_sort_by lint: Suggestion does not compile
I tried this code:

```rust
#[derive(Debug)]
pub struct Test {
    name: String,
}

impl Test {
    fn name(&self) -> &str {
        &self.name
    }
}

fn main() {
    let mut args: Vec<_> = std::env::args().map(|name| Test { name }).collect();
    args.sort_by(|a, b| a.name().cmp(b.name()));
    // Suggested by clippy, but causes a lifetime error:
    // args.sort_by_key(|a| a.name());
    println!("{:?}", args);
}
```
Clippy says:
```
    Checking playground v0.0.1 (/playground)
warning: use Vec::sort_by_key here instead
  --> src/main.rs:14:5
   |
14 |     args.sort_by(|a, b| a.name().cmp(b.name()));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `args.sort_by_key(|&a| a.name())`
   |
   = note: `#[warn(clippy::unnecessary_sort_by)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_sort_by

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
```
When applying the suggestion (= uncommenting the marked line in the code), the following happens:
```
    Checking playground v0.0.1 (/playground)
error: lifetime may not live long enough
  --> src/main.rs:16:26
   |
16 |     args.sort_by_key(|a| a.name());
   |                       -- ^^^^^^^^ returning this value requires that `'1` must outlive `'2`
   |                       ||
   |                       |return type of closure is &'2 str
   |                       has type `&'1 Test`

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

### Meta

No idea. This happens on the Rust playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=732732b92adbc28314716081acc4e733

The playground says this is clippy `0.0.212 (2020-06-26 7750c3d)` and I have no idea were to find the rustc version. Sorry.

I *cannot* reproduce locally with `clippy 0.0.212 (d4092ac 2020-05-11)`.

### PR DESCRIPTION
**Pull request by ebroto**
changelog: Avoid linting if key borrows in [`unnecessary_sort_by`]

Fixes #5754 
Closes #2313

### CODE REVIEW

**Comment by ebroto** [comment]
While working on this fix I've seen something that could backfire. 

In the `sort_by_key` cases, it's assumed that the involved types are `Copy` because the parameter of the closure it's unconditionally being dereferenced. I think it should work without it, because arithmetic operations and `std::ops::Neg` can work with references.

Am I missing something?

**Comment by ebroto** [comment]
Rebased to handle the rustup. 

I've no idea why the UI test for `multiple_crate_versions` had to be changed, especially since the manifest uses the "=X.X.X" syntax to specify the versions :thinking:

**Comment by flip1995** [comment]
@bors r+

Thanks!

**Pull request merged**
