### PR TITLE
`empty_enum_variants_with_brackets`: Do not lint `pub enum`s and `enum`s used as functions

### LINKED ISSUE #12551: empty_enum_variants_with_brackets is arguably not redundant
### Description

I noticed that Clippy in Rust 1.77 includes a new lint [`empty_enum_variants_with_brackets`](https://rust-lang.github.io/rust-clippy/master/index.html#/empty_enum_variants_with_brackets) (from #12047). The reasoning is that these are redundant.

Functionally, sure. But there is a feature of Rust where tuple-like enum variants get a kind of static function generated as a constructor for them, so you can do things like this:

```rs
pub enum Symbol {
    Number(i32),
    Text(String),
    Nothing(),
    Whitespace(),
}

pub fn parse_only_as_number(text: &str) -> Symbol {
    text.parse().ok().map_or_else(Symbol::Nothing, Symbol::Number)
}
```

This is extremely contrived, yes, but illustrates that (a) not every enum with empty variants will have a natural `Default` implementation, and (b) removing the `()` has effects outside of that change alone eg. any API requiring and receiving a `FnOnce() -> Symbol` now has to be called with a closure (`|| Symbol::Nothing`) or a static constructor has to be explicitly written.

I do not have _strong_ feelings about it, but I do use this sometimes and I wanted to raise it in case it hadn't been considered. (Ideally I'd like Rust to extend the automatic static constructor thing to _any_ empty-equivalent enum variant ie. `Empty`, `Empty()`, `Empty(())` and `Empty {}` would all have it, but I'm not writing any RFCs any time soon.)

### Version

```text
rustc 1.77.0 (aedd173a2 2024-03-17)
binary: rustc
commit-hash: aedd173a2c086e558c2b66d3743b344f977621a7
commit-date: 2024-03-17
host: x86_64-unknown-linux-gnu
release: 1.77.0
LLVM version: 17.0.6
```

### PR DESCRIPTION
**Pull request by ARandomDev99**
Fixes #12551 

changelog: [`empty_enum_variants_with_brackets`]: Do not lint `pub` enums and enums which are used as functions within the same crate.

### CODE REVIEW

**Comment by xFrednet** [comment]
Thank you for the reassign, you'll get a review from me soon. If you want to do some triaging on PRs that have been waiting for 2(+) weeks for a review you can also ping the reviewer or reassign them. `r? clippy` will pick a random reviewer but I also have some bandwidth, so `r? xFrednet` is fine :D

**Comment by xFrednet** [comment]
This PR is still marked as a draft, is there something you're still waiting on?

**Comment by xFrednet** [comment]
I'm high jacking this PR for a tiny test. 

@bors ping

You can ignore this and (hopefully) the next comment

**Comment by ARandomDev99** [comment]
> This PR is still marked as a draft, is there something you're still waiting on?

The implementation for checking if an `enum` variant is used as a function is still pending.

**Comment by xFrednet** [comment]
Okay, no pressure from my side, just wanted to know the status. Let me know if you have any questions =^.^=

**Pull request closed without merging**
