### PR TITLE
Fix typo in adding_lints.md

### PR DESCRIPTION
**Pull request by dp304**
changelog: none

### CODE REVIEW

**Comment by llogiq** [comment]
Thank you! @bors r+

**Comment by llogiq** [comment]
Error seems unrelated, we may need a rustup here.

**Comment by llogiq** [comment]
Let's rebase when #6277 lands.

**Comment by dp304** [comment]
Rebased.
I have a probably unrelated question: rustfmt is [unavailable in the nightly builds](https://rust-lang.github.io/rustup-components-history) since 2020-10-25, but that build is too old, and seems to conflict with new changes in clippy.
How can I set up the dev environment so that the most recent rustc-nightly is available as well as a recent enough rustfmt?

**Comment by llogiq** [comment]
Type `./setup_environment.sh` in your clippy project folder.

@bors r+

**Pull request merged**
