### PR TITLE
Change `redundant_pattern_matching` to also lint `std::task::Poll`

### PR DESCRIPTION
**Pull request by CDirkx**
`reduntant_pattern_matching` currently lints pattern matching on `Option` and `Result` where the `is_variant` utility methods could be used instead: `is_some`, `is_none`, `is_ok`, `is_err`. This PR extends this behaviour to `std::task::Poll`, suggesting the methods `is_pending` and `is_ready`.

Motivation: The current description of `redundant_pattern_matching` mentions

> It's more concise and clear to just use the proper utility function

which in my mind applies to `Poll` as well. 

changelog: Enhance [`redundant_pattern_matching`] to also lint on `std::task::Poll`

### CODE REVIEW

**Review by ebroto — APPROVED** [review]

**Comment by ebroto** [comment]
@bors r+

Thanks! (and sorry for the delay in reviewing, I did not have much free time lately)

**Comment by CDirkx** [comment]
If you agree with the similar reasoning I can create a PR to also add `IpAddr::is_ipv4` and `is_ipv6`

**Comment by ebroto** [comment]
Yep, sounds good to me!

**Pull request merged**
