### PR TITLE
Lint category macro-ception

### PR DESCRIPTION
**Pull request by camsteffen**
changelog: none

Caution: The speed of time reduces by a factor of two with each nested macro invocation.

### CODE REVIEW

**Comment by flip1995** [comment]
Hmm.. I don't really like this. It makes this simple piece of code so much more complex. I think the code duplication is fine here, since this is a part of code that almost never has to be touched. So I prefer the simplicity over DRY in this case.

**Comment by camsteffen** [comment]
I know what you mean. I could make it a tad simpler by inning the categories macro?

**Comment by camsteffen** [comment]
I changed it. But feel free to close.

**Comment by Manishearth** [comment]
Yeah I kinda agree with flip here. The trick is cool, but I think readability matters more than DRY here

**Pull request closed without merging**
