### PR TITLE
Rustup https://github.com/rust-lang/rust/pull/67359

### PR DESCRIPTION
**Pull request by lzutao**
cc https://github.com/rust-lang/rust/pull/67359

changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r+ 
thanks!

**Comment by flip1995** [comment]
Travis fails more and more often recently. Time for #5088 

@bors retry

**Comment by lzutao** [comment]
`bors r+` as I pushed a new commit.

**Pull request merged**
