### PR TITLE
triagebot no-merges: exclude "Rustup"s, add labels

### PR DESCRIPTION
**Pull request by pitaj**
https://github.com/rust-lang/triagebot/pull/1720

changelog: none

### CODE REVIEW

**Comment by xFrednet** [comment]
Clippy doesn't have the `has-merge-commits` label, not sure if it's worth adding it. :thinking:  The `Rustup` title check might be nice, though.

r? @flip1995 since you usually do the updates. Do you want to have fewer conversations with `@rustbot`? ^^

**Comment by pitaj** [comment]
Adding the label is low cost IMO. It's a visible reminder to the reviewer that can't get lost in a sea of comments, and bors may eventually become aware of it (reusing to merge a PR with it).

**Comment by flip1995** [comment]
Thanks! I added the label (copied from rust repo, same color and everything)

Will this PR work before merging the triagebot PR or will it break triagebot? r=me once the triagebot PR is merge or if this already works without that PR @bors delegate+

**Comment by pitaj** [comment]
It technically won't break anything but I'll wait until the triagebot change is merged.

**Pull request merged**
