### PR TITLE
Convert `&Option<T>` to `Option<&T>`

### PR DESCRIPTION
**Pull request by nyurik**
Run `ref_option` (#13336) on the Clippy's own code, quiet a few hits. Per mentioned video, this may actually improve performance as well.  Switch lint to `pedantic`

----

changelog: [`ref_option`]: upgrade lint to `pedantic`

### CODE REVIEW

**Comment by nyurik** [comment]
@rustbot r? @llogiq 
this is a follow up to #13336

**Comment by llogiq** [comment]
That makes sense to me. @bors r+

**Comment by nyurik** [comment]
Seems like some issue with the changelog?

**Pull request merged**
