### PR TITLE
Rustup to rust-lang/rust#69181

### PR DESCRIPTION
**Pull request by JohnTitor**
changelog: none

### CODE REVIEW

**Comment by JohnTitor** [comment]
cc rust-lang/rust#69269

**Comment by matthiaskrgr** [comment]
@bors r+
thanks!

**Comment by JohnTitor** [comment]
(btw I won't submit clippy-up, since usually someone from team should do it and I cannot self r+ anymore as per today's devtools meeting, so anyone feel free to <3)

**Comment by matthiaskrgr** [comment]
Looking at the diff of the currently testing rollup, clippy will likely break again if it merges, so I'm holding off on an update right now.

**Pull request merged**
