### PR TITLE
Add rust-toolchain for clippy_dev

### PR DESCRIPTION
**Pull request by mikerite**
AFAIK, `clippy_dev` is supposed to be built on stable. (This is why it's not a `[bin]` inside the root `Cargo.toml`.) This adds a `rust-toolchain` file for easy switching.

### CODE REVIEW

**Comment by phansch** [comment]
IIRC, when I added it, I was unable to make it work on stable due to interactions with the `Cargo.toml` in the root directory. Maybe that's fixed now?

**Comment by mikerite** [comment]
It seems to work on CI but should `clippy_dev` be listed as a dev dependency? With this change it gets built twice. Once with master as a dependency and again with stable when it's actually used. IMO we should remove it from the root Cargo.toml and just let it get built on demand when people run `util/dev`.

**Comment by phansch** [comment]
> IMO we should remove it from the root Cargo.toml and just let it get built on demand when people run util/dev.

Sounds good =)

**Pull request merged**
