### PR TITLE
allow refs in our constant folder

### LINKED ISSUE #3804: Allow float comparison with zero
`cargo clippy -V`: `clippy 0.0.212 (d61b254 2019-02-19)`

Clippy should allow float comparison with zero. The current behavior seems to be a regression as this has apparently already been reported and fixed in #165/#1142.

```
error: strict comparison of f32 or f64
   --> tests/test_datetime.rs:125:5
    |
125 |     assert_eq!(offset, 0f32);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[deny(clippy::float_cmp)] on by default
note: std::f32::EPSILON and std::f64::EPSILON are available.
   --> tests/test_datetime.rs:125:5
    |
125 |     assert_eq!(offset, 0f32);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#float_cmp
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by llogiq**
This helps with #3804 (but won't completely fix it).

---

changelog: none

### CODE REVIEW

**Review by ebroto — COMMENTED** [review]
Even though this is a nice improvement in the constant folder, and catches some false positives in the `float_cmp` lint, `assert_eq` is still linted when it shouldn't.

This example:
```rust
const ZERO: f32 = 0.0;

fn main() {
    let offset = ZERO;
    assert_eq!(offset, ZERO);
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dd9db61de7c81eabdac5e27f55dd9ceb))

expands to:
```rust
// ...
const ZERO: f32 = 0.0;

fn main() {
    let offset = ZERO;
    {
        match (&offset, &ZERO) {
            (left_val, right_val) => {
                if !(*left_val == *right_val) {
                    // panicking code
                }
            }
        }
    };
}
```

So to fix this the constant folder should be taught about the intermediate bindings of the `match`.

Would you be willing to add this enhancement in this PR so we can close that issue? We can also land this as is for the moment, as I said it's already an improvement.

**Comment by llogiq** [comment]
I see. In that case, I'll add match statements and derefs to our const folder. Probably later tonight.

**Comment by llogiq** [comment]
@ebroto r?

**Review by ebroto — APPROVED** [review]
>I'll add deref, but match is a lot more complex; this will require introducing binding scope. I'd like to leave this to a follow-up PR.

Seems fair. Thanks for the enhancement!

**Pull request merged**
