### PR TITLE
HirIdification fixes

### PR DESCRIPTION
**Pull request by ljedrz**
Supersedes https://github.com/rust-lang/rust-clippy/pull/3828, enables https://github.com/rust-lang/rust/pull/58836.

As usual, requesting a branch.

### CODE REVIEW

**Comment by flip1995** [comment]
Done!

**Comment by phansch** [comment]
Just needs a `rustfmt` run: https://travis-ci.com/rust-lang/rust-clippy/jobs/181875391#L1400

**Comment by ljedrz** [comment]
Cool, I'll update shortly (a bit later today or tomorrow).

**Comment by phansch** [comment]
@ljedrz I took the liberty and pushed 68096cf to your branch, that should fix Clippy for now =)

**Pull request merged**
