### PR TITLE
 build: switch back to latest official RTIM release 

### LINKED ISSUE #4666: Point RTIM to latest release
In #4663 we started using [this branch](https://github.com/kennytm/rustup-toolchain-install-master/pull/27) for CI and `./setup-toolchain.sh`. Once there's a new release out, we should switch back to that again.

cc @lzutao

### PR DESCRIPTION
**Pull request by lzutao**
Closes #4666

changelog: none

### CODE REVIEW

**Comment by lzutao** [comment]
Hmm, ICE in use_self lint ?

**Comment by mati865** [comment]
Could be rustc change, maybe `cx` is not longer right in some cases?

**Comment by flip1995** [comment]
I have a test case for this, but no fix yet. Will open a PR soon.

Problem is building this span:
https://github.com/rust-lang/rust-clippy/blob/55e7818a06c8d83bead9c81e10e73ba33fb20890/clippy_lints/src/use_self.rs#L55-L60

when the path span is in a macro in another file, but the span of the last segment is in the current file.

**Pull request merged**
