### PR TITLE
let_and_return: avoid "does not live long enough" errors

### LINKED ISSUE #3324: Possible false positive with `let_and_return`
The following code works but returns a clippy lint error: https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=2417f60b483ac63fd3ffd90b66d6db16

```
warning: returning the result of a let binding from a block. Consider returning the expression directly.
 --> src/main.rs:7:5
  |
7 |     ret
  |     ^^^
  |
  = note: #[warn(clippy::let_and_return)] on by default
note: this expression can be directly returned
 --> src/main.rs:6:15
  |
6 |     let ret = foo.borrow().baz();
  |               ^^^^^^^^^^^^^^^^^^
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#let_and_return
```

When using the suggestion of clippy to remove the let, it fails to compile: https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=285ab39429037278c362bbb6d7ffddf6

```
error[E0597]: `foo` does not live long enough
 --> src/main.rs:6:5
  |
6 |     foo.borrow().baz()
  |     ^^^ borrowed value does not live long enough
7 | }
  | - `foo` dropped here while still borrowed
  |
  = note: values in a scope are dropped in the opposite order they are created

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

### LINKED ISSUE #3792: let_and_return false positive
```
$ cargo clippy -V
0.0.212
```

The following code:

```rust
fn read_line() -> String {
    use std::io::BufRead;
    let stdin = ::std::io::stdin();
    let line = stdin.lock().lines().next().unwrap().unwrap();
    line
}
```
Triggers the let_and_return lint, however upon applying the suggested fix as so:
```rust
fn read_line() -> String {
    use std::io::BufRead;
    let stdin = ::std::io::stdin();
    stdin.lock().lines().next().unwrap().unwrap()
}
```
The code fails to compile with the following message:
```rust
error[E0597]: `stdin` does not live long enough
 --> src\main.rs:8:5
  |
8 |     stdin.lock().lines().next().unwrap().unwrap()
  |     ^^^^^---------------
  |     |
  |     borrowed value does not live long enough
  |     a temporary with access to the borrow is created here ...
9 | }
  | -
  | |
  | `stdin` dropped here while still borrowed
  | ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `std::io::Lines<std::io::StdinLock<'_>>`
  |
  = note: The temporary is part of an expression at the end of a block. Consider forcing this temporary to be dropped sooner, before the block's local variables are dropped. For example, you could
save the expression's value in a new local variable `x` and then make `x` be the expression at the end of the block
```

Basically the compiler suggest I undo the change I just made.

### PR DESCRIPTION
**Pull request by ebroto**
EDIT: Add #3324 to the list of fixes

<details>
<summary>Description of old impl</summary>
<br>
Avoid suggesting turning the RHS expression of the last statement into the block tail expression if a temporary borrows from a local that would be destroyed before.

This is my first incursion into MIR so there's probably room for improvement!
</details>

Avoid linting if the return type of some method or function called in the last statement has a lifetime parameter.

changelog: Fix false positive in [`let_and_return`]

Fixes #3792
Fixes #3324

### CODE REVIEW

**Comment by Manishearth** [comment]
I wonder if we really need the full set of checks here: MIR lints are trickier in general, perhaps just checking if the let-and-return statement contains any borrowed data is enough? This leads to some false negatives, but that's okay IMO.

**Comment by Manishearth** [comment]
thoughts, @flip1995 ?

**Comment by flip1995** [comment]
> perhaps just checking if the let-and-return statement contains any borrowed data is enough?

Can we do this easily without the MIR? Can we check for borrows in e.g. a method chain in the HIR? If there is a short and simple way to do this, I would prefer it for simplicity. But I can't think of how to do this right now.

**Comment by Manishearth** [comment]
We can just check the type for lifetime params, no?

**Comment by ebroto** [comment]
It may be relevant to the discussion that the same fix (regardless of the implementation choice in the end) can be applied to `needless_return`, removing the "known problem" in the lint description.

@Manishearth TBH I did not think of that possibility, I guess it could be valid but I kinda like the possibility of being more precise and avoid the false negatives. 

Also, (maybe due to inexperience with the code base) I'm not sure if that approach would be simpler to implement, if I'm not mistaken it would imply walking the RHS expression looking for function and method calls, and then checking the definition to see if the return value type has lifetimes (at least, maybe I'm missing other cases?)

Just wanted to give my 2 cents, but of course I'll implement whatever we decide in the end :)

**Comment by Manishearth** [comment]
Yeah, but MIR stuff is hard to maintain and I'd avoid it if we can. A couple false negatives is no biggie imo.

You don't need to walk anything, you just need to check the type of the returned value for any lifetime substitutions

**Comment by flip1995** [comment]
@Manishearth which return type do you mean? In this example:

```rust
    fn read_line() -> String {
        let stdin = io::stdin();
        let line = stdin.lock().lines().next().unwrap().unwrap();
        line
    }
```

The return type of the function is just `String`, without any lifetimes. But the FP comes from the `stdin.lock()` method call, which borrows `stdin`. So I think @ebroto is right and we would have to implement an expression visitor, that checks for borrows.

Am I missing something?

**Comment by Manishearth** [comment]
oh, I see. yeah, my bad, my model of the issue was incorrect.

**Comment by ebroto** [comment]
@Manishearth I've written the solution we discussed to avoid using the MIR, it should be ready for review :)

**Comment by Manishearth** [comment]
@bors r+

hmm, this has to go through every expression, so it's more likely that there will be false negatives. but i guess this is okay, @flip1995 do you have opinions on this vs the more complicated but more correct MIR approach?

(we can land that later if folks feel the MIR approach was also okay)

**Comment by flip1995** [comment]
As you already wrote, MIR lints are harder to maintain. I don't have experience with MIR, so reviewing code is already kind of hard. So if there is a nearly equivalent solution (a few more FNs) without MIR, I guess it's better than the MIR version. 

But in cases where MIR is necessary to prevent FPs and still have an effective lint (e.g. `redundant_clone`), I'd always go with MIR lints.

**Comment by flip1995** [comment]
For this case especially, I prefer the solution with just HIR, since it at least didn't introduce FNs in our tests.

**Comment by Manishearth** [comment]
@flip1995 yeah the current solution fixes FPs, but introduces some FNs. I care less about FNs.

**Pull request merged**
