### PR TITLE
partially HirIdify lints

### PR DESCRIPTION
**Pull request by ljedrz**
Enables https://github.com/rust-lang/rust/pull/58232 (a part of https://github.com/rust-lang/rust/pull/57578).

### CODE REVIEW

**Comment by oli-obk** [comment]
I created a local branch that we'll need to merge before bumping the clippy submodule in rustc again

**Comment by phansch** [comment]
Just needs a rustfmt run: https://travis-ci.com/rust-lang/rust-clippy/jobs/180079355#L1377

**Comment by mati865** [comment]
Note: you cannot modify 1fac380 anymore, you have to add another commit with the fix.

**Comment by ljedrz** [comment]
I'll send a fix shortly.

**Comment by ljedrz** [comment]
@mati865 thanks for the warning (makes perfect sense); I'm usually very squash-happy ^^.

**Pull request merged**
