### PR TITLE
Make `comparison_to_empty` work on `if let`/`let` chains

### PR DESCRIPTION
**Pull request by Centri3**
This adds `LetChain` to `clippy_utils::higher`, other lints may benefit from such a change as well :D

changelog: Enhancement: [`comparison_to_empty`]: Now lints on `if let`

### CODE REVIEW

**Comment by Jarcho** [comment]
This would work just as well by checking for `ExprKind::Let` rather then the whole if condition. `ExprKind::Let` can only exist as part or it.

**Comment by Centri3** [comment]
Done, I've kept `LetChain` though as I still think it can be useful in other cases

**Comment by Jarcho** [comment]
I'm not sure how useful it will end up. An iterator over binary operator chains might be useful, but I'd rather wait for a definite use case before adding it.

Generally util functions shouldn't be added without at least a single use case.

**Comment by Centri3** [comment]
> I'm not sure how useful it will end up. An iterator over binary operator chains might be useful, but I'd rather wait for a definite use case before adding it.
> 
> Generally util functions shouldn't be added without at least a single use case.

#9665. It requires something like this, and my prototype implementation uses it.

**Comment by Jarcho** [comment]
If that's the case then it should be added with that PR so it can be reviewed with it's use case.

**Comment by Jarcho** [comment]
ping @Centri3

This is only waiting on a rebase and the removal of the let-chain util.

**Comment by Jarcho** [comment]
Thank you. @bors r+

**Pull request merged**
