### PR TITLE
Move path_buf_push_overwrite to nursery

### PR DESCRIPTION
**Pull request by kraai**
See #4012.

changelog: move `path_buf_push_overwrite` to the nursery

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Looks like the rustfix stdout snippet needs an update as well?

**Comment by kraai** [comment]
@matthiaskrgr Thanks, fixing now.

**Comment by matthiaskrgr** [comment]
Looks like a change in rustc just broke clippy  :/  https://github.com/rust-lang/rust/pull/60124#issuecomment-485264491 
Don't worry about failing CI until a fix has landed in this repo...

**Comment by matthiaskrgr** [comment]
The clippy might be fixed soon :)
@bors r+

**Pull request merged**
