### PR TITLE
[Perf] Rearrange match arms according to arm frequency

### PR DESCRIPTION
**Pull request by blyxyas**
This PR changes the match arms in `check_proc_macro.rs` to match the frequency of the tokens being matched.
I made a test lint that just walks every expression and annotates its kind (same with other tokens). Then, after running a `cargo lintcheck` and studying the results, these were the results.

It was a bad decision (probably not even a decision, just that nobody thought about it) to have the match arms to be in the same order of the variants in the code. It seems like `Path`s are **very** common (19k occurences just in `serde`), so having `ConstBlock` as a first arm is not the way to go. 

I mostly used `serde` with some generalizations to make the final result.

Note that this commit doesn't change how the code works, just the structure of it.

changelog:none

### CODE REVIEW

**Comment by blyxyas** [comment]
I have some other optimizations, but it seems like this commit was the most safe to merge without being 120% sure it's an optimization using benchmarks. It's pretty obvious that it will save time (I still benchmarked it)

As soon as I have some more verifications of the riskier commits, I'll open some more PRs.

**Comment by Jarcho** [comment]
Is this really an optimization? Match expression get compiled to jump tables unless they're either very small or sparse. I'm pretty sure code layout doesn't even depend much on the written order.

> This PR changes the match arms in check_proc_macro.rs to match the frequency of the tokens being matched.
I made a test lint that just walks every expression and annotates its kind (same with other tokens). Then, after running a cargo lintcheck and studying the results, these were the results.

Is this the total count of all the nodes? That isn't the same as the count of all nodes passed to `is_from_proc_macro`. I would still suspect `Path` is very high on that list though.

**Comment by blyxyas** [comment]
I just manually inspected the assembly for both `master` and this patch (release builds), the output indeed is rearranged in the intended way.

It's normal behaviour AFAIK and something that the user is intended to do to arrange the match arms.

> Is this the total count of all the nodes? That isn't the same as the count of all nodes passed to is_from_proc_macro. I would still suspect Path is very high on that list though.

I would think that proc-macros being subsets of the whole codebase, hold the same proportions. I can make a second `lintcheck` just annotating what kind of token the ones in a proc macro are, but I'd suppose that the listings are very similar if not the same.

**Comment by Jarcho** [comment]
That doesn't match what I'm getting at all. Built with `cargo build --release` or `cargo asm --release` since they get the same code.

With this patch built on-top of a71211d:
```asm
push rbp
push r15
push r14
push rsi
push rdi
push rbx
sub rsp, 136
lea rbp, [rsp + 128]
mov qword ptr [rbp], -2
mov rdi, rdx
mov rsi, rcx
lea rcx, [rip + .LJTI723_0] ; Load jump table address
jmp .LBB723_2

; DropTemps
mov r8, qword ptr [r8 + 16]

.LBB723_2:
movzx eax, byte ptr [r8 + 8] ; Read ExprKind discriminant 
cmp rax, 31
ja .LBB723_88 ; Jump to default match arm
movsxd rax, dword ptr [rcx + 4*rax] ; Read jump table entry
add rax, rcx
jmp rax ; Jump to entry

; Tup
mov rax, qword ptr [r8 + 16] ; Load first ExprKind field (&Expr)
mov rdx, qword ptr [r8 + 24] ; Load second ExprKind field (usize)
cmp rdx, 1
ja .LBB723_106 ; If more than one expr
mov r8, rax 
je .LBB723_2 ; If one expr
test rdx, rdx
jne .LBB723_88 ; If a non-zero number of exprs

; Tup([])
movabs rax, -9223372036854775808
mov qword ptr [rsi], rax
lea rcx, [rip + __unnamed_575]
mov qword ptr [rsi + 8], rcx
mov qword ptr [rsi + 16], 1
mov qword ptr [rsi + 24], rax
lea rax, [rip + __unnamed_576]
jmp .LBB723_186 ; jump to return.

; Binary, Assign, AssignOp
mov rax, qword ptr [r8 + 24]
mov rbx, qword ptr [r8 + 32]
jmp .LBB723_107 ; jump to shared (&Expr, &Expr) handling
```

Without this patch I get the same order with very slightly different code. `Array` & `Repeat` are next the next chunk of code followed by `Cast` and `Type`.

**Comment by blyxyas** [comment]
I'll close this for now, the potential improvement isn't as important as the amount of time I would spend trying to verify the improvement.

I'll schedule a benchmark of this patch on the next few days. But it will probably not bring noticeable improvements.

**Pull request closed without merging**
