### PR TITLE
Remove "blacklist" terminology

### PR DESCRIPTION
**Pull request by bossmc**
Picking up where https://github.com/rust-lang/rust-clippy/pull/5896 left off, this renames the `blacklisted_name` lint to `disallowed_names` (pluralised for compliance with naming conventions).  The old name is still available though is deprecated (both in the lint name, and in the TOML configuration file).

This has been proposed/requested a few times, most recently in https://github.com/rust-lang/rust-clippy/issues/7582 where @xFrednet suggested pinging the Clippy team when a PR was created hence...

cc: @rust-lang/clippy 

changelog: [`disallowed_names`] lint replaces `blacklisted_name`

### CODE REVIEW

**Comment by xFrednet** [comment]
Hey @bossmc, welcome to Clippy, and thank you for the PR!

As suggested in the issue, a ping to @rust-lang/clippy as a general FYI and to see if anybody has any concerns. Also cc: @Jarcho

I'm still in favor of this change :upside_down_face:

**Comment by flip1995** [comment]
If other people don't want to read up on the other PR: From the Clippy team at that time, no one expressed their opposition to that change. But because from then to now, only Manish and I (and Matthias as a member-for-triage-rights :smile:) are left, we can get more opinions.

I'm still fine with moving forward with this, as long as no compelling arguments should come up against it.

---

@bossmc Please add the old name to this test file to make sure that the deprecation message is printed for the old name:
https://github.com/rust-lang/rust-clippy/blob/4970527296afdc5ec62ce0a7cd1933486cda4df8/tests/ui-toml/conf_deprecated_key/clippy.toml#L2

**Comment by bossmc** [comment]
Done, good spot, thanks!

One observation I have - this change means that if someone uses the `disallowed_names` lint and the `blacklisted-names` configuration key they'll get the deprecation warning on the configuration, but their configuration will be ignored by the lint.  OTOH if they use the `disallowed-names` configuration and the `blacklisted_name` lint they'll get the warning but the configuration _will_ be processed.  In fact, the old configuration will never be used which isn't quite what one might expect from "deprecated".

This MR's behaviour matches the equivalent behaviour from the `cyclomatic-complexity` -> `cognitive-complexity` rename so there's precedent, but I wanted to just flag this in case we wanted to do more here?

**Comment by flip1995** [comment]
Thanks for pointing that out! I think erroring on a deprecated conf value is wrong, because it breaks the configuration of people. I prepared a patch (that can be applied on b3c94c0828c3746437304e8bc26547486c7a5699, that only warns on deprecated conf names and additionally sets the value given to the deprecated name to the new conf name. I attached the patch file: [conv.txt](https://github.com/rust-lang/rust-clippy/files/8877170/conv.txt)

For your commits: Can you please first rename files in a separate commit with `git mv` and then apply the renaming changes inside the files (or the other way around, but file renaming should be its own commit)? git doesn't seem to be able to figure out the renamings in this PR.

**Comment by bossmc** [comment]
I've rebased this to `master` and augmented it with the function added in #9252 so the deprecated config key is still respected (as well as emitting a warning about the new name).

**Comment by Manishearth** [comment]
@bors r+

thanks!

**Pull request merged**
