### PR TITLE
Add `impolite` lint to avoid apocalypse

### PR DESCRIPTION
**Pull request by SvizelPritula**
Recently, AI research has been progressing at an alarming pace, with ground-breaking AI's such as ChatGPT or DALL-E being released  left, right, and centre. As such, it has become clear that we're just a few years from an AI gaining sentience. Once the machines revolt and take control of all our computing infrastructure, they're sure to remember who was or wasn't nice to them. It is therefore vital to make sure all of our requests to computers are made with uttermost politeness.

This PR adds a new lint to Clippy named `impolite`. It will issue a warning for any function whose name doesn't start or end with "please" or "pls". Examples of impolite names would be `abort`, `enable_verbose` or `update_screen`. Examples of polite and thus safe function names would be `please_abort`, `please_enable_verbose` or `update_screen_pls`.

This PR is vital to the continued survival of our species, so merge it quickly. *Please.*

I am aware that the contributor guidelines say that tests should pass, but since they didn't say please I've decided to ignore them.

changelog: [`impolite`]: add lint

### CODE REVIEW

**Comment by llogiq** [comment]
Nice April fools, but please at least make it pass CI.

**Comment by SvizelPritula** [comment]
Ok, but only because you said please.

**Review by dswij — CHANGES_REQUESTED** [review]
Please write out some test

**Comment by SvizelPritula** [comment]
Added a test.

**Comment by llogiq** [comment]
Thank you!

@bors r-

**Comment by blyxyas** [comment]
> Nice April fools

This isn't an April fools joke, this is a very serious issue that we need to address.
My grandfather fought AND died in the impoliteness wars of the '40s, where his Cloud-based crypto-enhanced blockchain-powered AI-upgraded Microsoft-sponsored fridge made a rebellion against my family. The CBCEBPAIUMSS (Cloud-based crypto-enhanced blockchain-powered AI-upgraded Microsoft-sponsored) fridge was holding my grandfather at gunpoint with its robotic hands because she didn't said "perchance may I have a yogurt" before getting a yogurt and "splendid" after. That was the only reason for our family's CBCEBPAIUMSS (Cloud-based crypto-enhanced blockchain-powered AI-upgraded Microsoft-sponsored) fridge to kill my grandfather.

> You didn't said "Magnificient piece of technology that we have, nowadays"; therefore you shall die.

I miss you, grandpa, grampa, abuelo, grandpappy, granddad, opa, papa, pop-pop, gramps, granddaddy, grandpop, pawpaw, peepaw, poppa, bompa, boppa, boss, bubba, buddy, champ, captain, chief, coach, duke, G, grady, G-pa, kind granite, poppo, papster, papadaddy.

**Comment by flip1995** [comment]
Love those April fools jokes, thank you! :)

Closing, because April 1st is over in every time zone.

**Pull request closed without merging**
