### PR TITLE
Rustup to rust-lang/rust#70634

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth 

changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
https://www.githubstatus.com/incidents/80d0cs6kpsps perhaps the github outage is related?

**Comment by matthiaskrgr** [comment]
```
/usr/share/rust/.cargo/bin/rustup toolchain install nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-nightly.toml' to '/home/runner/.rustup/tmp/s67ugji6hhj2raqi_file.toml'
error: caused by: error reading from socket
error: caused by: error reading a body from connection: Connection reset by peer (os error 104)
error: caused by: Connection reset by peer (os error 104)
error: backtrace:
error: stack backtrace:
   0: error_chain::backtrace::imp::InternalBacktrace::new
   1: download::reqwest_be::download
   2: rustup::utils::utils::download_file_with_resume
   3: rustup::dist::download::DownloadCfg::download_and_check
   4: rustup::dist::dist::dl_v2_manifest
   5: rustup::dist::dist::try_update_from_dist_
   6: rustup::toolchain::Toolchain::install
   7: rustup::toolchain::Toolchain::install_from_dist
   8: rustup_init::rustup_mode::update
   9: rustup_init::rustup_mode::main
  10: rustup_init::run_rustup_inner
  11: rustup_init::main
```

**Comment by flip1995** [comment]
Yep, `if` conditions in jobs seem to be broken somehow.

**Comment by Manishearth** [comment]
This is a github bug and will be fixed on monday, in the meantime we should hard-merge rustups that pass tests

**Pull request merged**
