### PR TITLE
Suggest `.as_ref()?` instead of `?` in certain circumstances.

### PR DESCRIPTION
**Pull request by fuerstenau**

### CODE REVIEW

**Comment by fuerstenau** [comment]
It works^{TM} but obviously should be sanity checked by someone who knows what they are doing. I'm not even capable of not confirming the pull request by some accidental button mashing before writing a description. (=

**Comment by mikerite** [comment]
This change contains a bug. When the `if` expression contains an `else` branch but that doesn't match `subject`.

```
#![deny(clippy::all)]

pub fn func(x: Option<u32>) -> Option<u32> {

    let _ = if x.is_none() {
        return None;
    } else {
        //x
        Some(0)
    };

    Some(0)
}

fn main() {
}
```

```
error: this block may be rewritten with the `?` operator
  --> src/main.rs:12:13
   |
12 |       let _ = if x.is_none() {
   |  _____________^
13 | |         return None;
14 | |     } else {
15 | |         //x
16 | |         Some(0)
17 | |     };
   | |_____^ help: replace_it_with
```

**Comment by fuerstenau** [comment]
Well the stupid “let's see if this lint should trigger but print out something in any case” bug should be fixed and even includes a test now to make it a bit harder to repeat my mistake.

The commata have been reinserted by hand.

**Comment by fuerstenau** [comment]
That's what I had assumed based on your rather cryptic comment but after a week of trying to confirm my hypothesis without finding a way to do so I elected to ask you about it.

**Comment by oli-obk** [comment]
I am very sorry about that. I should write my comments out. I'll do my best to do that in the future.

Please never hesitate to ask for clarification or anything else for that matter.

**Pull request merged**
