### PR TITLE
Clippy: Remove `TyCtyt::super_traits_of` public comment and test behavior

### PR DESCRIPTION
**Pull request by xFrednet**
The `TyCtyt::super_traits_of` function is actually not needed. This PR removes the reference and adds a test as well :)

changelog: none

### CODE REVIEW

**Comment by Jarcho** [comment]
That note is still accurate. `while_let_on_iterator` is working because the closure's kind is `FnOnce`.

I'm not sure if `ty_is_fn_once_param` is needed any more. It might be needed to handle cases where the closure is first assigned to a local, but that would have to be implemented first.

**Comment by xFrednet** [comment]
Could you give an example for code that wouldn't work? I tested this ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=56922f378b04ac2583fd899a888edb0c)):

```rs
    // Lint if `FnOnce` is a super trait
    trait MySpecialFnMut: FnOnce() {}
    impl<T: FnOnce()> MySpecialFnMut for T {}
    fn f4(_: impl MySpecialFnMut) {}
    let mut it = 0..10;
    let x: Box<dyn MySpecialFnMut> = Box::new(|| {
        while let Some(x) = it.next() {
            if x % 2 == 0 {
                break;
            }
        }
    });
    f4(x);
```

and it lints just fine. I have the feeling I'm just overlooking something :sweat_smile:

**Comment by Jarcho** [comment]
You're not missing anything. Looks like the closure's kind is now being set based on how it's used rather than how it's capable of being used. I guess the function can be removed then.

**Comment by Jarcho** [comment]
Ping @xFrednet

`ty_is_fn_once_param` can just be removed and `get_enclosing_loop_or_multi_call_closure` can be simplified (`is_once` will always be false due to the closure kind check right before). 

@rustbot author

**Comment by xFrednet** [comment]
Hey, year sorry, I wasn't sure if I could just remove the function and then I lost track of it :see_no_evil:

I'll close this in favor of https://github.com/rust-lang/rust-clippy/pull/11812, since that includes the suggested change.

**Pull request closed without merging**
