### PR TITLE
Fix emitting in nested (proc_)macros for nonstandard_macro_braces lint

### LINKED ISSUE #7422: False positive in nonstandard_macro_braces involving macros
```rust
// src/main.rs

#[derive(testing::Derive)]
pub struct S;

fn main() {}
```

```rust
// src/lib.rs

use proc_macro::TokenStream;

#[proc_macro_derive(Derive)]
pub fn derive(input: TokenStream) -> TokenStream {
    let _ = input;
    "fn _f() -> Vec<u8> { vec![] }".parse().unwrap()
}
```

```console
$ cargo clippy
warning: use of irregular braces for `vec!` macro
 --> src/main.rs:1:10
  |
1 | #[derive(testing::Derive)]
  |          ^^^^^^^^^^^^^^^
  |
  = note: `#[warn(clippy::nonstandard_macro_braces)]` on by default
help: consider writing `testing::Derive`
 --> src/main.rs:1:10
  |
1 | #[derive(testing::Derive)]
  |          ^^^^^^^^^^^^^^^
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#nonstandard_macro_braces
  = note: this warning originates in the derive macro `testing::Derive` (in Nightly builds, run with -Z macro-backtrace for more info)
```

`vec![]` seems like the standard braces. The ``consider writing `testing::Derive`​`` doesn't make sense.

@DevinR528 @llogiq

<br>

### Meta

- `cargo clippy -V`: clippy 0.1.55 (798baeb 2021-07-02)
- `rustc -Vv`:
  ```
  rustc 1.55.0-nightly (798baebde 2021-07-02)
  binary: rustc
  commit-hash: 798baebde1fe77e5a660490ec64e727a5d79970d
  commit-date: 2021-07-02
  host: x86_64-unknown-linux-gnu
  release: 1.55.0-nightly
  LLVM version: 12.0.1
  ```

### PR DESCRIPTION
**Pull request by DevinR528**
fixes #7422

changelog: fixes false positives in [`nonstandard_macro_braces`]

### CODE REVIEW

**Comment by llogiq** [comment]
Thank you! @bors r+

**Comment by DevinR528** [comment]
Hope this fixes it, good that it's still in `nursery` but at least now it's usable. As it was borderline unusable because of the nested macros, oh well thanks, and sorry about that.

**Comment by llogiq** [comment]
Yeah, I was about to comment that we should keep an eye on it to see when and if it can leave the nursery.

**Comment by DevinR528** [comment]
Sounds good to me! As soon as it's ready I'll enable it on a very macro (rules/fn like/derive/attribute) [heavy project](https://github.com/ruma/ruma) so that should exercise it pretty well, then maybe in a few weeks open a PR.

**Pull request merged**
