### PR TITLE
Remove old Symbol reexport

### PR DESCRIPTION
**Pull request by phansch**
I couldn't really tell what it was meant to improve. It seems more clear
without the renaming to `Name`?

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
I can't reproduce the ui-toml failure locally... 🤔

**Comment by phansch** [comment]
@flip1995 Hm, I can. In fact it has been happening for a couple of months.. I just ignored it because CI was always passing and I never had the time to investigate properly :neutral_face: 

Maybe running `cargo update` will make it reproducible? I think it has something to with compiletest_rs switching from the `test` crate to the `tester` crate some time ago.

**Pull request merged**
