### PR TITLE
deprecate invalid_ref lint

### PR DESCRIPTION
**Pull request by RalfJung**
This fixes the `invalid_ref` lint test to no longer fail when https://github.com/rust-lang/rust/pull/63346/ lands.  I also fixed the lint itself, because its wording made no sense: there is no "reference to zeroed/uninitialized memory" here.

changelog: none

### CODE REVIEW

**Comment by RalfJung** [comment]
The clippy lint is also almost entirely subsumed by the new rustc lint added in that PR, so maybe it should just be removed?

("Almost" because I didn't bother warning for direct uses of the intrinsic. That is perma-unstable, after all.)

**Comment by RalfJung** [comment]
Windows CI failure doesn't look like I caused it?

**Comment by RalfJung** [comment]
@Manishearth could you take a look? This blocks a new rustc lint that would be really nice to have in the beta.

**Comment by Manishearth** [comment]
> The clippy lint is also almost entirely subsumed by the new rustc lint added in that PR, so maybe it should just be removed?

Yes, just move it to the list of deprecated lints

**Comment by RalfJung** [comment]
@Manishearth done.

**Comment by phansch** [comment]
Also needs `./util/dev update_lints`

**Comment by RalfJung** [comment]
@phansch done.

@bors r=oli-obk (let's see if I can do this)

**Pull request merged**
