### PR TITLE
Forbid redundant_pattern_matching triggering in macros

### LINKED ISSUE #6065: redundant_pattern_matching shouldn't complain about macro generated redundant patterns
I tried this code:

```rust
fn main() {
    macro_rules! if_let_in_macro {
        ($pat:pat, $x:expr) => {
            if let Some($pat) = $x {}
        };
    }

    if_let_in_macro!(_, Some(42));
}
```

Macro is external to the crate in actual code.

I expected to see this happen: No complaints

Instead, this happened: 

```
warning: redundant pattern matching, consider using `is_some()`
 --> src/main.rs:4:20
  |
4 |               if let Some($pat) = $x {}
  |  _____________-      ^^^^^^^^^^
5 | |         };
6 | |     }
7 | |
8 | |     if_let_in_macro!(_, Some(42));
  | |     ------------------------------
  | |_____|__________________________|
  |       |                          help: try this: `if Some(42).is_some()`
  |       in this macro invocation
  |
  = note: `#[warn(clippy::redundant_pattern_matching)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pattern_matching
  = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

I believe this is wrong as it's not always fixable in macros

### Meta

- `cargo clippy -V`: clippy 0.0.212 (f3c923a 2020-09-17)
- `rustc -Vv`:
  ```
  rustc 1.48.0-nightly (f3c923a13 2020-09-17)
  binary: rustc
  commit-hash: f3c923a13a458c35ee26b3513533fce8a15c9c05
  commit-date: 2020-09-17
  host: x86_64-unknown-linux-gnu
  release: 1.48.0-nightly
  LLVM version: 11.0
  ```

<details><summary>Backtrace</summary>
  <p>
  
  ```
  <backtrace>
  ```
  
  </p>
</details>

### PR DESCRIPTION
**Pull request by alex-700**
fixes #6065 

changelog: forbid redundant_pattern_matching triggering in macros

### CODE REVIEW

**Review by matthiaskrgr — APPROVED** [review]

**Comment by matthiaskrgr** [comment]
Mmh, looks like a test is failing:
https://github.com/rust-lang/rust-clippy/pull/6069/checks?check_run_id=1139967161#step:10:138

**Review by Manishearth — APPROVED** [review]
r+ but this should pass tests

**Comment by alex-700** [comment]
@Manishearth, hm... Is it OK to remove falling test? :) This test is about regression in one of the `matches` lints and check that message generation inside a macro don't cause ICE. But it seems the forbidding triggerring a lint inside a macro is a common pattern for most of Clippy lints.

**Comment by Manishearth** [comment]
We don't suppress macros for all of these, so maybe pick a different lint there.

**Comment by alex-700** [comment]
> We don't suppress macros for all of these

But there are a lot of constructions like `if in_macro(...) { return; }`...

> so maybe pick a different lint there.

Sorry, I don't understand, what you mean. I can see two options here: 
- lift the check down (only for `redundant_pattern_matching`)
- remove `ice2636.stderr` (or even with ice2636.rs (because in this case it checks nothing)).

Which one of them do you think better?

**Comment by Manishearth** [comment]
I mean that the test can be rewritten to use a different lint. But I think it's also fine to remove, most cases where this ICEs should have a macro check anyway.

**Comment by alex-700** [comment]
tests failed because of #6067

**Pull request merged**
