### PR TITLE
Fix `let_undescore_lock` false-positive when binding without locking

### LINKED ISSUE #8486: `clippy::let_underscore_lock` false-positive when binding mutex without locking
### Summary

`let_underscore_lock` should only fire if the `.lock()` method is being invoked (and/or the type being bound is a lock guard)

### Lint Name

let_underscore_lock

### Reproducer

I tried this code:

```rust
pub fn main() {
    let x = parking_lot::Mutex::new(0);
    let _ = x;
}
```

I saw this happen:

```
    Checking playground v0.0.1 (/playground)
error: non-binding let on a synchronization lock
 --> src/main.rs:3:5
  |
3 |     let _ = x;
  |     ^^^^^^^^^^
  |
  = note: `#[deny(clippy::let_underscore_lock)]` on by default
  = help: consider using an underscore-prefixed named binding or dropping explicitly with `std::mem::drop`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_lock
```

I expected to see this happen:

Nothing

### Version

```text
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-pc-windows-msvc
release: 1.59.0
LLVM version: 13.0.0
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by tsoutsman**
Fixes #8486.

changelog: Fix `let_undescore_lock` false-positive when binding without locking.

### CODE REVIEW

**Comment by llogiq** [comment]
Thank you! @bors r+

**Comment by llogiq** [comment]
Rebasing might help as #9055 was just merged.

**Comment by tsoutsman** [comment]
Thanks for the hint, @llogiq; it should be good now.

**Pull request merged**
