### PR TITLE
Add tests for issues #10285, #10286, #10289, #10287

### LINKED ISSUE #10285: deny transmute of `&[T]` into `&[U]` where `U` is larger than `T`
### What it does

This prevents a kind of UB.

Examples:

```rs
let bytes = &[1u8, 2u8, 3u8, 4u8] as &[u8];
let alt_slice: &[u32] = unsafe { core::mem::transmute(bytes) };
// expected to be expanded
assert_eq!(alt_slice[0], 1);
assert_eq!(alt_slice[1], 2);
assert_eq!(alt_slice[2], 3);
assert_eq!(alt_slice[3], 4);
```

This is not true. `alt_slice[0]` have (mostly) `0x01020304` or `0x04030201` depending on byte-order, and left is looks like garbage and user thinks it is not what (s)he wanted.

Also, this contains UB. Miri reports call to `transmute` is UB.

I believe: `mem::transmute::<&[T], &[U]>` is UB if and only if `mem::size_of<T> < mem::size_of<U>`.

Alternatives:

This may not be `MachineApplicable`, because:
If user is expected to keep length and transmute each element:

```rs
// let original_slice: &[T] = ...
let alt_slice: &[U] = original_slice
    .iter()
    .map(|original| unsafe { core::mem::transmute(original) })
    .collect::<Vec<_>>()
    .as_slice()
```

If user is expected to transmute entire bit pattern of pointing bit-pattern: 
```rs
// let original_slice: &[T] = ...
let (prefix, align_result, suffix) = original_slice.align_to::<U>();
assert_eq!(prefix.len(), 0);
assert_eq!(suffix.len(), 0);
```

### Lint Name

transmute_to_larger_element_slice

### Category

correctness

### Advantage

- Prevents a kind of UB.

### Drawbacks

_No response_

### Example

```rust
// let bytes = &[1u8, 2u8, 3u8, 4u8] as &[u8];
let alt_slice: &[u32] = unsafe { core::mem::transmute(bytes) };
```

Could be written as:

```rust
let alt_slice: &[u32] = original_slice
    .iter()
    .map(|original| unsafe { core::mem::transmute(original) })
    .collect::<Vec<_>>()
    .as_slice()
```

or

```rust
let (prefix, align_result, suffix) = original_slice.align_to::<u32>();
assert_eq!(prefix.len(), 0);
assert_eq!(suffix.len(), 0);
```

### LINKED ISSUE #10286: transmute `&[T]` to `&[U]` may cause truncations for whole bit-pattern when `size_of::<T>` > `size_of::<U>`
### What it does

Consider following example:
```rs
let a: &[u32] = &[0x12345678, 0x90ABCDEF, 0xFEDCBA09, 0x87654321];
let b: &[u8] = unsafe { std::mem::transmute(a) };

assert_eq!(b[0], 0x78);
assert_eq!(b[1], 0xEF);
assert_eq!(b[2], 0x09);
assert_eq!(b[3], 0x21);
```

but this is not true. This may be true (depending on architecture):
```rs
assert_eq!(b[0], 0x12);
assert_eq!(b[1], 0x34);
assert_eq!(b[2], 0x56);
assert_eq!(b[3], 0x78);
```

or this:

```rs
assert_eq!(b[0], 0x78);
assert_eq!(b[1], 0x56);
assert_eq!(b[2], 0x34);
assert_eq!(b[3], 0x12);
```

This is generic over both element type (in above example, `u32` and `u8`).

This can be rewritten as:

```rs
// reinterpret bit-pattern of *each element*
let b: &[u8] = a.iter()
    .map(|it| unsafe { std::mem::transmute(it) })
    .collect::<Vec<_>>()
    .collect();
```

or

```rs
// reinterpret whole bit-pattern
let (prefix, align_result, suffix) = original_slice.align_to::<u8>();
assert_eq!(prefix.len(), 0);
assert_eq!(suffix.len(), 0);
```

### Lint Name

transmute_to_smaller_element_may_cause_truncation

### Category

suspicious

### Advantage

- Prevents truncations for whole bit-pattern.

### Drawbacks

- None

### Example

```rust
let a: &[u32] = &[0x12345678, 0x90ABCDEF, 0xFEDCBA09, 0x87654321];
let b: &[u8] = unsafe { std::mem::transmute(a) };
```

Could be written as:

```rust
// reinterpret bit-pattern of *each element*
let b: &[u8] = a.iter()
    .map(|it| unsafe { std::mem::transmute(it) })
    .collect::<Vec<_>>()
    .collect();
```

or 

```rs
// reinterpret whole bit-pattern
let (prefix, b, suffix) = original_slice.align_to::<u8>();
assert_eq!(prefix.len(), 0);
assert_eq!(suffix.len(), 0);
```

### LINKED ISSUE #10287: deny transmute `&T` to `&U` where `size_of::<T>` < `size_of::<U>`
### What it does

Consider following example:

```rs
let u8_ref: &u8 = &0u8;
let u64_ref: &u64 = unsafe { std::mem::transmute(u8_ref) };
```

This is UB, reported by miri.

Above example can be written:

```rs
let u8_ref: &u8 = &0u8;
let u64_ref: &u64 = &(*u8_ref as u64);
```

Generalize:
let `Original` is original type, and `Dest` is destination type.

If `Original: Clone` and can be coerced into `Dest` by `as`-cast, this can be written as:
```rs
let original_ref: &Original = Original;
let dest_ref: &Dest = &(original_ref.clone() as Dest);
```

If `Original: Clone + Into<Dest>`, this can be written as:
```rs
let original_ref: &Original = Original;
let dest_ref: &Dest = &(original_ref.clone().into());
```

If `Original: AsRef<Dest>`, this can be written as:
```rs
let original_ref: &Original = Original;
let dest_ref: &Dest = original_ref.as_ref();
```

### Lint Name

transmute_to_reference_to_larger_content

### Category

correctness

### Advantage

- Prevents UB.

### Drawbacks

- None.

### Example

```rs
let u8_ref: &u8 = &0u8;
let u64_ref: &u64 = unsafe { std::mem::transmute(u8_ref) };
```

Could be written:

```rs
let u8_ref: &u8 = &0u8;
let u64_ref: &u64 = &(*u8_ref as u64);
```

### LINKED ISSUE #10289: deny transmute `&[T]` to `&[bool]`
### What it does

consider following example:

```rs
let single_u64: &[u64] = &[0xDEAD_BEEF_DEAD_BEEF];
let bools: &[bool] = unsafe { std::mem::transmute(single_u64) };
assert_eq!(bools.len(), 64);
```

but this is not true, because transmute does not change slice length.
this contains UB: Every integral value except `0` or `1` cannot be `bool`.
this also contains error-prone: `bool`'s alignment is 1-byte, which may be surprizing if user thought bool is 1-bit (formally `size_of::<[T; N]>() == size_of::<[bool; N * size_of::<T>]>()`).

### Lint Name

transmute_slice_to_bool_slice

### Category

correctness, suspicious

### Advantage

- Removes potential UB.
- Prevents error-prone.

### Drawbacks

_No response_

### Example

```rs
let single_u64: &[u64] = &[0xDEAD_BEEF_DEAD_BEEF];
let bools: &[bool] = unsafe { std::mem::transmute(single_u64) };
```

may be written as:

```rust
    // under #![feature(strict_provenance)] to help miri
    let bools: Vec<bool> = {
        let element_size_in_bytes = std::mem::size_of::<u64>();
        let original_slice_len = u64.len();
        let mut ret = Vec::with_capacity(original_slice_len * element_size_in_bytes * 8);
        for i in 0..original_slice_len {
            let elem: u64 = u64[i];
            let head: *const u8 = std::ptr::from_exposed_addr((&elem as *const u64).addr());
            let u8_slice: &[u8] = unsafe { std::slice::from_raw_parts(head, element_size_in_bytes) };
            let bits = element_size_in_bytes * 8;
            for bit in 0..bits {
                let is_bit = u8_slice[bit] & (1 << bit % 8) == 1;
                ret[i * element_size_in_bytes * 8 + bit] = is_bit;
            }
        }
        
        ret
    };
    
    // assert_eq!(bools, [true, true, false, true, true, true, true, false, true, false, true, false, true, true, false, true, true, false, true, true, true, true, true, false, true, true, true, false, true, true, true, true, true, true, false, true, true, true, true, false, true, false, true, false, true, true, false, true, true, false, true, true, true, true, true, false, true, true, true, false, true, true, true, true]);

```

but miri reports this code as an UB.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #10285.
Fixes #10286.
Fixes #10289.
Fixes #10287.

This PR simply adds tests for the listed issues as they're already implemented so we can close them.

r? @blyxyas 

changelog:none

### CODE REVIEW

**Comment by blyxyas** [comment]
Could you please list where are they implemented? (ㅇㅅㅇ❀)

**Comment by GuillaumeGomez** [comment]
You mean adding a comment in the UI tests for each of them or something else?

**Comment by blyxyas** [comment]
Thinking more about it, it doesn't matter

**Comment by GuillaumeGomez** [comment]
As you wish. ;)

**Review by blyxyas — APPROVED** [review]
LGTM, thanks! :heart:

**Comment by blyxyas** [comment]
ฅ^•ﻌ•^ฅ

**Pull request merged**
