### PR TITLE
Rustup to https://github.com/rust-lang/rust/pull/64746

### PR DESCRIPTION
**Pull request by phansch**
changelog: none

### CODE REVIEW

**Comment by phansch** [comment]
Looks like we're running into https://github.com/rust-lang/cargo/issues/7427

**Comment by Manishearth** [comment]
This isn't the correct rustup, we should add a type annotation so that the error isn't hit at all.

We should avoid hitting compiler errors in tests, otherwise they tend to exit before some of their things get tested :smile:

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust-clippy/pull/4574

**Pull request closed without merging**
