### PR TITLE
Rewrite `empty_line_after_doc_comments` and `empty_line_after_outer_attr`, move them from `nursery` to `suspicious`

### PR DESCRIPTION
**Pull request by Alexendoo**
changelog: [`empty_line_after_doc_comments`], [`empty_line_after_outer_attr`]: rewrite and move them from `nursery` to `suspicious`

They now lint when there's a comment between the last attr/doc comment and the empty line, to cover the case:

```rust
/// Docs for `old_code
// fn old_code() {}

fn new_code() {}
```

When these lints or `suspicious_doc_comments` trigger we no longer trigger any other doc lint as a broad fix for #12917, reverts some of #13002 as the empty line lints cover it

I ended up not doing https://github.com/rust-lang/rust-clippy/issues/12917#issuecomment-2161828859 as I don't think it's needed

### CODE REVIEW

**Comment by dswij** [comment]
Sorry for the wait, I'll review it in the weekend

**Comment by Alexendoo** [comment]
No rush here, whenever you get around to it is fine

**Comment by Alexendoo** [comment]
No changes in that rebase, just wanted to try out https://github.com/rust-lang/rust-clippy/pull/13124

**Review by dswij — APPROVED** [review]
This is great stuff! Thanks for this!

**Pull request merged**
