### PR TITLE
Revert "Bump ui_test to 0.23"

### PR DESCRIPTION
**Pull request by blyxyas**
#12746 introduced very buggy behaviour (`.fixed` tests not being checked, not showing what went wrong... etc.), this commit reverts that and it should fix all those issues. We'll check again once ui_test 0.24.0 is available.

### CODE REVIEW

**Comment by flip1995** [comment]
Did you already report this issue to `ui_test` and will it be fixed with `0.24`?

**Comment by blyxyas** [comment]
It seems to be this issue https://github.com/oli-obk/ui_test/issues/238

**Comment by flip1995** [comment]
Is the issue just that no summary is printed or that the files don't actually get checked, resulting in broken tests?

**Comment by xFrednet** [comment]
cc @oli-obk

**Comment by xFrednet** [comment]
Maybe https://github.com/oli-obk/ui_test/issues/176 could also be related? There was a time, where `ui_test` blessed files automatically, which would prevent any errors

**Comment by blyxyas** [comment]
Just tested this, seems that while the testing is not shown on screen, if the `.fixed` file was different it would output an error.
It's still quite annoying that the screen doesn't refresh to show this, and that it isn't uncommon to not show output. After commenting it to Timo on #12830, he sent this screenshot about how it looks.

> > EDIT: On CI it seems like there aren't any issues, could you test the patch on your PC to check? Maybe it's just my workflow
> 
> Oh sorry, didn't see this edit. Huh... yeah, I'm seeing something similar. image
> 
> I don't think this is something caused by this PR though. It also seems to happen on master for me.
> 
> Anyway, I'll try taking a closer look at the changes in a bit

**Comment by flip1995** [comment]
Running UI tests a few times the last few days, I also noticed this bug. It goes away when running with blessing, I think. But since it is just a visual bug, I would rather not downgrade ui_test again. This would introduce multiple ui_test versions in rustc and it might make it harder to upgrade once 0.24 is released (with this potentially fixed).

**Comment by oli-obk** [comment]
I have figured out what the `.fixed` issue is and am currently refactoring to fix it. Not sure yet what the issue is with the missing final report

**Comment by blyxyas** [comment]
?? This shouldn't have propagated here? I was just testing a test bot and using this branch as a test for a PR (in my Clippy fork.)
I'll close the PR, and let's see if the issue gets fixed on future versions.

**Pull request closed without merging**
