### PR TITLE
Check for `.to_string().into_bytes()` in string_lit_to_bytes

### LINKED ISSUE #6927: string_lit_as_bytes should also detect `"str".to_string().into_bytes()`
Lint name: `string_lit_as_bytes `

I tried this code:

```rust
let bytes1 = "Length".as_bytes();

let bytes2 = "Length".to_string().into_bytes();
```

I expected to see this happen:  for the second case (`bytes2`) to also be detected by the lint and recommend using `b"Length" instead

Instead, this happened: only the first case for `bytes1` was detected.

This came from real user code we had and manually fixed, would be nice if the lint can be extended to this case as well.

### Meta

- clippy 0.0.212 (cb75ad5d 2021-02-10)
- `rustc -Vv`:
  ```
   rustc 1.50.0 (cb75ad5db 2021-02-10)
   binary: rustc
   commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
   commit-date: 2021-02-10
   host: x86_64-pc-windows-msvc
   release: 1.50.0
  ```

### PR DESCRIPTION
**Pull request by ebobrow**
fixes #6927 

changelog: Add a check for `into_bytes()` to string_lit_to_bytes lint

### CODE REVIEW

**Review by camsteffen — CHANGES_REQUESTED** [review]
Good first contribution! Just a few comments.

**Comment by ebobrow** [comment]
Thanks for the review! I've applied your suggestions.

**Review by camsteffen — APPROVED** [review]
Looks good. Please squash your commits.

**Comment by camsteffen** [comment]
Thanks! @bors r±

**Pull request merged**
