### PR TITLE
Move cognitive_complexity to nursery

### PR DESCRIPTION
**Pull request by dtolnay**
As discussed in https://github.com/rust-lang/rust-clippy/issues/5418#issuecomment-610054361; Clippy's current understanding of cognitive complexity is not good enough yet at analyzing code for understandability to have this lint be enabled by default.

changelog: Remove cognitive_complexity from default set of enabled lints

### CODE REVIEW

**Comment by felix91gr** [comment]
Wow, you're so fast!

I came here to comment on this little thing, because in my original comment I was a bit ambiguous:

> Clippy's current understanding of cognitive complexity is not good enough yet

What I meant in #5418 by "our" current understanding of cognitive complexity was not just Clippy's machinery and the developers that have worked on it. I meant us as in, the computer science + developer community. We just don't know how to properly quantify cognitive complexity (in the conversation quoted at #5418 I went into more detail). That's why no tools, not even Clippy, are able to give a satisfying, or generally useful, answer to the question of "Is this function/file/impl too complex?"

**Comment by flip1995** [comment]
@dtolnay a rebase is required after the rollup #5438

**Comment by dtolnay** [comment]
Rebased.

**Pull request merged**
