### PR TITLE
[WIP] Test if clippy got much slower over the last few days

### PR DESCRIPTION
**Pull request by lzutao**
The aid is to check if clippy got much slower over the last few days.
And check if its cause is #4703.

changelog: none

### CODE REVIEW

**Comment by lzutao** [comment]
After merging #4702, clippy integration tests got much slower.

The test time for log in #4702: [25.05](https://travis-ci.com/rust-lang/rust-clippy/jobs/247543055#L4760)

But in another build after that PR, it got much slower: [5m 37s](https://travis-ci.com/rust-lang/rust-clippy/jobs/248140128#L2746)

**Comment by lzutao** [comment]
Closed and reopend to trigger rebuild.

**Comment by phansch** [comment]
Note that Clippy is not building right now due to https://github.com/rust-lang/rust/pull/65647. The integration tests don't fail even if they should?

**Comment by lzutao** [comment]
> The integration tests don't fail even if they should

Should be fixed in #4675

**Pull request closed without merging**
