### PR TITLE
Bump ui_test version

### PR DESCRIPTION
**Pull request by oli-obk**
r? @alexendoo

the rustfix diff is caused by https://github.com/oli-obk/ui_test/pull/244

This should solve the issues around missing summaries at the end

changelog: none

### CODE REVIEW

**Comment by oli-obk** [comment]
cc @GuillaumeGomez https://github.com/rust-lang/rust-clippy/pull/11421

**Comment by GuillaumeGomez** [comment]
Awesome, thank you!

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by flip1995** [comment]
I opened https://github.com/rust-lang/rust-clippy/issues/13099 to fix the `@no-rustfix` attributes that were added. The same thing already worked great with https://github.com/rust-lang/rust-clippy/issues/12379

**Review by Alexendoo — APPROVED** [review]

**Comment by Alexendoo** [comment]
🎉

@bors r+

**Comment by GuillaumeGomez** [comment]
Sorry but the bug is still there:

```
thread 'main' panicked at /home/imperio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/annotate-snippets-0.11.4/src/renderer/display_list.rs:1103:29:
byte index 18 is not a char boundary; it is inside '脑' (bytes 16..19) of `    let _ = "电脑\0".as_ptr();`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Pull request merged**
