### PR TITLE
Add `manual_bits` lint

### LINKED ISSUE #6670: Replace `std::mem::size_of<T>()` with `::BITS` constant
### What it does

Starting in Rust 1.51, all integer types will have a ::BITS constant for the number of bits in the type. `std::mem::size_of::<usize>() * 8` can be replaced with `usize::BITS` and similarly for all signed and unisigned integers. This lint suggests such a change.

### Categories (optional)

- Kind: clippy::style

*What is the advantage of the recommended code over the original code*

For example:

- One fewer function call (saving several nanoseconds)
- Easier to read

### Drawbacks

None.

### Example

```rust
std::mem::size_of::<usize>() * 8
```

Could be written as:

```rust
usize::BITS
```

### PR DESCRIPTION
**Pull request by paolobarbolini**
Closes #6670 

---

changelog: new lint: [`manual_bits`]

### CODE REVIEW

**Comment by paolobarbolini** [comment]
:thinking: I tried reproducing the CI error [^1] locally by running `cargo test --features deny-warnings,internal-lints,metadata-collector-lint` but all tests pass for me.

[^1]: https://github.com/rust-lang/rust-clippy/runs/4688893836?check_suite_focus=true#step:8:835

**Comment by m-ou-se** [comment]
Oh nice! Thanks for implementing this! (I'm not a clippy reviewer. Just happy to see this getting added. ^^)

**Comment by mikerite** [comment]
It looks like it triggers for `size_of_val` instead. I don't think it should do this.

```rust
#![warn(clippy::size_of_as_bits)]

use std::mem;

fn main() {
    let x = 0u32;
    println!("{}", 8 * mem::size_of_val(&x));
}

```
```
warning: you seem to be using `mem::size_of::<T>()` to obtain the size of `T` in bits
 --> src/main.rs:7:20
  |
7 |     println!("{}", 8 * mem::size_of_val(&x));
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using: `u32::BITS`
  |
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![warn(clippy::size_of_as_bits)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#size_of_as_bits
```

**Comment by mikerite** [comment]
There is also an issue with type aliases.

```rust
#![warn(clippy::size_of_as_bits)]

use std::mem;

type Word = u32;

fn main() {
    println!("{}", 8 * mem::size_of::<Word>());
}
```
```
warning: you seem to be using `mem::size_of::<T>()` to obtain the size of `T` in bits
 --> src/main.rs:8:20
  |
8 |     println!("{}", 8 * mem::size_of::<Word>());
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using: `u32::BITS`
  |
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![warn(clippy::size_of_as_bits)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#size_of_as_bits
```
I think the suggestion should be `Word::BITS` instead.

**Comment by camsteffen** [comment]
The name is a bit funny to me. Perhaps `size_of_to_bits` or `bits_from_size_of`.

**Comment by mikerite** [comment]
I like `manual_bits` for the name.

**Comment by paolobarbolini** [comment]
I applied all of the above suggestions

**Comment by paolobarbolini** [comment]
:+1:. I also rebased on top of master since #8190 would have broken my code and bumped the `clippy::version` to 1.60.

**Comment by flip1995** [comment]
@bors r+

Thanks!

**Comment by HaoYang670** [comment]
I am afraid that in most contexts (especially in match arms), `sizeof::<u8>() * 8` cannot be simply replaced by `u8::BITS` because the return type of `sizeof` is `usize` but `u8::BITS` is `u32` type (especially in match arms).

What about  "help: consider using: `u32::BITS as usize` "?

**Comment by mikerite** [comment]
@HaoYang670, what is the point of tacking a comment onto a PR that was merged three months ago? The correct way to get your problem addressed is to create an issue.

**Comment by xFrednet** [comment]
I'll fix the suggestion, that'll probably faster than creating an issue for it ^^

**Pull request merged**
