### PR TITLE
just a typo II

### PR DESCRIPTION
**Pull request by o752d**
resolves #6309

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
This has to be done in the same PR, otherwise it won't pass the CI. Please push this commit (4cfa49e) to the branch used in #6309.

**Comment by o752d** [comment]
I wasn't able to simply pull the prior PR into my fork

**Comment by flip1995** [comment]
Alright, in that case, can you apply the change you made there, here instead?

**Comment by o752d** [comment]
These commits are being done in GitHubs IDE, I can change my clippy branch to whichever PR but cannot seem to then simply pull it locally, I will probably recall these PRs and fork clippy

**Pull request closed without merging**
