### PR TITLE
Merge backport branch back into master

### PR DESCRIPTION
**Pull request by flip1995**
Merge back backport branch rust-1.42.0 into master.

Waiting on rust-lang/rust#68753

changelog: none

### CODE REVIEW

**Comment by JohnTitor** [comment]
@flip1995 Just confirm: could I r+ clippy up on rust-lang/rust? Or is there any thoughts?

**Comment by flip1995** [comment]
I don't have rights in the rust-lang/rust repo, so not really my place to decide. But if you just clippyuped to the latest master branch, this normally gets accepted with `bors r+ p=1`.

Since you posted here: **No commits** from this PR or the `rust-1.42.0` branch should be included in the clippyup.

**Pull request merged**
