### PR TITLE
Update `ui_test` to `0.22`

### PR DESCRIPTION
**Pull request by Jarcho**
Blocked on oli-obk/ui_test#198.

changelog: None

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust-clippy/pull/12198 :thinking:

**Comment by Jarcho** [comment]
I thought I had seen that earlier, but a search for 'ui_test' didn't show anything. Thank you GitHub.

**Comment by flip1995** [comment]
Should we close the other PR, in favor of this? I like this PR better, as it doesn't change all the `$DIR` replacements in the `stderr` files.

**Comment by Jarcho** [comment]
This will still have the same change, I just hadn't updated the tests on this yet due to the linked issue.

**Comment by oli-obk** [comment]
Thanks for fixing ui_test @Jarcho

**Pull request closed without merging**
