### PR TITLE
Make empty_line_after_outer_attr an early lint

### LINKED ISSUE #5567: false positive on empty_line_after_outer_attr with async-trait
Hello!

I think I found an issue with the `empty_line_after_outer_attr` when using `async-trait` crate.

here's the clippy output

```rs
error: Found an empty line after an outer attribute. Perhaps you forgot to add a `!` to make it an inner attribute?
  --> src/main.rs:19:5
   |
19 |     async fn fetch_user_feed(&self, _user_id: &str) -> Result<(), ClientError> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> src/main.rs:2:9
   |
2  | #![deny(clippy::nursery)]
   |         ^^^^^^^^^^^^^^^
   = note: `#[deny(clippy::empty_line_after_outer_attr)]` implied by `#[deny(clippy::nursery)]`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#empty_line_after_outer_attr

error: aborting due to previous error

error: could not compile `async-trait-bug`.
```

the `cargo clippy -V`

```rs
clippy 0.0.212 (204bb9b5 2020-03-17)
```

and you can find the source here: https://github.com/Freyskeyd/async-trait-bug

Thanks!

### PR DESCRIPTION
**Pull request by phansch**
Fixes #5567

Unfortunately I couldn't find a way to reproduce the issue without syn/quote. Considering that most real-world macros use syn and/or quote, I think it's okay to pull them in anyway.

changelog: Fix false positive in [`empty_line_after_outer_attr`]

### CODE REVIEW

**Comment by flip1995** [comment]
We may have to be careful with the versions we use in syn and quote, so it is compatible with other tools of the rust-lang/rust repo?

**Comment by phansch** [comment]
Hm `rust-lang/rust` is on 

> We may have to be careful with the versions we use in syn and quote, so it is compatible with other tools of the rust-lang/rust repo?

For now I've specified the same versions as in rustc's `Cargo.lock`. I'm not sure how it will behave with the `full` feature though - it's required for the `TraitItem` and `ItemTrait` types.

**Comment by mati865** [comment]
Rust will override features with https://github.com/rust-lang/rust/blob/master/src/tools/rustc-workspace-hack/Cargo.toml
That means:
```
quote = { version = "1", features = ["default"] }
...
syn-1 = { package = "syn", version = "1", features = ['fold', 'full', 'extra-traits', 'visit'] }
```

**Comment by flip1995** [comment]
@phansch I think using just `version = "1"` would be better here, since the same is used in rustc-workspace-hack. After that r=me

**Pull request merged**
