### PR TITLE
Update `stable_sort_primitive` to prefer `sort` not only primitive types

### LINKED ISSUE #9970: New / Updated Lint: Prefer `sort_unstable` over `sort`
### What it does

While there already is a similar lint `stable_sort_primitive`, this should be extended to **all** types, not just primitives. If you call the plain `.sort()` (importantly not the other variants), then typically all bits of a type contribute to the sorting. It is therefore impossible to differentiate equal elements after the fact, meaning there was no need for a stable sort in the first place. Only in exceedingly rare situations (which I wouldn't even have any example of) would calling the plain `.sort()` ever make sense over `.sort_unstable()`. Linting against all (maybe as a performance lint) and forcing users to explicitly `#[allow(...)]` the lint in those incredibly rare situations makes the most sense to me.

### Lint Name

stable_sort_primitive

### Category

perf

### Advantage

- It's faster in most cases.

### Drawbacks

- There are rare situations (of which I haven't found an example) where it may be wrong to use `sort_unstable`.
- `sort_unstable` is not always faster.

### Example

```rust
foo.sort();
```

Could be written as:

```rust
foo.sort_unstable();
```

### PR DESCRIPTION
**Pull request by chansuke**
Fixes #9970 

- \[x] Followed [lint naming conventions][lint_naming]
- \[x] Added passing UI tests (including committed `.stderr` file)
- \[x] `cargo test` passes locally
- \[x] Executed `cargo dev update_lints`
- \[ ] Added lint documentation
- \[x] Run `cargo dev fmt`

---

changelog: Move: Renamed `stable_sort_primitive` to `stable_sort`
[#10258](https://github.com/rust-lang/rust-clippy/pull/10258)
changelog: Enhance: `stable_sort`: Now suggests using unstable sort for all types
[#10258](https://github.com/rust-lang/rust-clippy/pull/10258)

### CODE REVIEW

**Comment by Manishearth** [comment]
This should also declare this as a renamed lint

**Comment by xFrednet** [comment]
Hey @chansuke, this is a ping from triage. Are you planning to continue working on this PR?

**Comment by chansuke** [comment]
@xFrednet 
Thank you for your ping.I'd like to finish up this PR.I will rebase (or recreate PR)this branch in this weekend.

**Comment by xFrednet** [comment]
Hey this is triage, I'm closing this due to inactivity. If you want to continue this implementation, you're welcome to create a new PR. Thank you for the time, you already put into this!

Interested parties are welcome to pick this implementation up as well :)

@rustbot label +S-inactive-closed -S-waiting-on-author -S-waiting-on-review

**Pull request closed without merging**
