### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by flip1995**
r? @ghost

cc @max-niederman With the latest sync, I'm getting a lot of FP in the `redundant_locals` lint you recently added. Any ideas where this could come from?

changelog: none

### CODE REVIEW

**Comment by max-niederman** [comment]
> r? @ghost
> 
> cc @max-niederman With the latest sync, I'm getting a lot of FP in the `redundant_locals` lint you recently added. Any ideas where this could come from?
> 
> changelog: none

Excuse my ignorance. What is FP in this context?

**Comment by matthiaskrgr** [comment]
FP / FN is usually False Positive and False Negative in clippy context

**Comment by Centri3** [comment]
I think it's #11290 in particular. Maybe there are other issues, @flip1995?

Basically, for shadowing a local in a new scope, we need to ensure that it's never explicitly dropped or mutated within that block to lint it. We can still lint other cases fine.

I will work on this soon, or you can if you want.

**Comment by flip1995** [comment]
I won't get to this over the weekend :neutral_face:

**Comment by Centri3** [comment]
Looks like async functions are expanded to have a redundant redefinition now: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=3cfab52003203ea576c2ebdf97ba6843

Maybe there's a `from_expansion`-like function for *compiler generated*-expansions, regardless of whether it's external or not?

**Comment by flip1995** [comment]
Thanks for investigating. I managed to fix it with your suggested one-liner :heart:

**Pull request merged**
