### PR TITLE
Fix FP in `unnecessary_lazy_evaluations`

### PR DESCRIPTION
**Pull request by giraffate**
Fix https://github.com/rust-lang/rust-clippy/issues/6343

changelog: Fix FP in `unnecessary_lazy_evaluations`

### CODE REVIEW

**Comment by llogiq** [comment]
Sorry it took me so long. @bors r+

**Comment by llogiq** [comment]
Seems to need cargo dev fmt, perhaps rustfmt has changed?

**Comment by giraffate** [comment]
Yes, rustfmt seems to be updated. I added `cargo dev fmt` commit in this PR.

**Comment by flip1995** [comment]
Thanks, it seems that rustfmt learnt about the `matches!` macro:)

@bors r=llogiq,flip1995

**Pull request merged**
