### PR TITLE
Restrict suggestion of deriving Default for enums to MSRV 1.62.

### PR DESCRIPTION
**Pull request by khuey**
See https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html#default-enum-variants

---

changelog: none

### CODE REVIEW

**Comment by llogiq** [comment]
Thank you!

@bors r+

**Comment by khuey** [comment]
If that failure is me I don't know what to do about it.

**Comment by llogiq** [comment]
Ah, I missed that you had the `changelog` line in the PR description removed. I re-added it.

@bors retry

**Pull request merged**
