### PR TITLE
Change defaults of `accept-comment-above-statement` and `accept-comment-above-attributes`

### PR DESCRIPTION
**Pull request by tgross35**
This patch sets the two configuration options for `undocumented_unsafe_blocks` to `true` by default: these are `accept-comment-above-statement` and `accept-comment-above-attributes`. Having these values `false` by default prevents what many users would consider clean code, e.g. placing the `// SAFETY:` comment above a single-line functino call, rather than directly next to the argument.

This was originally discussed in https://github.com/rust-lang/rust-clippy/issues/11162

changelog: [`undocumented_unsafe_blocks`]: set
`accept-comment-above-statement` and `accept-comment-above-attributes` to `true` by default.

### CODE REVIEW

**Comment by tgross35** [comment]
Conflicts should be resolved

Since you were involved in the original conversation:

r? @Centri3

**Review by Centri3 — APPROVED** [review]

**Comment by Centri3** [comment]
LGTM, though we should probably use revisions for the default/custom configuration options instead of duplicating the file with minor comment changes, but that's not a big deal

Ideally however, these wouldn't even be configuration options as I highly doubt there are any cases (other than bugs) where somebody would actually want to have these set to `false`. We could probably deprecate them and say that this behavior will be forced in the future, but that can be done in a future PR.

@bors r+

**Comment by tgross35** [comment]
> LGTM, though we should probably use revisions for the default/custom configuration options instead of duplicating the file with minor comment changes, but that's not a big deal

If this is something that we can do now, is there an example? I have to fix something here anyway it seems so might as well change that too if possible

**Comment by Centri3** [comment]
You usually put the following headers at the top of the file:
```rust
//@revisions: a b
//@[a] rustc-env:CLIPPY_CONF_DIR=tests/ui-toml/mylint/a
//@[b] rustc-env:CLIPPY_CONF_DIR=tests/ui-toml/mylint/b
```
With a `clippy.toml` file existing in both subdirectories `a` and `b`. Doubt you can conditionally add a comment though so just have something like `SAFETY: will be allowed if <configoption> is true`

**Comment by Centri3** [comment]
Hey @tgross35, any progress on the revisions? If not, this just needs a `cargo collect-metadata` run and a rebase and this can be merged.

**Comment by tgross35** [comment]
@Centri3 sorry about that, it fell off my radar. I think I got the dual config working right as you suggested, and did the rebase.

I'm not sure why github shows the four deleted/renamed files as conflicts when my tree is clean, I am trying to figure this out but do you have any ideas?

**Comment by tgross35** [comment]
I guess I was just rebasing against my own fork instead of upstream 🤦 I think this should be good to go

**Review by Centri3 — APPROVED** [review]

**Comment by Centri3** [comment]
Thanks!

@bors r+

**Pull request merged**
