### PR TITLE
Set doc-tests to `no_run`

### PR DESCRIPTION
**Pull request by Alexendoo**
This excludes `should_panic` tests, those are still run to ensure they panic. Most of our other doc snippets don't gain much from being run though so this frees up a nice bit of CI time

It also fixes the occasional issue such as `foo.txt`s being created https://github.com/rust-lang/rust-clippy/blob/f942470ca774b9648bac042f5d4c4ec74b81b61a/clippy_lints/src/permissions_set_readonly_false.rs#L19

changelog: none

### CODE REVIEW

**Comment by llogiq** [comment]
I wonder if it wouldn't be better to either use `rust,ignore` or just change CI to only run `--lib` tests, as both would still allow us to run the doctests manually if we so desire without changing a lot of lines.

**Comment by Alexendoo** [comment]
I think we should still be checking that the examples compile in CI, `ignored` is used for doc snippets that would not compile, so manually running ignored tests is not going to result in a lot of errors

**Comment by llogiq** [comment]
Ah, yes, we want to compile but not necessarily run the tests. That makes sense.

@bors r+

**Comment by llogiq** [comment]
For some reason the collect\_metadata check failed.

**Comment by Alexendoo** [comment]
Ah, there were a couple code blocks that got copied to `book/src/lint_configuration.md`

**Pull request merged**
