### PR TITLE
Correct version for incompatible_msrv

### PR DESCRIPTION
**Pull request by Manishearth**
Unsure what happened here

Probably what caused https://github.com/rust-lang/blog.rust-lang.org/issues/1277

changelog: none

### CODE REVIEW

**Comment by epage** [comment]
> Probably what caused https://github.com/rust-lang/blog.rust-lang.org/issues/1277

I explicitly checked the changelog but the entry was generated after I suggested it go into the blog post.  In Cargo, we generate the beta changelog entry when branched from master which would have made it available and this would have been caught.

**Comment by xFrednet** [comment]
> Unsure what happened here

This was the correct version when the lint PR was created and a great example, why nightly lints would be awesome. I usually update the version attributes when I write the changelog for that version. But this sadly creates a desync. I'd correct this version, when I write the changelog for 1.78.

**Comment by Mark-Simulacrum** [comment]
FWIW, rust-lang/rust has a magic string and script that we bump version numbers for during nightly -> beta promotion (when the version number becomes fixed). See https://github.com/rust-lang/rust/blob/master/src/tools/replace-version-placeholder/src/main.rs for the script.

If clippy wanted to, you could likely rely on us running that script and picking up the version numbers in a subsequent subtree sync?

**Comment by xFrednet** [comment]
That's something I haven't considered before. Thank you for the idea, I'll investigate it, when I find the time :D

**Comment by xFrednet** [comment]
Either way, I think we can merge this for now :)

r? @xFrednet

@bors r+

**Review by xFrednet — APPROVED** [review]

**Pull request merged**
