### PR TITLE
Enable rustc internal lints

### LINKED ISSUE #3965: Use rustc internal lints in Clippy
In rust-lang/rust#59316 internal lints were implemented. Let's also activate those in Clippy. 

This includes removing the internal lint
https://github.com/rust-lang/rust-clippy/blob/fbb3a47b90b6468ae9cb308c3f49548c78615326/clippy_lints/src/utils/internal_lints.rs#L59-L68
from Clippy, since it got uplifted.

### PR DESCRIPTION
**Pull request by flip1995**
Closes #3965 

I'm not 100% sure if enabling the `-Zunstable-options` flag in the `.cargo/config` file is the right place.

### CODE REVIEW

**Comment by oli-obk** [comment]
> I'm not 100% sure if enabling the -Zunstable-options flag in the .cargo/config file is the right place.

It seems not :D the stable compiler test doesn't work

**Comment by flip1995** [comment]
Any idea how we can hack in the `-Zunstable-options` so it is only set in `clippy_lints`? Adding a `clippy_lints/.cargo/config` file doesn't work, since cargo is run from the root of the project and therefore ignores the config file in `clippy_lints`. 

Also adding a `clippy_dev/.cargo/config` with
```toml
[build]
rustflags = []
```
does not work, since the config file in the root gets unified with this file.

Adding it to the build script also seems not really possible:
> rustc-flags=FLAGS is a set of flags passed to the compiler, only -l and -L flags are supported.
https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script

**Comment by oli-obk** [comment]
Maybe `clippy_dev` should not be using `stable`. I mean there's no need to download a full stable compiler in CI just for that crate.

**Comment by flip1995** [comment]
It was just changed to stable recently: #3885

I think removing the rust-toolchain file again would be the easiest fix.

**Comment by oli-obk** [comment]
sgtm

**Pull request merged**
