### PR TITLE
Move `semicolon_if_nothing_returned` lint to `pedantic`

### PR DESCRIPTION
**Pull request by mbartlett21**
This moves the `semicolon_if_nothing_returned` lint to `pedantic` category.

changelog: Move [`semicolon_if_nothing_returned`] lint into `pedantic` category.

### CODE REVIEW

**Comment by flip1995** [comment]
What's the motivation in moving this to `style`?

**Comment by mbartlett21** [comment]
According to the formatting guide, this lint is enforcing the preferred style, so I think it should be in that category, rather than `restriction`.

> Use a semi-colon where an expression has void type, even if it could be propagated. E.g.,
>
> ```rust
> fn foo() { ... }
> 
> fn bar() {
>     foo();
> }
> ```
<https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/statements.md>

**Comment by flip1995** [comment]
Since the rust style guidelines recommend that, I guess we could move it to style. But at the same time I feel like this is really pedantic for a warn-by-default lint. So if we move this, we should only move it to `pedantic`. I'm open for different opinions though.

**Comment by camsteffen** [comment]
That style guide is in `fmt-rfcs` which seems to be in a sort of limbo-state, not really an accepted official style guide. Also those guidelines are mainly intended for rustfmt - rules that can be automatically enforced by a formatter. This is a bit of a unique rule since it is "type-aware" which is why Clippy adopted it. So the weird RFC status combined with the "pickiness" makes it fit into pedantic IMO.

Would this be a good time to consider a rename or is it too late? The current name reads badly as `allow(semicolon_if_nothing_returned)`. I'd suggest `unit_statements_without_semicolon`.

**Comment by giraffate** [comment]
ping from triage @mbartlett21. Is there anything you still want to discuss?

**Comment by mbartlett21** [comment]
@giraffate 
Thinking over this again, I've now moved this instead to `pedantic`.

**Comment by mbartlett21** [comment]
Now I realise that I should probably not be doing this on my master branch, since I can't rebase very well. I will redo in another branch and make another pr and link it.

**Pull request closed without merging**
