### PR TITLE
Use windows-sdk-10.1 to avoid installation failure

### PR DESCRIPTION
**Pull request by JohnTitor**
This fixes installation failure on Windows on Travis but we need to fix rustfmt issue first to pass the CI completely.

changelog: none

### CODE REVIEW

**Comment by phansch** [comment]
Not sure if this is still needed with https://github.com/rust-lang/rust-clippy/pull/4624, but I'm curious how this upgrade interacts with the merged PR.

@bors try

**Comment by JohnTitor** [comment]
Note that this affects Travis' Windows job only. This fixes the installation failure on Travis' Windows job. This is unrelated to recently fmt failure.

**Comment by phansch** [comment]
> Note that this affects Travis' Windows job only. This fixes the installation failure on Travis' Windows job. This is unrelated to recently fmt failure.

Oh right, then they don't interact at all.

@bors r+

thanks!

**Comment by JohnTitor** [comment]
Hmm, the installation failure is fixed but another error has occurred. If it's not temporary, I'll investigate later.

**Comment by mati865** [comment]
@JohnTitor probably rustup cannot replace binary because it's still running (or there is another hook attached).
Given the fact Clippy should migrate to Github Action or Azure Pipelines soon I think it's not worth wasting time on this.

**Pull request merged**
