### PR TITLE
Rollup of 12 pull requests

### PR DESCRIPTION
**Pull request by flip1995**
Successful merges:

 - #5345 (Add lint for float in array comparison)
 - #5406 (Fix update_lints)
 - #5409 (Downgrade let_unit_value to pedantic)
 - #5410 (Downgrade trivially_copy_pass_by_ref to pedantic)
 - #5412 (Downgrade inefficient_to_string to pedantic)
 - #5415 (Add new lint for `Result<T, E>.map_or(None, Some(T))`)
 - #5417 (Update doc links and mentioned names in docs)
 - #5419 (Downgrade unreadable_literal to pedantic)
 - #5420 (Downgrade new_ret_no_self to pedantic)
 - #5422 (CONTRIBUTING.md: fix broken triage link)
 - #5424 (Incorrect suspicious_op_assign_impl)
 - #5425 (Ehance opt_as_ref_deref lint.)

Failed merges:

 - #5411 (Downgrade implicit_hasher to pedantic)
 - #5428 (Move cognitive_complexity to nursery)

r? @ghost

changelog: rollup

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
>changelog: rollup

I think this should be `changelog: none` otherwise we might end up with "rollup" in the changelog (which doesn't make much sense imo)?

**Comment by flip1995** [comment]
Changelog is written by hand anyway. This is just a marker for me/the person who writes the next changelog, that there should be rollup merges in the output of the `fetch-prs.sh` script.

**Comment by dtolnay** [comment]
Needs rebase on #5434.

**Pull request closed without merging**
