### PR TITLE
Improve release compile time

### PR DESCRIPTION
**Pull request by lzutao**
On my test, it reduced release compile time of root project from 62.9s to 54.2s.
cargo-timing files: https://send.firefox.com/download/42c022429ebe714d/#g0unPjM989ED38syPZU3Fg
changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
I don't think we want `opt-level = 0` on Clippy, since then the packaged Clippy would also be compiled with `opt-level = 0`, wouldn't it?

**Comment by flip1995** [comment]
And I think, the only time Clippy gets compiled in release mode is when shipping it.

**Comment by flip1995** [comment]
Or am I missing something?

**Comment by lzutao** [comment]
> packaged Clippy would also be compiled with `opt-level = 0`

No, it still be compile with optimization. Only build scripts (`build.rs`), proc-macro and theirs deps
are compile with no optimization. https://doc.rust-lang.org/nightly/cargo/reference/profiles.html#overrides

> only time Clippy gets compiled in release mode

It's a fair point. But I think a case when someone build clippy from source.

**Comment by flip1995** [comment]
> It's a fair point. But I think a case when someone build clippy from source.

`clippy_dummy` cannot be compiled.

`clippy_dev` had worse release compile times on my system with this change.

`clippy`  itself has this timing from a clean build:

```bash
# With this change
cargo build --release  451.07s user 7.01s system 239% cpu 3:11.53 total
# Without this change
cargo build --release  515.73s user 5.77s system 253% cpu 3:25.63 total
```

Which is only ~7% faster. I don't think that this matters for people that want to compile Clippy from source.

**Comment by lzutao** [comment]
> `clippy_dev` had worse release compile times on my system with this change.

You're right. I just measure it now. In my machine, it doesn't make a noticeable different in compilation time. Remove it then.

> Which is only ~7% faster. I don't think that this matters for people that want to compile Clippy from source.

At least it is an improvement. If you think this is a risky or unknown trade-off, I would close this PR.

**Comment by flip1995** [comment]
> At least it is an improvement. If you think this is a risky or unknown trade-off, I would close this PR.

I really don't know, how big the difference is. We could try to run it on some crates and time it with and without this change.

**Comment by phansch** [comment]
To move the discussion a bit forward:

Would it help if we had a performance dashboard where we run Clippy on a few crates? Maybe integration in [perf.rust-lang.org](https://perf.rust-lang.org) is something that's possible?

**Comment by flip1995** [comment]
I think that would help to optimize Clippy.

**Comment by mati865** [comment]
Do we know if change like this PR won't make Clippy run slower on large code bases?

**Comment by lzutao** [comment]
This PR is about compilation time. IMO it shouldn't affect runtime performance.
If it does, maybe that a question for cargo team and its documentation because
I see nothing mention about that affects codegen.

**Comment by Manishearth** [comment]
Yeah not convinced that this is very useful to have, and given that it's making clippy_dev worse perhaps we should leave things as is and close this? In general it is worth playing around with build_override though, thanks for investigating!

**Comment by lzutao** [comment]
Ok fine

**Pull request closed without merging**
