### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by flip1995**
r? @ghost

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
insufficient disk space on the windows runner. Please be a one-time thing :pray: 

@bors retry

**Comment by flip1995** [comment]
```
  = note: D:\a\rust-clippy\rust-clippy\target\debug\deps\clippy_driver.exe : fatal error LNK1180: insufficient disk space to complete link
```

image

**Comment by xFrednet** [comment]
Hmmm, windows, haven't we had this problem before? I think we had to ping the infra team, if I'm not mistaken

**Comment by flip1995** [comment]
I don't think so. But then again, if there are problems, it is with windows and I usually suppress windows memories.

**Comment by xFrednet** [comment]
I can't remember where I saw that message before. Zulip and GH search isn't too helpful either :thinking:. There is a long thread with a message like this on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/1.2E58.2E1.20release/near/268526756), but it seems to be focussed on a release.

> But then again, if there are problems, it is with windows and I usually suppress windows memories.

:joy: I switched to Linux about 3 - 4 years ago and haven't regretted it one bit.

**Comment by flip1995** [comment]
Sadly I don't have time to debug this today. Maybe I can look into it this evening

**Comment by mikerite** [comment]
It seems related to generating the pdb file. Maybe try testing with `--release`.

**Comment by Jarcho** [comment]
Something is going wrong here. Just built this locally and the target dir is almost 12GB after running `cargo test`. `clippy_driver.exe` itself is 1GB. For reference current master has the target dir at 4.3GB with `clippy_driver.exe` at a reasonable 17MB. `clippy_utils` rlib is also ~800MB on this pr.

Both use about 2GB for incremental stuff.

**Comment by flip1995** [comment]
Found a rust issue for this: https://github.com/rust-lang/rust/issues/99143

**Comment by flip1995** [comment]
Blocking this for now, hoping for a fix on the rustc side soon-ish. I will work on a workaround if no fix is in sight by the end of the week.

**Comment by mati865** [comment]
You might have some luck with (temporarily) replacing windows-msvc with windows-gnu. It's another Tier 1 target which AFAIK is not affected by this issue.

**Comment by flip1995** [comment]
@bors try

This should now work with the fix merged just before the nightly got released.

@Jarcho Can you please double check, that this indeed works on windows and then r+ this PR?

**Comment by Jarcho** [comment]
Thank you.

@bors r+

**Pull request merged**
