### PR TITLE
HirIdify some lints

### PR DESCRIPTION
**Pull request by ljedrz**
Unblocks https://github.com/rust-lang/rust/pull/58561 (a part of [rust-lang/rust#57578](https://github.com/rust-lang/rust/pull/57578)). Can we branch it like with https://github.com/rust-lang/rust-clippy/pull/3790? I can rebase on a different commit if need be.

Haven't had time to run tests yet, so I'd wait for Travis 🙈.

### CODE REVIEW

**Comment by ljedrz** [comment]
Ah, I forgot this will already break on new rustc stuff; in any case, please advise which commit I should attach this PR to (unless this one's fine).

**Comment by flip1995** [comment]
Done!

**Comment by ljedrz** [comment]
There was a bug; I went through all the changes and found a bug, but unfortunately I'm unable to run tests at this moment :neutral_face:; hope it's the only one.

Can we please branch the new commit so I can retry?

**Comment by oli-obk** [comment]
done

**Comment by ljedrz** [comment]
Yep, that was the only one; thanks!

**Comment by ljedrz** [comment]
[rust-lang/rust#58561](https://github.com/rust-lang/rust/pull/58561) was merged, feel free to merge this branch now.

**Comment by phansch** [comment]
You're fast! Retriggering CI =)

**Comment by ljedrz** [comment]
I'm guessing the branch build doesn't have the most recent rust-lang commits?

**Comment by phansch** [comment]
> I'm guessing the branch build doesn't have the most recent rust-lang commits?

Nope, just some formatting to be done: https://travis-ci.com/rust-lang/rust-clippy/jobs/180536937#L1395

**Comment by ljedrz** [comment]
Ah, I was looking at appveyor that was showing old errors; I'll send a fix shortly.

**Pull request merged**
