### PR TITLE
Add regression ui test for #2371

### LINKED ISSUE #2371: Don't suggest eta-reducible replacements in UNNECESSARY_FOLD lint
See TODO in lint_unnecessary_fold.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #2371.

#2371 seems to already be handled correctly in the lint. This PR adds a ui regression test so we can close it.

r? @blyxyas 

changelog: Add regression ui test for #2371

### CODE REVIEW

**Review by blyxyas — APPROVED** [review]
LGTM, thanks! :heart:

**Comment by GuillaumeGomez** [comment]
I think it's a flaky failure.

**Pull request merged**
