### PR TITLE
Rustup to rust-lang/rust#65647

### PR DESCRIPTION
**Pull request by flip1995**
cc rust-lang/rust#65647

waiting on rust-lang/rust#65690

changelog: none

### CODE REVIEW

**Comment by phansch** [comment]
r=me once the Rust PR is merged

**Comment by phansch** [comment]
Ah note that https://github.com/rust-lang/rust/pull/65474 is currently testing, which will require the rustc-dev toolchain to be added again @flip1995

**Comment by flip1995** [comment]
Thanks, the fix for this was to add `-c rustc-dev` to the RTIM, right?

**Comment by lzutao** [comment]
You could revert 974a05b806954ebdc6640b7ef539667bd7baca56.

**Pull request merged**
