### PR TITLE
Ignore `rustc-ice-` files

### PR DESCRIPTION
**Pull request by xFrednet**
When ui-test detects a crash, it writes it into a `rustc-ice-*` file. I find it a bit annoying that git always want's to add them. So this just adds these files to our `.gitignore` :D

---

changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
I think the proper fix for this would be to pass `RUSTC_ICE=0` somewhere in our test harness :thinking:

**Comment by xFrednet** [comment]
> edit: may also want to add `-Zwrite-long-types-to-disk=no` to rustcflags if you want

What does the flag do?

> I think the proper fix for this would be to pass RUSTC_ICE=0 somewhere in our test harness 🤔
>
> This will magically fix all of rustcs and clippys crashes so that encountering an ice is no longer possible.

But why would be refuse free ICE? This is our best approach to fighting global warming rn :ice_cube:

**Comment by matthiaskrgr** [comment]
This does not affect clippy per-se but sometimes when rustc wants to show a very very long type in a diagnostic, lets say 300 nested `Vec<Vec<...>>`s, in a diagnostic, it will abbreviate and dump the file name to disk instead and show something like
```
   = note: the full name for the type has been written to '87AE7FBF95A2CBEDBD88AAD86A8DD13EB6F01ABF54923F0DD37D5A17CC76B8A9.long-type-12985950398914741889.txt'
   = note: consider using `--verbose` to print the full type name to the console
```

**Comment by y21** [comment]
I agree setting `RUSTC_ICE=0` sounds good if that's possible, it still ICEs and fails tests that don't expect them, it just doesn't write it to a file.
But adding it to `.gitignore` also makes sense to me. They're never something that should be checked in to the repo.

I wonder if it'd also make sense to set it in `cargo dev`. As I understand it, these ICE files are primarily for users that run into them and helps reporting them. I mainly use `cargo dev lint` and a separate file outside of `tests/` when I'm in the middle of writing a lint since it makes some things easier and I run into ICEs a lot, so these files are more annoying than they help. Not sure if it's just me though and if some people find them useful.

**Comment by xFrednet** [comment]
Thank you for the explanation, the variable name is not very on its own. Setting it in both cases makes sense to me. :+1:

**Comment by xFrednet** [comment]
I tested it locally and everything seems to work just fine. IDK how to test it in the CI, but believe this should be good enough :D

**Comment by y21** [comment]
Let's see, @bors try

Do you think it's worth nominating for tomorrow's clippy meeting? (I can't remember if it's tomorrow or the other week)

**Comment by xFrednet** [comment]
My calendar says tomorrow. I don't think it's worth it, but if you're unsure about this change, we can nominate it :)

**Review by y21 — APPROVED** [review]
Ok, yeah, seems like an uncontroversial change. I was wondering if anyone working on clippy would *need* these files, but I can't think of a reason. LGTM

**Comment by xFrednet** [comment]
I don't think so, rustc still dumps the stack trace into the console, which can be used for debugging. If someone notices this change, we could just add a new flag to `cargo dev lint` :)

Then let's get this merged

**Comment by y21** [comment]
Do we have some kind of test that makes sure that ICEs are still reported even with this change? Just so that we'd notice if the meaning of `RUSTC_ICE=0` changes to "don't write ICEs at all, not even to stdout".

**Comment by xFrednet** [comment]
We have: https://github.com/rust-lang/rust-clippy/blob/7e83df40685907ea917813ec5b13fea360bdc070/tests/ui-internal/custom_ice_message.rs#L15-L16

**Comment by y21** [comment]
Ah ok good 👍 
Thanks! @bors r+

**Pull request merged**
