### PR TITLE
Remove `dead_code` paths

### PR DESCRIPTION
**Pull request by CBSpeir**
The following paths are `dead_code` and can be removed:

### `clippy_utils::paths::VEC_RESIZE` 
* Introduced when `vec_resize_to_zero` lint added in PR https://github.com/rust-lang/rust-clippy/pull/5637
* No longer used after commit https://github.com/rust-lang/rust-clippy/pull/8957/commits/8acc4d2f1e255e0e97e48b7a285a7d6db4a03bd6
### `clippy_utils::paths::SLICE_GET`
* Introduced when `get_first` lint added in PR https://github.com/rust-lang/rust-clippy/pull/8882
* No longer used after commit https://github.com/rust-lang/rust-clippy/pull/8957/commits/a8d80d531f1d358c26295eb3d81624594544dd4b
### `clippy_utils::paths::STR_BYTES`
* Introduced when `bytes_count_to_len` lint added in PR https://github.com/rust-lang/rust-clippy/pull/8711
* No longer used after commit https://github.com/rust-lang/rust-clippy/pull/8957/commits/ba6a4595285e38f35970e66db903475989e0be6f
 
When the lints were moved into the `Methods` lint pass, they switched from using paths to diagnostic items.  However, the paths were never removed.  This occurred in PR https://github.com/rust-lang/rust-clippy/pull/8957.
 
This relates to issue https://github.com/rust-lang/rust-clippy/issues/5393
 
changelog: none

### CODE REVIEW

**Review by y21 — APPROVED** [review]
Makes sense. A bit unfortunate that `dead_code` can't emit a warning here. Do you know if there are more unused paths or is this the only one?

**Comment by CBSpeir** [comment]
I've been matching up the paths to the lints/code that use them.  I made it through about half before I found `VEC_RESIZE`.  I will continue checking the rest, and report back if I find any more `dead_code`.  

If I find additional ones, should I add them as commits to this PR or create a new PR?

**Comment by y21** [comment]
Yeah, you can just add them here to this PR.

**Comment by CBSpeir** [comment]
In addition to `VEC_RESIZE`, both `SLICE_GET` and `STR_BYTES` were `dead_code` paths.  I update the top comment to reflect this.

**Comment by y21** [comment]
Looks good. Thank you for taking the time to go through these!

@bors r+

**Pull request merged**
