### PR TITLE
Only suggest map_or for copy types

### LINKED ISSUE #2686: `option_map_unwrap_or` lint suggestion does not compile
In the following case
```
#![deny(option_map_unwrap_or)]
pub fn main() {
  let id: String = "identifier".to_string();
  let prefix: Option<&str> = Some("prefix");
  let id = prefix.map(|p| format!("{}.{}", p, id)).unwrap_or(id);
}
```
Clippy suggests the following change:
```
note: lint level defined here
  --> main/src/main.rs:1:9
   |
1  | #![deny(option_map_unwrap_or)]
   |         ^^^^^^^^^^^^^^^^^^^^
   = note: replace `map(|p| format!("{}.{}", p, id)).unwrap_or(id)` with `map_or(id, |p| format!("{}.{}", p, id))`
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.186/index.html#option_map_unwrap_or
```

which would not compile:
```
error[E0382]: capture of moved value: `id`
  --> main/src/main.rs:10:30
   |
10 |   let id = prefix.map_or(id, |p| format!("{}.{}", p, id));
   |                          --  ^^^ value captured here after move
   |                          |
   |                          value moved here
   |
   = note: move occurs because `id` has type `std::string::String`, which does not implement the `Copy` trait
```

### PR DESCRIPTION
**Pull request by detrumi**
Fixes #2686

### CODE REVIEW

**Comment by mikerite** [comment]
Isn't this going to cause false negatives?

**Comment by mikerite** [comment]
I was thinking of when the default isn't used in the closure.

```
#![warn(clippy::option_map_unwrap_or)]
pub fn main() {
    // Example
    {
        let default = "default".to_string();
        let option = Some("option");
        option.map(|value| format!("{}!", value)).unwrap_or(default);
    }

    // Example fixed
    {
        let default = "default".to_string();
        let option = Some("option");
        option.map_or(default, |value| format!("{}!", value));
    }
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=62f8e9b90002126394fc49fc7b9bab77

**Comment by oli-obk** [comment]
Oh right. That should be "easy" (as in simple but needs loads of code) to catch though: A visitor run on the `map` argument could check for any identifiers found by a visitor run on the `unwrap_or` argument.

**Comment by detrumi** [comment]
> Oh right. That should be "easy" (as in simple but needs loads of code) to catch though: A visitor run on the `map` argument could check for any identifiers found by a visitor run on the `unwrap_or` argument.

So you first collect all identifiers, and then do a second run, right? How do I check for identifiers? My first thought was to do a `visit_path` and collect identifiers using a `FxHashSet<Path>`, but paths don't implement Hash.

**Comment by detrumi** [comment]
@oli-obk So I'm trying to check for identifiers using `visit_path`, but it's not finding the variable (which is a `Path` that you should find when visiting the expression, right?)
```
    fn visit_path(&mut self, path: &'tcx Path, _id: HirId) {
        if let Some(def_id) = path.def.opt_def_id() {
            self.identifiers.insert(def_id);
        }
        walk_path(self, path);
    }
```
Do I need to use `visit_expr` with pattern matching on `ExprKind` instead, or am I doing this wrong?

**Comment by flip1995** [comment]
ping from triage @detrumi. Sorry for the long wait time. This LGTM. Can you rebase this so it can be merged?

**Comment by detrumi** [comment]
@flip1995 Rebase done

**Pull request merged**
