### PR TITLE
[1/N] Implement Arithmetic lint

### PR DESCRIPTION
**Pull request by c410-f3r**
Assuming that https://github.com/rust-lang/rust-clippy/issues/8903 is OK, this PR starts the creation of the `Arithmetic` lint with configurable types.

My current struggle to get a rustc review inspired me to create smaller PRs in order to easy review and make merges as fast as possible. So the first step here only moves the `arithmetic.rs` file to `numeric_arithmetic.rs` to make room for the new lint.

--
changelog: none

### CODE REVIEW

**Comment by Jarcho** [comment]
There's no need to split PR's up this much. There isn't much of a reason to accept the change as it stands. As part of a PR adding a lint for any use of an arithmetic operator the change is perfectly fine. Feel free to keep adding to this PR rather than closing it.

Side note the changes you have here will be broken by #8921 when it gets merged.

**Comment by c410-f3r** [comment]
> There's no need to split PR's up this much. There isn't much of a reason to accept the change as it stands. As part of a PR adding a lint for any use of an arithmetic operator the change is perfectly fine. Feel free to keep adding to this PR rather than closing it.
> 
> Side note the changes you have here will be broken by #8921 when it gets merged.

There are PR sitting idle for months and if the Clippy team couldn't merge 9 diff lines in 5 days, my perception is that a full PR would take much, much, much, much longer.

Perhaps another reviewer? r? rust-lang/rust-clippy

**Comment by llogiq** [comment]
Ok. Feel free to make the next PR bigger and directly ask for my review.

@bors r+

**Comment by c410-f3r** [comment]
Thank you @llogiq

**Pull request merged**
