### PR TITLE
Rollup of 4 pull requests

### LINKED ISSUE #3683: `Sugg` structured snippet modifications wishlist
Our `Sugg` builder type has support for many code snippets, but in some cases we still fall back to strings. One such case is https://github.com/rust-lang/rust-clippy/blob/0a0792e53571540cf6de8e60099a814201c5664e/clippy_lints/src/needless_bool.rs#L77-L83

There are probably more, but for now we should add methods for

* `return $sugg` (e.g. a `return_expr` method that wraps the current suggestion in a `return` call)
* blockifying (turns the current suggestion into a block where the current suggestion is the trailing expression)

### PR DESCRIPTION
**Pull request by flip1995**
Successful merges:

 - #3582 (Add assert(true) and assert(false) lints)
 - #3679 (Fix automatic suggestion on `use_self`.)
 - #3684 ("make_return" and "blockify" convenience methods, fixes #3683)
 - #3685 (Rustup)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by flip1995** [comment]
Hmm, this PR is stuck in the queue...  I can't figure out how to get it out of the queue :thinking:

**Comment by phansch** [comment]
Maybe reopening and closing could work?

**Comment by Manishearth** [comment]
Can't, the branch changed while it was closed, so it's stuck

**Comment by Manishearth** [comment]
I'm going to synchronize

**Comment by Manishearth** [comment]
It's fixed

**Pull request closed without merging**
