### PR TITLE
enable rust-lang/rust#58754

### PR DESCRIPTION
**Pull request by ljedrz**
Enables the next iteration of HidIdification which also brings recent clippy updates to rust-lang.

As usual, a branch will be most welcome :ok_hand:.

### CODE REVIEW

**Comment by ljedrz** [comment]
(like before, the build error is expected until the branch is merged)

**Comment by ljedrz** [comment]
I just learned the compiler can break tools again; feel free to merge this fix when you see fit :+1:.

**Comment by flip1995** [comment]
I created a branch.

Even though tools are allowed to break it's always better if they don't. Thanks for keeping Clippy always up to date!

**Comment by ljedrz** [comment]
Superseded by https://github.com/rust-lang/rust-clippy/pull/3834

**Pull request closed without merging**
