### PR TITLE
[`seek_from_current`]: readability improvements

### LINKED ISSUE #12457: `seek_from_current` description has some readability issues
### Description

https://rust-lang.github.io/rust-clippy/master/index.html#/seek_from_current has the current description.

### Version

_No response_

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #12457.

---

*Please write a short comment explaining your change (or "none" for internal only changes)*

changelog: [`seek_from_current`]: readability improvements

### CODE REVIEW

**Review by dswij — APPROVED** [review]
Thank you!

**Comment by hamirmahal** [comment]
You're welcome!

**Comment by hamirmahal** [comment]
I'm happy to help.

**Pull request merged**
