### PR TITLE
Alphabetically order arms in `methods/mod.rs` match

### PR DESCRIPTION
**Pull request by lengyijun**
changelog: none

just order the arms in the match block

### CODE REVIEW

**Comment by lengyijun** [comment]
not sure the `skip` arm, it looks good to be neighbour to `last` arm

**Comment by blyxyas** [comment]
If we're keeping an alphabetical order, then making an exception just for `skip` would be inconsistent.

**Comment by Centri3** [comment]
While it's pretty, I'm pretty sure having them in alphabetical order would affect performance as match arms are always evaluated in the order they're written. It'd have to go through tons of arms for even the most common methods, like `len`.

For now, let's go with the nice alphabetical order but in the future we should probably reorder them based on how common that method is (and the following checks), like `write` vs `resize`.

**Comment by blyxyas** [comment]
I don't think it matters as the majority of users use Clippy to warn, it doesn't need to fail fast.

It'd still be good to reorder this by use in the future, though.

**Review by blyxyas — APPROVED** [review]
LGTM, Thanks ❤️!

**Pull request merged**
