### PR TITLE
Rename `FunctionRetTy` to `FnRetTy`

### PR DESCRIPTION
**Pull request by JohnTitor**
Rustup to rust-lang/rust#69179

changelog: none

### CODE REVIEW

**Comment by JohnTitor** [comment]
Uhm? It's a same failure, let me take a look.

**Comment by JohnTitor** [comment]
Seems global issue, we should just wait ¯\_(ツ)_/¯

**Comment by flip1995** [comment]
Travis had the same problem about 2 years ago: https://www.traviscistatus.com/incidents/bbp3rj9jktnd

yeah, let's wait. Currently this is not listed on the travis status page though.

**Comment by flip1995** [comment]
Seems to be an npm problem https://github.com/npm/cli/issues/836

**Comment by flip1995** [comment]
It seems to work again. That npm issue was/is a great read though :smile: 

@bors retry

**Pull request merged**
