### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by flip1995**
@oli-obk Do you know, how we can enforce (ui-)tests pass in rust-lang/rust for Clippy? I can open a PR for this, if you tell me what would be necessary for this.

changelog: none

### CODE REVIEW

**Comment by oli-obk** [comment]
Yea I couldn't figure it out either. There are a few points:

1. https://github.com/rust-lang/rust/blob/42acd9086f93fdc68a61cd79152abca77c6cd369/src/bootstrap/test.rs#L501 should probably be `true` so `./x.py test` runs clippy tests
2. https://github.com/rust-lang/rust/blob/027149919e36ce5645ca5d02d55b97ef52eb55ba/src/bootstrap/dist.rs#L1365 could be wrong. Maybe we need to also `ensure(test::Clippy)`, but I think that's not the correct way to do it. I think at the very least this should have a `const DEFAULT: bool = true;`.

**Comment by flip1995** [comment]
@phansch re-pushed latest rustc changes

**Pull request merged**
