### PR TITLE
Test workspace at once

### PR DESCRIPTION
**Pull request by camsteffen**
changelog: none

Follow-up to #6733

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors r+

neat

**Comment by Manishearth** [comment]
This doesn't break the rustc workspace, does it? cc @flip1995

**Comment by camsteffen** [comment]
Oh I meant to merge this after #6733 since that change is also here. I don't know about the rustc workspace.

**Comment by flip1995** [comment]
> This doesn't break the rustc workspace, does it?

Don't know. rustc is itself a workspace with Clippy being a member of that. I'm not sure if a workspace in a workspace may cause problems. But I can test it.

**Pull request merged**
