### PR TITLE
rustup https://github.com/rust-lang/rust/pull/72342, allow unused_crate_dependencies

### PR DESCRIPTION
**Pull request by matthiaskrgr**
changelog: none

### CODE REVIEW

**Comment by phansch** [comment]
@matthiaskrgr Huh, why would the lint have to be allowed only in these two specific files?

**Comment by matthiaskrgr** [comment]
I have no idea to be honest :/

**Comment by phansch** [comment]
Weird.. I will try and see if I can reproduce this in the rustc testsuite :man_shrugging:

**Comment by matthiaskrgr** [comment]
I wondered if it is perhaps related to the `unused` lint group but one test allows it while the other one warns on it so I dunno ...

**Comment by phansch** [comment]
> I wondered if it is perhaps related to the `unused` lint group but one test allows it while the other one warns on it so I dunno ...

Ahh, right :facepalm:  `tests/ui/cognitive_complexity_attr_used.rs` was the only of our tests with `#![warn(unused)]` that's why it triggered only there. I believe the `#![allow(unused_crate_dependencies)]` in `tests/ui/cognitive_complexity.rs` is not required either?

**Comment by mati865** [comment]
Soon will be fixed by https://github.com/rust-lang/rust/pull/72702

**Pull request merged**
