### PR TITLE
Rustup rust-lang/rust#66188

### PR DESCRIPTION
**Pull request by HMPerson1**
changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
@bors treeclose=10

There are currently 3 more PRs in queue. (it's `treeclose-`, not `treeclosed-` to open up the queue again, BTW)

**Comment by flip1995** [comment]
But to actually close the tree you have to write `treeclosed`? :thinking:

**Comment by matthiaskrgr** [comment]
Hm, it should be `treeclose` according to the page https://buildbot2.rust-lang.org/homu/ :thinking:

**Comment by flip1995** [comment]
It actually is `treeclosed` for both. See source code: https://github.com/rust-lang/homu/blob/1e0041c8f6db6500dbc587cf581597092b130cea/homu/parse_issue_comment.py#L246

**Comment by flip1995** [comment]
Is it possible, that bors doesn't fetches closed PRs and you have to open the tree in an open PR?

**Comment by mati865** [comment]
@flip1995 it's exactly the case.

**Pull request merged**
