### PR TITLE
Use more diagnostic items

### PR DESCRIPTION
**Pull request by phansch**
In particular for:

* `VecDeque`
* `String`
* `Mutex`
* `HashMap`
* `HashSet`

cc rust-lang/rust#71414 #5393

---

changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r+
thanks!

**Comment by matthiaskrgr** [comment]
Something went wrong while checking cargo :thinking: https://github.com/rust-lang/rust-clippy/runs/611405018#step:10:11

**Comment by phansch** [comment]
Hmm, doesn't really look spurious, but let's retry one time at least

@bors retry

And the error log in case it's needed:

<details>
<pre>
 running 1 test
 Cloning into '/tmp/.tmpvLbWMu/cargo'...
 test integration_test ... test integration_test has been running for over 60 seconds
 test integration_test ... FAILED
 
 failures:
 
 ---- integration_test stdout ----
 thread 'integration_test' panicked at 'internal compiler error
 Backtrace:
 
 thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:366:17
 stack backtrace:
    0:     0x7fbb64814ab4 - backtrace::backtrace::libunwind::trace::h9a3f8cc4f7c49d26
                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
    1:     0x7fbb64814ab4 - backtrace::backtrace::trace_unsynchronized::h9f7d573af4032bf9
                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
    2:     0x7fbb64814ab4 - std::sys_common::backtrace::_print_fmt::hafe2eb75170bc7f4
                                at src/libstd/sys_common/backtrace.rs:78
    3:     0x7fbb64814ab4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h11ce3a0794842b72
                                at src/libstd/sys_common/backtrace.rs:59
    4:     0x7fbb648530bc - core::fmt::write::hc280d07a68b039c1
                                at src/libcore/fmt/mod.rs:1069
    5:     0x7fbb648064d3 - std::io::Write::write_fmt::haf0bbf54a4a27a71
                                at src/libstd/io/mod.rs:1504
    6:     0x7fbb64819ab5 - std::sys_common::backtrace::_print::ha424a7b62c7e99bc
                                at src/libstd/sys_common/backtrace.rs:62
    7:     0x7fbb64819ab5 - std::sys_common::backtrace::print::hc512c85fbefba727
                                at src/libstd/sys_common/backtrace.rs:49
    8:     0x7fbb64819ab5 - std::panicking::default_hook::{{closure}}::h326074768044843e
                                at src/libstd/panicking.rs:198
    9:     0x7fbb648197f2 - std::panicking::default_hook::h46edc7a9c0017de5
                                at src/libstd/panicking.rs:218
   10:     0x5571f170fbb6 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::hef4b6ad49dfe7ff3
                                at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/liballoc/boxed.rs:1022
   11:     0x5571f1707d97 - clippy_driver::report_clippy_ice::h714dd0018a8f486e
                                at src/driver.rs:242
   12:     0x5571f16cbb75 - <clippy_driver::ICE_HOOK as core::ops::deref::Deref>::deref::__static_ref_initialize::{{closure}}::h966afdec1363d691
                                at src/driver.rs:235
   13:     0x7fbb55dadb06 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h7cc839c653e1f153
                                at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/liballoc/boxed.rs:1022
   14:     0x7fbb55da6e55 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h2c0aae1cc0050e3e
                                at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/libproc_macro/bridge/client.rs:312
   15:     0x7fbb6481a235 - std::panicking::rust_panic_with_hook::h14c6fc6fab3f955c
                                at src/libstd/panicking.rs:515
   16:     0x7fbb675a7f9e - std::panicking::begin_panic::h353e55d696efbce4
   17:     0x7fbb675e0ad2 - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h2bba7ef535e0a8da
   18:     0x7fbb64f00fc6 - core::ptr::drop_in_place::hff74ce8e24eff7cc
   19:     0x7fbb64f03826 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::hf65b4f24927c1106
   20:     0x7fbb64f26b5d - core::ptr::drop_in_place::hc8c504b2b8173710
   21:     0x7fbb64f0b974 - rustc_interface::interface::run_compiler_in_existing_thread_pool::h212da03d828c7c6a
   22:     0x7fbb64dc056d - scoped_tls::ScopedKey<T>::set::h2028e6e083b0f43a
   23:     0x7fbb64dbd4c2 - rustc_ast::attr::with_globals::h7b491afd0064c237
   24:     0x7fbb64dc91e1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h631e1bede474152a
   25:     0x7fbb64f0edae - core::ops::function::FnOnce::call_once{{vtable.shim}}::h423b6297d263ed5d
   26:     0x7fbb6482a2aa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha322cc7de20f352a
                                at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/liballoc/boxed.rs:1008
   27:     0x7fbb6482a2aa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7dcbc4f271b0973f
                                at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/liballoc/boxed.rs:1008
   28:     0x7fbb6482a2aa - std::sys::unix::thread::Thread::new::thread_start::h9505c04d88c91577
                                at src/libstd/sys/unix/thread.rs:87
   29:     0x7fbb6458e6db - start_thread
   30:     0x7fbb6409f88f - __clone
   31:                0x0 - <unknown>
 
 ', tests/integration.rs:60:9
 stack backtrace:
    0: backtrace::backtrace::libunwind::trace
              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
    1: backtrace::backtrace::trace_unsynchronized
              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
    2: std::sys_common::backtrace::_print_fmt
              at src/libstd/sys_common/backtrace.rs:78
    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
              at src/libstd/sys_common/backtrace.rs:59
    4: core::fmt::write
              at src/libcore/fmt/mod.rs:1069
    5: std::io::Write::write_fmt
              at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/libstd/io/mod.rs:1504
    6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
              at src/libstd/io/impls.rs:156
    7: std::sys_common::backtrace::_print
              at src/libstd/sys_common/backtrace.rs:62
    8: std::sys_common::backtrace::print
              at src/libstd/sys_common/backtrace.rs:49
    9: std::panicking::default_hook::{{closure}}
              at src/libstd/panicking.rs:198
   10: std::panicking::default_hook
              at src/libstd/panicking.rs:215
   11: std::panicking::rust_panic_with_hook
              at src/libstd/panicking.rs:511
   12: rust_begin_unwind
              at src/libstd/panicking.rs:419
   13: std::panicking::begin_panic_fmt
              at src/libstd/panicking.rs:373
   14: integration::integration_test
              at tests/integration.rs:60
   15: integration::integration_test::{{closure}}
              at tests/integration.rs:8
   16: core::ops::function::FnOnce::call_once
              at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/libcore/ops/function.rs:232
   17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
              at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/liballoc/boxed.rs:1008
   18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
              at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/libstd/panic.rs:318
   19: std::panicking::try::do_call
              at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/libstd/panicking.rs:331
   20: std::panicking::try
              at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/libstd/panicking.rs:274
   21: std::panic::catch_unwind
              at /rustc/8af87b1126319721c79af6bb65a9fa0caeaf28aa/src/libstd/panic.rs:394
   22: test::run_test_in_process
              at src/libtest/lib.rs:541
   23: test::run_test::run_test_inner::{{closure}}
              at src/libtest/lib.rs:450
 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 
 
 failures:
     integration_test
 
 test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
 
 ##[error]Process completed with exit code 101.

</pre>
</details>

**Pull request merged**
