### PR TITLE
Fix false positive with cast_sign_loss lint

### LINKED ISSUE #4818: Euclidean operations combined with sign casting cannot result in loss of a sign
`.rem_euclid` and `.div_euclid` always results in a non-negative value, so casting to the same or larger size (except unsigned) should be allowed.

```rust
(-1_001).rem_euclid(1_000 as i16) as u16
```

There are also checked versions of these functions (`.checked_rem_euclid` and `.checked_div_euclid`) which should also be handled.

Version: `clippy 0.0.212 (c8e3cfb 2019-10-28)`

Related: #4605 (`.abs`), #4743 (`.checked_abs`)

### PR DESCRIPTION
**Pull request by krishna-veerareddy**
`cast_sign_loss` lint incorrectly suggests that the result of `checked_abs`, `rem_euclid` and `checked_rem_euclid` cannot be casted to an unsigned integer without loss.

Fixes #4818 #4764 #4743 

changelog: Fix false positives in `cast_sign_loss` lint

### CODE REVIEW

**Comment by jhpratt** [comment]
Does this also work with type widening, such as `(-1i8).rem_euclid(1i8) as u16`?

Other than that question, looks good to me.

**Comment by krishna-veerareddy** [comment]
@jhpratt It allows widening as well. Should I add test cases for that as well?

**Comment by jhpratt** [comment]
It certainly wouldn't hurt!

**Comment by krishna-veerareddy** [comment]
Should I add test cases for all the sized types or just one for u8 -> u16 widening?

**Comment by krishna-veerareddy** [comment]
@flip1995 Please review when you have some time.

**Comment by flip1995** [comment]
Sorry, was absent for the past few days. Can be merged as is, awesome! 🎉 

@bors r+

**Comment by krishna-veerareddy** [comment]
@flip1995 No worries. Thanks!

**Pull request merged**
