### PR TITLE
rustup https://github.com/rust-lang/rust/pull/65792/

### PR DESCRIPTION
**Pull request by matthiaskrgr**
changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Looks like we're crashing while checking rustfmt :|

````
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: DistinctSources(DistinctSources { begin: (Real("src/lib.rs"), BytePos(0)), end: (Real("src/comment.rs"), BytePos(107716)) })', src/libcore/result.rs:1165:5
````

**Comment by flip1995** [comment]
cc #4742

**Comment by flip1995** [comment]
Just disable rustfmt integration test until this is fixed?

**Comment by lzutao** [comment]
https://github.com/rust-lang/rust-clippy/blob/66df92aeba64547f3e9600635a30df34b12a11d8/clippy_lints/src/lib.rs#L39-L40
need to be removed?

**Pull request merged**
