### PR TITLE
accept `String` in `span_lint*` functions directly to avoid unnecessary clones

### PR DESCRIPTION
**Pull request by y21**
context: https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Accepting.20.60Into.3C.7BSub.7DdiagMessage.3E.60.20in.20.60span_lint*.60.20functions/near/425703273

tldr: the `span_lint*` functions now accept both `String`s, which are then reused and not recloned like before, and also `&'static str`, in which case it [doesn't need to allocate](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_error_messages/lib.rs.html#359).
Previously, it accepted `&str` and would always call `.to_string()`, which is worse in any case: it allocates for `&'static str` and forces a clone even if the caller already has a `String`.

---------

This PR has a massive diff, but the only interesting change is in the first commit, which changes the message/help/note parameter in the `span_lint*` functions to not take a `&str`, but an `impl Into<DiagMessage>`.

The second commit changes all of the errors that now occur:
- `&format!(...)` cannot be passed to `span_lint` anymore. Instead, we now simply pass `format!()` directly.
- `Into<DiagMessage>` can be `&'static str`, but not any `&str`. So this requires changing a bunch of other `&str` to `&'static str` at call sites as well.
- Added [`Sugg::into_string`](https://github.com/y21/rust-clippy/blob/9fc88bc2851fbb287d89f65b78fb67af504f8362/clippy_utils/src/sugg.rs#L362), which, as opposed to `Sugg::to_string`, can take advantage of the fact that it takes ownership and is able to reuse the `String`

changelog: none

### CODE REVIEW

**Comment by y21** [comment]
(To be fair, I don't think an unnecessary clone is going to make any noticeable difference on the `span_lint` path, but this still seemed like a low hanging fruit and doesn't really add any complexity to lints. We now need one borrow less everywhere 🤷 )

**Comment by y21** [comment]
I'll wait with fixing conflicts since there will be many more.

About this:
> rustc seems to intentionally ICE if a function is called with both an `impl Into<SubdiagMessage>` and `impl Into<DiagMessage>` parameter for some reason, so this currently works around it with a new trait.

It looks like the span_bug I ran into ([here](https://github.com/rust-lang/rust/blob/3521a2f2f317cb978063842485c7d1bc86ec82b6/compiler/rustc_lint/src/internal.rs#L432)) was added in rust-lang/rust#121382. @nnethercote since you created that PR, do you think that it'd make sense to add a way to "allow" it in some way? I'm not too sure what exactly it's asserting, but it seems somewhat specific to rustc and translatable diagnostics, which clippy doesn't have anyway

**Comment by nnethercote** [comment]
FWIW, the compiler isn't ICEing (i.e. crashing due to a bug), rather a compiler-internal lint is giving an error.

There's no fundamental reason for the restriction on the number of `impl Into<{D,Subd}iagMessage>` parameters. It was just slightly easier to implement that way and it was good enough at the time. It will be easy to change `impl_into_diagnostic_message_param` from an `Option` to a `Vec` to handle multiple such arguments. I can do that later today.

**Comment by y21** [comment]
I'm thinking that having our own trait for things that can be turned into diagnostic messages wouldn't be so bad of an idea anyway (like it currently does as a workaround), since it allows us to implement it for other clippy-specific types (which normally wouldn't work b/c of orphan rules).

For example, we could implement it for the [`Sugg`](https://doc.rust-lang.org/nightly/nightly-rustc/clippy_utils/sugg/enum.Sugg.html) helper type used for building up suggestions, then lints can pass it without having to turn it into a `String` at callsite first

**Comment by y21** [comment]
Oh wait no, we should totally be able to `impl From<DiagMessage> for Sugg`. Not sure why I thought that'd go against the orphan rules

**Comment by nnethercote** [comment]
> FWIW, the compiler isn't ICEing (i.e. crashing due to a bug), rather a compiler-internal lint is giving an error.

My mistake, it *is* an ICE.

> There's no fundamental reason for the restriction on the number of `impl Into<{D,Subd}iagMessage>` parameters. It was just slightly easier to implement that way and it was good enough at the time. It will be easy to change `impl_into_diagnostic_message_param` from an `Option` to a `Vec` to handle multiple such arguments. I can do that later today.

Done in rust-lang/rust/pull/122315.

**Comment by y21** [comment]
Nice, thanks for getting to it so quickly!

**Comment by blyxyas** [comment]
@y21 Meow meow, meow I think that the wisest course of action now would be to wait until the sync, and then undo the workaround (it isn't necessary anymore thanks to nnethercote's fix)

**Comment by Centri3** [comment]
fwiw, this might have a bigger impact than would first seem (haven't done a benchmark tho). `to_string` is called regardless of whether the lint is allowed or not, so for, e.g., `allow_attributes_without_reason` (which is very likely to show up 100s of times in a codebase, and is allow-by-default), this allocation would be done a lot of times.

It doesn't do anything else before checking the lint level, so is definitely pretty good for that case.

**Comment by blyxyas** [comment]
I'll do a benchmark soon, maybe this is even better than expected!

**Comment by blyxyas** [comment]
Okis, the sync has been done today =^w^=

**Comment by y21** [comment]
Alright, I removed the workaround. The functions now accept the real `impl Into<DiagMessage>` as a parameter.
(The relevant changes are in the first commit again)

**Comment by blyxyas** [comment]
I'll benchmark this PR right now (from the server, while working on other issues)

**Comment by y21** [comment]
It probably makes sense to run the benchmark on a crate/crates that emit a lot of lints. Maybe the `unicode-normalization` crate would be interesting. I remember that one from lintcheck runs because it emits about 260,000 diagnostics(!) for one match expression. Maybe it'd also be interesting to somehow benchmark the testsuite, since that also primarily consists of code that emits lints?

Even in such an extreme case with 200k diagnostics though, with a "guess" that an allocation takes maybe 20ns, that would still be 5 milliseconds, which I'm not sure if that's noticeable.
Regardless, it seems like a "free" low hanging fruit that doesn't really impact complexity of lints

**Comment by Centri3** [comment]
I would be very skeptical of that guess since allocating on the heap is usually thousands of instructions, is it not? There's a lot involved, even just in the kernel (excluding any tricks the allocator does - idk if clippy uses the default [system] global allocator, unlike rustc)

A single cycle should be ~0.4ns for me excluding anything else,

**Comment by Centri3** [comment]
`unicode-normalization` might be a good pick. I didn't realize before that this PR also allocated for `&str` and thought it was only for passing `&String`

**Comment by blyxyas** [comment]
I've been trying to benchmark this for days. It's ridiculous how much a patch can resist to being benchmarked.
And I'll do it, I sweat that I'll benchmark this. Even if it takes... I don't know what more it would take ¯\\\_(ツ)\_/¯

**Comment by y21** [comment]
> I would be very skeptical of that guess

Yea, fair points. I realize now that the number could be totally wrong so I take that part of my message back. I guess real benchmarks are the only source of truth we can trust :)

**Comment by blyxyas** [comment]
Okis, the benchmarks are finally done. Yeah, it has some small improvements.
At some point this became something more related to honor than it was to performance :sweat_smile:

**Review by blyxyas — APPROVED** [review]
LGTM, thanks! :heart:

**Comment by y21** [comment]
Looks like the `large_stack_frames` lint was changed in the meantime to pass `&format!` and now had to be changed too.

**Comment by blyxyas** [comment]
??
@bors r+

**Comment by blyxyas** [comment]
Oh I thought you fixed it in the latest push :sweat_smile:
DM me on Zulip when you have it :3

**Comment by y21** [comment]
oh well, another lint was changed to use `&format!()` in the meantime. I did fix the other one. But yeah, I can fix it locally and we can coordinate on zulip when I should push so this doesnt keep happening

**Pull request merged**
