### PR TITLE
Import rustc_plugin from its new location

### PR DESCRIPTION
**Pull request by SimonSapin**
Depends on https://github.com/rust-lang/rust/pull/62727

changelog: none

### CODE REVIEW

**Comment by phansch** [comment]
The RLS integration failed because.. it needs to be updated to a Clippy version that contains _this_ Clippy PR.

Since everything else passed, I'm going to merge this PR manually and file a rls PR.

**Comment by SimonSapin** [comment]
I thought https://github.com/rust-lang/rust/pull/62727 was not in Nightly yet?

**Comment by lzutao** [comment]
We use master rustc, not nightly.

**Pull request merged**
