### PR TITLE
Fix some problems

### LINKED ISSUE #2892: allow(partialeq_ne_impl) broken
The following Rust code ([playground](https://play.rust-lang.org/?gist=350b805763cca2051263907b98649cab&version=stable&mode=debug&edition=2015)):

```rust
struct Foo();

impl PartialEq for Foo {
    fn eq(&self, _: &Self) -> bool {
        true
    }
    #[cfg_attr(feature = "cargo-clippy", allow(partialeq_ne_impl))]
    fn ne(&self, _: &Self) -> bool {
        false
    }
}

fn main() {}
```

produces the `partialeq_ne_lint`:

```
warning: re-implementing `PartialEq::ne` is unnecessary
  --> src/main.rs:8:5
   |
8  | /     fn ne(&self, _: &Self) -> bool {
9  | |         false
10 | |     }
   | |_____^
   |
   = note: #[warn(partialeq_ne_impl)] on by default
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.211/index.html#partialeq_ne_impl
```

but it shouldn't produce it because it is `allow`ed.

### PR DESCRIPTION
**Pull request by sinkuu**
Fixes #2892, #3199, #2841, #3476

### CODE REVIEW

**Comment by phansch** [comment]
Is there any reason for 328e105? Otherwise r=me :sparkler:

**Comment by sinkuu** [comment]
These are not equivalent:

```rust
let _ = if self.opt.is_none() {
    /* no `return` here */ None
} else {
    self.opt
};
```

```rust
let _ = self.opt?;
```

I'll add this as a comment along with conflict resolution.

If the last expression of a `fn` is something like `if opt.is_none() { None } else { opt }` it can be changed to `opt`, but that may be out of scope of this lint ("question\_mark").

**Comment by oli-obk** [comment]
```rust
let x = self.opt.is_none() {
    return None;
} else {
    self.op
};
```

is also not 

```rust
let _ = self.opt?;
```

We can always suggest `let _ = Some(self.opt?);` and have the user take it from there.

**Pull request merged**
