### PR TITLE
Check PRs for changelog entry in the body

### PR DESCRIPTION
**Pull request by flip1995**
changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
Hmm. The MacOS fails because of the rate limit of the GitHub API. 

Can we somehow get an API key or do we need to find another way to check for this? cc @Manishearth

**Comment by oli-obk** [comment]
We could just run this in a single instance (e.g. linux)

**Comment by flip1995** [comment]
Even then we only have 60 requests per hour per IP address. And since we're using some Travis IP address I think this is not something we want to rely on.

**Comment by flip1995** [comment]
Linux build also failed for the same reason:
https://travis-ci.com/rust-lang/rust-clippy/jobs/195597674#L501-L503

**Comment by oli-obk** [comment]
60 per hour isn't great indeed. Is an API key the same thing as a deploy key? I can add one in that case.

**Comment by flip1995** [comment]
I just found out, that this could be done with personal access tokens: https://developer.github.com/v3/auth/#via-oauth-tokens

I can add one of these by myself 👍

**Comment by flip1995** [comment]
That didn't work. I continue with this later.

**Comment by flip1995** [comment]
Oh no: https://travis-ci.com/rust-lang/rust-clippy/jobs/195669235#L413-L414
```
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
```

**Comment by flip1995** [comment]
Closing this, since
1. Secret env vars don't work on PRs from forks (obv security reasons)
2. Pulling the PR body through the github API doesn't work, since we need some kind of API token. And using this API token is (AFAIK) only possible through secrets.

**Pull request closed without merging**
