### PR TITLE
Nuke the clippy plugin interface

### PR DESCRIPTION
**Pull request by oli-obk**
It's been ~~a month or so~~ 10 days since the plugin interface emits unsilencable warnings. I have not seen any complaints. I guess noone was using the plugin interface anymore.

### CODE REVIEW

**Comment by phansch** [comment]
Hmm, [this GitHub search](https://github.com/search?l=Rust&o=desc&q=%23%21%5Bcfg_attr%28feature%3D%22clippy%22%2C+plugin%28clippy%29%29%5D+stars%3A%3E20+created%3A%3E2018-01-01&s=indexed&type=Code) reveals quite a few results where the plugin interface is used.

Some popular users include:
* diesel (lib)
* https://github.com/cretonne/cretonne (bin/lib)
* https://github.com/racer-rust/racer (lib)
* https://github.com/habitat-sh/habitat (bin)
* https://github.com/citybound/citybound (bin)
* https://github.com/Wilfred/remacs (bin)
* https://github.com/pingcap/tikv (bin)

Perhaps we should communicate this better (through the dev-tools news, perhaps) before removing it?

**Comment by oli-obk** [comment]
Indeed. Let's wait a while longer.

# Not actively using it:

* racer (0.0.103) https://github.com/racer-rust/racer/blob/d465e38e0893850790a3f6d7c99933552064babf/Cargo.toml#L33
* cretonne (just has the plugin attributes, but uses cargo clippy) https://github.com/cretonne/cretonne/blob/122249ad2dd8dbb6c6e3c24162366e7a9bafdf45/clippy-all.sh#L7

# PRs open to remove it
* habitat: https://github.com/habitat-sh/habitat/pull/5102

# Issues open for removing it
* citybound https://github.com/citybound/citybound/issues/264
* remacs https://github.com/Wilfred/remacs/issues/757
* tikv https://github.com/pingcap/tikv/issues/3090
* diesel https://github.com/diesel-rs/diesel/issues/1709

**Comment by oli-obk** [comment]
Getting the word out via twir: https://twitter.com/elegmit/status/998178638234341377

**Comment by ssokolow** [comment]
Drat. I was looking forward to when clippy was available on stable channel so I could switch **to** the plugin API.

**Comment by oli-obk** [comment]
Well... even without this change we would not be stabilizing the plugin interface.

What you can always do is just set the `RUSTC_WRAPPER` env var to `clippy-driver` and `CLIPPY_TESTS` to `true` to unconditionally replace rustc with the driver.

**Comment by oli-obk** [comment]
You want to force users of your library to use clippy?

**Comment by oli-obk** [comment]
Yea in that case I'd just resolve to the `#[cfg(not(cargo-clippy))]` trick. Seems like an edge case

**Comment by flip1995** [comment]
Do we want to do this before releasing Clippy 1.0?

**Comment by oli-obk** [comment]
It seems all the linked issues have been resolved.

The only thing left is to figure out how to make cargo not rebuild everything when going from cargo build to cargo clippy. I believe we need cargo support for this.

**Comment by flip1995** [comment]
Ping @oli-obk. Should we `S-inactive-closed` this and revisit it (in a new PR) once #3837 is resolved?

**Comment by oli-obk** [comment]
yea, that makes sense

**Comment by tylerhawkes** [comment]
> Well... even without this change we would not be stabilizing the plugin interface.
> 
> What you can always do is just set the `RUSTC_WRAPPER` env var to `clippy-driver` and `CLIPPY_TESTS` to `true` to unconditionally replace rustc with the driver.

I just tried this on a non-trivial project and it doubled my build time from 20 minutes to 40 minutes. I've been wanting a way to use clippy without having to also separately build but nothing seems to be working. It's nice to have clippy automatically run whenever I do a build so I don't have to remember it and fix clippy issues later. Any ideas on how we can keep build times reasonable without having to do multiple clippy steps?

**Comment by mati865** [comment]
@tylerhawkes on nightly you can try `cargo clippy-preview -Z unstable-options`.

**Pull request closed without merging**
