### PR TITLE
Fix Clippy subcommand name

### LINKED ISSUE #5640: Clippy's CLI usage error screen shows `cargo check`
Clippy's CLI usage error screen shows `cargo check` instead of `cargo clippy`:

```
error: Found argument 'src/librustc_driver/lib.rs' which wasn't expected, or isn't valid in this context

USAGE:
    cargo check [OPTIONS]

For more information try --help
```

Output of `cargo clippy -V`:

```
clippy 0.0.212 (204bb9b5 2020-03-17)
```

### PR DESCRIPTION
**Pull request by camelid**
Fixes #5640.

changelog: none

### CODE REVIEW

**Comment by camelid** [comment]
I wasn't able to verify that this works because clippy won't build for me (it says it can't find `rustc_ast`). Is there something about this in `CONTRIBUTING.md`?

**Comment by yaahc** [comment]
@camelid you probably need to run `setup-toolchain.sh`

**Comment by camelid** [comment]
@yaahc Thanks! I just ran it, though now I'm getting compiler errors:

<details>
```
error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
    --> clippy_lints/src/utils/ast_utils.rs:509:14
     |
509  |             (DocComment(l), DocComment(r)) => l == r,
     |              ^^^^^^^^^^^^^ expected 2 fields, found 1

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
    --> clippy_lints/src/utils/ast_utils.rs:509:29
     |
509  |             (DocComment(l), DocComment(r)) => l == r,
     |                             ^^^^^^^^^^^^^ expected 2 fields, found 1

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
    --> clippy_lints/src/doc.rs:321:16
     |
321  |         if let AttrKind::DocComment(ref comment) = attr.kind {
     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 fields, found 1

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
    --> clippy_lints/src/tabs_in_doc_comments.rs:63:16
     |
63   |         if let ast::AttrKind::DocComment(comment) = attr.kind {
     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 fields, found 1

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0023`.
error: could not compile `clippy_lints`.
```
</details>

Is this because Clippy depends on rustc internals?

**Comment by yaahc** [comment]
>  Is this because Clippy depends on rustc internals?

AFAIK yes. Whenever they change internal APIs we have to update them in clippy to match. I'm a little surprised though because I thought they just finished making it so clippy is tested on every rustc PR to prevent these kinds of breakages but I don't know the details of how the new subtree stuff works so I'm guessing its still possible for breakages to occur.

cc @flip1995 @matthiaskrgr

**Comment by ebroto** [comment]
@yaah `setup-toolchain.sh` still uses rust-lang/rust master's HEAD (including the breaking changes for clippy). There are plans to pin to a nightly, but it's blocked on https://github.com/rust-lang/rustup/issues/2350

@camelid I'm afraid your solution won't work. `cargo-clippy` correctly calls `cargo check` setting `RUSTC_WRAPPER` to point to `clippy-driver`, which is called by cargo instead of `rustc`.

If I'm not mistaken, the problem in the issue you linked is that you were using a wrong command-line which is not understood by cargo check, so it errors out.

**Comment by flip1995** [comment]
@yaahc Clippy has to pass tests in rustc, but the changes to fix clippy have to be synced back to Clippy. Currently the `subtree` usage only makes it easier to do a rustup. @ebroto pointed out the rest of the story. (See discord why I didn't sync Clippy yet.)

We should fix this issue _$somehow_, but we definitely need a test for this (after it is fixed).

**Comment by camelid** [comment]
@yaahc I just opened #5874 to try to make it extra obvious that you need to run a script to set up your toolchain

**Comment by camelid** [comment]
> `@camelid` I'm afraid your solution won't work. `cargo-clippy` correctly calls `cargo check` setting `RUSTC_WRAPPER` to point to `clippy-driver`, which is called by cargo instead of `rustc`.

Ah, that's unfortunate. It just seems confusing that errors from running `cargo clippy` make it look like you were running `cargo check`.

**Comment by flip1995** [comment]
This produces `error: infinite recursion detected` when running the `cargo clippy` command

Closing this, since I think, that this has to be fixed in `cargo`, rather than Clippy.

**Pull request closed without merging**
