### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by flip1995**
r? @ghost

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
@matthiaskrgr `cargo --version` still outputs `1.50.0`, because it wasn't bumped in the rust compiler yet. `rustc --version` outputs `1.51.0`, which is the actual compiler version we're using after this PR. I think we should also use `rustc --version` in the `versioncheck.rs` test. Please review 106ca96

**Comment by flip1995** [comment]
@bors r+

(Merging myself. Only commit to review is 106ca96, but this can easily be reverted later, if necessary)

**Comment by matthiaskrgr** [comment]
@flip1995 lgtm

I think I misinterpreted the version when I compared `cargo --version` and `rustc --version`.
still not 100% sure how the cargo version is determined though since the commit in the rustc cargo repo is  468af39 / Dec 22   but  cargo --version is (a3c2627fb 2020-12-14)

**Comment by flip1995** [comment]
`cargo --version` outputs the version of cargo of the cargo submodule in `rust-lang/rust`. This submodule is not necessarily updated with the release. So if we would continue to use `cargo --version` this would randomly start to fail once the cargo submodule is updated with the new version.

**Pull request merged**
