### PR TITLE
Standardized some lint formulation

### PR DESCRIPTION
**Pull request by Rahul721999**
cc: https://github.com/rust-lang/rust-clippy/issues/10660

This is my first contribution to open source. Hope I didn't messed up anything. 
Please merge this PR if everything is good.

---

chaneglog: none

### CODE REVIEW

**Comment by xFrednet** [comment]
Hey and welcome to Clippy :wave: 

The issue in question, is about implementing an internal lint, to detect lint descriptions that don't conform with this convention. Correcting the lint descriptions of all lints is a part of it, but should ideally be done closely before adding the internal lint. So, if you want to work on the issue, you should ideally take a look at our documentation: [Adding a new lint](https://doc.rust-lang.org/clippy/development/adding_lints.html#adding-a-new-lint)

**Comment by xFrednet** [comment]
Hey, you're very welcome to work on the issue if you're still interested. I'm sorry if my comment discouraged you. If you need any help, just reach out. We're all happy to help! If you have a question in an issue, I'd recommend pinging one of us directly, as the notifications are easy to miss otherwise. :)

**Comment by Rahul721999** [comment]
No, it's okay sir, I was going through the docs, of create new lint,and still trying to understand the problem.

**Comment by xFrednet** [comment]
Internal lints are rare enough that they sadly don't have a `new_lint` comment. Instead, I'd recommend orientating yourself on an existing one, like `invalid_clippy_version_attribute`. Here is the commit that implemented the lint: https://github.com/rust-lang/rust-clippy/commit/9d9d06d5572b815ca934f0ad1c6a69e4791a85fd

To run the test, you can add a test in ui-tests and use this comment `collect-metadata = "test --test dogfood --features internal` (At least I believe it's this one)

If this sounds a bit too complicated, you can also select another first-good-issue, understanding the connection between components might be a bit complex with this one :sweat_smile:

**Comment by Rahul721999** [comment]
yes, I believe I should find a easy one, as I've experience less than a year in **Rust** as well as **Development.** I think the good part is that at least I tried.

**Comment by xFrednet** [comment]
It's wonderful that you tried and I hope you're still motivated to try working on a new lint. At first, it might seem intimidating, but over time it's a great learning experience, and everyone is happy to help :)

**Pull request closed without merging**
