### PR TITLE
Collect renamed lints

### PR DESCRIPTION
**Pull request by Serial-ATA**
changelog: Display past names of renamed lints on Clippy's lint list

cc #7172

r? @xFrednet

### CODE REVIEW

**Comment by xFrednet** [comment]
Have you thought about how we want to display the renamed lint name on the website?

I was considering something like this:

image

Or maybe

image

(Though I like the first option more)

In either case, we can prepare do some work in out metadata collector to make the website faster. That's why I'm asking :upside_down_face: 

r? @dswij

**Comment by Serial-ATA** [comment]
I had a similar idea to the first one, except it was "Past names" instead of "Notes". Since it'll show up in search regardless, I don't think making a new entry to point to the rename is necessary. 🙂

**Comment by xFrednet** [comment]
> I had a similar idea to the first one, except it was "Past names" instead of "Notes". Since it'll show up in search regardless, I don't think making a new entry to point to the rename is necessary.

Past names is a better name. In that case, I would already add this to the documentation in rust, similar to how it's done for configurations. :upside_down_face:

**Comment by dswij** [comment]
Was just thinking if `Notes` can even include recent changelogs to the lint, but that's probably too much noise

What happens when we rename a lint twice? Would `Past Names` have all past lint names?

**Comment by Serial-ATA** [comment]
I updated it to account for multiple renames :slightly_smiling_face:.

**Comment by xFrednet** [comment]
Nice, this still leaves the question where these will be rendered. I'm still for adding it to the lint description like it's done for the configuration :upside_down_face:

**Comment by Serial-ATA** [comment]
Yeah, I think it should go under the configuration as a bulleted list.

**Comment by xFrednet** [comment]
What I meant with my question of *where this will be rendered* was, where in our *tech-stack*. So if this will append the section in the metadata collector (Like the configuration section) or on the website. Where possible, I usually prefer adding it during the collection in rust, since any logic on Clippy's lint list is multiplied by the number of lints and delays the rendering. That's also why I'm mentioning this here and not in the related frontend PR since, we can implement this without touching the frontend. :upside_down_face:

**Comment by Serial-ATA** [comment]
Oh :smile:. In that case, yeah it should definitely be added like the configuration. I'll get that done soon.

**Comment by Serial-ATA** [comment]
Here's how it looks:
example

**Comment by xFrednet** [comment]
The example looks good IMO :+1:

**Comment by flip1995** [comment]
The `Past Names` option also was my first thought when seeing this PR in my notifications :+1:

**Comment by xFrednet** [comment]
I'm stealing this review back. I hope that's alright with you @dswij 

r? @xFrednet

**Comment by dswij** [comment]
Sure, go ahead!

**Review by xFrednet — APPROVED** [review]

**Comment by xFrednet** [comment]
Excellent work! I've also tested it locally and everything works perfectly. Thank you very much for this update. I'm happy to see the metadata collection project to make progress and with your work probably also be completed! :heart: This was my first big project in Clippy, and it's also the one that held me here and introduced me to the team. I hope you also had fun with it.

Now enough rambling:

@bors r+

**Comment by xFrednet** [comment]
Sorry for the r-, this is worth a changelog entry. I don't want this to slip under the radar of who ever will write it for that version. I've added the entry and also ticked of the checkbox in the tracking issue

@bors r+

**Pull request merged**
