### PR TITLE
Refactor types lints

### PR DESCRIPTION
**Pull request by Y-Nak**
Ref #6724.
As described in #6724, `types.rs` contains many groups inside it.
In this PR, I reorganize the lints of the `types` group into their own modules.

changelog: none

### CODE REVIEW

**Comment by Y-Nak** [comment]
Changes: Import declared lint at the top of the file instead of using it with `super::` prefix in the code. See [this review](https://github.com/rust-lang/rust-clippy/pull/6693#discussion_r576698303).

**Review by magurotuna — APPROVED** [review]
LGTM 👍

**Review by nahuakang — APPROVED** [review]
Very neat! LGTM :recycle:

**Comment by Y-Nak** [comment]
Changes: Resolve conflicts.

**Comment by Y-Nak** [comment]
Argh, this conflict needs much work to resolve.

@flip1995 Please notify me when you are ready to review this, I don't want to rebase this again and again.

**Review by flip1995 — APPROVED** [review]
Non-rebased changes LGTM. Ping me, if you get to rebasing this and I can quickly review the rebase.

**Comment by Y-Nak** [comment]
@flip1995 Thanks for your review! I've finished the rebase.

**Comment by flip1995** [comment]
Thanks!

As promised:

@bors r+ p=3

**Pull request merged**
