### PR TITLE
Add `imports_granularity = "Module"` to rustfmt.toml

### PR DESCRIPTION
**Pull request by Alexendoo**
This lets rustfmt split/merge imports, `Module` seems to be the most common style in clippy

https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#imports_granularity

changelog: none

Almost all the updates other than the config file change are from `cargo dev fmt` or blessed tests, the exceptions being

- `tests/ui/single_component_path_imports.rs`
- `tests/ui/single_component_path_imports_nested_first.rs`
- `tests/ui/single_component_path_imports_self_after.rs`
- `tests/ui/single_component_path_imports_self_before.rs`
- `tests/ui/unsafe_removed_from_name.rs` (added a test with merged imports as a drive by)
- `tests/ui/wildcard_imports.rs`
- `tests/ui/wildcard_imports_2021.rs`

### CODE REVIEW

**Comment by Centri3** [comment]
What about `group_imports`? I see something akin to `StdExternalCrate` used often but that's likely because of what rustfmt does automatically

**Comment by flip1995** [comment]
I'd like to switch to https://github.com/rust-lang/rustfmt/pull/5781 if that should get merged.

**Comment by Centri3** [comment]
Ooh I like that :)

**Comment by Alexendoo** [comment]
FWIW this also only modifies just under a third of the files, 195/605 (excluding tests since most of those are unchanged)

**Review by flip1995 — APPROVED** [review]
I'm fine with adding this. But once the above linked feature is available, I'd like to move to that one. But I wouldn't block this PR on that.

Leaving this PR open for 1-3 days, so that people can raise their objections, if any.

**Review by Manishearth — APPROVED** [review]
same opinion as @flip1995 , r=me after a couple days

**Comment by Alexendoo** [comment]
Let's create a bunch of conflicts!

@bors r=Manishearth

**Pull request merged**
