### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by mati865**
Supersedes https://github.com/rust-lang/rust-clippy/pull/3889

Addresses some review comments from previous PR and rustups to https://github.com/rust-lang/rust/pull/58899

### CODE REVIEW

**Comment by mati865** [comment]
Formatting with `--all` this time...

@bors retry

**Comment by matthiaskrgr** [comment]
````
  Installing /Users/travis/.cargo/bin/rustup-toolchain-install-master
detecting the channel of the `cd45b19bd2d8b4f9a3940a409ea43285019f3280` toolchain...
error: https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds/cd45b19bd2d8b4f9a3940a409ea43285019f3280/rust-src-nightly.tar.xz: timed out
error: toolchain 'master' is not installed
info: backtrace:
stack backtrace:
   0:        0x10cd8bf8e - backtrace::backtrace::trace::hb39615e846d97438
   1:        0x10cd8b1a4 - error_chain::backtrace::imp::InternalBacktrace::new::h42957417422586b4
   2:        0x10c9ebcc1 - rustup_init::rustup_mode::main::ha2b3dbc277471d62
   3:        0x10ca27c4c - rustup_init::run_rustup::he197b959e963ea85
   4:        0x10ca26f87 - rustup_init::main::h9d7da49ccb0c8cc2
   5:        0x10c9cddc5 - std::rt::lang_start::{{closure}}::h11a539400a49a543
   6:        0x10ca2cc68 - _main
````
@bors retry

**Comment by mati865** [comment]
Appveyor is broken :disappointed:

**Comment by Xanewok** [comment]
Please let me know if/when you decide to update tools in the Rust tree - I'd like to update to the current RLS master (which also means pulling in Rustfmt 1.1) in tandem with this.

**Comment by mati865** [comment]
@Xanewok you can upgrade all the tools in Rust repo at same time if you want.

**Pull request merged**
