### PR TITLE
update urls (rust-lang-nursery => rust-lang)

### PR DESCRIPTION
**Pull request by matthiaskrgr**
I hope I got everything here.
Links to issues and the repos get auto-redirected to the new repo but urls to links on github.io were broken.

Do we need to backport this change somehow?

I left the relicensing docs untouched on purpose.

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
I wonder if we should run some kind of link-checker on CI to make sure this *noticeably* breaks things in the future?

**Comment by matthiaskrgr** [comment]
>bors r+

looks like the bot got left behind as well

**Comment by oli-obk** [comment]
cc @alexcrichton can you enable bors.tech for rust-lang/rust-clippy?

**Comment by alexcrichton** [comment]
I don't know what bors.tech is?

**Comment by hcpl** [comment]
@alexcrichton the site https://bors.tech/

**Comment by alexcrichton** [comment]
Hm ok, the fact that I don't know what that is though means that I don't know how it was set up earlier or how to set it up now, I think you'll need to find someone else.

**Comment by flip1995** [comment]
`bors.tech` can be added as a GitHub App via https://github.com/integration/bors. It should be activated only for the `rust-clippy` repository and not for all repositories.

**Pull request merged**
