### PR TITLE
Clippy Book Chapter Updates Reborn: Type Checking

### PR DESCRIPTION
**Pull request by blyxyas**
This PR adds a new chapter to the book: "Type Checking", it hasn't changed a lot from the source mainly because there wasn't many reviews on it and I haven't see a lot of things that needed a change.

## Notes

- I have some doubts about the whole "`is_*` Usage" section, what do you think about it.
- For discussion about  the whole project, please use the tracking issue for the project #10597 (It also contains a timeline, discussions, and more information)

changelog: Add a new "Type Checking" chapter to the book

r? @flip1995

### CODE REVIEW

**Comment by llogiq** [comment]
Nice improvement!

I'm missing a way to relate or convert `hir::Ty` to `ty::Ty`, as one someone does when working with function signatures. Would you like to add a paragraph about that?

**Comment by blyxyas** [comment]
> Would you like to add a paragraph about that

For sure!

**Comment by llogiq** [comment]
Great! 👍

**Comment by llogiq** [comment]
As @flip1995 seems to be busy, @bors r+

**Pull request merged**
