### PR TITLE
Add new lint `obfuscated_if_else`

### PR DESCRIPTION
**Pull request by arieluy**
part of #9100, additional commits could make it work with `then` and `unwrap_or_else` as well

changelog: Add new lint `obfuscated_if_else`

### CODE REVIEW

**Comment by Jarcho** [comment]
Just going to nitpick the name here. Basically the same lint applies to any combinations of [`then`, `then_some`] and [`unwrap_or`, `unwrap_or_default`, `unwrap_or_else`, `map_or`, `map_or_else`, `is_some_and`].

**Comment by arieluy** [comment]
I was trying to follow the naming guidelines of stating the thing that is wrong. What do you think about `obfuscated_if_else`, or do you have any other suggestions?

**Comment by Jarcho** [comment]
I think `obfuscated_if_else` should be fine.

**Comment by Jarcho** [comment]
Looks good. Thank you.

@bors r+

**Comment by arieluy** [comment]
Thanks @Jarcho !

**Pull request merged**
