### PR TITLE
Revive test in `enum_clike_unportable_variant`

### PR DESCRIPTION
**Pull request by JohnTitor**
Revive one test since mentioned ICE has been resolved.

changelog: none

### CODE REVIEW

**Comment by JohnTitor** [comment]
Ugh, travis is encountering trouble: https://www.traviscistatus.com/

**Comment by flip1995** [comment]
I'll mark it as `S-waiting-on-rustup` until that is resolved

**Comment by flip1995** [comment]
should work now

@bors r+

**Pull request merged**
