### PR TITLE
Changes cast-lossless to a pedantic lint

### LINKED ISSUE #4528: cast-lossless is too strict
`cast-lossless` includes issuing a warning about what might happen *if* you change your code: `warning: casting u8 to i32 may become silently lossy if you later change the type`. Given that the cast is totally safe with the code as written, this seems like it should be a pedantic lint, rather than a default one.

### PR DESCRIPTION
**Pull request by jolson88**
As discussed in #4528, this moves the cast-lossless lint from `all` to `pedantic`.

I couldn't tell from description alone if it should also be removed from the complexity category, so I left it as part of complexity for now. I didn't see any impact to the tests from this change, but I could be wrong (as this is my first PR).

fixes #4528 

changelog: Moves cast-lossless from default to checking only as a `pedantic` lint.

### CODE REVIEW

**Comment by jolson88** [comment]
Great! Thanks Mike. I'll do that this evening and get the PR updated :).

**Comment by jolson88** [comment]
Updated and corrected tests. I think (?) that the build failures are from the needed change to the clippy-driver: https://github.com/rust-lang/rust/issues/64440

**Comment by phansch** [comment]
going to retrigger the build

**Comment by jolson88** [comment]
Force pushing after rebasing to latest master (hoping to pick up recent redundant-clone.rs changes).

**Comment by jolson88** [comment]
Hm, looks like another breaking change in rustc_driver perhaps?

**Comment by jolson88** [comment]
Here's the PR and change that caused the new build failures: https://github.com/rust-lang/rust/pull/60584/files#diff-707a0eda6b2f1a0537abc3d23133748cL1151. I will get a new PR opened soon to fix that issue.

**Comment by jolson88** [comment]
PR opened for the breaking change: https://github.com/rust-lang/rust-clippy/pull/4545.

**Pull request merged**
