### PR TITLE
Add new `unnecessary_get_then_check` lint

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
No issue linked to this as far as I can see. It's a lint I discovered that could be added when I worked on another lint.

r? @llogiq 

changelog: Add new `unnecessary_get_then_check` lint

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Finally fixed doc examples and dogfood. ^^'

Pretty nice to see that the lint already caught some cases in clippy source code. :)

**Comment by llogiq** [comment]
Thank you!

@bors r+

**Comment by GuillaumeGomez** [comment]
Rebasing just in case...

**Comment by GuillaumeGomez** [comment]
Rebased!

**Pull request merged**
