### PR TITLE
fix-typos

### PR DESCRIPTION
**Pull request by sheshnath-at-knoldus**
fixes some typos in lintcheck

changelog: None

### CODE REVIEW

**Comment by Jarcho** [comment]
`Lintcheck` is named that way on purpose to match the tool name. The other changes are fine.

**Comment by sheshnath-at-knoldus** [comment]
ok @Jarcho

**Comment by sheshnath-at-knoldus** [comment]
should I need to revert the changes for LintcheckConfig

**Comment by Jarcho** [comment]
Yes. Reverting just the second commit would be great.

**Review by Jarcho — APPROVED** [review]
Just need to have the commits squashed and then we're good.

**Comment by sheshnath-at-knoldus** [comment]
@Jarcho  who will squashed the commits ?

**Comment by Jarcho** [comment]
You will have to.

**Comment by Jarcho** [comment]
I would generally use `git rebase -i HEAD~N` to squash the last `N` commits together. There are other more concise ways to do it, but they're also more open to typos leading to problems.

**Comment by sheshnath-at-knoldus** [comment]
so what should i do next ?

**Comment by Jarcho** [comment]
Assuming your local state and github's are the same the easiest way would be `git reset HEAD~3` (will undo the last three commits), then discard the changes and force push.

**Comment by sheshnath-at-knoldus** [comment]
thanks it worked

**Comment by Jarcho** [comment]
Thank you. @bors r+

**Pull request merged**
