### PR TITLE
Improve wording for suggestion messages

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Follow-up of https://github.com/rust-lang/rust-clippy/pull/12140.

r? @llogiq 

changelog: Improve wording for suggestion messages

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Fixed CI.

**Comment by smoelius** [comment]
Please forgive me for chiming in. I was planning to submit a PR to remove all the uses of "consider".

Here is a concrete example: https://github.com/rust-lang/rust-clippy/blob/4b3a9c09f32b725c77acbbf411158cb03af7a36a/clippy_lints/src/copy_iterator.rs#L54

IMHO, "consider" doesn't add anything here, and just the following would suffice:
```
"implement `IntoIterator` instead", 
```

**Comment by GuillaumeGomez** [comment]
It's possible that the clippy suggestion is either wrong or not the best in a given context. Using "consider" leaves this possibility open and tells the users "it might be better than what you already have, so maybe consider using it?". At least that's how I see it.

**Comment by smoelius** [comment]
> It's possible that the clippy suggestion is either wrong or not the best in a given context. Using "consider" leaves this possibility open ...

OK. (Sorry for jumping on your PR.)

**Comment by GuillaumeGomez** [comment]
It's fine don't worry. Better discuss before changes are merged to ensure everyone is on board. :)

**Comment by llogiq** [comment]
Looks good to me. Thank you!

@bors r+

**Comment by GuillaumeGomez** [comment]
I ran the tests locally and it all worked. Not sure what happened... I rebased just in case.

**Comment by y21** [comment]
something's up with the macos runners, they have been failing in a bunch of PRs for a few days now
https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Sporadic.20macos.20failures

so it probably just needs a retry run

**Comment by y21** [comment]
Hmm seems like that wasn't picked up by bors? Maybe it needs to be reapproved since a new commit was added/history was changed because of the rebase? 🤔

**Comment by llogiq** [comment]
Let's try that then.

@bors r+

**Pull request merged**
