### PR TITLE
[`single_component_path_imports`] to include super:: and crate::; …

### LINKED ISSUE #7168: FP single_component_path_imports
Lint name:

single_component_path_imports

I tried this code:

```rust
#[cfg(feature = "log")]
use log;

mod foo {
    use crate::log::warn;

    pub fn bar() {
        warn!("bar");
    }
}

pub fn bar() {
    foo::bar()
}
```

(I think it doesn't matter whether the feature `log` is turned on or off.)

I expected to see this happen: no warning, since the `log` import is used in an inner module.

Instead, this happened:

```rust
warning: this import is redundant
 --> src/lib.rs:3:1
  |
3 | use log;
  | ^^^^^^^^ help: remove it entirely
  |
  = note: `#[warn(clippy::single_component_path_imports)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_component_path_imports
```

### Meta

- `cargo clippy -V`: clippy 0.1.53 (42816d61 2021-04-24)
- `rustc -Vv`:
  ```
  rustc 1.53.0-nightly (42816d61e 2021-04-24)
  binary: rustc
  commit-hash: 42816d61ead7e46d462df997958ccfd514f8c21c
  commit-date: 2021-04-24
  host: x86_64-apple-darwin
  release: 1.53.0-nightly
  LLVM version: 12.0.0
  ```

### PR DESCRIPTION
**Pull request by mautamu**
Howdy,

This is my attempt to fix #7168. 

I added a tracker variable to [`single_component_path_imports`]  for what I'm referring to as "root paths," i.e. `crate::*` and `super::*`. With this, we add another check to filter out those prior to emitting warnings.

Let me know what could be done better!

Best,
Mautamu

r? @djc @camsteffen 
fixes: #7168
changelog: Don't trigger [`single_component_path_imports`] on an import if crate::import or super::import are invoked.

### CODE REVIEW

**Comment by camsteffen** [comment]
Thanks for contributing to clippy!

We should make sure we don't introduce false negatives where `super` refers to something at a different level. If I'm not mistaken, we need a more robust solution to detect theses cases (and we should have tests for some negative cases).

```rust
use x; // this should lint

mod a {
    use x; // this should not lint
	mod b {
	      fn f() {
	          super::x::..;
	      }
	}
}
```

Also I'm concerned about performance with collecting `use`s for the entire crate in a `Vec` and then using `Vec::contains`.

This is a little difficult for a first-time contribution, but you are certainly welcome to stick to it! 

<details>
<summary>Here is one idea.</summary>

1. Add `imports: Vec<FxHashMap<Symbol, Span>>` to `SingleComponentPathImports`
2. When you visit `use x`, add it to `imports.last()`
2. When you visit a nested `mod` (in `check_item` if `ItemKind::Mod`) push a new set onto `imports`
3. When you visit `super::x::..` remove `x` from `imports[imports.len() - number_of_supers - 1]`
4. At the end of a module (`check_item_post`), `imports.pop()` and lint every element in the set.

Perhaps all of the `Vec`s currently being used could be removed and just use `imports`. But not required.
</details>

**Comment by giraffate** [comment]
ping from triage @mautamu. Can you have any updates on this? If you have any questions, feel free to ask us!

**Comment by mautamu** [comment]
> ping from triage @mautamu. Can you have any updates on this? If you have any questions, feel free to ask us!

Oh thanks for checking back! Sorry about the delay, I’ll see what I can get done tomorrow.

**Comment by giraffate** [comment]
ping from triage @mautamu. Can you have any updates on this?

**Comment by giraffate** [comment]
ping from triage @mautamu. According to the triage procedure, I'm closing this because 2 weeks have passed with no activity. If you have more time to work on this, feel free to reopen this.

**Pull request closed without merging**
