### PR TITLE
Move unimplemented to an EarlyLintPass

### LINKED ISSUE #3528: clippy::unimplemented doesn't detect unimplemented!() with message
When a message is given to `unimplemented!()` (rust-lang/rust@f51771939ba5b36ec89b9f0b51c2cbda51164676), the `unimplemented` lint doesn't detect it.

```rust
#[allow(unreachable_code)]
#[warn(clippy::unimplemented)]
fn main() {
    unimplemented!("a()"); // case 1, not detected
    unimplemented!();      // case 2
}
```

    warning: `unimplemented` should not be present in production code
     --> src/main.rs:5:5
      |
    5 |     unimplemented!();      // case 2
      |     ^^^^^^^^^^^^^^^^^
      |
    note: lint level defined here
     --> src/main.rs:2:8
      |
    2 | #[warn(clippy::unimplemented)]
      |        ^^^^^^^^^^^^^^^^^^^^^
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unimplemented

clippy: 29bf75cd3147d4e34a5e70bd167898a8105f7e5d (2018-12-05)

### PR DESCRIPTION
**Pull request by maxencefrenette**
fixes #3528
WIP

Hi all ! As suggested in the issue thread, I moved the `unimplemented` lint to an `EarlyLintPass`. It works great and makes the code much simpler. However, I don't know how to move the panic lint to an `EarlyLintPass`. I see a couple options right now. 

- Keep the LateLintPass for it and move it to another file.
- Adapt the `check_tts()` function from `clippy_lints/src/write.rs`. However, I couldn't fully grasp how to adapt it to work in this case.
- Something much simpler that I'm not seeing right now.

### CODE REVIEW

**Comment by flip1995** [comment]
The `check_tts` function of `write.rs` is way to complex for this use case, but as you noticed correctly you can copy some code from there. 

You basically just need this part of the `check_tts` function:

https://github.com/rust-lang/rust-clippy/blob/01ab9fe6532bec62b5c90ba18f1588e2bd7bf3b1/clippy_lints/src/write.rs#L326

https://github.com/rust-lang/rust-clippy/blob/01ab9fe6532bec62b5c90ba18f1588e2bd7bf3b1/clippy_lints/src/write.rs#L339-L342

For `panic!("foo {}", a)`, this will parse you the string `"foo {}"`, which you can then examine with the code

https://github.com/rust-lang/rust-clippy/blob/01ab9fe6532bec62b5c90ba18f1588e2bd7bf3b1/clippy_lints/src/panic_unimplemented.rs#L87-L89

This will tell you if there is a `{}` in the string.

After this, you can check if there are parameters with 

https://github.com/rust-lang/rust-clippy/blob/01ab9fe6532bec62b5c90ba18f1588e2bd7bf3b1/clippy_lints/src/write.rs#L334-L336

and 

```rust
// You only need to try to parse one expression and not all format parameters
parser.parse_expr().map_err(|mut err| err.cancel()).is_some()
```

**Comment by mikerite** [comment]
Did [the problem](https://github.com/rust-lang/rust-clippy/pull/3217#issuecomment-424574271) with `EarlyLintExpansion` and nested macros get fixed? I don't think we should use pre-expansion lints at all until that's resolved.

**Comment by flip1995** [comment]
The problem got not fixed and probably won't be fixed.

cc https://github.com/rust-lang/rust-clippy/pull/3217#issuecomment-424641680
> We should limit `PreExpansionPass` to lints that **really** only look for a specific macro call.

This is the case here. So it should be fine to turn this into a `PreExpansionPass`

@maxencefrenette Could you add following test:
```rust
macro_rules! outer_macro {
    ($e:expr) => {
        $e;
    };
}

// ...
outer_macro!(unimplemented!());
```
This `unimplemented!` call should get linted! If that's not the case the problem @mikerite described is more severe than I thought.

**Comment by maxencefrenette** [comment]
> The problem got not fixed and probably won't be fixed.
> 
> cc [#3217 (comment)](https://github.com/rust-lang/rust-clippy/pull/3217#issuecomment-424641680)
> 
> > We should limit `PreExpansionPass` to lints that **really** only look for a specific macro call.
> 
> This is the case here. So it should be fine to turn this into a `PreExpansionPass`
> 
> @maxencefrenette Could you add following test:
> 
> ```rust
> macro_rules! outer_macro {
>     ($e:expr) => {
>         $e;
>     };
> }
> 
> // ...
> outer_macro!(unimplemented!());
> ```
> 
> This `unimplemented!` call should get linted. If that's not the case the problem @mikerite described is more severe than I thought.

Interesting stuff. I'll for sure add that test when I get back to it. Thanks a lot for your help @flip1995 !

**Comment by maxencefrenette** [comment]
Everything passes locally and I updated the .stderr for the test. @mikerite  @flip1995 what you feared happened. It doesn't detect nested macros, as can be seen in the test files.

**Comment by flip1995** [comment]
> It doesn't detect nested macros, as can be seen in the test files.

Well that's bad :( I'm not sure what's the best course of action here... Let's be naive: Can we use the `check_mac` function in an `EarlyLintPass` after macro expansion?

**Comment by flip1995** [comment]
Thanks for the work! But I don't think moving this lint to a pre_expansion_pass is the right thing to do here. Since this is stale for some time, I'm going ahead and close this PR.

**Comment by HKalbasi** [comment]
finished in #5811
@rustbot label -S-inactive-closed

**Pull request closed without merging**
