### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by flip1995**
r? @ghost

changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
ok some tests need to be blessed it seems

**Comment by Jarcho** [comment]
Panic is cause by line 64 of the integration test. This is the line which is supposed to print the backtrace from the failing test...

**Comment by matthiaskrgr** [comment]
Hmm , looks like the ICE happens in a test of combines lib.rs
````rust
    #[test]
    fn chainl1_error_consume() {
        fn first<T, U>(t: T, _: U) -> T {
            t
        }
        let mut p = chainl1(string("abc"), char(',').map(|_| first));
        assert!(p.parse("abc,ab").is_err());
    }
  ````

**Comment by matthiaskrgr** [comment]
I opened https://github.com/rust-lang/rust/issues/102289 for the rustc ICE but I didn't manage to get a small mvce :disappointed:  anyway, its way past bed time here :/

**Comment by matthiaskrgr** [comment]
once https://github.com/rust-lang/rust/pull/102378 lands, the ice should be fixed :tada:

**Comment by flip1995** [comment]
@bors r+

Let's see if it works. Thanks for keeping track of this!

**Comment by matthiaskrgr** [comment]
I think we have to wait for next nightly, the fix was just merged this morning

**Comment by flip1995** [comment]
Ah right. Let's hope that Clippy won't be touched in the Rust repo until tomorrow :D

**Comment by flip1995** [comment]
@bors r+ 

Bumping the nightly version was enough, puh.

**Pull request merged**
