### PR TITLE
Inherit stdout/stderr for `cargo dev dogfood`

### PR DESCRIPTION
**Pull request by Alexendoo**
changelog: none

Prints progress as it happens and in colour, and will also show anything printed to stderr

### CODE REVIEW

**Comment by flip1995** [comment]
> Prints progress as it happens and in colour, and will also show anything printed to stderr

I didn't see any progress printing on CI and also don't understand how the committed changes should achieve this. Is this only done if there is something emitted to `stderr`?

I think this is a code improvement nonetheless, so r=me, if I missed something obvious.

**Comment by Alexendoo** [comment]
For CI it wouldn't show anything different, but `cargo dev dogfood` was hiding the output of the `cargo test --test dogfood ...` until it was completed, so you wouldn't see the initial clippy + test compilation progress

I've now added `--nocapture` so the test output can be seen

I tried doing the same thing in the dogfood test itself but that seemed to print stuff even when `--nocapture` wasn't passed in which is weird so I reverted that

**Comment by flip1995** [comment]
I see, thanks for the explanation. 

@bors r+

**Comment by Alexendoo** [comment]
Huh, tests capture print macros and panics [by asking `std` to do it](https://doc.rust-lang.org/src/std/io/stdio.rs.html#19-22) 😨

So other ways of writing to stdout/stderr [aren't captured](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8526aa2c1adb0ed704b2edbdab3eccf9)

**Pull request merged**
