### PR TITLE
Trigger modulo_one lint also on -1.

### LINKED ISSUE #6321: Lint for calculating remainder with divisor of -1
While for remainder with 1 there is the [modulo_one](https://rust-lang.github.io/rust-clippy/master/index.html#modulo_one) lint, a remainder with -1 is only caught by the [integer_arithmetic](https://rust-lang.github.io/rust-clippy/master/index.html#integer_arithmetic) lint, which is disabled by default ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=46cc562dba8887fa743d6aacf683228c)). The issue has been discussed briefly in #663 but not resolved.

As there are only two possible outcomes when calculating the remainder with -1 (overflow/panic or 0), this should definitely be linted in my opinion. I suggest modifying the [modulo_one](https://rust-lang.github.io/rust-clippy/master/index.html#modulo_one) lint to also be triggered by -1 (potentially with a different warning).

### PR DESCRIPTION
**Pull request by mlegner**
Fixes #6321.

changelog: trigger `modulo_one` lint also on `-1`

### CODE REVIEW

**Comment by mlegner** [comment]
Question about tests with static constants: Is there a good reason why the lint should not be triggered by those or is this a bug?
If it is a bug, I could either try to fix it in this PR or create an issue for it.

**Comment by llogiq** [comment]
I don't know the reason. At least filing an issue sounds like a good idea.

**Comment by mlegner** [comment]
> I don't know the reason. At least filing an issue sounds like a good idea.

In general, there seems to be quite some inconsistency with constant/literal testing in clippy. For example, the [integer_arithmetic](https://rust-lang.github.io/rust-clippy/master/index.html#integer_arithmetic) lint also tests for literals but does not do constant folding at all. I will suggest consolidating these to rely on a single constant-comparison function similar to / replacing the [is_integer_const](https://github.com/rust-lang/rust-clippy/blob/8325d48d2de179490eba9e682ffaaea375d2e1c9/clippy_lints/src/utils/mod.rs#L837) function.

**Comment by llogiq** [comment]
This fails the dogfood test. There's a function in misc.rs with 110 lines. We should probably factor some of the lines out into another function.

**Comment by mlegner** [comment]
> This fails the dogfood test. There's a function in misc.rs with 110 lines. We should probably factor some of the lines out into another function.

I have created a `check_binary` function that is called in the `check_expr` function.

**Comment by llogiq** [comment]
Thank you! @bors r+

**Pull request merged**
