### PR TITLE
Remove me from `users_on_vacation`

### PR DESCRIPTION
**Pull request by blyxyas**
Came back from surgery about 2 days ago, totally cool to review some more PRs.

changelog:none
r? ghost

### CODE REVIEW

**Comment by xFrednet** [comment]
Directly r+ing your own PRs? We changed policies in the time *years* you were gone, that's not okay /s

---

She's alive!!! `＼(^o^)／`

**Comment by blyxyas** [comment]
Sorry mom

**Comment by xFrednet** [comment]
Mom, what did I miss? O.o

Good to have you have pricness!

**Comment by xFrednet** [comment]
Small FYI @blyxyas, the `chaneglog: none` filter is space sensitive. If there is no space before the `none` it will still be included in the PRs to check.

Is this a thing, which is probably easy to fix? Yes, but asking you to include the space is easier rn xD

=^.^=

**Comment by blyxyas** [comment]
If it uses a regex, the pattern could use `\s*` to support any amount of spaces between "changelog:" and "none" (With the `i` flag for case insensitivity)

```regex
/changelog:\s*none/gi
```

**Comment by xFrednet** [comment]
I know how to fix it, but telling you is a bit easier rn, as said

**Pull request merged**
