### PR TITLE
build: do not reinstall master toolchain if it is up-to-date

### PR DESCRIPTION
**Pull request by lzutao**
changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
When I run `git ls-remote https://github.com/rust-lang/rust master` it can sometimes take several 10s of seconds to execute. Is anyone else getting that?
```
git ls-remote https://github.com/rust-lang/rust master  0,17s user 0,10s system 0% cpu 53,640 total
```

**Comment by phansch** [comment]
> When I run `git ls-remote https://github.com/rust-lang/rust master` it can sometimes take several 10s of seconds to execute. Is anyone else getting that?
> 
> ```
> git ls-remote https://github.com/rust-lang/rust master  0,17s user 0,10s system 0% cpu 53,640 total
> ```

Yes, I can also reproduce this. About 5% of the time it will take 10+ seconds to get the result. On my slow 2Mbps connection this PR is still a significant speed up currently.

Also considering that it isn't always that slow, I'd say it's fine to merge this?

**Comment by lzutao** [comment]
Ci passed

**Pull request merged**
