### PR TITLE
Fix false positive in `PartialEq` check in `unconditional_recursion` lint

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust-clippy/issues/12133.

We needed to check for the type of the previous element <del>in case it's a field</del>.

EDIT: After some extra thoughts, no need to check if it's a field, just if it's the same type as `Self`.

r? @llogiq 

changelog: Fix false positive in `PartialEq` check in `unconditional_recursion` lint

### CODE REVIEW

**Comment by llogiq** [comment]
Thank you!

@bors r+

**Comment by Robbepop** [comment]
@GuillaumeGomez is this fix supposed to already have been shipped in the most recent nightly `clippy` version via `rustup`? I wonder since it has been merged for quite some days but I am still receiving false positive bugs with newest nightly Clippy with the Wasmi project CI. (https://github.com/paritytech/wasmi)

**Comment by GuillaumeGomez** [comment]
It's synced every 15 days. I thin next sync is in ~10 days. If you want a faster sync, please open an issue so someone can do it.

**Comment by Robbepop** [comment]
> It's synced every 15 days. I thin next sync is in ~10 days. If you want a faster sync, please open an issue so someone can do it.

Good to know! This is fine for me, I just wanted to know if I am running into yet another case that has not yet been covered and should therefore be reported. :)

**Comment by GuillaumeGomez** [comment]
Don't hesitate to add a new test if none of the existing ones look like yours. ;)

**Comment by Robbepop** [comment]
Will do as soon as such a situation arises. :)

**Pull request merged**
