### PR TITLE
`manual_filter_map` and `manual_find_map`

### LINKED ISSUE #3188: Make the `filter_map` lint more specific
The intent of the `filter_map` method is to unwrap element values and skip `None`s when iterating over elements that are `Option`s. It's not a universal shorthand for `filter` followed by a call to`map`. The `filter_map` [documentation](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter_map) indicates this.

The current implementation of the `fliter_map` lint triggers on every call to `filter` followed by a call to`map` and basically notes that the suggestion can make the code more complicated as a [known issue](https://rust-lang-nursery.github.io/rust-clippy/master/index.html#filter_map). It encourages changes like this (from #3186):

```
extra_args
    .split("__CLIPPY_HACKERY__")
    .filter(|s| !s.is_empty())
    .map(str::to_owned)
```
to
```
extra_args
   .split("__CLIPPY_HACKERY__")
   .filter_map(|s| if s.is_empty() {
       None
   } else {
       Some(s.to_string())
   })
```
I find the final code is less readable and more complicated than the code at the start. Although, there is one less function call, there is now an `if` statement and extra code for constructing an option.

Let's change the lint to only trigger in the following conditions. In the table below `option_expr` is an expression with type `Option<_>` and `result_expr` is an expression with type `Result<_, _>`.

|Code|Suggestion|
|----|----|
| `filter(\|x\| option_expr.is_some()).map(\|x\| x.unwrap())` | `filter_map(\|x\| option_expr)` |
| `filter(\|x\| option_expr.is_some()).flat_map(\|x\| x)` | `filter_map(\|x\| option_expr)` |
|`filter(\|x\| result_expr.is_ok()).map(\|x\| x.unwrap())` | `filter_map(\|x\| result_expr.ok())` |

### LINKED ISSUE #4193: Make `find_map` lint be more conservative
The find_map lint will trigger if you do a `filter` followed by a `map` but its not always preferable.

```
---- dogfood stdout ----
status: exit code: 101
stdout:
stderr:     Blocking waiting for file lock on package cache lock
    Checking clippy v0.0.212 (/home/jlusby/git/rust/clippy)
error: called `find(p).map(q)` on an `Iterator`. This is more succinctly expressed by calling `.find_map(..)` instead.
   --> src/driver.rs:129:9
    |
129 | /         LINT_LEVELS
130 | |             .iter()
131 | |             .find(|level_mapping| level_mapping.0 == lint.group)
132 | |             .map(|(_, level)| level)
    | |____________________________________^
    |
    = note: `-D clippy::find-map` implied by `-D clippy::pedantic`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#find_map

error: called `filter(p).map(q)` on an `Iterator`. This is more succinctly expressed by calling `.filter_map(..)` instead.
   --> src/driver.rs:205:24
    |
205 |               let desc = lints
    |  ________________________^
206 | |                 .iter()
207 | |                 .filter(|&lint| lint.group == group)
208 | |                 .map(|lint| lint.name)
    | |______________________________________^
    |
    = note: `-D clippy::filter-map` implied by `-D clippy::pedantic`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#filter_map

error: called `find(p).map(q)` on an `Iterator`. This is more succinctly expressed by calling `.find_map(..)` instead.
   --> src/driver.rs:129:9
    |
129 | /         LINT_LEVELS
130 | |             .iter()
131 | |             .find(|level_mapping| level_mapping.0 == lint.group)
132 | |             .map(|(_, level)| level)
    | |____________________________________^
    |
    = note: `-D clippy::find-map` implied by `-D clippy::pedantic`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#find_map

error: called `filter(p).map(q)` on an `Iterator`. This is more succinctly expressed by calling `.filter_map(..)` instead.
   --> src/driver.rs:205:24
    |
205 |               let desc = lints
    |  ________________________^
206 | |                 .iter()
207 | |                 .filter(|&lint| lint.group == group)
208 | |                 .map(|lint| lint.name)
    | |______________________________________^
    |
    = note: `-D clippy::filter-map` implied by `-D clippy::pedantic`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#filter_map

error: aborting due to 2 previous errors
```

In the case of the first lint at least, you'll run into lifetime issues if you try to replace lines 131 and 132 with a find_map call.

```rust
        LINT_LEVELS
            .iter()
            .find_map(|level_mapping| {
                if level_mapping.0 == lint.group {
                    Some(level_mapping.1)
                } else {
                    None
                }
            })
            .map(|level| match level {
                Level::Allow => "allow",
                Level::Warn => "warn",
                Level::Deny => "deny",
            })
            .unwrap()
```

```
master ✗ $ cargo check
    Checking clippy v0.0.212 (/home/jlusby/git/rust/clippy)
error[E0507]: cannot move out of `level_mapping.1` which is behind a shared reference
   --> src/driver.rs:133:26
    |
133 |                     Some(level_mapping.1)
    |                          ^^^^^^^^^^^^^^^ move occurs because `level_mapping.1` has type `lintlist::lint::Level`, which does not implement the `Copy` trait

error: aborting due to previous error

For more information about this error, try `rustc --explain E0507`.
error: Could not compile `clippy`.

To learn more, run the command again with --verbose.
```

And even if it didn't run into the borrow error I personally feel like the find_map version is less concise than the filter -> map version.

If the Item type of the iterator was already a `Try` type then I can see it being easy enough to write a concise find_map impl, but with the boolean as the only starting point for the closure outputting `Some` or `None` I don't think it works as nicely as filter and map.

### PR DESCRIPTION
**Pull request by camsteffen**
changelog: Add `manual_filter_map` and replace `find_map` with `manual_find_map`

Replaces #6453

Fixes #3188
Fixes #4193

~Depends on #6567 (to fix an internal lint false positive)~

This replaces `filter_map` and `find_map` with `manual_filter_map` and `manual_find_map` respectively. However, `filter_map` is left in place since it is used for a variety of other cases. See discussion in #6453.

### CODE REVIEW

**Comment by llogiq** [comment]
Our internal path check isn't having the `OPTION_IS_SOME` and `RESULT_IS_OK` paths. Shouldn't we have symbols for those anyway?

**Comment by camsteffen** [comment]
That will be fixed in #6567.

Hmm I suppose it is better to use the Option diagnostic item + method name. I'll do that.

**Comment by llogiq** [comment]
Sorry for leaving you waiting for so long. r=me once the conflicts are resolved.

**Comment by camsteffen** [comment]
No worries!

r? @llogiq 

^Is that right?

**Comment by llogiq** [comment]
Thank you! @bors r+

**Pull request merged**
