### PR TITLE
chore(module_name_repeat): Rename stutter lint to module_name_repeat to avoid ableist language

### PR DESCRIPTION
**Pull request by klausi**
See #3521

### CODE REVIEW

**Comment by klausi** [comment]
I did not touch CHANGELOG.md so far, it looks like the links there are auto-generated?

**Comment by flip1995** [comment]
Thanks for your contribution and welcome to Clippy! 🎉 

The changelog will be adapted automatically if you run `$ ./util/dev update_lints`.

The lint also needs to be registered as renamed. See [rustc-docs](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/lint/struct.LintStore.html#method.register_renamed)

Since until now we never registered a lint as renamed, I'm not sure where to do this exactly. Could you try to call the `register_renamed()` function in the obvious places (`clippy_lints/lib.rs`)? If that doesn't work I will take a closer look at this myself.

**Comment by klausi** [comment]
Thanks! Ran `$ ./util/dev update_lints` and the CHANGELOG should be good now.

Tried to add the register_renamed() call at the end after all lints are registered, but that fails with "invalid lint renaming of stutter to module_name_repeat". What is the correct name of the new module_name_repeat lint so that it is valid here? Maybe it is not in the store where I'm running the register_renamed() on? How can I get the store which has the new module_name_repeat lint?

**Comment by flip1995** [comment]
Yeah I thought of recalling something, that the lints actually get added later in the compiler. I need to give this a closer look tomorrow. :)

**Comment by phansch** [comment]
We could also deprecate the old one with a deprecation message that mentions the new lint name, if `register_renamed` doesn't work properly.

**Comment by oli-obk** [comment]
Just a bikeshed now:

I think we need to name it `module_name_repetitions` or `repetition_in_module_names` according to the [naming rules for lints](https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#lints)

**Comment by oli-obk** [comment]
r=me with everyone involved alright with the new name.

**Pull request merged**
