### PR TITLE
Some rustups

### PR DESCRIPTION
**Pull request by JohnTitor**
changelog: none

### CODE REVIEW

**Comment by JohnTitor** [comment]
More rustup is needed, one sec.

**Comment by flip1995** [comment]
@bors r+

Thanks!

**Comment by JohnTitor** [comment]
Hm, I guess rls also needs rustups. Would you mind my skipping it for now?

**Comment by flip1995** [comment]
You can disable it for now. Doesn't seem to be a Clippy issue

**Comment by JohnTitor** [comment]
Sure thing, disabled.

**Pull request merged**
