### PR TITLE
fix: broken GitHub corner

### LINKED ISSUE #11946: Broken GitHub Corner on `Clippy Lints` page
### Summary

There's a broken GitHub corner at https://rust-lang.github.io/rust-clippy/stable/index.html.

### Reproducer

_No response_

### Version

_No response_

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by hamirmahal**
changelog: none

fixes #11946

### CODE REVIEW

**Comment by hamirmahal** [comment]
# Without this change

[Screencast from 12-10-2023 01:38:40 AM.webm](https://github.com/rust-lang/rust-clippy/assets/43425812/dafa249c-bfc3-4834-a2c1-9e6aaf562919)

**Comment by hamirmahal** [comment]
# With this change

[Screencast from 12-10-2023 01:41:08 AM.webm](https://github.com/rust-lang/rust-clippy/assets/43425812/000b3c13-4704-4fa4-8593-4cfaa933d9c7)

**Comment by hamirmahal** [comment]
# Without this change

[Screencast from 12-10-2023 01:38:40 AM.webm](https://github.com/rust-lang/rust-clippy/assets/43425812/dafa249c-bfc3-4834-a2c1-9e6aaf562919)

# With this change

[Screencast from 12-10-2023 01:41:08 AM.webm](https://github.com/rust-lang/rust-clippy/assets/43425812/000b3c13-4704-4fa4-8593-4cfaa933d9c7)

**Review by blyxyas — COMMENTED** [review]
Could you separate the formatting changes from the changes that fix the corner?

**Comment by hamirmahal** [comment]
Sure, I'll take a look now.

**Review by blyxyas — APPROVED** [review]
I haven't checked in a browser to see that it's responsive enough, but the code seems fine (that checking step is pretty crucial, but I'm sure Fred will take care of that) (=^‥^=)

**Comment by xFrednet** [comment]
Hey, I'm sadly busy this week, but I'll be able to review this on the weekend. Sorry for the delay.

**Review by xFrednet — APPROVED** [review]

**Comment by xFrednet** [comment]
Works excellent and the small wave is super cute. Thank you for the update!

@bors r=blyxyas,xFrednet

**Comment by hamirmahal** [comment]
> Works excellent and the small wave is super cute. Thank you for the update!
> 
> @bors r=blyxyas,xFrednet

You're welcome! I'm glad you like it. It's from https://tholman.com/github-corners/.

**Pull request merged**
