### PR TITLE
[`read_line_without_trim`]: detect string literal comparison and `.ends_with()` calls

### PR DESCRIPTION
**Pull request by y21**
This lint now also realizes that a comparison like `s == "foo"` and calls such as `s.ends_with("foo")` will fail if `s` was initialized by a call to `Stdin::read_line` (because of the trailing newline).

changelog: [`read_line_without_trim`]: detect string literal comparison and `.ends_with()` calls

r? @giraffate assigning you because you reviewed #10970 that added this lint, so this is kinda a followup PR ^^

### CODE REVIEW

**Comment by y21** [comment]
wow, this PR is ancient :D

(The first commit is the actual relevant addition, the second one moves some things around which causes the diff to look a bit annoying, so it's probably better reviewed commit-by-commit)

**Review by dswij — APPROVED** [review]
Thanks for this! Sorry that the review take awhile.

Can you help to rebase this? I think it's good to merge afterward.

**Review by dswij — APPROVED** [review]

**Pull request merged**
