### PR TITLE
move lint documentation into macro invocations

### PR DESCRIPTION
**Pull request by euclio**
This PR moves lint documentation inside `declare_clippy_lint!` macro invocations, to avoid triggering the `unused_doc_comments` lint once it's modified in rust-lang/rust#57882. This PR is necessary to unblock that work, since the large number of warnings generated in `clippy_lints` causes Travis to hit the log length limit.

This PR also updates the documentation and website generation script. 

It would be nice to get a clippy update in the Rust repo once this is merged.

cc @phansch

### CODE REVIEW

**Comment by phansch** [comment]
Thanks for the PR! I must admit that I've never really written a lot of macros. Is there any way to keep the documentation before the macro calls and pass the meta items through to `declare_tool_lint!`?
I ask because we currently have [a regex](https://github.com/rust-lang/rust-clippy/blob/master/clippy_dev/src/lib.rs#L13-L26) that parses the `declare_clippy_lints!` calls and the documentation that is before them. If there's no way to pass through the documentation from in front of the macro, then the regex will have to be updated.

Apart from that question, this makes me really happy because it means that the lint documentation is now doc-tested :confetti_ball: 
It looks like a lot of the doc tests are currently failing, which is not really surprising. I would be fine with putting `ignore` on the failing ones for now to get this PR merged.

**Comment by euclio** [comment]
There isn't a way to keep the documentation before the macro calls, since it gets removed when the macro gets expanded.

[I've actually updated the python script already](https://github.com/rust-lang/rust-clippy/pull/3845/files#diff-cf0592f61c08e42896746392a5555189) -- though it probably got lost in this massive diff 😅

I'll push a commit later today to fix the failing doc tests.

**Comment by euclio** [comment]
Ok, should be good to go. I ignored most of the doc tests, but I fixed a few that were trivial to fix.

**Comment by phansch** [comment]
LGTM, thanks again!

@bors r+

**Pull request merged**
