### PR TITLE
Split up `transmute` ui test

### PR DESCRIPTION
**Pull request by JohnTitor**
Part of #2038

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
Is it now possible to add `run-rustfix` to the new test files?

**Comment by flip1995** [comment]
```
$ wc -l tests/ui/*.stderr | sort -nr | head -n 7
 20404 total
   245 tests/ui/needless_range_loop.stderr
   245 tests/ui/match_same_arms.stderr
   235 tests/ui/non_copy_const.stderr
   234 tests/ui/matches.stderr
   220 tests/ui/drop_forget_ref.stderr
   213 tests/ui/indexing_slicing.stderr
   184 tests/ui/doc.stderr
```

Only 7 stderr files have more than 200 lines (hard limit target) now.

You can also reduce the limit to 245 now:
https://github.com/rust-lang/rust-clippy/blob/f7b3e4f29c5360bb8bc7de906c8959178ab43d0b/clippy_dev/src/stderr_length_check.rs#L10

**Comment by JohnTitor** [comment]
> Is it now possible to add `run-rustfix` to the new test files?

We can't do at this point because applicability is unspecified in `transmute_ptr_to_ptr`/`transmute_ptr_to_ref`. But maybe we can do it as follow-up work.

> You can also reduce the limit to 245 now

I think the 200 line limit is in the near future. But if it is appropriate to reduce the limit little by little, I'll do so.

**Comment by flip1995** [comment]
> We can't do at this point because applicability is unspecified

Ah I remember now. Back when I added `Applicability` to every lint, I was to lazy to read all the transmute code to figure out the applicability of these lints :smile: 

So I guess follow up it is :+1: 

> But if it is appropriate to reduce the limit little by little, I'll do so.

I think we should do this, so that we won't get new bigger test files again. Also `@phansch` did this now and then in some of these kind of PRs.

**Comment by JohnTitor** [comment]
> I think we should do this, so that we won't get new bigger test files again.

It's reasonable. Decreased the line length limit.

**Pull request merged**
