### PR TITLE
rustup https://github.com/rust-lang/rust/pull/62964

### PR DESCRIPTION
**Pull request by matthiaskrgr**
changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
cc https://github.com/rust-lang/rust/pull/62943

**Comment by matthiaskrgr** [comment]
rustfmt is broken https://github.com/rust-lang/rustfmt/issues/3703
I temporarily disabled it in CI

**Comment by mikerite** [comment]
You also might need to `#[ignore]` the fmt test.
```
diff --git a/tests/fmt.rs b/tests/fmt.rs
--- a/tests/fmt.rs
+++ b/tests/fmt.rs
@@ -1,4 +1,5 @@
 #[test]
+#[ignore]
 fn fmt() {
     if option_env!("RUSTC_TEST_SUITE").is_some() {
         return;
```

**Comment by matthiaskrgr** [comment]
Done, thanks!

**Comment by flip1995** [comment]
I think travis lost track of this PR. Let's reopen it.

**Comment by matthiaskrgr** [comment]
Hmm, still can't find the corresponding build on travis https://travis-ci.com/rust-lang/rust-clippy/builds/ :confused:

**Comment by matthiaskrgr** [comment]
I probably messed up something in the ci config which fails to parse...

**Pull request merged**
