### PR TITLE
Don't use ExpnKind::descr to get the name of a bang macro.

### PR DESCRIPTION
**Pull request by eddyb**
This is the same change as the first commit in rust-lang/rust#68407, but applied to clippy.
The new code should work both before and after the changes in rust-lang/rust#68407.

changelog: none

### CODE REVIEW

**Comment by eddyb** [comment]
> ERROR: PR body must contain 'changelog: ...'

Huh, how come that's not checked in the PR CI?

**Comment by mati865** [comment]
> Huh, how come that's not checked in the PR CI?

Unfortunately that's not an easy task, you see links in https://github.com/rust-lang/rust-clippy/pull/4211

**Comment by flip1995** [comment]
>Closing this, since
>
>1. Secret env vars don't work on PRs from forks (obv security reasons)
> 2. Pulling the PR body through the github API doesn't work, since we need some kind of API token. And using this API token is (AFAIK) only possible through secrets.

**Comment by eddyb** [comment]
@flip1995 would moving to github actions fully fix this?

**Comment by flip1995** [comment]
Maybe. Depends if the `GITHUB_TOKEN` by GHA is available for forks. I'll try this, once #5088 is merged.

**Pull request merged**
