### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by flip1995**
r? @ghost

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
@matthiaskrgr The CI ICE test stopped working with the latest nightly. I would assume that the `span_delayed_bug_from_inside_query` thing was changed/removed again.

**Comment by flip1995** [comment]
Yes, it is `delayed_bug_from_inside_query` now.

**Comment by matthiaskrgr** [comment]
"There are only two hard things in Computer Science: cache invalidation and naming things."

Pushed an update

**Comment by matthiaskrgr** [comment]
Sent an invite.

**Pull request merged**
