### PR TITLE
Rustup

### PR DESCRIPTION
**Pull request by flip1995**
r? @ghost

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
Huh an ICE in our integration tests? :open_mouth: We didn't have that for a long time. I can't find `clippy` in the backtrace, except for the ICE hook, so this might be on rustc.

**Comment by flip1995** [comment]
Might be this: https://github.com/rust-lang/rust/issues/96175

I also get a similar ICE, when syncing this into the Rust repo and running `./x.py test src/tools/clippy`

Sadly I don't have time to investigate this further today...

**Comment by matthiaskrgr** [comment]
Hmm, this one? https://github.com/rust-lang/rust-clippy/runs/6116665649?check_suite_focus=true#step:7:22
This does not look like 96175 to me tbh.

**Comment by flip1995** [comment]
Damn, it isn't fixed in rustc by now... I sadly don't have the bandwidth to dump that much time into this...

**Comment by matthiaskrgr** [comment]
Hmm, I tried to run `rust-clippy/target/debug/cargo-clippy --all-targets --all-features -- --cap-lints warn -Wclippy::pedantic -Wclippy::nursery`  of the rustup branch a5cc047 on chalk e0ade19d139bc784384acc6736cd960c91dd55a1 but I was not able to reproduce the ice, weird :confused:

**Comment by Alexendoo** [comment]
This one looks to be on rustc, I get the same ICE with `cargo +nightly check --all-targets --all-features`

**Comment by flip1995** [comment]
I played ICE breaker: https://github.com/rust-lang/rust/issues/96638

**Comment by flip1995** [comment]
This ICE should be fixed by now. I'm closing this, since Thursday is already the next sync day.

**Pull request closed without merging**
