### PR TITLE
Rustup `macro expansion and resolution`

### PR DESCRIPTION
**Pull request by lzutao**
Rustup https://github.com/rust-lang/rust/pull/62476

changelog: none

### CODE REVIEW

**Comment by mati865** [comment]
Does anything other than RTIM use nightly toolchain?
It could have been built with stable/beta toolchain.

**Comment by flip1995** [comment]
> Does anything other than RTIM use nightly toolchain?

Yes, we use nightly `rustfmt`, since it is can't reliably be installed on the `master` toolchain.

**Comment by flip1995** [comment]
That won't work either, because of
https://github.com/rust-lang/rust-clippy/blob/032ae968560e78708f40f2fdd5ce95775daec836/ci/base-tests.sh#L27

I think waiting a day is easier, than changing CI for one day.

**Pull request merged**
