### PR TITLE
fulfill expectations in `check_unsafe_derive_deserialize`

### PR DESCRIPTION
**Pull request by B14CK313**
The utility function `clippy_utils::fulfill_or_allowed` is not used because using it would require to move the check for allowed after the check iterating over all inherent impls of the type, doing possibly unnecessary work.
Instead, `is_lint_allowed` is called as before, but additionally, once certain that the lint should be emitted, `span_lint_hir_and_then` is called instead of `span_lint_and_help` to also fulfill expectations.

Note: as this is my first contribution, please feel free to nitpick or request changes. I am happy to adjust the implementation.

fixes: #12802

changelog: fulfill expectations in [`unsafe_derive_deserialize`]

### CODE REVIEW

**Review by y21 — COMMENTED** [review]
This should also ideally have a test to make sure that `#[expect]` now actually works (in `tests/ui/unsafe_derive_serialize.rs`).

**Comment by Manishearth** [comment]
r? @y21 

just got back from my trip and have a large backlog

**Review by y21 — APPROVED** [review]

**Comment by y21** [comment]
Looks good, thanks! @bors r+

--------

If you're interested in a similar followup PR, there's another lint in this file (`DERIVE_PARTIAL_EQ_WITHOUT_EQ`) that also uses `span_lint_and_sugg` and has the same problem as this one here, which is that `#[expect]` has no effect on it ([demo](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=fd5f5eac95b66cb241ebd175ab64d3d8)). Can r? me in the PR if you want to pick that up. If not I'll try to get to that eventually

**Pull request merged**
