### PR TITLE
Refactor: arrange lints in misc_early module

### PR DESCRIPTION
**Pull request by TaKO8Ki**
This PR arranges misc_early lints so that they can be accessed more easily.
Basically, I refactored them following the instruction described in #6680.

cc: @Y-Nak, @flip1995, @magurotuna 

changelog: Move lints in misc_early module into their own modules.

### CODE REVIEW

**Comment by llogiq** [comment]
Thank you!

@bors r+

**Comment by flip1995** [comment]
Thanks for splitting up those lints! This will need a follow up PR though. The main issue with the `misc` and `misc_early` modules was that they combine multiple unrelated lints. Those lints should be integrated in existing other lint passes or get their own lint passes. For example the `MIXED_CASE_HEX_LITERALS` lint would fit into the `literal_representation.rs` module. The end goal would be to get rid of the `misc_early` and `misc` modules completely.

**Comment by TaKO8Ki** [comment]
@flip1995 
Sure! I'm going to open a new issue about that and work on it.

**Comment by flip1995** [comment]
Thanks! If you're unsure about lints, just ask or put them where you see the best fit for them and we can look at it during review.

**Pull request merged**
