### PR TITLE
issue_6357 update unreachable macro usage

### PR DESCRIPTION
**Pull request by rajcspsg**
changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
This message also appears in the lint message. Can you change that too, please?

**Comment by flip1995** [comment]
Thanks, you need to update the reference files of the tests.

**Comment by rajcspsg** [comment]
@flip1995 I updated reference files. I don't know why the tests are still failing. Any idea?

**Comment by flip1995** [comment]
You forgot to commit a line. FYI you can run the `tests/ui/update-all-references.sh`, which automatically updates the files for you.

**Comment by flip1995** [comment]
@bors r+

Thanks!

**Pull request merged**
