### PR TITLE
Switch transmute_ptr_to_ptr to "pedantic" class.

### PR DESCRIPTION
**Pull request by taralx**
Per discussion in https://github.com/rust-lang/rust-clippy/issues/6372, this lint has significant false positives.

changelog: transmute_ptr_to_ptr defaults to "allow".

### CODE REVIEW

**Comment by flip1995** [comment]
Moving this lint to `pedantic` only treats the symptoms, not the cause.

@oli-obk wrote in the issue discussing this lint first:

> You can do `&*(&some_u32 as *const u32 as *const f32)` which conveys the horror of it much better than `transmute(&some_u32)`

I don't think Clippy should suggest more complicated code which should then implicitly suggest to the programmer that what they're doing may be wrong. Either we say that this is just wrong (which it isn't in all cases) or we remove the lint completely. Or better explain why this lint exists.

@oli-obk in https://github.com/rust-lang/rust-clippy/pull/2418#issuecomment-367932636

> We should [...] create a lint for transmuting references to references, because one should be using raw ptr casts in that case.

Why is that?

**Comment by taralx** [comment]
The description on pedantic is that it is for lints that may be incorrect in some cases. That seems to match your complaint above. Have I misunderstood the nature of this category?

**Comment by oli-obk** [comment]
Yea, my opinions have changed since I wrote that. Pedantic sounds right

**Comment by flip1995** [comment]
Ok, SGTM.

@bors r+

Thanks!

**Pull request merged**
