### PR TITLE
[`missing_panics_doc`]: pickup expect method

### LINKED ISSUE #10240: [missing_panics_doc] doesn't trigger on expect
### Summary

Doesn't trigger on `expect`. Noticed when changing from `unwrap` to `expect` to provide a better message, and the lint was suddenly gone.

### Lint Name

missing_panics_doc

### Reproducer

I tried this code:

```rust
#[deny(clippy::missing_panics_doc)]

pub fn last_unwrap(v: &[u32]) -> u32 {
    *v.last().unwrap()
}

pub fn last_expect(v: &[u32]) -> u32 {
    *v.last().expect("passed an empty thing")
}
```

I expected to see this happen: issue error for both `last_unwrap` and `last_expect`.

Instead, this happened:

missing-panics-doc-expect

### Version

```text
rustc 1.67.0 (fc594f156 2023-01-24)
binary: rustc
commit-hash: fc594f15669680fa70d255faec3ca3fb507c3405
commit-date: 2023-01-24
host: x86_64-unknown-linux-gnu
release: 1.67.0
LLVM version: 15.0.6
```

### PR DESCRIPTION
**Pull request by KisaragiEffective**
close #10240 

*Please write a short comment explaining your change (or "none" for internal only changes)*

changelog: [`missing_panics_doc`]: pickup expect method

### CODE REVIEW

**Review by dswij — COMMENTED** [review]
Thanks for the PR! The lint itself looks great. Just a small comment

We have a test for `missing_panics_doc` here https://github.com/rust-lang/rust-clippy/blob/eee3112dc343fc52d2221bffa4d832c9c27df054/tests/ui/missing_panics_doc.rs. Can we extend on that instead of creating a new test file?

**Comment by KisaragiEffective** [comment]
Oh, I didn't notice it; fixed it :)

**Review by dswij — APPROVED** [review]
Looks great, thanks for addressing the comments!

**Pull request merged**
