### PR TITLE
travis: sort integration test jobs so that the jobs taking the most time are run first

### PR DESCRIPTION
**Pull request by matthiaskrgr**
changelog: none

### CODE REVIEW

**Comment by phansch** [comment]
Yeah, since about two weeks the Travis jobs seem to start with some additional delay each. I'm not really sure why :(

@bors r+

**Comment by mati865** [comment]
@phansch Rust recently migrated to newer machines for Travis, IIRC it happened like 3 weeks ago.
cc @pietroalbini

**Comment by pietroalbini** [comment]
Hmm, we didn't yet migrate to faster Travis machines...

**Pull request merged**
