### PR TITLE
[WIP] Add a condition of camel case detection

### LINKED ISSUE #4639: Incomplete postfix detected for `enum_variant_names`
Given this enum (reproduced in its entirety):

```rust
pub(crate) enum IDataRequest {
    PutIData(IData),
    GetIData(IDataAddress),
    DeleteUnpubIData(IDataAddress),
}
```

The error I get is:

```
error: All variants have the same postfix: `Data`
```

It seems to me like the complete, shared postfix should be `IData` instead of `Data`. Maybe the `I` part is too short and doesn't get detected.

### PR DESCRIPTION
**Pull request by chansuke**
Fixes #4639.

I simply added a condition to `camel_case` util to pass `IData` type of word but I'm not sure this is the right approach..

### CODE REVIEW

**Comment by phansch** [comment]
@chansuke Let us know if you need any help =)

**Comment by chansuke** [comment]
@phansch Thanks for your help!! I probably misunderstanding the way to detect the `IData` type of camel case. I simply thought that I could solve the issue by appending a condition to `if c.is_uppercase()` but I think it's wrong. Can you give me any suggestions for an another approach?

**Comment by chansuke** [comment]
@phansch Sorry again, I am trying to detect `IData` with below condition

`if c.is_uppercase() && !s.chars().nth(i - 1).unwrap().is_uppercase() {}` 

but is this a good approach to solve the problem?

**Comment by flip1995** [comment]
Thanks for contributing to Clippy! Sadly this PR was not updated in quite some time. If you waited on input from a reviewer, we're sorry that this fell under the radar. If you want to continue to work on this, just reopen the PR and/or ping a reviewer.

**Comment by HKalbasi** [comment]
finished in #6770
@rustbot label -S-inactive-closed

**Pull request closed without merging**
