### PR TITLE
[DNM] Also install llvm-tools on toolchain setup

### PR DESCRIPTION
**Pull request by flip1995**
Preparation for rust-lang/rust#72000

cc @cuviper @Mark-Simulacrum Is this the correct way to install the llvm-tools with RTIM?

Before merging this, I want to try if llvm-tools are really necessary to compile Clippy. From the rust PR I understood, that it probably will be.

changelog: none

### CODE REVIEW

**Comment by cuviper** [comment]
> Before merging this, I want to try if llvm-tools are really necessary to compile Clippy. From the rust PR I understood, that it probably will be.

Try removing `lib/rustlib/$target/lib/libLLVM*.so` (but leave the one in `lib/`) and then see what happens. I'm guessing you'll get link errors for missing `-lLLVM`.

**Comment by Mark-Simulacrum** [comment]
This looks correct to me.

**Comment by mati865** [comment]
Clippy doesn't use LLVM directly so it should be fine since rustc still works?

**Comment by flip1995** [comment]
Yes there are linking errors. https://github.com/rust-lang/rust-clippy/pull/5632/checks?check_run_id=699500949

But it's `-c llvm-tools` without `preview`.

This is included into #5632

**Pull request closed without merging**
