### PR TITLE
Remove unsafe_vector_initialization lint

### PR DESCRIPTION
**Pull request by dtolnay**
This lint looks for:

```rust
let mut vec = Vec::with_capacity(len);
vec.set_len(len);
```

The suggested replacement is `vec![0; len]`.

This is far too opinionated to be a deny-by-default lint because the performance characteristics of the suggested replacement are totally different.

I am not convinced that this lint has value beyond what deny(unsafe_code) gives you. Unsafe code is unsafe but we should not deny-by-default lint if that's the only reason.

r? collaborators involved in #3365: @flip1995 @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
I think we should only take out the unsafe option, since that is indeed wrong.

Instead of moving the lint to `restriction`, we should fix the lint to not be emitted for `set_len` at all. The other cases are valid.

**Comment by dtolnay** [comment]
I believe unsafe_vector_initialization *only* looks for with_capacity followed by set_len with the same argument value between the two. The other vector initialization lints are under a different lint name.

Would you like me to remove unsafe_vector_initialization entirely?

**Comment by oli-obk** [comment]
Yes, but you also need to register it in https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/lib.rs#L292

**Comment by dtolnay** [comment]
I added unsafe_vector_initialization to deprecated and removed the implementation.

**Comment by oli-obk** [comment]
Thanks!

**Pull request merged**
