### PR TITLE
Remove requirement of fully qualified path for disallowed_method/type

### PR DESCRIPTION
**Pull request by DevinR528**
changelog: Remove the need for fully qualified paths in disallowed_method and disallowed_type

After fixing this issue in [import_rename](https://github.com/rust-lang/rust-clippy/pull/7300#discussion_r650127720) I figured I'd fix it for these two.

If this does in fact fix the **Known problems:** section I was planning to remove them from both lints after confirmation.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
r=me with the known problems sections removed

**Comment by DevinR528** [comment]
Should it be moved out of `nursery`? Or leave it to confirm there are no problems?

**Comment by Manishearth** [comment]
@bors r+

I don't know about removing it from nursery, it honestly feels like a restriction lint to me. @rust-lang/clippy thoughts?

**Comment by camsteffen** [comment]
Moving to restriction SGTM. Probably any lint that only works with config is restriction.

**Pull request merged**
