### PR TITLE
Replace `expr_visitor` with  `for_each_expr`

### PR DESCRIPTION
**Pull request by Jarcho**
This is a minor change which uses `ControlFlow` rather than a boolean. This also runs the visitor rather than returning the visitor, which results in a small readability win as well.

changelog: None

### CODE REVIEW

**Comment by Jarcho** [comment]
Great. The compiler broke...

**Comment by flip1995** [comment]
LGTM. Will merge after the next sync.

**Comment by flip1995** [comment]
Huh. Forgot about it. Can you rebase and then r+ yourself, if CI passes?

**Comment by Jarcho** [comment]
Looks like this is still broken. rust-lang/rust#101410 is a possible fix.

**Comment by Jarcho** [comment]
Narrowed the issue down to something with let-chains mir opt levels. Pretty good match with rust-lang/#99852. Just added a workaround until the rustc bug is fixed.

@bors r+

**Pull request merged**
