### PR TITLE
Move conf.rs back into clippy_lints

### PR DESCRIPTION
**Pull request by smoelius**
This is an alternative solution to #6785 to fix the CI break caused by #6756.

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
@bors r+

I'll approve this and hope that it fixes the deploy workflow. If not, I'll go and investigate further this evening.

**Comment by flip1995** [comment]
cc @matthiaskrgr ^

**Comment by flip1995** [comment]
Hm dogfood is failing on Mac :thinking:

**Comment by smoelius** [comment]
FWIW, the dogfood tests pass for me locally on a Mac.

Also, you probably noticed this, but it's failing with "signal: 9".

**Comment by flip1995** [comment]
Didn't notice, Just skimmed the logs. So probably spurious.

Let's try again @bors retry

**Pull request merged**
