### PR TITLE
Fix: Use multipart_suggestion for derivable_impls

### PR DESCRIPTION
**Pull request by scottgerring**
This should address  #13099 for the `derivable_impls` test. As I've not contributed to clippy before, I'd like to make sure i'm on the right track before doing more :) 

changelog: [`derivable_impls`]: Use multipart_suggestion to aggregate feedback

### CODE REVIEW

**Review by samueltardieu — APPROVED** [review]
Nice!

**Comment by scottgerring** [comment]
Hey @samueltardieu , thanks for taking a look!
Do I need to do anything else to kick this along now - ?

**Review by flip1995 — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
