### PR TITLE
Update ui stderr with improved rustc output

### PR DESCRIPTION
**Pull request by mikerite**
Related rust pull request: rust-lang/rust#76160

changelog: none

### CODE REVIEW

**Comment by scileo** [comment]
I'm the author of rust-lang/rust#76160. This is my second non-doc contribution to rust, and I lack experience in OSS in general.

Was I supposed to open such PR myself?

**Comment by ebroto** [comment]
@scileo not necessarily :)

When changes in rustc break Clippy, the in-tree version of Clippy must be fixed, and you already did that :+1: 
Syncing back those changes to this repo is Clippy's responsibility and can be done by anyone, see [CONTRIBUTING.md](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md#fixing-build-failures-caused-by-rust).

**Comment by scileo** [comment]
@ebroto thank you for your explanations. Next time I'll open it a PR there too :)

**Pull request merged**
