### PR TITLE
Downgrade needless_pass_by_value to allow by default

### PR DESCRIPTION
**Pull request by dtolnay**
I noticed that I suppress this lint in many of my projects.

https://github.com/search?q=needless_pass_by_value+user%3Adtolnay+user%3Aserde-rs&type=Code

Upon further inspection, this lint has a *long* history of false positives:

- https://github.com/rust-lang-nursery/rust-clippy/issues/1844
- https://github.com/rust-lang-nursery/rust-clippy/issues/1876
- https://github.com/rust-lang-nursery/rust-clippy/issues/1939
- https://github.com/rust-lang-nursery/rust-clippy/issues/2114
- https://github.com/rust-lang-nursery/rust-clippy/pull/2117
- https://github.com/rust-lang-nursery/rust-clippy/issues/2208
- https://github.com/rust-lang-nursery/rust-clippy/issues/2222
- https://github.com/rust-lang-nursery/rust-clippy/issues/2357

And several false positives outstanding:

- https://github.com/rust-lang-nursery/rust-clippy/issues/2434
- https://github.com/rust-lang-nursery/rust-clippy/issues/3067
- https://github.com/rust-lang-nursery/rust-clippy/issues/3420

Generally I feel that this lint is the definition of pedantic and should not be linted by default.

```rust
#[derive(Debug)]
enum How {
    ThisWay,
    ThatWay,
}

// Are we really better off forcing the call sites to write f(&_)...?
fn f(how: How) {
    println!("You want to do it {:?}", how);
}

fn main() {
    f(How::ThatWay);
}
```

@birkenfeld @mitsuhiko

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I'm very much in favour of this. Can we have this @birkenfeld? :)

**Comment by dtolnay** [comment]
AppVeyor failure appears unrelated.

**Comment by oli-obk** [comment]
Restarting appveyor

**Comment by dtolnay** [comment]
@oli-obk I clicked the "Re-build PR" button in AppVeyor and it built successfully:
https://ci.appveyor.com/project/rust-lang-libs/rust-clippy/builds/20521715

**Pull request merged**
