### PR TITLE
Migrate `dbg_macro` to late pass

### LINKED ISSUE #7274: dbg_macro does not catch invocation inside macro
Lint name: dbg_macro

I tried this code:

```rust
pub fn main() {
    // dbg!(1);
    MyThing.foo();
}

trait Thing<'b> {
    fn foo(&self);
}

macro_rules! define_thing {
    ($thing:ident, $body:expr) => {
        impl<'a> Thing<'a> for $thing {
            fn foo<'b>(&self) {
                $body
            }
        }
    };
}

struct MyThing;
define_thing!(MyThing, {
    dbg!(2);
});
```

I expected to see (by enabling `clippy::dbg_macro`) a full-throated rejection of that `dbg!(2)` macro invocation, something like:

```text
$ cargo clippy -- -F clippy::dbg_macro
...
error: `dbg!` macro is intended as a debugging tool
 --> src/main.rs:22:5
  |
22|     dbg!(2);
  |     ^^^^^^^
  |
  = note: requested on the command line with `-F clippy::dbg-macro`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#dbg_macro
```

... like I do get for the `dbg!(1);` invocation if I uncomment that.

Instead, I get no clippy warnings/errors.

### Meta

- `cargo clippy -V`: clippy 0.1.52 (9bc8c42b 2021-05-09)
- `rustc -Vv`:
  ```
  rustc 1.52.1 (9bc8c42bb 2021-05-09)
  binary: rustc
  commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
  commit-date: 2021-05-09
  host: x86_64-apple-darwin
  release: 1.52.1
  LLVM version: 12.0.0
  ```

### LINKED ISSUE #7275: dbg_macro not caught when in submodule
Lint name: dbg_macro

I tried this code:

```rust
// src/main.rs
#![deny(warnings)]
#![deny(clippy::dbg_macro)]

mod sub;

fn main() {
    sub::func();
}


// src/sub.rs
pub fn func() {
    dbg!(10);
}

```

I expected the dbg! macro to be caught when running `cargo clippy`.

Instead, the lint does not trigger, and clippy finishes successfully.

The surprising bit (perhaps connected to #4612 ?) is when running clippy after forcefully touching the file (e.g. `find . -name "*.rs" -exec touch {}`), clippy catches it just fine 🤷 

### Meta

- `cargo clippy -V`: clippy 0.1.52 (9bc8c42b 2021-05-09)
- `rustc -Vv`:
  ```
  rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-apple-darwin
release: 1.52.1
LLVM version: 12.0.0
  ```

### PR DESCRIPTION
**Pull request by Alexendoo**
changelog: Make `dbg_macro` work with crate level attributes and inside macro calls

One down for #6610, fixes #7275

Also fixes #7274, and adds parenthesis around the suggestion for `dbg!(1, 2, 3)` as it expands to a tuple

### CODE REVIEW

**Comment by flip1995** [comment]
Awesome, thank you! 2 pre-expansion passes to go :tada: 

@bors r+

**Comment by smoelius** [comment]
@flip1995

> Awesome, thank you! 2 pre-expansion passes to go tada

Is there an effort to eliminate pre-expansion pass lints? Can I ask why?

**Comment by giraffate** [comment]
> Is there an effort to eliminate pre-expansion pass lints? Can I ask why?

FYI: https://github.com/rust-lang/rust-clippy/pull/5518

**Comment by smoelius** [comment]
Thanks, @giraffate. :)

**Pull request merged**
