### PR TITLE
Fix async functions handling for `needless_pass_by_ref_mut` lint

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust-clippy/issues/11179.

The problem with async is that "internals" are actually inside a closure from the `ExprUseVisitor` point of view, meaning we need to actually run the check on the closures' body as well.

changelog: none

r? @llogiq

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Fixed the failing lints on my code changes. ^^'

**Comment by llogiq** [comment]
Thank you!

@bors r+

**Comment by GuillaumeGomez** [comment]
It failed because of the commit format. I added `changelog: none` to the first comment of the PR. Hopefully it should fix the issue?

**Pull request merged**
