### PR TITLE
Remove clippy plugin

### PR DESCRIPTION
**Pull request by msizanoen1**
This PR removes the clippy plugin, which is already deprecated and is causing the `fmt_macros` not found error in rust-lang/rust#62558: https://github.com/rust-lang/rust/issues/62558#issuecomment-529884322

changelog: remove plugin interface

### CODE REVIEW

**Comment by flip1995** [comment]
This won't remove the `fmt_macros` dependence? Also we didn't decide on how / when to remove the Clippy plugin interface. I think just nuking it is ok though, since the warning existed for a long time. cc #2783 

ping @rust-lang/clippy thoughts on this?

**Comment by flip1995** [comment]
Maybe this is better done in combination with #4650

**Comment by msizanoen1** [comment]
The error happens because clippy_lints was compiled for the host but fmt_macros is only available for the target. Plugins are compiled for the host so removing the plugin should fix the error.

**Comment by flip1995** [comment]
Ah ok, thanks for the clarification!

**Comment by Manishearth** [comment]
We should definitely just remove it, yeah

**Comment by flip1995** [comment]
I opened rust-lang/blog.rust-lang.org#435 for this. Feedback welcome.

**Comment by msizanoen1** [comment]
Now with https://github.com/rust-lang/rust/pull/65698 merged, this PR is the only remaining roadblock for https://github.com/rust-lang/rust/issues/62558

**Comment by Manishearth** [comment]
@bors r+

https://blog.rust-lang.org/inside-rust/2019/11/04/Clippy-removes-plugin-interface.html

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust-clippy/pull/4770

**Comment by lzutao** [comment]
This can be merged.
@bors r=Manishearth

**Pull request merged**
