### PR TITLE
Rustup to latest rustc master

### PR DESCRIPTION
**Pull request by phansch**
Broken due to:

* https://github.com/rust-lang/rust/pull/63180 (`Existential` -> `OpaqueTy`)
* https://github.com/rust-lang/rust/pull/63121 (New fields for `FormatSpec`)

changelog: none

### CODE REVIEW

**Comment by mikerite** [comment]
In `appveyor.yml`, Try replacing 
```
    - rustup component add rustfmt --toolchain nightly || echo "rustfmt nightly is unavailable"
```
with 
```
    - rustup component add rustfmt --toolchain nightly & exit 0
```
It looks like that is the correct way to ignore if a command fails.
https://help.appveyor.com/discussions/questions/752-how-to-ignore-exit-codes-of-a-cmd

The format test should be able to handle rustfmt being missing.

**Comment by phansch** [comment]
Thanks, let's see if that works!

@bors r+

**Pull request merged**
