### PR TITLE
Don't lint blocks in closures for blocks_in_conditions

### PR DESCRIPTION
**Pull request by Alexendoo**
Seemed like an outlier for the lint which generally caught only the syntactically confusing cases, it lints blocks in closures but excludes closures passed to iterator methods, this changes it to ignore closures in general

changelog: none

### CODE REVIEW

**Comment by y21** [comment]
I think this also basically (indirectly) fixes #12281 , right? Last time I looked into that issue it gets to the code that's deleted here because `#[tracing::instrument]` has `match async move { ... } {}` expansions that desugar to closures

**Comment by Alexendoo** [comment]
Yeah looks like it, there's also an extra context check for the main part of the lint that wasn't checked for the closure checking

**Comment by Alexendoo** [comment]
Testing for https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Windows.20CI.20failing

@bors try

**Review by dswij — APPROVED** [review]
Sweet, thanks!

**Pull request merged**
