### PR TITLE
Fix breakage due to rust-lang/rust#61856

### PR DESCRIPTION
**Pull request by mikerite**
changelog: none

### CODE REVIEW

**Comment by mikerite** [comment]
It looks like rust-lang/rust#61856 broke Map::is_argument(..). Part of this fix should be reverted when that gets fixed. Also, I expected the dogfood test to warn for ` single_match_else` in the `is_arguments` function. Maybe it's a false negative or we're not checking for pedantic lints.

**Comment by flip1995** [comment]
We check for `pedantic` lints in dogfood, and this should trigger the lint, weird...
https://github.com/rust-lang/rust-clippy/blob/dc69a5c0b610df452217291db1a0ebc4f76401e3/tests/dogfood.rs#L21

@bors r+ p=1

**Pull request merged**
