### PR TITLE
Update Changelog

### PR DESCRIPTION
**Pull request by flip1995**
[Rendered](https://github.com/flip1995/rust-clippy/blob/changelog/CHANGELOG.md)

changelog: none

### CODE REVIEW

**Comment by llogiq** [comment]
Thank you! This is going to be a good release. Should we add notes for the 1.58.1 release, too?

**Comment by matthiaskrgr** [comment]
Just a side note: I wonder if we should also inform about the lints default severity (deny, warn, allow..) so that people can see at a glance "ah, this will lint by default on my crate" or "I'll have to enable this one manually if I'm interested".

**Comment by flip1995** [comment]
I added the changes of `1.58.1` as a subsection of `1.58`. 

I also added comments about the updated lint severity.

**Comment by llogiq** [comment]
Thank you! @bors r+

**Pull request merged**
