### PR TITLE
[experimental] ci: bootstrap from beta instead of nightly

### PR DESCRIPTION
**Pull request by matthiaskrgr**
A lot of nighties have been missing lately, so I hope this is a bit more stable?

Let's see how this works out.

Currently we rely on rustfmt nightly for formatting, this would make us switch to beta I supposed (maybe we can work around?)

### CODE REVIEW

**Comment by Manishearth** [comment]
when a nightly is missing it just falls back to the previous nightly, no?

**Comment by matthiaskrgr** [comment]
Nope.

**Comment by matthiaskrgr** [comment]
It would be great to have some kind of tool-aware automatic rollback but it doesn't look like anyone is working on that https://github.com/rust-lang/rustup.rs/issues/1501

**Comment by mati865** [comment]
It'd be bad when somebody who ran nightly rustfmt got CI errors because beta formatting differs.

**Comment by mati865** [comment]
CI error: https://github.com/rust-lang/rust/issues/57488

**Comment by phansch** [comment]
Next time we could also temporarily fallback to the latest working nightly like cargo did: https://github.com/rust-lang/cargo/pull/6530/commits/5576372d3833f72ff4db865ece7b8acdbade2911

**Pull request closed without merging**
