### PR TITLE
Suggest `is_some_and` for `map(<f>).unwrap_or(false)`

### PR DESCRIPTION
**Pull request by TheCodingWombat**
This is my first PR and contribution to Clippy.

changelog: `map_unwrap_or`: Added suggesting `is_some_and` when pattern `Option.map(<f>).unwrap_or(false)` occurs.

This is a first step in fixing all suggestions in issue #9125.

### CODE REVIEW

**Comment by TheCodingWombat** [comment]
I had help from @xFrednet in getting started with conributing to Clippy

**Comment by xFrednet** [comment]
Hey, awesome to see a PR for this!

I've just noticed that this suggestion requires the `is_some_and` feature. This is totally fine, but the documentation should clearly state that and the suggestion should only be made if the feature is enabled.

Usually, we use `cx.tcx.sess.features_untracked().<featur-name>` to check if a feature is enabled, but I can't find there [`rustc_feature::Features`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_feature/struct.Features.html). I've ask on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Check.20if.20a.20library.20feature.20is.20enabled.20rust-clippy.2310102/near/316850568) so see if the others know :)

r? @xFrednet

**Comment by Niki4tap** [comment]
Coming back from zulip, the code you are looking for to check for a library feature is:
```rust
cx
    .tcx
    .sess
    .features_untracked()
    .declared_lib_features
    .iter()
    .any(|(name, _span)| name.as_str() == "is_some_and")
```

**Comment by TheCodingWombat** [comment]
@xFrednet  Check! Sounds useful to learn how to do that. Will do soon (tm).

**Comment by xFrednet** [comment]
I'll mark this as waiting on author. GitHub will notify me when there are any updates. Enjoy the festive season!

@rustbot author

**Comment by xFrednet** [comment]
Hey @TheCodingWombat, this is a small ping from triage. Do you think you'll have time to continue this PR? :upside_down_face:

**Comment by xFrednet** [comment]
Hey, I will closes this PR due to inactivity. This was already a very good start and I will link it in the issue for further development. If you have the time, @TheCodingWombat you're more than welcome to pick the issue up again. Thank you for the work you did in this PR :)

**Pull request closed without merging**
