### PR TITLE
build: avoid timing out in Travis

### PR DESCRIPTION
**Pull request by lzutao**
cc #4770 
changelog: none

### CODE REVIEW

**Comment by Manishearth** [comment]
Can you include the other PR that disables the stdsimd test? We can't land this without both

**Comment by lzutao** [comment]
Done.

**Comment by lzutao** [comment]
The build didn't start
@bors r-

**Comment by lzutao** [comment]
Hmm, it's building now: https://travis-ci.com/rust-lang/rust-clippy/builds/135085299

**Comment by ecstatic-morse** [comment]
@lzutao rust-lang/rust#66016 should now be fixed on the latest nightly.

**Comment by mati865** [comment]
@ecstatic-morse indeed, stdsimd test was re-enabled by https://github.com/rust-lang/rust-clippy/pull/4777.

**Pull request merged**
