### PR TITLE
Fix all occurences `needless_borrow` internally

### PR DESCRIPTION
**Pull request by Jarcho**
The bug that got 'needless_borrow' moved into the nursery was fixed two years ago in d4370f8b.

This did trigger over a thousand times internally, so that's all the other changes. I vetted most of them, but there's a lot The only interesting change is to the lint list. `declare_tool_lint` already makes a reference, so there's no need to take a reference to the lints.

changelog: None

### CODE REVIEW

**Comment by phansch** [comment]
@Jarcho Did you happen to run `lintcheck` to see if there were any false positives or similar amounts of triggers?

I'm currently a bit hesitant to merge this because it caused so many changes in our codebase alone.

**Comment by Jarcho** [comment]
Not bad overall

- rayon: 7
- regex: 1
- ripgrep: 2
- syn: 1
- tam-oidc: 3
- xsv: 3

Pretty much every instance in clippy is from taking a reference to a HIR node. Those are mostly all references to start with.

**Review by flip1995 — COMMENTED** [review]
The changes LGTM and I would merge them like this after a rebase.

But I would do the actual move of the lint in another PR. This PR should then add tests for the remaining [open issues about this lint](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+is%3Aopen+needless_borrow) to verify that they're fixed or to at least know the state this lint is in.

**Comment by flip1995** [comment]
This is a great code cleanup btw! Thanks for all the work you put into this!

**Comment by Jarcho** [comment]
I'll pull out the category change when I rebase it. There's still the bad suggestion with pattern references to deal with. The rest of those are just enhancements.

**Comment by flip1995** [comment]
@Jarcho Sorry that we missed your rebase. Please self-approve this after rebasing again.

@bors delegate+ p=10

**Comment by flip1995** [comment]
@bors r=phansch,flip1995

Thanks!

**Comment by Jarcho** [comment]
Looks like you got to it before me.

**Pull request merged**
