### PR TITLE
Don't warn about modulo arithmetic when comparing to zero

### LINKED ISSUE #12006: `modulo_arithmetic` should not trigger if result is only checked to be zero or non-zero
### Summary

A common usage of `%` is to check exact divisibility, and I believe `%` and `rem_euclid` output `0` for exactly the same set of inputs. So `a % b == 0` or `a % b != 0` should not trigger the lint.

### Lint Name

modulo_arithmetic

### Reproducer

I tried this code:

```rust
let x = 12_isize;
let y = -4_isize;
if x % y == 0{
    println!("{x} is divisible by {y}");
}
```

I saw this happen: The lint `modulo_arithmetic` triggers and suggests using `rem_euclid`.

I expected to see this happen: Nothing.

### Version

```text
rustc 1.74.1 (a28077b28 2023-12-04)
binary: rustc
commit-hash: a28077b28a02b92985b3a3faecf92813155f1ea1
commit-date: 2023-12-04
host: x86_64-unknown-linux-gnu
release: 1.74.1
LLVM version: 17.0.4
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by mdm**
closes #12006 

By default, don't warn about modulo arithmetic when comparing to zero. This behavior is configurable via `clippy.toml`.

See discussion [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/.E2.9C.94.20Is.20issue.20.2312006.20worth.20implementing.3F)

changelog: [`modulo_arithmetic`]: By default don't lint when comparing the result of a modulo operation to zero.

### CODE REVIEW

**Comment by llogiq** [comment]
Thank you, r=me after a rebase.

**Comment by mdm** [comment]
@llogiq I rebased. Is there anything else you need me to do? Sorry if I missed something obvious. I'm a new contributor.

**Comment by llogiq** [comment]
Thank you! Sorry for the delay.

@bors r+

**Comment by llogiq** [comment]
@bors retry

Seems the Mac runner is acting up again

**Pull request merged**
