### PR TITLE
Fix ICE on `unsound_collection_transmute`

### LINKED ISSUE #4968: Clippy ICE: normalize_erasing_regions: could not fully normalize `<Trait>::Assoc`
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cdb7bc71b2a8f4b52bc6c239ea1965df)

```rust
trait Trait {
    type Assoc;
}

use std::{
    mem::{self, ManuallyDrop},
};

#[allow(unused)]
fn func<T: Trait>(slice: Vec<T::Assoc>) {
    unsafe {
        let _: Vec<ManuallyDrop<T::Assoc>> = mem::transmute(slice);
    }
}
```

This ICEs with `cargo clippy` but not with `cargo build` or `cargo check`.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #4968

Check if `Ty`s are normalizable. It might show hidden false negative, I'm not sure.
Also, the regression tests are placed on two dirs, so move them to `/crashes`. I think it will be easier to find the right place.

changelog: Fix ICE on `unsound_collection_transmute`

### CODE REVIEW

**Comment by flip1995** [comment]
Thanks for moving the tests, I also wanted to do this recently.

Maybe we should put the `is_normalizable` in a `utils` function, in case we'll need it sometimes in the future.

**Comment by JohnTitor** [comment]
> Maybe we should put the is_normalizable in a utils function, in case we'll need it sometimes in the future.

It's reasonable, moved into `utils`.

**Comment by phansch** [comment]
Huh, never saw this before. `rustfmt` fails:

```
error: couldn't read \\?\C:\projects\rust-clippy\tests\ui\crashes\..\auxiliary\use_self_macro.rs: The filename, directory name, or volume label syntax is incorrect. (os error 123)
 --> \\?\C:\projects\rust-clippy\tests\ui\crashes\ice-4671.rs:5:5
  |
5 | mod use_self_macro;
  |     ^^^^^^^^^^^^^^
rustfmt failed on C:\projects\rust-clippy\tests\ui\crashes\ice-4671.rs
```

Maybe move the auxiliary file into `crashes`, too?

**Comment by JohnTitor** [comment]
Oh, it seems so, moved it.

**Pull request merged**
