### PR TITLE
Fix example `SELF_ASSIGNMENT`

### PR DESCRIPTION
**Pull request by alex-semenyuk**
changelog: Fix example in `SELF_ASSIGNMENT` docs

### CODE REVIEW

**Comment by llogiq** [comment]
Thank you! @bors r+

**Comment by llogiq** [comment]
Oops. This may have been due to my having r+ed multiple PRs in short order. Sorry, but you'll have to rebase.

**Comment by alex-semenyuk** [comment]
@llogiq done

**Comment by llogiq** [comment]
Rebasing onto #9055 might help.

**Comment by alex-semenyuk** [comment]
@llogiq rebased

**Comment by xFrednet** [comment]
The changelog text has to be on the same line, as the `changelog` entry. I've fixed that now

@bors retry

**Pull request merged**
