### PR TITLE
Added restriction lint: pattern-type-mismatch

### PR DESCRIPTION
**Pull request by phaylon**
changelog: Added a new restriction lint `pattern-type-mismatch`. This lint is especially helpful for beginners learning about the magic behind pattern matching. (This explanation might be worth to include in the next changelog.)

### CODE REVIEW

**Comment by phaylon** [comment]
Hello,

I'd like to propose a new off-by-default restriction lint called `pattern-type-mismatch`.

# Description

The purpose of the lint is to enforce that patterns accurately represent the types they
are applied to.

As far as I'm aware, this would currently only be triggered when default binding modes
are in effect for a particular pattern. Although it is possible that this should include
some future developments, like patterns applying transparently through `Deref` implementations.

I have avoided mentioning default binding modes in the name and the description. Due to past
controversies I felt it would be benficial to stay away from the specific feature, and focus
on the actual guarantees the lint is supposed to provide. I hope that `pattern-type-mismatch`
is a good name to achieve that goal.

By going this route, it should be easy for people who are looking for these guarantees to
find them. Yet, since default binding modes aren't mentioned, noone should be inclined to
activate the lint simply because they vaguely remember past discussions.

# Motivation

The lint allows enforcing the following code properties:

* All pattern specifications reflect the actual types they are applied to, and give some
  hints of the ownership, mutability, and drop semantics of the specified types and their
  contents.
* Bindings for values that aren't moved or copied are explicitly bound via
  `ref` and `ref mut`. This explicitly communicates their mutability which can help
  during refactoring and review.
* Code can be made less adaptive to API changes. This includes things like dropping
  of values, side effects of modifications, and switching between shared and mutable
  access.

# Details

The lint would guard the following language constructs:

* `let`
* `match`
* `if let`
* `while let`
* `for`
* function signatures and closure parameter specifications

The suggestion to the user takes the following form:

* It highlights the pattern that doesn't exactly match the type.
* It suggests using `&_` and `&mut _` in the patterns and to adjust the resulting bindings.
* It will begin the hint with suggesting dereferencing the matched expression with `*` if
  the syntax construct allows it, as per the default idiomatic style.

# cargo fix

On the surface, it seems like this should be automatable. Some of the bindings would stay
as they are copied. Others would have to be modified to include `ref` or `ref mut` as necessary
by other code. I assume this would be hard to make reliable.

I'm also of the opinion that since one purpose of the lint is to give ownership hints in matched
structures, the hinted code should be reevaluated. For example, usage of `ref` instead of `ref mut`
bindings, and mutation based operations can be evaluted. I would see the potential for this
reevaluation as a further purpose of the lint by itself.

Given that, I would argue that this should not be automatically fixed. 

# Some Questions

As this is my first lint, I'm unsure about a few things:

* Is `cx.tables.liberated_fn_sigs()` the right way to get to a functions effective signature?
* Am I using `is_external_macro` correctly?

I'm sure there are other things I'll need to fix as well.

The implementation works by recursing through the involved types and patterns, and looking
for `&` and `&mut` types that don't have corresponding patterns. I think there shouldn't be
false positives due to how this works. I've been wondering though: Is there a good way to
run a clippy checkout against some other unrelated codebase without interfering with the
`rustup` version?

**Comment by phaylon** [comment]
It seems CI fails because the `.stderr` file I committed has 278 lines, but there is a 275 limit. The bigger number of lines comes from testing the different syntax constructs that involve patterns.

I'm unsure how to proceed.

**Comment by phaylon** [comment]
I upped the STDERR limit to a round 300 for now.

I'm having trouble understanding the new failures though. It seems some `ui` tests failed even though they are untouched by this PR. I managed to replicate them locally once, but after some branch switching for comparison and rerunning it seems they disappeared (I did a `cargo clean` run).

**Comment by flip1995** [comment]
The additional failures are addressed in #4846. Don't worry about them.

For the limit of the stderr files: We want to bring the limit even further down: #2038. You can create a new dir and split up the tests in multiple files.

**Comment by flip1995** [comment]
> Is there a good way to run a clippy checkout against some other unrelated codebase without interfering with the rustup version?

```bash
$ cargo +master install --force --debug --path .
# checkout a crate and `cd <crate>`
$ LD_LIBRARY_PATH=$(rustc +master --print=sysroot)/lib cargo clippy
```

**Comment by phaylon** [comment]
@flip1995 Very helpful, thank you!

I'll have a go at splitting up the STDERR files and reset the limit down to 275.

**Comment by flip1995** [comment]
> I'll have a go at splitting up the STDERR files and reset the limit down to 275.

That would be great. I think a good split would be in the different syntax constructs. Make sure to add tests that _should_ trigger the lint **and** tests that _shouldn't_ trigger it.

**Comment by phaylon** [comment]
I've split up the test file into a subdirectory. I tried to use the opportunity to reorganize the tests themselves to be a bit more easy to follow.

The different kinds of syntaxes are actually now in one file, as the tests there can be rather simple. Instead, I've split it up the different pattern constructs (structs, tuples, alternatives). That's the complex part of the actual lint I feel, and has more variation due to the different forms types can have.

I also removed some probably redundant tests (functions vs associated functions) that I had added more for the purpose of discovering the compiler's API and ensuring my assumptions hold.

**Comment by phaylon** [comment]
A procedural question: Should I keep rebasing the PR or would the forced pushes interfere with reviewing?

**Comment by flip1995** [comment]
You can keep rebasing it. It doesn't make a difference for reviewing. So once I get to reviewing this I can ping you, so you don't have to rebase every other day.

**Comment by phaylon** [comment]
Squashed, rebased and caught up with recent changes in master.

**Comment by phaylon** [comment]
Pushed some changes to catch up to master. There are still some errors when trying to compile, but since they're coming from another lint I assume this is a clippy/nightly divergence issue.

**Comment by phaylon** [comment]
@flip1995 Apologies for taking a while.

I can see where the expanded diagnostic including bindings can be useful. I think expanding it for nested patterns or those with many bindings might make things less clear. There are advantages to the extra information when the lint is used as a teaching utility, but outside of that it would potentially be a very long version of a type mismatch error.

Do you have a preference as to how the diagnostic should look for the cases where bindings aren't mentioned? Should it just stay the way it currently is implemented for those?

**Comment by flip1995** [comment]
> Do you have a preference as to how the diagnostic should look for the cases where bindings aren't mentioned?

Maybe add a configuration option for this lint: `pattern-type-mismatch-verbose`. If this is set, for every binding a suggestion is made. If this is not set output something like

```
   = help: ...and adjust the enclosed variable bindings
   = note: for suggestions on how to do this set the configuration `pattern-type-mismatch-verbose = true`
```

Without the configuration set, this help message should be span-less or you can just point at bindings like this:
```
   = help: ...and adjust the enclosed variable bindings
   |
LL |         ManyBindings(x, y, z) => (),
   |                      ^^^^^^^
   = note: for suggestions on how to do this set the configuration `pattern-type-mismatch-verbose = true`
```

**Comment by flip1995** [comment]
As I said above, the recursive suggestion for all bindings might be too hard to implement for a fist version and we can add the configuration option and inner binding suggestions later.

**Comment by flip1995** [comment]
Thanks for contributing to Clippy! Sadly this PR was not updated in quite some time. If you waited on input from a reviewer, we're sorry that this fell under the radar. If you want to continue to work on this, just reopen the PR and/or ping a reviewer.

**Comment by phaylon** [comment]
@flip1995 Hello! Apologies for the siilence. I am still working on the PR, but it is taking me a bit.

Would it be best to simply open a new PR referencing this one when I manage to finish it up?

**Comment by flip1995** [comment]
Thanks for responding! In that case, I'll reopen this PR. If you need help with something, feel free to ask.

**Comment by flip1995** [comment]
ping from triage @phaylon. Do you have any questions on how to proceed with this PR? IIRC the only thing left would be to improve the suggestion behavior. Can I help you with that?

**Comment by phaylon** [comment]
@flip1995 My main issue is landing on a nightly that will build with master and my changes. Is there any trick to that?

It technically needs only the diagnostics changes, but I also need to catch up with changes to nightly (I have `rustc::` errors en masse). Figuring out how those should be changed, and doing changes and test runs takes me at least one day, and I need to try that on a day when I manage to compile :)

I'll have a go this week, but after a rebase I get 726 lines of errors I have to get through currently :)

It might be worth to just start over with a fresh branch off master at this point.

**Comment by flip1995** [comment]
@phaylon I rebased this branch for you, so you can comfortably continue you're work here, once you come back.

This should now build with tomorrows nightly (`nightly-2020-06-09`).

**Comment by phaylon** [comment]
@flip1995 Thank you! :D

**Comment by flip1995** [comment]
The Clippy master always compiles with the master toolchain (well, except when a rustup is necessary), which you can get through the `setup-toolchain.sh` script.

**Comment by phaylon** [comment]
@flip1995 Giving it a go now, I ran into one small issue with emitting the discussed diagnostics. I'm not quite sure how I'd go about taking (for example) a `match expr {` piece of code and add a `*` in front of that `expr` for the suggestion, given I'll have to manage to do that for every kind of place where a pattern might show up, including `let` statements.

I'll also have to do that for prefixing the patterns with `&`, of course. Which is potential even more places (like function and closure signatures).

**Comment by flip1995** [comment]
Not sure, if I understood you correctly. You can take the span of this `expr` and then add a `db.span_suggestion(expr.span, format!("*{}", snippet(expr.span))`.

If you have to do this in multiple places you can use `db.multipart_suggestion`

**Comment by phaylon** [comment]
@flip1995 Yes, that was the right thing, thank you!

I did however run into one issue, and I'm no longer sure there will be any teachability advantage here given how imprecise the diagnostics would have to be:

For example, linting against a simple expression like:

```
for (_a, _b) in slice.iter() {}
```

I can produce the error:

```
error: type of pattern does not match the expression type
  --> $DIR/syntax.rs:59:9
   |
LL |     for (_a, _b) in slice.iter() {}
   |         ^^^^^^^^
   |
help: explicitly match against a `&_` pattern
   |
LL |     for &(_a, _b) in slice.iter() {}
   |         ^^^^^^^^^
help: ...and adjust your bindings with `ref` as needed
   |
LL |     for (ref _a, ref _b) in slice.iter() {}

```
But that has a variety of issues:

* The glaring one is that the two suggestions are separate. None of them by themselves are correct. And to get to a more correct place, I'd have to deparse and adjust all kinds of places where patterns show up, which is a lot.
* Deciding if a binding should become `ref` or `ref mut` would require complex analysis of later usage. I'd have to rediscover exactly the kind of details that default binding modes hides.
* I'd like to add a limit to the amount of bindings that are highlighted, which leaves the other ones unhighlighted.

So I'm a bit uncertain how it makes sense to proceed to get the suggestions to a helpful place. I'm just not sure how a newcomer would be helped by shallow, partially vague, and probably at least somewhat incorrect suggestions for code adjustments.

**Comment by flip1995** [comment]
Hm yeah, I see the problem. You thought about this way more than I have, so I would suggest that you implement the suggestion as you think is the way, that adds the most value to the lint.

In addition to that it would then probably help most, to add examples like the tuple-in-for-loop with an explanation to the documentation.

**Comment by phaylon** [comment]
@flip1995 Yeah, I do agree that there is a usecase for having the information itself, certainly.

I feel like there's two usecases that clash a bit in here. For an actual restriction, like making your unsafe code harder to compile if ownership semantics change in an API, a shorter message like the one we have now is enough. It highlights whats linted, and gives a simple hint for contributors towards a solution, or at least where to look at. This also has the advantage that an early wrong assumption in a function won't give you many screens of warnings or errors.

For people wanting to simply be precise for learnability, I think having the lint as a warning in the area of inspection combined with tooling to inspect the types of the code would bring the most value.

So, my suggestion would be to keep the simple diagnostic message that's there now (assuming it's considered proper helpful english, being a non-native speaker). But additionally add the following to the documentation (including your quite good suggestion):

* A paragraph explaining what adjustments are required. Basically telling contributors coming to a project explicitly that to satisfy the lint, they should make sure their patterns represent the types matched against, and to bind via `ref`, `ref mut` or leave them plain to be copied. This would bring the biggest value for projects using it for restrictions in certain places.
* Add a note that there are IDEs and tooling that can give type feedback on the involved types.This would be helpful for the projects using it as a safeguard as well as people wanting to be explicit just to get familiarity. Suggest that people can still use the lint to highlight areas of interest where patterns are adjusted automatically.
* Add at least one more example. The one that is there now gives a short view on the actual mechanics, but it might be worth to add one that shows an advantages, such as iterating over a `&mut Vec<(&str, i32)>`, where one tuple item is modified, but another one isn't.

If that sounds alright to you I can quickly make those changes.

I also remembered you suggested to move the external macro detection to the beginning of the lint, but I'm not sure that works out in this case. While the macro can be unchangeable and come from an external source, the pattern that causes the mismatch could still come from the user code. As such I think having the check on the pattern itself rather than the full construct makes sense.

Hope this all makes sense :)

**Comment by flip1995** [comment]
Your suggestions sound good to me! You can go ahead and write the documentation, I will review it for "proper" English as far as I can (not a native English speaker myself).

> I also remembered you suggested to move the external macro detection to the beginning of the lint, but I'm not sure that works out in this case

Alright, disregard my comment in that case.

**Comment by phaylon** [comment]
@flip1995 I've now updated the documentation to include the discussed changes.

**Comment by flip1995** [comment]
Thanks, this looks really good now!

Also big thanks for sticking around so long and be patiently waiting for my reviews.

@bors r+

**Comment by phaylon** [comment]
@flip1995 Thanks! :D And a very big thanks to you for being so helpful!

**Comment by flip1995** [comment]
You need to remove the first LT parameter of every `LateLintPass` / `LateContext`.

**Comment by phaylon** [comment]
@flip1995 
> You need to remove the first LT parameter of every `LateLintPass` / `LateContext`.

Thanks, and done!

**Comment by flip1995** [comment]
@bors r+

Thanks! Let's get this finally through 🚀

**Pull request merged**
