### PR TITLE
docs(explicit_write): add missing backtick to complete code snippet

### LINKED ISSUE #11918: Typo in explicit_write docs
### Description

The section explaining why [`explicit_write`](https://rust-lang.github.io/rust-clippy/stable/index.html#/explicit_write) is bad is missing a backtick.

```rust
    /// ### Why is this bad?
    /// Using `(e)println! is clearer and more concise
```

It should be:
```rust
    /// ### Why is this bad?
    /// Using `(e)println!` is clearer and more concise
```

### Version

```text
rustc 1.74.0 (79e9716c9 2023-11-13)
binary: rustc
commit-hash: 79e9716c980570bfd1f666e3b16ac583f0168962
commit-date: 2023-11-13
host: x86_64-unknown-linux-gnu
release: 1.74.0
LLVM version: 17.0.4
```

### Additional Labels

@rustbot label +C-enhancement

### PR DESCRIPTION
**Pull request by KisaragiEffective**
close #11918 

*Please write a short comment explaining your change (or "none" for internal only changes)*

changelog: [`explicit_write`]: add missing backtick to document to complete code snippet

### CODE REVIEW

**Comment by glmdgrielson** [comment]
Well, that was quick.

**Comment by xFrednet** [comment]
LGTM, thanks!

@bors r+

**Comment by xFrednet** [comment]
It looks like bors is hanging. The CI should be fixed after the next sync in #11929

@bors r-

**Comment by matthiaskrgr** [comment]
@bors force

something is weird

**Pull request merged**
