### PR TITLE
Add `usize` cast to `clippy::manual_bits` suggestion

### PR DESCRIPTION
**Pull request by xFrednet**
A fix for the suggestion from https://github.com/rust-lang/rust-clippy/pull/8213

changelog: [`manual_bits`]: The suggestion now includes a cast for proper type conversion

### CODE REVIEW

**Comment by giraffate** [comment]
The test fails in `ui/manual_bits.rs`, can this be updated?

**Comment by xFrednet** [comment]
Thank you for the message, I've missed the failed CI. Now it should be ready, the update only added `clippy::useless_conversion` to the allowed lint list in the test file :)

**Review by giraffate — COMMENTED** [review]
Can the example in doc be updated like below?
```
    /// ### Example
    /// ```rust
    /// std::mem::size_of::<usize>() * 8;
    /// ```
    /// Use instead:
    /// ```rust
    /// usize::BITS as usize;
    /// ```
```

**Review by giraffate — APPROVED** [review]

**Comment by giraffate** [comment]
@bors r+

Thanks!

**Pull request merged**
