### PR TITLE
Add lint for 'field_reassign_with_default` #568

### LINKED ISSUE #568: suggest struct constructor instead of mutable object + field mod
If you have a struct where all fields are public, then you should never do `let mut a = A::default(); a.x = 42;` but instead use a constructor with `.. A::default()` at the end:

``` rust
#[derive(Default)]
struct A {
    i: i32,
    j: i64,
}

fn main() {
    let mut a: A = Default::default();
    a.i = 42;
}

fn should_be() {
    let a = A {
        i: 42,
        .. Default::default()
    };
}
```

### PR DESCRIPTION
**Pull request by hegza**
changelog: Add lint for `field_reassign_with_default` that checks if mutable object + field modification is used to edit a binding initialized with Default::default() instead of struct constructor.

Fixes #568

Notes:
- Checks for immediate reassignment of fields of a binding initialized with Default::default().
- Implemented using EarlyLintPass, might be future proofed better with LateLintPass.
- Does not trigger if Default::default() is used via another type implementing Default.

### CODE REVIEW

**Comment by flip1995** [comment]
Thanks for implementing this and sorry for not replying. This went under my radar.  

Do you think, you could enhance this lint, to also catch more than one assignment. So that

```rust
let a = Default::default();
a.i = 42;
a.j = 43;
```

suggests

```rust
let a = A { i: 42, j: 43, ..Default::default() };
```

**Comment by hegza** [comment]
Ah, yes, sure, doesn't look too difficult. I'm sure I intended it that way but forgot about it somehow.

**Comment by phansch** [comment]
Hi @hegza, are you still interested in continuing the PR? As far as I can tell the last suggestion isn't implemented yet; or there's no test case for it at least.

Let us know if you need any help =)

**Comment by hegza** [comment]
Yeah, sorry, trying to get papers out at work and really having to push it down on the priority list. I'm interested, just busy.

**Comment by flip1995** [comment]
Thanks for contributing to Clippy! Sadly this PR was not updated in quite some time. If you waited on input from a reviewer, we're sorry that this fell under the radar. If you want to continue to work on this, just reopen the PR and/or ping a reviewer.

**Comment by HKalbasi** [comment]
finished in #5911
@rustbot label -S-inactive-closed

**Pull request closed without merging**
