### PR TITLE
rustup https://github.com/rust-lang/rust/pull/60928

### PR DESCRIPTION
**Pull request by matthiaskrgr**
changelog: none

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
I did this speculatively, the change upstream change did not merge yet and I have not tested if this actually builds.

**Comment by flip1995** [comment]
It's merged now

**Comment by matthiaskrgr** [comment]
All tests pass locally with rustc master now.
r? @flip1995

**Comment by flip1995** [comment]
also in travis 👍 

@bors r+

**Comment by matthiaskrgr** [comment]
Can't really see what's wrong. Perhaps dogfood froze?
@bors retry

**Comment by matthiaskrgr** [comment]
It's hanging again, this time on travis...
@bors retry

**Comment by phansch** [comment]
The AppVeyor build seems to have started one hour after it was queued; that's definitely too late :/

**Pull request merged**
