### PR TITLE
Remove deprecated set-env from GHA

### PR DESCRIPTION
**Pull request by flip1995**
This updates all of our action dependencies and removes every usage of `set-env`. `set-env` and `add-path` has been deprecated: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

changelog: none

### CODE REVIEW

**Comment by flip1995** [comment]
Debugging CI, yay 🎉 😭

**Comment by flip1995** [comment]
Ready for review 🚀

**Review by ebroto — APPROVED** [review]
LGTM

**Pull request merged**
