### PR TITLE
Few improvement to `utils::conf` module

### PR DESCRIPTION
**Pull request by lzutao**
* Fix a few typos
* Handle Option<&Path> early
* Use `env::var_os` when possible

changelog: none

### CODE REVIEW

**Comment by lzutao** [comment]
Todo: fix the dogfood test about explicit `for loop`

**Comment by lzutao** [comment]
Done

**Comment by lzutao** [comment]
It's interesting with #4950, in `fn read` I locked the `ERRORS` in start of the function
the it made the `ui-toml/bad_toml_types` test hang.

**Comment by flip1995** [comment]
I guess, this is because tests are run in parallel?

@bors r+

**Pull request merged**
