### PR TITLE
`significant_drop_in_scrutinee`: Fix false positives due to false drops of place expressions

### PR DESCRIPTION
**Pull request by lrh2000**
Place expressions do not really create temporaries, so they will not create significant drops. For example, the following code snippet is quite good (#8963):
```rust
fn main() {
    let x = std::sync::Mutex::new(vec![1, 2, 3]);
    let x_guard = x.lock().unwrap();
    match x_guard[0] {
        1 => println!("1!"),
        x => println!("{x}"),
    }
    drop(x_guard); // Some "usage"
}
```

Also, the previous logic thinks that references like `&MutexGuard<_>`/`Ref<'_, MutexGuard<'_, _>>` have significant drops, which is simply not true, so it is fixed together in this PR.

Fixes https://github.com/rust-lang/rust-clippy/issues/8963
Fixes https://github.com/rust-lang/rust-clippy/issues/9072

changelog: [`significant_drop_in_scrutinee`]: Fix false positives due to false drops of place expressions.

r? @blyxyas

### CODE REVIEW

**Comment by blyxyas** [comment]
> Also, the previous logic thinks that references like &MutexGuard<_>/Ref<'_, MutexGuard<'_, _>> have significant drops, which is simply not true, so it is fixed together in this PR.

MutexGuard<_> Has a significant drop [(the attribute)](https://doc.rust-lang.org/src/std/sync/mutex.rs.html#207) [(the drop function itself)](https://doc.rust-lang.org/src/std/sync/mutex.rs.html#546), I'm not sure why do you think that it doesn't have one. Could you elaborate? Maybe I'm not understanding something correctly, as mutexes are quite a deep topic.

**Comment by lrh2000** [comment]
> MutexGuard<_> Has a significant drop [(the attribute)](https://doc.rust-lang.org/src/std/sync/mutex.rs.html#207) [(the drop function itself)](https://doc.rust-lang.org/src/std/sync/mutex.rs.html#546), I'm not sure why do you think that it doesn't have one. Could you elaborate? Maybe I'm not understanding something correctly, as mutexes are quite a deep topic.

It's `MutexGuard<_>` that has a significant drop, not `&MutexGuard<_>` (note that it's a reference).

For example, I've added a unit test for this:
```rust
struct Guard<'a, T>(MutexGuard<'a, T>);

impl<'a, T> Guard<'a, T> {
    fn guard(&self) -> &MutexGuard<T> {
        &self.0
    }
}
```
```rust
    match guard.guard().len() {
        0 => println!("empty"),
        _ => println!("not empty"),
    }
```

`guard.guard().len()` does not even create a `MutexGuard` temporary, so it has nothing to do with the significant drop check.

Actually, I think it's rare for this to happen in real-world scenarios (which is why no one has complained about it). However, I do think that the previous logic does not seem correct in this sense.

**Comment by lrh2000** [comment]
> Sorry for the delay, I'm currently working on a pretty big change that will optimize the linting module in Rust (both Clippy and builtin lints) by about 50%. So I've been focusing on that optimization. (I also wanted to make sure that everything's right)

Thanks for the explanation. That's pretty cool :+1:, and I completely understand that you're busy, so the review may be delayed (though I certainly want things to move faster). Also, thanks for the review!

**Pull request merged**
