### PR TITLE
Allow using `clippy::msrv` as an outer attribute

### PR DESCRIPTION
**Pull request by Alexendoo**
changelog: Allow specifying `#[clippy::msrv]` as an outer attribute

Probably not too useful to clippy users, but it makes the MSRV tests slightly cleaner

### CODE REVIEW

**Comment by Jarcho** [comment]
Why was this limited to inner attributes in the first place?

**Comment by Alexendoo** [comment]
I missed it the first time I looked through #6201 but just found https://github.com/rust-lang/rust-clippy/pull/6201#discussion_r516774498

I think the reasoning applied to an earlier version of the PR, but it ended up using `enter_lint_attrs` which should work fine for both inner & outer attrs

**Comment by Jarcho** [comment]
Just want to make sure my interpretation is correct. This looks like when an msrv attribute is seen, it sets the msrv until the next msrv attribute, totally ignoring the scope of the attribute. This would make something like:
```rust
#[clippy::msrv = "1.28"]
fn foo() {}
fn bar() {}
```
apply the msrv to both `foo` and `bar`. If that's the case this is just encouraging a footgun on stable.

**Comment by Alexendoo** [comment]
Yeah that's https://github.com/rust-lang/rust-clippy/issues/6920, it being used on stable is a good point. I'll get that fixed up first

**Comment by flip1995** [comment]
I made the decision to limit this to inner attributes, because I didn't really see a use case where it would make sense to apply this to items/expressions/... and because the implementation of only inner attributes was simpler to do.

Together with the [`cfg_version`](https://doc.rust-lang.org/beta/unstable-book/language-features/cfg-version.html) feature of `rustc` also having this as an outer attribute makes sense.

**Comment by Alexendoo** [comment]
Opened #9924

Didn't know about that feature, hopefully that gets to stable at some point

Picking it up automatically could be good, I would guess a cfg doesn't get passed to `enter/exit_lint_attrs` though

**Comment by flip1995** [comment]
> In the case of `cfg_version` version would it not be better to set that as the msrv if it's higher than the current value?

As with all `cfg` attributes, we don't even see that attribute. We even see the code, if the feature is enabled or we don't see the code at all. We sadly cannot access `cfg` attributes.

**Review by Jarcho — APPROVED** [review]
LGTM. Github seems to be only sending me about half the email notifications right now, so you might need to approve yourself after rebasing

**Comment by Alexendoo** [comment]
Thanks! Hopefully they fix that 👀

@bors r=Jarcho

**Pull request merged**
