### PR TITLE
Add error message to manual_inspect lint

### PR DESCRIPTION
**Pull request by flip1995**
r? @Jarcho 

changelog: none

### CODE REVIEW

**Comment by Jarcho** [comment]
@bors r+

I don't know why anybody would want error messages.

**Comment by RalfJung** [comment]
> I don't know why anybody would want error messages.

I honestly can't tell if you are joking...
but in case you are not: it is very confusing to have an error that just says "error". It basically says "something is wrong with your code" but then it doesn't tell me *what* is wrong with my code, which is something between confusing and irritating.

**Comment by Jarcho** [comment]
I'm not sure if that could have been less serious. I figured the approval in the same comment would be enough of an indicator.

**Comment by RalfJung** [comment]
Without any non-verbal cues, interpreting text messages on the internet is very tricky, which is why it is customary to indicate jokes textually, such as with a smiley: ";)". Without such an indication, I think you are expecting too much from random people on the internet being able to read your thoughts. The approval in the same message could easily also have meant " :shrug: but the PR also doesn't hurt so whatever, let's just land it".

**Pull request merged**
